import { useState, useEffect, useRef } from "react";

const PHASES = [
  { id: 1, title: "LISTEN", subtitle: "Hear what's really being said", days: "Day 1-21", icon: "👂", description: "The foundation of all great communication. Learn to listen deeply, read between the lines, and make others feel truly heard.", mnemonic: "H.E.A.R. - Halt distractions, Engage fully, Absorb meaning, Respond thoughtfully", gradient: { dark: "linear-gradient(160deg, #1c1410 0%, #2d1f18 50%, #1a1510 100%)", light: "linear-gradient(160deg, #fdf6f0 0%, #faf0e6 50%, #fdf8f2 100%)" }, accent: { dark: "#e8a87c", light: "#c2703e" }, glow: "rgba(232, 168, 124, 0.25)" },
  { id: 2, title: "SPEAK", subtitle: "Words that land, not just leave", days: "Day 22-42", icon: "🎤", description: "Master verbal communication: clarity, confidence, storytelling, and the art of saying more with fewer words.", mnemonic: "V.O.I.C.E. - Volume, Order, Intent, Clarity, Emotion", gradient: { dark: "linear-gradient(160deg, #101c1a 0%, #183028 50%, #0d1a18 100%)", light: "linear-gradient(160deg, #f0faf7 0%, #e4f5f0 50%, #f2fbf8 100%)" }, accent: { dark: "#5eead4", light: "#0d9488" }, glow: "rgba(94, 234, 212, 0.25)" },
  { id: 3, title: "WRITE", subtitle: "Make every word earn its place", days: "Day 43-63", icon: "✍️", description: "Professional emails, Slack messages, documentation, LinkedIn posts, and YouTube scripts that people actually want to read.", mnemonic: "I.N.K. - Intentional, Necessary, Kind", gradient: { dark: "linear-gradient(160deg, #1a1020 0%, #2a1838 50%, #1c1225 100%)", light: "linear-gradient(160deg, #f8f0fd 0%, #f0e4f8 50%, #faf2ff 100%)" }, accent: { dark: "#c4b5fd", light: "#7c3aed" }, glow: "rgba(196, 181, 253, 0.25)" },
  { id: 4, title: "CONNECT", subtitle: "Build bridges, not just sentences", days: "Day 64-77", icon: "🤝", description: "Networking, difficult conversations, giving feedback, resolving conflict, and building relationships through communication.", mnemonic: "B.O.N.D. - Be present, Open up, Notice needs, Deliver value", gradient: { dark: "linear-gradient(160deg, #1c1015 0%, #301820 50%, #201218 100%)", light: "linear-gradient(160deg, #fdf0f4 0%, #f8e4ec 50%, #fdf2f6 100%)" }, accent: { dark: "#fda4af", light: "#e11d48" }, glow: "rgba(253, 164, 175, 0.25)" },
  { id: 5, title: "AMPLIFY", subtitle: "Your voice at scale", days: "Day 78-90", icon: "🚀", description: "YouTube content, social media presence, personal branding, public speaking, and building an audience that trusts you.", mnemonic: "R.E.A.C.H. - Resonate, Engage, Authentic, Consistent, Helpful", gradient: { dark: "linear-gradient(160deg, #18150d 0%, #2a2510 50%, #1c1a0d 100%)", light: "linear-gradient(160deg, #fdfaed 0%, #f8f3dd 50%, #fdfbf0 100%)" }, accent: { dark: "#fde047", light: "#ca8a04" }, glow: "rgba(253, 224, 71, 0.25)" },
];

const ALL_LESSONS = [
  // PHASE 1: LISTEN (Day 1-21)
  { day: 1, phase: 1, type: "bite", title: "You're Not Listening (Yet)", content: "Most people listen to REPLY, not to UNDERSTAND. The moment someone starts talking, you're already forming your response. Today, flip that. Listen to absorb, not to answer.", workChallenge: "In your next 1:1 or meeting, catch yourself forming a reply while someone is still speaking. When you notice it, drop your thought and re-focus on THEIR words.", lifeChallenge: "In a personal conversation today, wait 3 full seconds after they stop talking before you respond. Notice how different the conversation feels.", memoryTrick: "Two ears, one mouth. Use them in that ratio." },
  { day: 2, phase: 1, type: "bite", title: "The 3 Levels of Listening", content: "Level 1: Hearing words. Level 2: Understanding meaning. Level 3: Sensing emotion. Most people operate at Level 1. A great communicator lives at Level 3.", workChallenge: "In your next meeting, after someone speaks, identify: What did they SAY? (L1) What did they MEAN? (L2) How did they FEEL? (L3) You'll be shocked how different L1 and L3 can be.", lifeChallenge: "When a friend or family member talks today, listen for the emotion BENEATH the words. 'I'm fine' might mean Level 1 fine, but Level 3 exhausted.", memoryTrick: "Level 1 = ears. Level 2 = brain. Level 3 = heart. Great listeners use all three." },
  { day: 3, phase: 1, type: "bite", title: "Kill the Urge to Fix", content: "When someone shares a problem, your instinct is to solve it. But often, they don't want solutions. They want to feel heard. 'That sounds really tough' is sometimes more valuable than 'Here's what you should do.'", workChallenge: "Next time a colleague shares a frustration, resist offering solutions. Try: 'That sounds frustrating. Tell me more about what happened.' Only offer solutions if they ASK.", lifeChallenge: "When someone vents to you today, respond with empathy first: 'I can see why that would bother you.' Notice if they relax.", memoryTrick: "F.A.S. - Feel first, Ask if they want advice, Solve only if invited." },
  { day: 4, phase: 1, type: "bite", title: "Active Listening: The Visible Proof", content: "Listening is invisible unless you make it visible. Nodding, eye contact, leaning in, and verbal cues ('I see', 'Go on', 'That makes sense') prove you're engaged. Without them, even perfect listening looks like ignoring.", workChallenge: "In your next video call, turn camera ON. Nod visibly. Give verbal cues. After the call, notice if the other person was more open than usual.", lifeChallenge: "In a face-to-face conversation, put your body in 'listening mode': lean slightly forward, uncross arms, maintain eye contact 60-70% of the time.", memoryTrick: "Listening is like applause. Silent appreciation is nice, but visible appreciation makes the performer SOAR." },
  { day: 5, phase: 1, type: "bite", title: "The Power of Paraphrasing", content: "The single most powerful listening technique: repeat back what you heard in YOUR words. 'So what you're saying is...' This does 3 things: confirms understanding, shows respect, and catches misunderstandings early.", workChallenge: "Use paraphrasing 3 times today at work. 'If I understand correctly, you're saying that...' Watch how it transforms the conversation.", lifeChallenge: "Try this with a friend or family member. 'So you felt X when Y happened?' They'll feel deeply understood.", memoryTrick: "Paraphrasing is a MIRROR for their words. People love seeing their thoughts reflected back clearly." },
  { day: 6, phase: 1, type: "deep", title: "Listening for What's NOT Said", content: "The most important information is often between the lines. What someone avoids mentioning, where they change the subject, what they downplay. A master listener hears the silence as loudly as the words.", workChallenge: "In your next architecture discussion or standup, notice what WASN'T mentioned. Is someone avoiding a topic? Is a risk being glossed over? Ask about the gap: 'I notice we didn't discuss X. Should we?'", lifeChallenge: "In a conversation today, listen for what the person ISN'T saying. Are they talking around something? Gently open the door: 'Is there something else on your mind?'", memoryTrick: "Words are the TIP of the iceberg. The real mass is underwater, in what's left UNSAID." },
  { day: 7, phase: 1, type: "practice", title: "Week 1 Reflection: Listening Audit", content: "After 6 days of intentional listening, time to honestly assess your baseline.", workChallenge: "Rate yourself 1-10 on: Not interrupting, Paraphrasing, Reading emotions, Asking follow-ups, Giving full attention. Lowest score = your Week 2 focus.", lifeChallenge: "Ask someone close: 'Do I listen well? Be honest.' Their answer is more accurate than your self-assessment.", memoryTrick: "You can't fix what you can't HEAR about yourself. Ask, listen, and grow." },
  { day: 8, phase: 1, type: "bite", title: "The Interruption Killer", content: "Interrupting is the #1 listening sin. Every interruption says: 'My thought is more important than yours.' Even if your point is brilliant, the interruption ruins it. Wait. Always wait.", workChallenge: "For the next 3 meetings, set a personal rule: ZERO interruptions. If you catch yourself starting to interrupt, physically close your mouth and wait.", lifeChallenge: "In family conversations, notice how often people interrupt each other. Be the one who waits. Be the anchor of patience.", memoryTrick: "An interruption is a STOP SIGN you put in someone else's lane. Stay in yours." },
  { day: 9, phase: 1, type: "bite", title: "Listening Across Cultures", content: "Different cultures communicate differently. Some are direct, some indirect. Some value silence, some fill every pause. At BHN with global teams, cultural listening is a superpower.", workChallenge: "Think about a colleague from a different cultural background. How is their communication style different from yours? Adjust your listening to THEIR style, not yours.", lifeChallenge: "Next time you watch a video or podcast from a different culture, notice the communication norms. Pace, directness, use of silence. Expand your listening range.", memoryTrick: "Listening has DIALECTS. A great listener is multilingual in communication styles." },
  { day: 10, phase: 1, type: "bite", title: "Listening to Difficult People", content: "The hardest but most valuable listening: hearing someone who frustrates you. When you dismiss people, you miss information. A master communicator listens hardest when they least want to.", workChallenge: "Think of the person at work whose opinion you most often dismiss. Next time they speak, force yourself to find ONE valid point. It's always there.", lifeChallenge: "Next time someone says something you disagree with, listen for the NEED behind the opinion. What are they actually asking for?", memoryTrick: "The person you LEAST want to listen to often has the message you MOST need to hear." },
  { day: 11, phase: 1, type: "bite", title: "Listening in Remote Work", content: "Remote work kills 55% of communication (body language). That means your ears need to work 2x harder. Tone shifts, pause lengths, energy changes. All are data points you're probably missing.", workChallenge: "On your next Teams/Zoom call, close all other tabs. Listen with 100% focus. Note tone changes, hesitations, and energy drops. What story do they tell?", lifeChallenge: "On your next phone call (not video), listen ONLY to voice. Without visuals, you'll hear emotions you normally miss.", memoryTrick: "Remote = fewer channels. But fewer channels means each one carries MORE signal. Tune in harder." },
  { day: 12, phase: 1, type: "bite", title: "The Question Follow-Up", content: "Most people ask one question and move on. Great listeners ask the FOLLOW-UP question. The second question is where real depth lives. 'Why did you choose that approach?' then 'What made that factor the most important?'", workChallenge: "In every conversation today, ask at least ONE follow-up question. Not a new topic. A deeper dive into what they just said.", lifeChallenge: "When someone shares something interesting, go one layer deeper: 'What was that like for you?' People rarely get asked to elaborate. It's a gift.", memoryTrick: "The first question opens a door. The follow-up walks THROUGH it." },
  { day: 13, phase: 1, type: "deep", title: "Empathic Listening: Feeling Their World", content: "Empathic listening is the highest form. You're not just understanding words or emotions. You're temporarily stepping into their reality. How does the world look from THEIR seat?", workChallenge: "Before your next interaction with a difficult stakeholder or colleague, spend 2 minutes imagining their day: their pressures, their fears, their goals. Now listen from THAT perspective.", lifeChallenge: "Next time someone is upset with you, before defending yourself, say: 'Help me see this from your side.' Then actually try.", memoryTrick: "Empathic listening is TELEPORTATION. You leave your world and visit theirs. Briefly. But it changes everything." },
  { day: 14, phase: 1, type: "practice", title: "Week 2 Practice: The Silent Meeting", content: "This week's challenge: attend one meeting where you ONLY listen. No contributions. No opinions. Just absorption.", workChallenge: "Pick one meeting this week where your contribution isn't critical. Attend silently. Take notes. Observe dynamics. You'll learn more in one silent meeting than ten active ones.", lifeChallenge: "Have one conversation today where you ask questions only. Zero statements about yourself. Make it entirely about the other person.", memoryTrick: "A day of silence teaches more about communication than a year of talking." },
  { day: 15, phase: 1, type: "bite", title: "Listening to Feedback Without Armor", content: "When receiving feedback, your body goes into defense mode. Heart rate up, excuses forming, justifications loading. A communication master drops the armor and listens with genuine curiosity.", workChallenge: "Next code review or performance conversation, catch the defensive reflex. Replace 'But I...' with 'Can you tell me more about what you noticed?'", lifeChallenge: "Ask for feedback on one specific thing today. When it comes, respond only with: 'Thank you. I'll think about that.' No defending. No explaining.", memoryTrick: "Armor protects you FROM feedback. Openness lets feedback TRANSFORM you. Choose transformation." },
  { day: 16, phase: 1, type: "bite", title: "Note-Taking as Listening", content: "Writing while someone speaks forces you to distill their message. But beware: don't become a stenographer. Capture themes and key points, not transcripts. Your notes should be INSIGHTS, not records.", workChallenge: "In your next meeting, take notes in your own words, not theirs. After the meeting, review: did your notes capture what MATTERED or just what was SAID?", lifeChallenge: "After an important conversation, write down the 3 most important things they said. Can you? If not, you weren't listening deeply enough.", memoryTrick: "Notes are EVIDENCE of listening. But the best evidence is how you ACT on what you heard." },
  { day: 17, phase: 1, type: "bite", title: "Listening to Your Own Body", content: "Communication isn't just with others. It's with yourself. Are you tired? Anxious? Rushed? Your internal state leaks into every conversation. Self-awareness is the foundation of other-awareness.", workChallenge: "Before your first meeting tomorrow, do a 30-second body scan: am I tense? Tired? Distracted? Name your state. Then choose how to show up despite it.", lifeChallenge: "Notice your energy today. When are you a great listener? When are you terrible? Map your listening energy throughout the day.", memoryTrick: "You can't POUR from an empty cup. Check your cup before every conversation." },
  { day: 18, phase: 1, type: "bite", title: "The Gift of Undivided Attention", content: "In a world of divided attention, giving someone your COMPLETE focus is the rarest and most valuable gift. No phone, no laptop, no wandering eyes. Just them.", workChallenge: "In your next 1:1 with Arun or a teammate, close your laptop. Put your phone away. Give 100% eye contact and attention for the full duration.", lifeChallenge: "Tonight, give someone 15 minutes of undivided attention. No screens, no multitasking. Just presence. Watch what happens to the depth of conversation.", memoryTrick: "Attention is the new CURRENCY. In a world where everyone's distracted, full attention is a FORTUNE." },
  { day: 19, phase: 1, type: "bite", title: "Listening for Patterns", content: "When someone tells you the same thing multiple ways, or returns to a topic repeatedly, they're telling you what matters MOST. Pattern recognition in conversations reveals priorities.", workChallenge: "In your next sprint planning or retro, track what topics keep resurfacing. That repetition IS the priority, even if it's not on the agenda.", lifeChallenge: "Think about what your close friends or family keep talking about. What themes repeat? That's what they need from you.", memoryTrick: "Repetition in conversation is a HIGHLIGHTER. The speaker is underlining what matters. Notice the highlights." },
  { day: 20, phase: 1, type: "deep", title: "Deep Listening: The 5-Minute Challenge", content: "Deep listening means listening to someone for 5 full minutes without any response. No nodding cues, no 'mhmm', no interruptions. Just pure, absorptive silence. It's harder than it sounds and more powerful than you'd expect.", workChallenge: "Ask a colleague: 'I want to really understand your perspective on X. Can you share your full thoughts while I just listen for a few minutes?' Then be silent.", lifeChallenge: "Try the 5-minute listening challenge with someone close to you. 'I want to hear everything you're thinking. I'll just listen.' The depth will surprise you both.", memoryTrick: "5 minutes of SILENCE is louder than 50 minutes of discussion. In silence, truth has room to BREATHE." },
  { day: 21, phase: 1, type: "practice", title: "Phase 1 Graduation: The Listener's Report", content: "21 days of listening training. Time to measure your transformation.", workChallenge: "Re-take the Day 7 audit. Compare scores. Write: 'My biggest listening shift was ___. I still struggle with ___. My next focus is ___.'", lifeChallenge: "Ask the same person from Day 7: 'Have you noticed any change in how I listen?' Their answer is your real graduation score.", memoryTrick: "Phase 1 done. You can now HEAR what others miss. Phase 2 teaches you to SPEAK so they listen back." },

  // PHASE 2: SPEAK (Day 22-42)
  { day: 22, phase: 2, type: "bite", title: "Clarity Beats Cleverness", content: "The goal of speaking isn't to sound smart. It's to be UNDERSTOOD. Simple, clear, direct language beats jargon and complexity every single time. If a 12-year-old can't follow you, simplify.", workChallenge: "Explain your current project to someone in 2 sentences using ZERO technical jargon. If you can't, your communication is too complex.", lifeChallenge: "In every conversation today, choose the simpler word. 'Use' instead of 'utilize.' 'Start' instead of 'initiate.' Clarity is kindness.", memoryTrick: "Clever words impress for a SECOND. Clear words are remembered FOREVER." },
  { day: 23, phase: 2, type: "bite", title: "The 1-Sentence Rule", content: "Before you speak in any meeting, know your ONE main point. If you can't state it in one sentence, you're not ready to speak. Everything else is supporting detail.", workChallenge: "Before your next standup or meeting contribution, write your ONE sentence. Then speak it first. Add detail only if asked.", lifeChallenge: "When someone asks 'What do you think?', answer in ONE sentence first. Then expand only if they want more. This is how leaders communicate.", memoryTrick: "If you need 5 minutes to say it, you need 5 more minutes to THINK about it first." },
  { day: 24, phase: 2, type: "bite", title: "The Pause: Your Secret Weapon", content: "A strategic pause before answering communicates: 'I'm thinking carefully about this.' Rushing to fill silence communicates: 'I'm nervous' or 'I'm not really thinking.' The pause is POWER.", workChallenge: "In your next 3 responses in meetings, pause for 2 seconds before speaking. Watch how people lean in, waiting for your words. That's influence.", lifeChallenge: "When someone asks you a question today, take a visible breath before answering. Even 'How was your day?' deserves a thoughtful pause.", memoryTrick: "The PAUSE is punctuation for speech. Without it, your words run together into noise." },
  { day: 25, phase: 2, type: "bite", title: "Eliminating Filler Words", content: "'Um', 'like', 'basically', 'you know', 'so', 'actually'. These fillers steal your authority. Every 'um' is a tiny crack in your credibility. You don't need them. Silence is better.", workChallenge: "Record your next meeting (or practice session). Count your fillers. Pick the top offender. Eliminate it over the next week by replacing it with a pause.", lifeChallenge: "Ask a friend to count your filler words in a 5-minute conversation. The number will shock you. Awareness is the first step.", memoryTrick: "Filler words are CRUTCHES. Remove them and you'll find your speech can WALK on its own." },
  { day: 26, phase: 2, type: "bite", title: "Speaking With Your Body", content: "Your hands, posture, and movement amplify your words. Open gestures = openness. Steepled fingers = confidence. Pacing = nervous energy. Align your body with your message.", workChallenge: "In your next presentation or discussion, use hand gestures intentionally. Open palms when sharing, counting fingers for lists, level hands for balance.", lifeChallenge: "Stand in front of a mirror and deliver a 1-minute opinion on any topic. Watch your body. What does it say? Does it match your words?", memoryTrick: "Your body is the STAGE. Your words are the SCRIPT. A great performance needs BOTH." },
  { day: 27, phase: 2, type: "bite", title: "The Rule of Three", content: "The human brain loves threes. 3 points, 3 examples, 3 benefits. 'Fast, reliable, affordable.' 'Reduce cost, increase speed, improve quality.' Structure in threes and people remember.", workChallenge: "In your next proposal or explanation, structure it in 3 points. Not 7. Not 5. Three. Watch how much clearer your communication becomes.", lifeChallenge: "Next time someone asks for your opinion, give 3 reasons. 'I love this restaurant for 3 reasons: the biryani, the view, and the service.' Crisp and memorable.", memoryTrick: "3 is the magic number. 2 feels incomplete. 4 feels like a list. 3 is JUST RIGHT." },
  { day: 28, phase: 2, type: "practice", title: "Week 4 Practice: The 2-Minute Pitch", content: "Build your verbal communication muscle with a timed exercise.", workChallenge: "Pick a topic you know well (email centralization, SQS architecture, anything). Set a timer for 2 minutes. Explain it clearly. Record yourself. Review. Redo. Get tighter each time.", lifeChallenge: "Explain why you love motorcycling in exactly 2 minutes. Not 3. Not 5. The constraint forces clarity.", memoryTrick: "A time constraint is a CHISEL. It carves away the unnecessary and reveals the essential." },
  { day: 29, phase: 2, type: "bite", title: "Storytelling: The Human Language", content: "Data tells. Stories sell. Every great communicator wraps facts in narratives. Instead of 'Response time improved 40%', say 'Last month, our users waited 3 seconds. This week? Under 2. That's what this change did.'", workChallenge: "Take a dry metric or achievement and turn it into a 30-second story. Use the arc: Problem existed, action was taken, result was felt.", lifeChallenge: "Next time you share something that happened to you, tell it as a STORY. Set the scene, build tension, deliver the punchline. Watch people lean in.", memoryTrick: "Facts are BRICKS. Stories are BUILDINGS. Nobody lives in a pile of bricks." },
  { day: 30, phase: 2, type: "bite", title: "Matching Your Audience", content: "You wouldn't explain Kubernetes to your grandmother the same way you'd explain it to a DevOps engineer. A great speaker adjusts vocabulary, depth, and pace to match who's listening.", workChallenge: "Prepare 3 versions of your current project explanation: 1 for your team (technical), 1 for your manager (strategic), 1 for a stakeholder (impact-focused).", lifeChallenge: "Notice how you speak differently to different people today. Are you adjusting naturally, or using the same style for everyone? Adapt.", memoryTrick: "A DJ reads the room before choosing the track. A communicator reads the AUDIENCE before choosing the words." },
  { day: 31, phase: 2, type: "bite", title: "Saying No Gracefully", content: "A powerful communicator knows how to say no without burning bridges. Not 'I can't' but 'Here's what I CAN do instead.' Not 'That's not possible' but 'What if we tried X approach?'", workChallenge: "Next time you need to push back on a request, use: 'I want to help. Here's what's realistic given [constraints]. Would [alternative] work?'", lifeChallenge: "Practice saying no to one thing today without guilt or over-explaining. A simple 'I appreciate the invite, but I can't make it this time' is enough.", memoryTrick: "No is a COMPLETE sentence. But 'No + alternative' is a complete RELATIONSHIP SAVER." },
  { day: 32, phase: 2, type: "bite", title: "The Power of Silence in Speech", content: "Strategic silence mid-speech is magnetic. After making an important point, STOP. Let it land. The silence gives your words weight. Politicians, speakers, and leaders all use this.", workChallenge: "In your next presentation, after your most important point, pause for 3 full seconds. Don't rush to the next slide. Let the point breathe.", lifeChallenge: "In a conversation, after saying something meaningful, resist the urge to keep talking. Let the silence do the work.", memoryTrick: "Words fill the AIR. Silence fills the MIND. The best communicators use both." },
  { day: 33, phase: 2, type: "deep", title: "Speaking Under Pressure", content: "The real test of communication: high-pressure moments. Incidents, deadlines, confrontations. Your ability to speak clearly when stressed separates good communicators from great ones.", workChallenge: "Think of the last time you were under pressure at work. How was your communication? Did you get clearer or more scattered? Practice: breathe, state facts, propose action.", lifeChallenge: "Next time you're stressed in a conversation, use the 4-4-4 technique: breathe in 4 seconds, hold 4, out 4. Then speak. The calm will show.", memoryTrick: "Pressure turns COAL into diamonds. It turns good communicators into GREAT ones. But only if they stay CALM." },
  { day: 34, phase: 2, type: "bite", title: "Asking Great Questions in Meetings", content: "The quality of your questions determines the quality of information you receive. Specific, open-ended, and thought-provoking questions get better answers than generic ones.", workChallenge: "Replace 'Does anyone have questions?' with 'What's the biggest risk we haven't discussed?' Replace 'How's the project?' with 'What's the one thing that could derail us?'", lifeChallenge: "Replace 'How was your day?' with 'What was the best part of today?' Better questions = deeper conversations.", memoryTrick: "A great question is a KEY that opens a room. A lazy question is a key that opens a closet." },
  { day: 35, phase: 2, type: "practice", title: "Week 5 Practice: Record and Review", content: "The fastest way to improve your speaking: hear yourself speak.", workChallenge: "Record a 3-minute explanation of anything. Listen back without cringing (hard, but necessary). Note: pace, fillers, clarity, energy. Do version 2. Compare.", lifeChallenge: "Record a voice note to a friend explaining something you're passionate about. Before sending, listen back. Is it engaging? Clear? Would YOU want to listen to it?", memoryTrick: "A mirror shows your FACE. A recording shows your VOICE. Both are necessary for self-improvement." },
  { day: 36, phase: 2, type: "bite", title: "Speaking With Conviction", content: "End sentences going DOWN in tone, not up. Upward inflection turns statements into questions. 'We should deploy on Friday?' vs 'We should deploy on Friday.' One is asking permission. The other is leading.", workChallenge: "In your next standup, make every statement a STATEMENT. No upward inflections on decisions. Practice in front of a mirror first if needed.", lifeChallenge: "Notice your inflection patterns today. Are you accidentally turning opinions into questions? Own your words with downward tone.", memoryTrick: "Going UP at the end asks for permission. Going DOWN claims your SPACE. Choose your direction." },
  { day: 37, phase: 2, type: "bite", title: "The BLUF Method", content: "Bottom Line Up Front. Military communication principle. State your conclusion FIRST, then support it. 'We need to delay the release by 2 days. Here's why...' Not 5 minutes of context before the point.", workChallenge: "Rewrite your next Slack message or email using BLUF. Lead with the ask or the conclusion. Watch how much faster you get responses.", lifeChallenge: "Next time someone asks your opinion, lead with your answer. 'I think we should go to X restaurant. Here's why.' Direct, clear, decisive.", memoryTrick: "B.L.U.F. - Give them the HEADLINE, not the whole newspaper. Details come second." },
  { day: 38, phase: 2, type: "bite", title: "Humor: The Connector", content: "Appropriate, natural humor makes you memorable and relatable. You don't need to be a comedian. A well-timed observation or self-deprecating comment can transform a tense room.", workChallenge: "In your next presentation or meeting, include one light moment. Not a forced joke, but a genuine observation that might make people smile.", lifeChallenge: "Practice not taking yourself too seriously today. If you make a small mistake, laugh at it first. Self-awareness through humor = confidence.", memoryTrick: "Humor is WD-40 for communication. It loosens up stuck conversations and makes everything move smoother." },
  { day: 39, phase: 2, type: "bite", title: "Verbal Economy: Say More With Less", content: "Every extra word dilutes your message. 'In my personal opinion, I actually think that we should basically consider...' vs 'I think we should...' Same meaning. Half the words. Double the impact.", workChallenge: "Take your last email or Slack message. Cut it by 30%. Remove every word that doesn't add meaning. Send the shorter version next time.", lifeChallenge: "Challenge yourself today: every text message in under 2 sentences. Force yourself to be concise. Clarity follows brevity.", memoryTrick: "Words are like SPICES. A little enhances the dish. Too much ruins it. Season lightly." },
  { day: 40, phase: 2, type: "deep", title: "The Art of Presenting", content: "A presentation is a PERFORMANCE, not a reading. Know your material so well that slides are a background, not a script. Make eye contact, move with purpose, and speak TO people, not AT them.", workChallenge: "Prepare a 5-minute presentation on any work topic. Practice until you can deliver it without looking at slides. Present it to one person and ask for honest feedback.", lifeChallenge: "Watch one TED talk today. Don't listen to the content. Watch the DELIVERY: eye contact, pacing, pauses, gestures. What can you steal for your own style?", memoryTrick: "A presentation is a GIFT you give the audience. If you're reading slides, you're just handing them a printed receipt." },
  { day: 41, phase: 2, type: "bite", title: "Vocal Variety: Don't Be Monotone", content: "Varying your pitch, pace, and volume keeps people engaged. Slow down for important points. Speed up for energy. Get quieter to pull people in. Get louder to emphasize.", workChallenge: "In your next explanation, deliberately vary your pace: normal speed for context, slow for the key insight, faster for supporting details.", lifeChallenge: "Read a paragraph aloud to yourself with maximum vocal variety. Then read it monotone. The difference is the difference between engaging and boring.", memoryTrick: "A flat voice is a flat ROAD. Nobody remembers a flat road. Add hills and curves and people pay ATTENTION." },
  { day: 42, phase: 2, type: "practice", title: "Phase 2 Graduation: The Speaker's Reel", content: "21 days of speaking refinement. Time to demonstrate.", workChallenge: "Record a 3-minute 'best of' speaking demo: clear, confident, well-structured. Use BLUF, Rule of Three, pauses, and no fillers. This is your benchmark.", lifeChallenge: "Give a 2-minute impromptu talk to a friend or family member on any topic. Ask them: 'Was I clear? Engaging? Would you listen to more?'", memoryTrick: "Phase 2 done. You can LISTEN deeply and SPEAK powerfully. Phase 3: make your WRITING match your voice." },

  // PHASE 3: WRITE (Day 43-63)
  { day: 43, phase: 3, type: "bite", title: "Write Like You Talk (But Better)", content: "Good writing sounds like a smart person talking. Not formal robot language. Not text-speak. The sweet spot: clear, conversational, and polished.", workChallenge: "Rewrite one section of your latest documentation as if you're explaining it to a smart colleague over chai. Read it aloud. If it sounds natural, you've nailed it.", lifeChallenge: "Write a message to a friend that's neither too formal nor too sloppy. Find YOUR written voice: warm, clear, and authentically you.", memoryTrick: "If you wouldn't SAY it out loud, don't WRITE it. The ear test is the best editor." },
  { day: 44, phase: 3, type: "bite", title: "The Subject Line is Everything", content: "In emails and Slack, 80% of impact comes from the first line. A great subject line tells the reader: what this is about, what's needed, and how urgent it is. 'Quick question about SQS retry config' beats 'Hey'.", workChallenge: "Review your last 5 emails. Would YOU open them based on the subject line alone? Rewrite any that are vague.", lifeChallenge: "Apply this to texts too. Instead of 'Hey', start with context: 'Quick plan check for Saturday.' People respond faster when they know what to expect.", memoryTrick: "A subject line is a MOVIE TRAILER. If the trailer is boring, nobody watches the film." },
  { day: 45, phase: 3, type: "bite", title: "One Message, One Purpose", content: "Each email, each Slack message, each document should have ONE clear purpose. Mixing 3 topics in one email guarantees that 2 get ignored.", workChallenge: "Next email with multiple topics? Split it into separate messages. Each with a clear subject line and one ask. Watch your response rate improve.", lifeChallenge: "Texts too. Don't send a 5-topic paragraph. Send separate messages for separate topics. Respect their mental bandwidth.", memoryTrick: "One message, one purpose. Like one slide, one idea. FOCUS creates CLARITY." },
  { day: 46, phase: 3, type: "bite", title: "The Edit Ruthlessly Principle", content: "First drafts are for YOU. Final drafts are for THEM. Write freely, then cut 30%. Remove redundancy, soften harsh language, and tighten every sentence. Editing is where good writing becomes great.", workChallenge: "Take your next important email. Write it. Then cut it by 30%. Read both versions. The shorter one is almost always better.", lifeChallenge: "Before posting anything on social media, edit it once. Remove one sentence. Add one insight. Polish before publishing.", memoryTrick: "Writing is SCULPTING. The statue is already in the stone. Editing removes everything that ISN'T the statue." },
  { day: 47, phase: 3, type: "bite", title: "Professional Slack Etiquette", content: "Threading replies, using @mentions sparingly, not sending 'Hi' as a separate message before your actual message, and formatting long messages with structure. Slack is a skill.", workChallenge: "Audit your Slack habits. Do you thread? Use formatting for long messages? Respect DND status? Pick one habit to improve this week.", lifeChallenge: "Apply the same respect to WhatsApp groups. Don't send 8 separate one-line messages. Compose your thought, then send it complete.", memoryTrick: "Slack is a SHARED kitchen. If you leave a mess, everyone suffers. Keep your messages clean and organized." },
  { day: 48, phase: 3, type: "deep", title: "Writing for YouTube: Scripts That Connect", content: "A YouTube script isn't an essay read aloud. It's a conversation with the viewer. Use 'you' and 'I'. Short sentences. Hook in the first 5 seconds. For Vishwa Motovlogs, authenticity is your script.", workChallenge: "Write a 60-second script for a YouTube Short about one lesson you've learned at work. Hook, insight, takeaway. Read it aloud. Does it sound like YOU?", lifeChallenge: "Write captions for your next 3 Motovlogs posts. Each under 150 words. Each with a hook, a story, and a question for engagement.", memoryTrick: "YouTube scripts are LETTERS to one person, read by thousands. Write for ONE viewer. The rest will listen." },
  { day: 49, phase: 3, type: "practice", title: "Week 7 Practice: The Writing Sprint", content: "Sharpen your writing speed and quality with a timed exercise.", workChallenge: "Set a 15-minute timer. Write a 1-page technical summary of your current project. Edit in 5 minutes. The time pressure kills perfectionism and forces clarity.", lifeChallenge: "Write a 200-word LinkedIn post about something you learned this week. Timer: 10 minutes to write, 5 to edit. Post it.", memoryTrick: "Speed writing reveals your NATURAL voice. Editing reveals your BEST voice. Use both." },
  { day: 50, phase: 3, type: "bite", title: "Documentation That People Actually Read", content: "Most documentation is write-only: written by someone, read by no one. Great documentation is scannable, structured, and answers the reader's questions in the order they'd ask them.", workChallenge: "Take one piece of your documentation. Restructure it with: TL;DR at top, clear headings, code examples, and a 'common issues' section.", lifeChallenge: "Apply documentation thinking to personal notes: your travel plans, your goals, your recipes. Structured information is USABLE information.", memoryTrick: "Great docs are like great MAPS. You find what you need without reading the whole thing." },
  { day: 51, phase: 3, type: "bite", title: "The LinkedIn Post Formula", content: "Hook (1 line that stops scrolling) + Story (3-5 lines of context) + Insight (the lesson) + Call to action (engage the reader). This formula works for career growth and personal branding.", workChallenge: "Write a LinkedIn post about your Email Centralization project using this formula. Not 'I'm working on X', but 'Here's what I learned about Y while building X.'", lifeChallenge: "Write a personal LinkedIn post about your 1% improvement philosophy. Share the real you, not the corporate you.", memoryTrick: "LinkedIn is a STAGE. Your post is your 60-second spotlight. Make every second count." },
  { day: 52, phase: 3, type: "bite", title: "Tone: The Invisible Layer", content: "The same words with different tone create completely different messages. 'As per my last email' is technically polite but universally understood as aggressive. Be intentional about tone.", workChallenge: "Before sending any message today, re-read it imagining the WORST possible tone interpretation. If it could be misread, add warmth: 'Hope you're doing well' or 'Thanks for flagging this.'", lifeChallenge: "Text messages are tone-deaf by design. Add warmth explicitly. 'No worries at all!' reads differently from 'No worries.'", memoryTrick: "Tone is the MUSIC of your words. Same lyrics, different melody, completely different song." },
  { day: 53, phase: 3, type: "bite", title: "Writing for Decision-Makers", content: "Executives read differently. They want: the recommendation, the evidence, the risk, and the ask. In that order. No backstory, no journey, no process details. Results and decisions only.", workChallenge: "Rewrite your next proposal using the executive format: 1. Recommendation (1 line), 2. Why (3 bullets), 3. Risk (2 bullets), 4. Ask (1 line).", lifeChallenge: "When explaining something to someone busy, use the same format. Respect their time by front-loading the important stuff.", memoryTrick: "Executives are SPEED READERS of life. Give them the highlight reel, not the director's cut." },
  { day: 54, phase: 3, type: "bite", title: "The Thank-You Email", content: "After meetings, interviews, or someone helping you: send a thank-you within 24 hours. Specific, brief, and genuine. This tiny habit separates professionals from the crowd.", workChallenge: "After your next meeting where someone helped you, send a 3-line thank-you within 2 hours. Specific to what they contributed.", lifeChallenge: "Send a thank-you message to someone who helped you recently but you never acknowledged. Even if it's been weeks.", memoryTrick: "A thank-you email takes 2 MINUTES to write and YEARS to forget." },
  { day: 55, phase: 3, type: "deep", title: "Writing Your Personal Brand", content: "Every piece of writing builds your personal brand. Your emails, Slack messages, LinkedIn posts, YouTube descriptions, even your code comments. They all tell the world WHO you are.", workChallenge: "Write your personal brand statement in 2 sentences. What do you want people to feel when they read something you wrote? Every future piece of writing should align.", lifeChallenge: "Audit your last 10 social media posts. Do they tell a consistent story about who you are? Or are they random? Curate intentionally.", memoryTrick: "Your writing is your DIGITAL HANDSHAKE. Every post, email, and message says: 'This is who I am.'" },
  { day: 56, phase: 3, type: "practice", title: "Week 8: The Multi-Format Challenge", content: "Write the same message in 4 formats: email, Slack, LinkedIn post, and YouTube script. See how the same idea transforms across mediums.", workChallenge: "Pick one work insight. Write it as: a professional email to leadership, a Slack message to your team, a LinkedIn post, and a 30-second YouTube script. Notice how each format demands different writing.", lifeChallenge: "Pick a personal story. Write it as: a text to a friend, an Instagram caption, and a 2-minute Motovlogs script. Same story, three voices.", memoryTrick: "Great writers are like great MUSICIANS. They can play the same melody on any instrument. Master every format." },
  { day: 57, phase: 3, type: "bite", title: "Formatting as Communication", content: "White space, bullet points, bold text, and short paragraphs are communication tools, not decorations. A wall of text is a wall between you and your reader.", workChallenge: "Take a recent long email or document. Reformat it: shorter paragraphs, bold key points, clear headers. Show it to someone. Which version do they prefer?", lifeChallenge: "Even in personal messages, structure matters. Break long thoughts into separate paragraphs. Your reader's eyes will thank you.", memoryTrick: "Formatting is ARCHITECTURE for your words. Without structure, even beautiful words are just a pile of rubble." },
  { day: 58, phase: 3, type: "bite", title: "Writing Under Time Pressure", content: "You don't always have an hour to craft the perfect message. Master the 5-minute email: scan the request, identify the key question, answer it directly, add one supporting detail, send.", workChallenge: "For every email today, set a 5-minute max. Open, read, draft, edit, send. Under 5 minutes. The constraint builds speed without sacrificing quality.", lifeChallenge: "Apply the same to texts. Read, think for 10 seconds, reply in under 1 minute. Don't overthink personal messages.", memoryTrick: "5-minute emails are like 5-minute workouts. Short, focused, and surprisingly effective." },
  { day: 59, phase: 3, type: "bite", title: "Writing Difficult Messages", content: "Bad news, rejections, disagreements. These require extra care. The formula: empathy first, fact second, forward path third. 'I understand this isn't what you hoped for. Here's what happened. Here's what we can do.'", workChallenge: "Draft a difficult message you've been avoiding. Use the empathy-fact-forward formula. Let it sit for an hour, re-read, then send.", lifeChallenge: "If you need to cancel plans, say no, or share bad news, use the formula. People remember HOW you delivered bad news more than the news itself.", memoryTrick: "Difficult messages are SURGERIES. The empathy is anesthesia. The fact is the operation. The forward path is recovery." },
  { day: 60, phase: 3, type: "bite", title: "Code Comments as Communication", content: "Your code comments speak to future developers, including future-you. Not WHAT the code does (the code shows that) but WHY it does it. The reasoning, the trade-offs, the context.", workChallenge: "Review your last 3 PRs. Are your comments explaining WHAT (redundant) or WHY (valuable)? Rewrite one set of comments to focus on WHY.", lifeChallenge: "Apply this to life notes too. Don't write 'Doctor appointment Tuesday.' Write 'Doctor appointment Tuesday RE: blood work follow-up for iron levels.'", memoryTrick: "WHAT comments are subtitles. WHY comments are director's commentary. The audience wants the commentary." },
  { day: 61, phase: 3, type: "bite", title: "Writing Engaging YouTube Descriptions", content: "Your YouTube description is SEO gold and audience connection in one. First 2 lines are visible before 'Show more'. Make them count. Include keywords, a hook, and a call to subscribe.", workChallenge: "Rewrite the descriptions for your last 3 Motovlogs videos. First 2 lines: hook + keyword. Then: summary, timestamps, social links.", lifeChallenge: "Apply this to any bio you have online: LinkedIn, Instagram, YouTube. The first 2 lines should make someone want to read more.", memoryTrick: "Your description is a WELCOME MAT. If it's boring, nobody walks through the door." },
  { day: 62, phase: 3, type: "deep", title: "Building a Writing System", content: "You now have tools for emails, Slack, docs, LinkedIn, and YouTube. Build YOUR personal writing system: templates, formulas, and checklists you use for each format.", workChallenge: "Create a personal 'Writing Toolkit' note: your go-to formulas for emails (BLUF), proposals (executive format), LinkedIn (hook-story-insight), and code reviews.", lifeChallenge: "Create templates for messages you send often: thank-yous, scheduling, catching up with old friends. Templates aren't lazy. They're efficient.", memoryTrick: "A writing system is a FACTORY for your thoughts. Raw ideas go in. Polished communication comes out." },
  { day: 63, phase: 3, type: "practice", title: "Phase 3 Graduation: The Writing Portfolio", content: "21 days of writing mastery. Time to showcase.", workChallenge: "Compile your best work writing from this phase: a clear email, a tight Slack message, a LinkedIn post, and one code comment you're proud of. This is evidence for your 5-star review.", lifeChallenge: "Publish one piece of writing publicly: a LinkedIn post, a tweet thread, or a Motovlogs description. Your writing portfolio starts now.", memoryTrick: "Phase 3 done. You can LISTEN, SPEAK, and WRITE. Phase 4: CONNECT with people through all three." },

  // PHASE 4: CONNECT (Day 64-77)
  { day: 64, phase: 4, type: "bite", title: "Networking Without Being Fake", content: "Networking isn't collecting business cards. It's building genuine relationships. The secret: focus on giving value, not getting it. Help first, always.", workChallenge: "Reach out to one person at BHN you don't usually interact with. Share something useful: an article, a tool, an insight. No ask attached.", lifeChallenge: "Reconnect with one person from your past who you've lost touch with. Not for business. For genuine human connection.", memoryTrick: "Networking is GARDENING. Plant seeds (value), water them (follow-up), and harvest later (relationships). Never harvest without planting." },
  { day: 65, phase: 4, type: "bite", title: "Giving Feedback That Lands", content: "Feedback is a gift, but delivery matters. The SBI model: Situation (when/where), Behavior (what you observed), Impact (how it affected things). Specific, objective, actionable.", workChallenge: "Give one piece of SBI feedback to a teammate this week. Not 'Your code is messy' but 'In yesterday's PR (S), the function names didn't follow our convention (B), which made review take longer (I).'", lifeChallenge: "Give feedback to a friend or family member using SBI. 'When we were at dinner (S), you kept checking your phone (B), and I felt like I wasn't being heard (I).'", memoryTrick: "S.B.I. turns vague criticism into a GIFT WRAPPED in clarity. Same message, 10x better reception." },
  { day: 66, phase: 4, type: "bite", title: "Receiving Feedback Like a Pro", content: "When receiving feedback, your only job is to UNDERSTAND it, not to respond in the moment. 'Thank you for that. Let me think on it.' Then actually think. Then decide what to act on.", workChallenge: "Next time you receive feedback, respond ONLY with gratitude and a question: 'Thank you. Can you give me an example so I can understand better?'", lifeChallenge: "Ask someone for specific feedback today. Receive it with zero defensiveness. Sleep on it. Respond tomorrow.", memoryTrick: "Receiving feedback is like catching a ball. You can REACT (dodge it) or RECEIVE it (catch it). Catching requires open hands." },
  { day: 67, phase: 4, type: "bite", title: "Managing Up: Communicating With Leadership", content: "Communicating with your manager or leadership requires a different lens. They need: impact, risks, decisions needed, and timeline. Not process, not details, not complaints.", workChallenge: "Prepare your next update for Arun using the format: What I accomplished, what's blocked, what I need from you, and what's coming next. 4 lines. Clear and actionable.", lifeChallenge: "Apply 'managing up' to any authority relationship: a landlord, a doctor, a teacher. State what you need, why, and what you need from them. Clear asks get clear answers.", memoryTrick: "Managing up = speaking their LANGUAGE. Executives speak impact. Middle management speaks process. Know the difference." },
  { day: 68, phase: 4, type: "deep", title: "Resolving Conflict Through Communication", content: "Most conflicts aren't about the issue. They're about feeling unheard. The resolution formula: acknowledge their feeling, state your perspective, find common ground, propose a path forward.", workChallenge: "Think of an unresolved tension at work. Draft a conversation using: 'I understand you feel [X]. My perspective is [Y]. I think we both want [Z]. What if we tried [solution]?'", lifeChallenge: "Apply this to any personal tension. Most arguments dissolve when both people feel heard. Be the first to acknowledge.", memoryTrick: "Conflict is two people shouting from opposite banks of a river. Communication builds the BRIDGE between them." },
  { day: 69, phase: 4, type: "bite", title: "The Art of Small Talk", content: "Small talk isn't small. It's the gateway to every meaningful conversation. The key: be genuinely curious. Ask about THEM, not about topics. People love talking about themselves.", workChallenge: "Before your next informal chat at work, prepare 2 genuine questions: 'Working on anything exciting?' 'Have you tried any new restaurants lately?'", lifeChallenge: "At your next social event, start 3 conversations with strangers using genuine curiosity. Not 'What do you do?' but 'What are you passionate about?'", memoryTrick: "Small talk is the APPETIZER. Nobody orders dessert without it. Master the appetizer and the feast follows." },
  { day: 70, phase: 4, type: "practice", title: "Week 10 Practice: The Difficult Conversation", content: "Practice having one conversation you've been avoiding.", workChallenge: "Identify one difficult conversation you need to have at work. Script it. Practice it. Have it this week. Use everything from Phase 4.", lifeChallenge: "Identify one personal conversation you've been dodging. Write out what you want to say. Have it within 48 hours.", memoryTrick: "Avoiding a difficult conversation is like avoiding the dentist. The problem doesn't go away. It gets WORSE." },
  { day: 71, phase: 4, type: "bite", title: "Cross-Team Communication", content: "Communicating across teams requires translation. Your team's jargon isn't their team's jargon. Your priorities aren't their priorities. Bridge the gap with shared language and shared goals.", workChallenge: "Next time you need something from another team, frame it in THEIR context: 'This helps your team by [benefit to them]' instead of 'I need this for my project.'", lifeChallenge: "When communicating with someone from a different background or interest, find SHARED context. What do you have in common? Start there.", memoryTrick: "Cross-team communication is TRANSLATION. Speak their language, not yours. The message arrives faster." },
  { day: 72, phase: 4, type: "bite", title: "Building Trust Through Communication", content: "Trust is built in tiny communication moments: following up when you said you would, admitting when you're wrong, sharing credit, being honest even when it's uncomfortable.", workChallenge: "Do a trust audit: are there any pending follow-ups, unfulfilled promises, or unacknowledged mistakes? Clear ALL of them today.", lifeChallenge: "Think of one relationship where trust has weakened. What communication repair could you make? A message, a call, an admission?", memoryTrick: "Trust is a BANK ACCOUNT. Every honest message is a deposit. Every broken promise is a withdrawal. Check your balance." },
  { day: 73, phase: 4, type: "bite", title: "Influence Without Authority", content: "You don't need a title to influence. You need clarity, credibility, and empathy. Show people WHY your idea benefits THEM, not just why it's right.", workChallenge: "For your email centralization initiative, draft a message that sells the benefit to another team. Not 'I need your help' but 'This will reduce your team's error alerts by 40%.'", lifeChallenge: "Next time you want to convince someone of something, make it about THEIR benefit, not your preference.", memoryTrick: "Influence is not PUSHING someone toward your idea. It's LIGHTING a path they WANT to walk." },
  { day: 74, phase: 4, type: "bite", title: "Saying Sorry vs Saying Thank You", content: "Replace unnecessary apologies with gratitude. Instead of 'Sorry for the delay', say 'Thank you for your patience.' It reframes YOU from weak to appreciative, and THEM from victim to hero.", workChallenge: "Audit your messages this week. How many 'sorry's could be 'thank you's? Swap them. 'Thanks for waiting' instead of 'Sorry I'm late.'", lifeChallenge: "In personal life too: 'Thank you for listening to me vent' instead of 'Sorry for bothering you.' It changes the entire dynamic.", memoryTrick: "'Sorry' puts you DOWN. 'Thank you' lifts them UP. Same moment, opposite energy." },
  { day: 75, phase: 4, type: "bite", title: "Communication in 1:1 Meetings", content: "Your 1:1 with your manager is YOUR meeting, not theirs. Come prepared with updates, asks, and growth topics. Don't waste it on status updates they can read in Jira.", workChallenge: "For your next 1:1 with Arun, prepare: 1 win to share, 1 challenge to discuss, 1 growth topic to explore. Share the agenda 24 hours before.", lifeChallenge: "Apply 1:1 thinking to personal relationships. Schedule intentional check-ins with people who matter. Prepared, focused, meaningful.", memoryTrick: "A 1:1 without preparation is a WASTED meeting. A 1:1 with preparation is a CAREER-changing conversation." },
  { day: 76, phase: 4, type: "deep", title: "Building Your Connection Toolkit", content: "You now have tools for feedback, conflict, networking, and influence. Build YOUR personal connection system.", workChallenge: "Create your 'Connection Toolkit': SBI feedback template, difficult conversation formula, 1:1 agenda template, and your networking approach.", lifeChallenge: "List 10 people you want to strengthen relationships with. Create a simple plan: who to contact when, about what.", memoryTrick: "Connections don't happen by accident. They happen by SYSTEM. Build yours." },
  { day: 77, phase: 4, type: "practice", title: "Phase 4 Graduation: The Connection Audit", content: "14 days of relationship-building through communication. Assess your growth.", workChallenge: "Rate your connections at work: manager, peers, cross-team, leadership. Where are you strong? Where do you need to invest? This feeds your 5-star review.", lifeChallenge: "Rate your personal connections: family, friends, community. Who have you neglected? Reach out to one person today.", memoryTrick: "Phase 4 done. You can LISTEN, SPEAK, WRITE, and CONNECT. Final phase: AMPLIFY your voice to the world." },

  // PHASE 5: AMPLIFY (Day 78-90)
  { day: 78, phase: 5, type: "bite", title: "Finding Your Unique Voice", content: "Everyone has a unique communication fingerprint. Yours is shaped by your 1% philosophy, your motorcycle journeys, your engineering mind, and your Telugu roots. Don't copy someone else's voice. FIND yours.", workChallenge: "Write down 3 things that make YOUR perspective unique at BHN. Your cross-domain experience, your DevOps background, your observability expertise. That's your professional voice.", lifeChallenge: "For Vishwa Motovlogs, what makes YOU different from other motovloggers? Not just rides. Your philosophy, your solo travel lens, your authentic growth journey. That's your voice.", memoryTrick: "Your voice is your FINGERPRINT. Nobody else has it. Stop trying to sound like someone else." },
  { day: 79, phase: 5, type: "bite", title: "YouTube: The First 5 Seconds", content: "YouTube's algorithm and human attention both agree: you have 5 seconds to hook. Not 30. Not 10. Five. 'Here's what 1,000 km alone on a motorcycle taught me about life' beats 'Hey guys, welcome back to my channel.'", workChallenge: "Rewrite the first 5 seconds of your last 3 videos. Would they make someone STOP scrolling? If not, make them stronger.", lifeChallenge: "Apply the 5-second hook to everything: LinkedIn posts, emails, conversations. Lead with the most interesting thing. Always.", memoryTrick: "5 seconds is an AUDITION. You're auditioning for their attention. Make the first line your BEST line." },
  { day: 80, phase: 5, type: "bite", title: "Consistency Over Virality", content: "One viral video is luck. Consistent quality is a career. Post regularly, improve steadily, engage genuinely. The algorithm rewards consistency. So does trust.", workChallenge: "Create a content calendar for the next 30 days. What will you post, where, and when? Consistency beats sporadic brilliance.", lifeChallenge: "Apply consistency to all communication: regular check-ins with friends, steady LinkedIn presence, reliable responses. Consistency IS your brand.", memoryTrick: "Virality is LIGHTNING. Consistency is SUNRISE. Lightning is exciting but unpredictable. Sunrise is reliable and people plan their lives around it." },
  { day: 81, phase: 5, type: "bite", title: "Engaging With Your Audience", content: "Communication is 2-way, especially on social media. Reply to every comment. Ask questions in your captions. Create polls. Make your audience feel like a COMMUNITY, not spectators.", workChallenge: "Respond to every comment on your last 3 YouTube videos or LinkedIn posts. Not 'Thanks!' but genuine, thoughtful responses.", lifeChallenge: "In real life too: follow up on conversations. 'You mentioned X last week, how did that go?' People remember those who remember them.", memoryTrick: "A monologue builds a stage. A dialogue builds a COMMUNITY. Communities last longer." },
  { day: 82, phase: 5, type: "deep", title: "Building a Content Strategy", content: "Random content builds nothing. A strategy builds an audience. Define your pillars: for Vishwa Motovlogs, maybe Solo Travel, Life Philosophy, and Hidden Gems. Every piece of content should fit a pillar.", workChallenge: "Define 3 content pillars for your professional brand. Example: Engineering Excellence, Growth Mindset, Observability. Every LinkedIn post should fit one.", lifeChallenge: "Define 3 pillars for Vishwa Motovlogs. Every video, short, and post should align. Clarity of purpose attracts the right audience.", memoryTrick: "Content pillars are TRAIN TRACKS. Without them, your content goes everywhere. With them, it reaches a DESTINATION." },
  { day: 83, phase: 5, type: "bite", title: "LinkedIn: Your Professional Megaphone", content: "LinkedIn isn't a resume. It's a daily newspaper you publish about YOUR expertise. Share insights, not updates. Teach, don't brag. Be the person others follow to learn something.", workChallenge: "Write and publish one LinkedIn post this week about a technical lesson you learned. Use the hook-story-insight-CTA formula from Phase 3.", lifeChallenge: "Optimize your LinkedIn headline. Not 'Senior Software Engineer at BHN' but something that shows your VALUE: 'Building reliable email systems at scale | 1% better every day'", memoryTrick: "Your LinkedIn is a BILLBOARD on the highway of your industry. Make sure it says something worth slowing down for." },
  { day: 84, phase: 5, type: "practice", title: "Week 12 Practice: Create and Ship", content: "This week, create and PUBLISH one piece of content on every platform you're active on.", workChallenge: "Publish: 1 LinkedIn post, 1 internal tech insight on Slack/Teams, and 1 piece of documentation improvement. Ship, don't hoard.", lifeChallenge: "Publish: 1 YouTube video or Short, 1 Instagram story or post. The goal isn't perfection. It's SHIPPING.", memoryTrick: "A draft in your notes helps nobody. A published piece, even imperfect, helps SOMEONE. Ship it." },
  { day: 85, phase: 5, type: "bite", title: "Public Speaking: Beyond the Screen", content: "Present at a meetup, a tech talk, a team knowledge-sharing session. Speaking publicly accelerates your growth, your network, and your confidence faster than anything else.", workChallenge: "Volunteer for one internal presentation or knowledge-sharing session at BHN in the next 30 days. Topic: anything you're expert in.", lifeChallenge: "Present at a local meetup or community event. Even a 5-minute lightning talk. The stage amplifies your voice exponentially.", memoryTrick: "Every great speaker started with a SHAKY first talk. The first time is terrifying. The tenth time is natural. Start with one." },
  { day: 86, phase: 5, type: "bite", title: "Handling Online Criticism", content: "The bigger your voice, the more criticism you'll receive. Not all criticism is valid. Learn to distinguish: constructive feedback (gold) vs trolling (noise). Respond to the first. Ignore the second.", workChallenge: "Create a mental framework: 'Is this person trying to help me improve, or trying to feel superior?' Respond only to the first category.", lifeChallenge: "If you receive a negative comment on YouTube or social media, respond with grace: 'Thanks for the perspective. I'll think about that.' Kill them with maturity.", memoryTrick: "Criticism from above is COACHING. Criticism from below is HATING. The difference is in the INTENT. Learn to tell them apart." },
  { day: 87, phase: 5, type: "bite", title: "Collaboration as Communication", content: "The highest form of communication isn't solo broadcasting. It's collaborative creation. Guest videos, co-written articles, pair programming, cross-team projects. Together is louder.", workChallenge: "Propose one collaborative effort at work: a joint tech talk, a co-authored doc, or a cross-team knowledge session.", lifeChallenge: "Reach out to another content creator for a collaboration. Even a shoutout or a response video. Collaboration builds community faster than solo work.", memoryTrick: "1 voice is a note. 2 voices are a chord. A CHORD resonates further than any single note." },
  { day: 88, phase: 5, type: "bite", title: "Your Communication Dashboard", content: "Track your communication growth like you track metrics at work. Engagement rates, response quality, speaking opportunities, content published. What gets measured gets improved.", workChallenge: "Create a simple monthly communication tracker: Posts published, Presentations given, Feedback received, Connections made.", lifeChallenge: "Track your YouTube growth monthly: subscribers, watch time, comments. Not for vanity. For DIRECTION. Where are you growing? Where are you stagnant?", memoryTrick: "A dashboard for your VOICE is as important as a dashboard for your CODE. Monitor, measure, improve." },
  { day: 89, phase: 5, type: "deep", title: "Your Communication Brand", content: "After 89 days, you've built a communication IDENTITY. You listen deeply, speak clearly, write sharply, connect genuinely, and amplify authentically. That combination is rare and powerful.", workChallenge: "Write your communication brand statement: 'I communicate with [3 qualities].' Share it with your manager as part of your professional identity.", lifeChallenge: "For Vishwa Motovlogs, write your channel's communication promise: what will viewers ALWAYS get from you? Consistency, authenticity, and what else?", memoryTrick: "Your communication brand is the ECHO you leave behind. Long after you stop talking, people remember HOW you made them feel." },
  { day: 90, phase: 5, type: "practice", title: "GRADUATION: The Communicator's Manifesto", content: "90 days. 5 phases. One transformed communicator. You can now listen like a therapist, speak like a leader, write like a craftsman, connect like a bridge-builder, and amplify like a signal tower.", workChallenge: "Write your 1-page Communication Manifesto: your listening principles, speaking rules, writing standards, connection strategy, and amplification goals. This is gold for your 5-star review.", lifeChallenge: "Create a Motovlogs video or LinkedIn post about your 90-day communication journey. Teaching your journey helps others start theirs. That's legacy.", memoryTrick: "Day 1, you heard noise. Day 90, you hear MEANING. Day 1, you spoke words. Day 90, you speak IMPACT. The masterclass ends. The communicator keeps growing." },
];

const typeLabel = (t) => t === "bite" ? "5-min Bite" : t === "deep" ? "Deep Dive" : "Practice Day";
const typeIcon = (t) => t === "bite" ? "⚡" : t === "deep" ? "🌊" : "🏋️";

export default function App() {
  const [dark, setDark] = useState(true);
  const [selPhase, setSelPhase] = useState(null);
  const [selDay, setSelDay] = useState(null);
  const [done, setDone] = useState(() => { try { return JSON.parse(localStorage.getItem("masterclass_communication_done")) || {}; } catch { return {}; } });
  const [vw, setVw] = useState("home");
  const ref = useRef(null);
  useEffect(() => { localStorage.setItem("masterclass_communication_done", JSON.stringify(done)); }, [done]);
  const toggle = (d) => setDone((p) => ({ ...p, [d]: !p[d] }));
  const ct = Object.values(done).filter(Boolean).length;
  const pct = Math.round((ct / 90) * 100);
  const phase = selPhase ? PHASES.find((p) => p.id === selPhase) : null;

  useEffect(() => { ref.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [selDay]);

  const m = dark ? "dark" : "light";
  const t = {
    bg: dark ? "#0c0a08" : "#fdfbf7",
    surface: dark ? "rgba(18,15,12,0.9)" : "rgba(255,253,248,0.9)",
    surfHov: dark ? "rgba(24,20,16,0.96)" : "rgba(250,247,240,0.97)",
    bdr: dark ? "rgba(255,220,180,0.06)" : "rgba(120,80,40,0.08)",
    txt: dark ? "#f0ebe4" : "#1c1814",
    sub: dark ? "#9a8e80" : "#7a6e60",
    mut: dark ? "#605848" : "#b0a898",
    card: dark ? "rgba(16,13,10,0.75)" : "rgba(255,252,246,0.75)",
    ring: dark ? "#251f18" : "#ece6dc",
    tag: dark ? "rgba(0,0,0,0.35)" : "rgba(80,60,30,0.04)",
    togBg: dark ? "rgba(255,220,180,0.06)" : "rgba(80,60,30,0.06)",
    hero: dark
      ? "radial-gradient(ellipse at 15% 0%, rgba(232,168,124,0.1), transparent 45%), radial-gradient(ellipse at 85% 0%, rgba(94,234,212,0.08), transparent 45%), radial-gradient(ellipse at 50% 90%, rgba(253,224,71,0.06), transparent 50%)"
      : "radial-gradient(ellipse at 15% 0%, rgba(194,112,62,0.05), transparent 45%), radial-gradient(ellipse at 85% 0%, rgba(13,148,136,0.04), transparent 45%), radial-gradient(ellipse at 50% 90%, rgba(202,138,4,0.03), transparent 50%)",
  };
  const hGrad = dark
    ? "linear-gradient(135deg, #e8a87c 0%, #5eead4 30%, #c4b5fd 60%, #fda4af 80%, #fde047 100%)"
    : "linear-gradient(135deg, #c2703e 0%, #0d9488 30%, #7c3aed 60%, #e11d48 80%, #ca8a04 100%)";

  const Tog = () => (
    <button onClick={() => setDark(!dark)} style={{ position: "fixed", top: 14, right: 14, zIndex: 999, background: t.togBg, backdropFilter: "blur(14px)", border: `1px solid ${t.bdr}`, borderRadius: 40, padding: "7px 14px", cursor: "pointer", display: "flex", alignItems: "center", gap: 7, color: t.sub, fontSize: 12.5, fontFamily: "'Fira Code', monospace", transition: "all 0.35s", letterSpacing: 0.5 }}>
      <span style={{ fontSize: 15 }}>{dark ? "☀️" : "🌙"}</span>{dark ? "Light" : "Dark"}
    </button>
  );

  const phaseNav = (currentId) => (
    <div style={{ display: "flex", gap: 6, padding: "0 20px", overflowX: "auto", WebkitOverflowScrolling: "touch", scrollbarWidth: "none", marginBottom: 8 }}>
      {PHASES.map(p => (
        <button key={p.id} onClick={() => { setSelPhase(p.id); setSelDay(null); }} style={{ background: p.id === currentId ? `${p.accent[m]}18` : "transparent", border: `1px solid ${p.id === currentId ? `${p.accent[m]}44` : t.bdr}`, color: p.id === currentId ? p.accent[m] : t.mut, padding: "5px 12px", borderRadius: 8, cursor: "pointer", fontSize: 11, fontFamily: "'Fira Code', monospace", whiteSpace: "nowrap", transition: "all 0.2s", letterSpacing: 0.5 }}>{p.icon} {p.title}</button>
      ))}
    </div>
  );

  if (vw === "home") {
    return (
      <div style={{ fontFamily: "'Source Sans 3', sans-serif", background: t.bg, minHeight: "100vh", color: t.txt, transition: "background 0.45s, color 0.45s" }}>
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@300;400;500;600;700;800&family=Fira+Code:wght@300;400;500;600&display=swap" rel="stylesheet" />
        <style>{`@keyframes fu{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}.pc:hover{transform:translateY(-2px) scale(1.005);}.pc{transition:all 0.3s cubic-bezier(0.4,0,0.2,1)}*::-webkit-scrollbar{display:none}`}</style>
        <Tog />
        <div style={{ position: "relative", padding: "52px 24px 28px", textAlign: "center", overflow: "hidden" }}>
          <div style={{ position: "absolute", inset: 0, background: t.hero, pointerEvents: "none" }} />
          <div style={{ position: "relative", zIndex: 1 }}>
            <div style={{ fontSize: 11, letterSpacing: 7, textTransform: "uppercase", fontFamily: "'Fira Code', monospace", color: t.mut, marginBottom: 14 }}>90-Day Masterclass</div>
            <h1 style={{ fontFamily: "'Source Sans 3', sans-serif", fontSize: "clamp(32px,6.5vw,52px)", fontWeight: 800, lineHeight: 1.05, margin: "0 0 6px", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>Communication</h1>
            <p style={{ fontSize: 13.5, color: t.sub, fontFamily: "'Fira Code', monospace", margin: "10px 0 30px", fontWeight: 300, letterSpacing: 2 }}>listen / speak / write / connect / amplify</p>
            <div style={{ display: "inline-flex", alignItems: "center", gap: 20, background: t.surface, border: `1px solid ${t.bdr}`, borderRadius: 20, padding: "18px 28px", backdropFilter: "blur(16px)" }}>
              <div style={{ position: "relative", width: 60, height: 60 }}>
                <svg width="60" height="60" viewBox="0 0 60 60">
                  <circle cx="30" cy="30" r="26" fill="none" stroke={t.ring} strokeWidth="3" />
                  <defs><linearGradient id="pg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#e8a87c"/><stop offset="25%" stopColor="#5eead4"/><stop offset="50%" stopColor="#c4b5fd"/><stop offset="75%" stopColor="#fda4af"/><stop offset="100%" stopColor="#fde047"/></linearGradient></defs>
                  <circle cx="30" cy="30" r="26" fill="none" stroke="url(#pg)" strokeWidth="3" strokeDasharray={`${(pct/100)*163.4} 163.4`} strokeLinecap="round" transform="rotate(-90 30 30)" style={{ transition: "stroke-dasharray 0.7s cubic-bezier(0.4,0,0.2,1)" }} />
                </svg>
                <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 15, fontWeight: 600, fontFamily: "'Fira Code', monospace", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>{pct}%</div>
              </div>
              <div style={{ textAlign: "left" }}>
                <div style={{ fontSize: 26, fontWeight: 800 }}>{ct}<span style={{ fontSize: 14, color: t.mut, fontWeight: 400 }}> / 90</span></div>
                <div style={{ fontSize: 10.5, color: t.mut, fontFamily: "'Fira Code', monospace", letterSpacing: 1.5 }}>days completed</div>
              </div>
            </div>
          </div>
        </div>
        <div style={{ padding: "8px 20px 48px", maxWidth: 720, margin: "0 auto" }}>
          {PHASES.map((p, i) => {
            const pl = ALL_LESSONS.filter(l => l.phase === p.id);
            const pc = pl.filter(l => done[l.day]).length;
            const ac = p.accent[m];
            return (
              <div key={p.id} className="pc" onClick={() => { setSelPhase(p.id); setVw("phase"); }} style={{ background: t.card, border: `1px solid ${t.bdr}`, borderRadius: 16, padding: "22px 24px", cursor: "pointer", marginBottom: 12, borderLeft: `3px solid ${ac}`, animation: `fu 0.55s ease ${i*0.1}s both`, position: "relative", overflow: "hidden", backdropFilter: "blur(10px)" }}>
                <div style={{ position: "absolute", top: -20, right: -20, width: 130, height: 130, background: `radial-gradient(circle, ${p.glow}, transparent 65%)`, pointerEvents: "none", opacity: dark ? 0.5 : 0.3 }} />
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", position: "relative" }}>
                  <div style={{ display: "flex", gap: 14, alignItems: "center" }}>
                    <span style={{ fontSize: 30 }}>{p.icon}</span>
                    <div>
                      <div style={{ fontSize: 10, color: ac, letterSpacing: 4, textTransform: "uppercase", fontFamily: "'Fira Code', monospace", marginBottom: 4 }}>Phase {p.id} | {p.days}</div>
                      <div style={{ fontSize: 20, fontWeight: 800 }}>{p.title}</div>
                      <div style={{ fontSize: 12.5, color: t.sub, fontWeight: 400, marginTop: 2 }}>{p.subtitle}</div>
                    </div>
                  </div>
                  <div style={{ fontFamily: "'Fira Code', monospace", fontSize: 12, color: t.mut, textAlign: "right", minWidth: 48 }}>
                    <span style={{ color: ac, fontWeight: 600 }}>{pc}</span>/{pl.length}
                  </div>
                </div>
                <div style={{ marginTop: 16, height: 2.5, background: t.ring, borderRadius: 3, overflow: "hidden" }}>
                  <div style={{ height: "100%", width: `${(pc/pl.length)*100}%`, background: `linear-gradient(90deg, ${ac}, ${ac}66)`, borderRadius: 3, transition: "width 0.5s ease" }} />
                </div>
                <div style={{ marginTop: 11, fontSize: 10.5, color: t.mut, padding: "7px 12px", background: t.tag, borderRadius: 8, fontFamily: "'Fira Code', monospace", lineHeight: 1.5 }}>🧠 {p.mnemonic}</div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  if (vw === "phase" && phase) {
    const pl = ALL_LESSONS.filter(l => l.phase === phase.id);
    const ac = phase.accent[m];
    return (
      <div style={{ fontFamily: "'Source Sans 3', sans-serif", background: t.bg, minHeight: "100vh", color: t.txt, transition: "background 0.45s, color 0.45s" }}>
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@300;400;500;600;700;800&family=Fira+Code:wght@300;400;500;600&display=swap" rel="stylesheet" />
        <style>{`@keyframes fu{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}@keyframes ex{from{opacity:0;max-height:0}to{opacity:1;max-height:900px}}*::-webkit-scrollbar{display:none}`}</style>
        <Tog />
        <div style={{ position: "relative", overflow: "hidden" }}>
          <div style={{ position: "absolute", inset: 0, background: phase.gradient[m], opacity: dark ? 0.5 : 0.3, transition: "opacity 0.4s" }} />
          <div style={{ position: "relative", zIndex: 1, padding: "20px 20px 6px" }}>
            <button onClick={() => { setVw("home"); setSelPhase(null); setSelDay(null); }} style={{ background: t.togBg, border: `1px solid ${t.bdr}`, color: t.sub, padding: "7px 16px", borderRadius: 10, cursor: "pointer", fontSize: 12, fontFamily: "'Fira Code', monospace" }}>{"←"} Back</button>
          </div>
          <div style={{ position: "relative", zIndex: 1, padding: "8px 24px 20px", textAlign: "center" }}>
            <span style={{ fontSize: 42 }}>{phase.icon}</span>
            <h2 style={{ fontSize: 32, fontWeight: 800, margin: "8px 0 4px" }}>Phase {phase.id}: {phase.title}</h2>
            <p style={{ color: t.sub, fontWeight: 400, margin: 0, fontSize: 14 }}>{phase.subtitle}</p>
            <p style={{ color: t.sub, fontSize: 13, marginTop: 10, maxWidth: 480, marginInline: "auto", lineHeight: 1.6 }}>{phase.description}</p>
            <div style={{ marginTop: 12, display: "inline-block", fontSize: 11, color: ac, padding: "6px 14px", background: `${ac}12`, borderRadius: 8, fontFamily: "'Fira Code', monospace", border: `1px solid ${ac}22` }}>{phase.mnemonic}</div>
          </div>
        </div>
        {phaseNav(phase.id)}
        <div style={{ padding: "8px 20px 48px", maxWidth: 720, margin: "0 auto" }}>
          {pl.map((l, i) => {
            const op = selDay === l.day;
            return (
              <div key={l.day} ref={op ? ref : null} style={{ marginBottom: 8, animation: `fu 0.4s ease ${i*0.03}s both` }}>
                <div onClick={() => setSelDay(op ? null : l.day)} style={{ background: op ? t.surfHov : t.card, border: `1px solid ${op ? `${ac}40` : t.bdr}`, borderRadius: op ? "14px 14px 0 0" : 14, padding: "14px 18px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", transition: "all 0.25s", backdropFilter: "blur(8px)" }}>
                  <div style={{ display: "flex", gap: 14, alignItems: "center" }}>
                    <div onClick={e => { e.stopPropagation(); toggle(l.day); }} style={{ width: 26, height: 26, borderRadius: "50%", border: done[l.day] ? `2.5px solid ${ac}` : `2px solid ${t.bdr}`, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", background: done[l.day] ? `${ac}15` : "transparent", transition: "all 0.25s", flexShrink: 0 }}>
                      {done[l.day] && <span style={{ color: ac, fontSize: 12, fontWeight: 700 }}>{"✓"}</span>}
                    </div>
                    <div>
                      <div style={{ fontSize: 10, color: t.mut, fontFamily: "'Fira Code', monospace", letterSpacing: 1.2 }}>Day {l.day} | {typeIcon(l.type)} {typeLabel(l.type)}</div>
                      <div style={{ fontSize: 15, fontWeight: 600, color: done[l.day] ? t.mut : t.txt, textDecoration: done[l.day] ? "line-through" : "none", marginTop: 3 }}>{l.title}</div>
                    </div>
                  </div>
                  <span style={{ color: t.mut, fontSize: 14, transform: op ? "rotate(180deg)" : "rotate(0)", transition: "transform 0.25s", flexShrink: 0 }}>{"▾"}</span>
                </div>
                {op && (
                  <div style={{ background: t.surfHov, border: `1px solid ${ac}40`, borderTop: "none", borderRadius: "0 0 14px 14px", padding: 22, animation: "ex 0.35s ease", overflow: "hidden", backdropFilter: "blur(8px)" }}>
                    <p style={{ color: t.txt, lineHeight: 1.8, margin: "0 0 20px", fontSize: 14.5, fontWeight: 300 }}>{l.content}</p>
                    {[
                      { label: "💼 Work Challenge (BHN)", text: l.workChallenge, c: dark ? ["rgba(232,168,124,0.06)","rgba(232,168,124,0.14)","#e8a87c"] : ["rgba(194,112,62,0.04)","rgba(194,112,62,0.1)","#c2703e"] },
                      { label: "🌱 Life Challenge", text: l.lifeChallenge, c: dark ? ["rgba(94,234,212,0.05)","rgba(94,234,212,0.12)","#5eead4"] : ["rgba(13,148,136,0.04)","rgba(13,148,136,0.09)","#0d9488"] },
                      { label: "🧠 Memory Trick", text: l.memoryTrick, c: dark ? ["rgba(253,224,71,0.05)","rgba(253,224,71,0.13)","#fde047"] : ["rgba(202,138,4,0.04)","rgba(202,138,4,0.1)","#ca8a04"], highlight: true },
                    ].map((s, si) => (
                      <div key={si} style={{ background: s.c[0], border: `1px solid ${s.c[1]}`, borderRadius: 12, padding: "14px 18px", marginBottom: si < 2 ? 10 : 0 }}>
                        <div style={{ fontSize: 10, color: s.c[2], letterSpacing: 2.5, textTransform: "uppercase", fontFamily: "'Fira Code', monospace", marginBottom: 6 }}>{s.label}</div>
                        <p style={{ color: s.highlight ? (dark ? "#fef08a" : "#854d0e") : t.txt, fontSize: s.highlight ? 14 : 13.5, lineHeight: 1.65, margin: 0, fontWeight: s.highlight ? 500 : 300 }}>{s.text}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    );
  }
  return null;
}
