import { useState, useEffect, useRef } from "react";

const DAYS = [
  { id: 1, title: "FOUNDATIONS", subtitle: "Why patterns exist and how to think in patterns", icon: "🧱", accent: { dark: "#38bdf8", light: "#0369a1" }, glow: "rgba(56,189,248,0.2)", gradient: { dark: "linear-gradient(160deg, #0a1628 0%, #0f2440 50%, #081420 100%)", light: "linear-gradient(160deg, #eef4fb 0%, #e2eef8 50%, #f0f6fc 100%)" } },
  { id: 2, title: "CREATIONAL", subtitle: "How objects are born", icon: "🏭", accent: { dark: "#4ade80", light: "#15803d" }, glow: "rgba(74,222,128,0.2)", gradient: { dark: "linear-gradient(160deg, #0a1a10 0%, #123020 50%, #081a0e 100%)", light: "linear-gradient(160deg, #eefaf0 0%, #ddf5e5 50%, #f0fcf2 100%)" } },
  { id: 3, title: "STRUCTURAL I", subtitle: "How objects connect (The Essentials)", icon: "🏗️", accent: { dark: "#fbbf24", light: "#b45309" }, glow: "rgba(251,191,36,0.2)", gradient: { dark: "linear-gradient(160deg, #1a1508 0%, #302510 50%, #1c1808 100%)", light: "linear-gradient(160deg, #fef9ed 0%, #faf0d8 50%, #fffaf0 100%)" } },
  { id: 4, title: "STRUCTURAL II", subtitle: "How objects connect (The Power Patterns)", icon: "🔧", accent: { dark: "#fb923c", light: "#c2410c" }, glow: "rgba(251,146,60,0.2)", gradient: { dark: "linear-gradient(160deg, #1a100a 0%, #302012 50%, #1c120a 100%)", light: "linear-gradient(160deg, #fef5ed 0%, #faecd8 50%, #fff6f0 100%)" } },
  { id: 5, title: "BEHAVIORAL I", subtitle: "How objects talk (Communication Patterns)", icon: "🗣️", accent: { dark: "#c084fc", light: "#7e22ce" }, glow: "rgba(192,132,252,0.2)", gradient: { dark: "linear-gradient(160deg, #150a20 0%, #251540 50%, #180c25 100%)", light: "linear-gradient(160deg, #f8f0ff 0%, #f0e0fc 50%, #faf2ff 100%)" } },
  { id: 6, title: "BEHAVIORAL II", subtitle: "How objects talk (Advanced Orchestration)", icon: "🧠", accent: { dark: "#f472b6", light: "#db2777" }, glow: "rgba(244,114,182,0.2)", gradient: { dark: "linear-gradient(160deg, #200a15 0%, #381530 50%, #220c18 100%)", light: "linear-gradient(160deg, #fff0f5 0%, #fce0ec 50%, #fff2f7 100%)" } },
  { id: 7, title: "MASTERY", subtitle: "Combining patterns + modern patterns + when NOT to use them", icon: "🏆", accent: { dark: "#fde047", light: "#ca8a04" }, glow: "rgba(253,224,71,0.2)", gradient: { dark: "linear-gradient(160deg, #1a1808 0%, #302a10 50%, #1c1a08 100%)", light: "linear-gradient(160deg, #fffced 0%, #faf5d8 50%, #fffdf0 100%)" } },
];

const ALL_LESSONS = [
  // DAY 1: FOUNDATIONS
  { day: 1, slot: 1, title: "What is a Design Pattern?", type: "concept", content: "A design pattern is a REUSABLE SOLUTION to a commonly occurring problem in software design. It's not code you copy-paste. It's a TEMPLATE for thinking. Like a recipe: it tells you the approach, but you cook it with your own ingredients.", realWorld: "Think of a restaurant kitchen. The recipe (pattern) says 'sear the protein, deglaze, make sauce.' Whether it's chicken or fish, the PATTERN is the same. The implementation changes.", bhnExample: "At BHN, your email centralization uses several patterns already: Observer (events triggering emails), Strategy (different email providers), Factory (creating email objects from templates). You just didn't name them.", memoryTrick: "A pattern is a RECIPE, not a dish. The recipe works in any kitchen. The dish depends on your ingredients." },
  { day: 1, slot: 2, title: "The 3 Categories", type: "concept", content: "All 23 Gang of Four (GoF) patterns fall into 3 categories:\n\nCREATIONAL (5 patterns) - How objects are BORN: Singleton, Factory Method, Abstract Factory, Builder, Prototype.\n\nSTRUCTURAL (7 patterns) - How objects CONNECT: Adapter, Bridge, Composite, Decorator, Facade, Flyweight, Proxy.\n\nBEHAVIORAL (11 patterns) - How objects TALK: Strategy, Observer, Command, Chain of Responsibility, Iterator, Mediator, Memento, State, Template Method, Visitor, Interpreter.", realWorld: "Think of building a house. Creational = how you manufacture the bricks. Structural = how you arrange bricks into walls. Behavioral = how rooms communicate (plumbing, wiring, doors).", bhnExample: "Your BHN work touches all three: Creational (how email objects are created), Structural (how services compose together), Behavioral (how events flow through SQS to BNS).", memoryTrick: "C.S.B. - Created (born), Structured (connected), Behaved (communicated). Every object goes through all three." },
  { day: 1, slot: 3, title: "SOLID Principles: The Foundation", type: "concept", content: "Before patterns, understand SOLID:\n\nS - Single Responsibility: One class, one job.\nO - Open/Closed: Open for extension, closed for modification.\nL - Liskov Substitution: Subtypes must be substitutable for base types.\nI - Interface Segregation: Many small interfaces > one big one.\nD - Dependency Inversion: Depend on abstractions, not concretions.\n\nEvery design pattern is built on one or more SOLID principles.", realWorld: "S = A chef only cooks (doesn't do billing). O = You can add new menu items without rewriting the kitchen. L = Any chef can fill in for another. I = Waiters don't need to know kitchen operations. D = The menu depends on 'food' concept, not specific dishes.", bhnExample: "In Laravel, the Service Container is Dependency Inversion. Eloquent models follow Single Responsibility. Your email interfaces should follow Interface Segregation (IEmailSender, ITemplateResolver, not one giant IEmailService).", memoryTrick: "SOLID is the GRAMMAR. Patterns are the LITERATURE. You need grammar before you can write novels." },
  { day: 1, slot: 4, title: "When to Use (and NOT Use) Patterns", type: "concept", content: "USE patterns when: you see a recurring problem, you need flexibility for future changes, or multiple developers need to understand the architecture.\n\nDON'T use patterns when: the problem is simple (don't over-engineer), you're the only one reading the code and it's a quick script, or you're using a pattern just because you learned it.\n\nThe WORST mistake: applying a pattern where none is needed. That's like using a bulldozer to plant a flower.", realWorld: "A restaurant doesn't need a reservation system for 10 seats. But a 200-seat restaurant does. Match the pattern to the SCALE of the problem.", bhnExample: "Your email centralization NEEDS patterns (multiple providers, templates, queues). A simple logging helper does NOT need the full Strategy pattern. Use judgment.", memoryTrick: "Patterns are MEDICINE. The right one heals. The wrong one poisons. No medicine at all when you're healthy." },

  // DAY 2: CREATIONAL PATTERNS
  { day: 2, slot: 1, title: "Singleton - One and Only One", type: "creational", content: "WHAT: Ensures a class has only ONE instance and provides a global access point to it.\n\nWHEN: Database connections, configuration managers, logging services, cache instances.\n\nHOW: Private constructor, static method that returns the single instance.\n\nDANGER: Overuse makes code hard to test. In Laravel, use the Service Container's singleton binding instead of implementing it yourself.", realWorld: "A country has ONE president at a time. You don't create a new president for every decision. You access THE president.", bhnExample: "In Laravel: App::singleton('email.config', fn() => new EmailConfig()); Now every class gets the SAME config instance. Your Redis connection in schemes-api is effectively a singleton.", memoryTrick: "Singleton = there can be only ONE. Like Highlander. But unlike Highlander, it should be used sparingly." },
  { day: 2, slot: 2, title: "Factory Method - The Object Creator", type: "creational", content: "WHAT: Defines an interface for creating objects, but lets subclasses decide WHICH class to instantiate.\n\nWHEN: You don't know ahead of time which class to create. The decision depends on input, config, or context.\n\nHOW: A creator class with a method that returns objects. Subclasses override to return different types.", realWorld: "A logistics company has a transport method. Ship for international, Truck for domestic. The FACTORY decides based on destination. Client code just says 'create transport.'", bhnExample: "Your email system: EmailFactory::create('marketing') returns MarketingEmail. EmailFactory::create('transactional') returns TransactionalEmail. Same interface, different objects based on type.", memoryTrick: "Factory = the BIRTH CERTIFICATE office. You tell them what you need, they create the right object. You don't build it yourself." },
  { day: 2, slot: 3, title: "Abstract Factory - Factory of Factories", type: "creational", content: "WHAT: Creates FAMILIES of related objects without specifying concrete classes. A factory that produces other factories.\n\nWHEN: You need to create groups of related objects that must be used together (e.g., UI themes: DarkButton + DarkInput + DarkPanel).\n\nHOW: An abstract factory interface with methods for each product type. Concrete factories implement it for each family.", realWorld: "IKEA has different furniture lines (Modern, Classic, Rustic). Each line has a sofa, table, and chair that MATCH. The abstract factory is 'IKEA line.' Concrete factories are 'Modern line', 'Classic line.'", bhnExample: "Email provider families: AWSEmailFactory creates AWSSender + AWSTemplate + AWSTracker. SendGridFactory creates SendGridSender + SendGridTemplate + SendGridTracker. All implement the same interfaces.", memoryTrick: "Abstract Factory = a DEPARTMENT STORE. Each department (factory) sells matching products. You pick the department, everything inside matches." },
  { day: 2, slot: 4, title: "Builder - Step by Step Construction", type: "creational", content: "WHAT: Constructs complex objects step by step. Separates construction from representation.\n\nWHEN: Object has many optional parameters, or construction involves multiple steps.\n\nHOW: A builder class with methods like setSubject(), setBody(), addAttachment(), then a build() method that returns the final object.", realWorld: "Building a custom pizza: choose crust, add sauce, add toppings, select size. The BUILDER assembles it step by step. You don't get a half-built pizza.", bhnExample: "EmailBuilder::create()->to('user@example.com')->subject('Welcome')->template('onboarding')->withData(['name' => 'Vishwanath'])->priority('high')->build(); Each step is optional. The build() validates and creates.", memoryTrick: "Builder = SUBWAY sandwich artist. You choose each ingredient step by step. At the end, you get a complete sandwich." },
  { day: 2, slot: 5, title: "Prototype - Clone, Don't Create", type: "creational", content: "WHAT: Creates new objects by CLONING an existing object (the prototype) instead of creating from scratch.\n\nWHEN: Object creation is expensive (database calls, complex initialization), and you need many similar objects with small variations.\n\nHOW: Implement a clone() method. Copy the prototype and modify what's different.", realWorld: "Instead of writing a new resume from scratch for every job, you CLONE your template resume and customize it. The base stays the same.", bhnExample: "Email templates: clone a base template, modify subject/body for each campaign. $campaignEmail = clone $baseTemplate; $campaignEmail->setSubject('New Campaign');", memoryTrick: "Prototype = PHOTOCOPY. Don't rewrite the original. Copy it and mark it up." },

  // DAY 3: STRUCTURAL I (The Essentials)
  { day: 3, slot: 1, title: "Adapter - The Translator", type: "structural", content: "WHAT: Allows incompatible interfaces to work together. Converts the interface of one class into another that clients expect.\n\nWHEN: Integrating third-party libraries, legacy systems, or APIs with different interfaces.\n\nHOW: Create a wrapper class that implements the expected interface and delegates to the incompatible class.", realWorld: "A power adapter converts a US plug to fit an Indian socket. The DEVICE doesn't change. The SOCKET doesn't change. The adapter bridges them.", bhnExample: "Wrapping BNS API: class BnsEmailAdapter implements EmailSenderInterface { public function send(Email $email) { return $this->bnsClient->sendRaw($email->toArray()); } }. Your code talks to EmailSenderInterface. The adapter translates to BNS.", memoryTrick: "Adapter = UNIVERSAL TRAVEL ADAPTER. Different plugs, same electricity. Different APIs, same interface." },
  { day: 3, slot: 2, title: "Facade - The Simplifier", type: "structural", content: "WHAT: Provides a simplified interface to a complex subsystem. Hides complexity behind a clean API.\n\nWHEN: A subsystem has many classes and the client doesn't need to know about all of them.\n\nHOW: Create a facade class with simple methods that orchestrate the complex subsystem internally.", realWorld: "A hotel concierge is a facade. You say 'I need a restaurant reservation.' Behind the scenes, they call the restaurant, check availability, book the table, confirm with you. You just talked to ONE person.", bhnExample: "EmailFacade::send('welcome', $user); Behind this one line: it loads the template, resolves variables, creates the email object, dispatches to SQS, logs the attempt. The caller sees ONE method.", memoryTrick: "Facade = RECEPTION DESK. One point of contact. All complexity hidden behind the counter." },
  { day: 3, slot: 3, title: "Decorator - The Wrapper", type: "structural", content: "WHAT: Adds new behavior to objects dynamically by wrapping them in decorator objects. Each decorator adds one responsibility.\n\nWHEN: You want to add features to objects without modifying their class. Features can be mixed and matched.\n\nHOW: Decorators implement the same interface as the original. Each wraps the previous, adding behavior before/after delegating.", realWorld: "Coffee: start with basic coffee ($2). Add milk (+$0.50). Add whipped cream (+$0.75). Add caramel (+$1). Each addition WRAPS the previous, adding its cost and description.", bhnExample: "Email decorators: $email = new LoggingDecorator(new RetryDecorator(new RateLimitDecorator(new BasicEmailSender())))); Each layer adds behavior: rate limiting, retry logic, logging. The core sender stays clean.", memoryTrick: "Decorator = RUSSIAN NESTING DOLLS. Each layer wraps the previous one, adding something new. Open them all and the core is simple." },
  { day: 3, slot: 4, title: "Composite - The Tree Builder", type: "structural", content: "WHAT: Composes objects into tree structures. Lets clients treat individual objects and groups uniformly.\n\nWHEN: You have hierarchical data: file systems, org charts, menu structures, UI component trees.\n\nHOW: Both 'leaf' objects and 'composite' objects implement the same interface. Composites contain children (which can be leaves or other composites).", realWorld: "A file system: a Folder can contain Files and other Folders. You can get the size of a File (leaf) or a Folder (composite, which sums its children's sizes). Same operation, different levels.", bhnExample: "Email template groups: a TemplateGroup contains individual Templates and other TemplateGroups. $group->render() recursively renders all children. Same interface for single templates and groups.", memoryTrick: "Composite = a TREE. Branches (composites) hold leaves and other branches. Every node, whether branch or leaf, answers the same questions." },

  // DAY 4: STRUCTURAL II (Power Patterns)
  { day: 4, slot: 1, title: "Proxy - The Gatekeeper", type: "structural", content: "WHAT: Provides a substitute or placeholder for another object. Controls access to the original.\n\nTYPES: Virtual Proxy (lazy loading), Protection Proxy (access control), Remote Proxy (network access), Caching Proxy.\n\nWHEN: You need to add access control, caching, logging, or lazy loading without changing the original.", realWorld: "A security guard (proxy) at a building entrance. They check your ID before letting you access the real building. The building doesn't change. The guard adds a control layer.", bhnExample: "CachingEmailTemplateProxy: checks Redis first. If cached, returns it. If not, calls the real TemplateRepository, caches the result, then returns it. The real repo is unchanged.", memoryTrick: "Proxy = BODYGUARD. Same person behind them, but you go through the guard first. Access controlled, behavior added." },
  { day: 4, slot: 2, title: "Bridge - Decouple Abstraction from Implementation", type: "structural", content: "WHAT: Separates an abstraction from its implementation so both can vary independently. Uses composition instead of inheritance.\n\nWHEN: You have multiple dimensions of variation. Instead of creating a class for every combination, separate the dimensions.\n\nHOW: The abstraction holds a reference to the implementation. Both have separate hierarchies.", realWorld: "A remote control (abstraction) and a TV (implementation). Any remote can work with any TV. You can add new remotes WITHOUT changing TVs, and new TVs WITHOUT changing remotes.", bhnExample: "Email abstraction: NotificationEmail, MarketingEmail (abstraction hierarchy). Senders: SQSSender, HTTPSender, DirectSender (implementation hierarchy). Any email type can use any sender. Independent variation.", memoryTrick: "Bridge = a real BRIDGE connecting two separate lands. Abstraction land and Implementation land. They grow independently, connected by the bridge." },
  { day: 4, slot: 3, title: "Flyweight - Memory Optimizer", type: "structural", content: "WHAT: Shares common state across many objects to reduce memory usage. Separates intrinsic state (shared) from extrinsic state (unique per instance).\n\nWHEN: You have thousands of similar objects where most data is the same.\n\nHOW: A factory that returns shared instances for common data. Unique data is passed as parameters to methods.", realWorld: "In a text editor, each character 'A' could be a separate object. Flyweight: create ONE 'A' object and share it. The position (extrinsic) varies, but the glyph (intrinsic) is shared.", bhnExample: "Email template rendering: the template HTML (intrinsic, shared) is loaded once. The user-specific variables (extrinsic) are injected per send. Don't reload the template for each of 10,000 emails.", memoryTrick: "Flyweight = SHARED WARDROBE in a dorm. Everyone shares the suits (intrinsic). Each person brings their own shoes (extrinsic)." },
  { day: 4, slot: 4, title: "Adapter vs Facade vs Decorator vs Proxy", type: "comparison", content: "These four are often confused. Here's the key difference:\n\nADAPTER: Changes the INTERFACE to make incompatible things work together. 'Make this round peg fit a square hole.'\n\nFACADE: Simplifies a COMPLEX subsystem. 'I don't want to deal with 10 classes. Give me one simple API.'\n\nDECORATOR: Adds BEHAVIOR without changing the interface. 'Same interface, more features.'\n\nPROXY: Controls ACCESS to an object. 'Same interface, but I decide if/when you get through.'", realWorld: "Adapter = translator at a UN meeting. Facade = hotel concierge. Decorator = phone case (adds protection, same phone). Proxy = bouncer at a club (controls who enters).", bhnExample: "BnsAdapter adapts BNS to your interface. EmailFacade simplifies the whole email subsystem. LoggingDecorator adds logging to any sender. CachingProxy adds caching to template loading.", memoryTrick: "A.F.D.P. - Adapter TRANSLATES. Facade SIMPLIFIES. Decorator ENHANCES. Proxy CONTROLS." },

  // DAY 5: BEHAVIORAL I (Communication Patterns)
  { day: 5, slot: 1, title: "Strategy - Interchangeable Algorithms", type: "behavioral", content: "WHAT: Defines a family of algorithms, encapsulates each one, and makes them interchangeable. The client chooses which strategy to use at runtime.\n\nWHEN: You have multiple ways to do the same thing and want to switch between them easily.\n\nHOW: Define a strategy interface. Each algorithm implements it. The context holds a strategy and delegates to it.", realWorld: "Google Maps: you choose driving, walking, or transit. Same destination, different STRATEGY. The map app doesn't care which. It delegates to the chosen strategy.", bhnExample: "Email sending strategies: class SqsStrategy implements SendStrategy { ... } class HttpStrategy implements SendStrategy { ... }. Config determines which strategy: $sender = new EmailSender(config('email.strategy'));", memoryTrick: "Strategy = a TOOLBOX. Same job, different tools. The wrench and the pliers both tighten, but each works better in different situations." },
  { day: 5, slot: 2, title: "Observer - The Event System", type: "behavioral", content: "WHAT: Defines a one-to-many dependency. When one object changes state, all its dependents are notified automatically.\n\nWHEN: Events, pub/sub systems, UI updates, notification systems. Any time 'something happened' should trigger multiple reactions.\n\nHOW: Subject maintains a list of observers. When state changes, it calls update() on each observer.", realWorld: "A YouTube subscription. When a creator (subject) uploads a video, all subscribers (observers) get notified. The creator doesn't know or care who subscribes.", bhnExample: "Laravel events: UserRegistered event -> observers: SendWelcomeEmail, CreateDefaultSettings, NotifyAdmin. Each listener reacts independently. Adding a new reaction = adding a new listener, no changes to existing code.", memoryTrick: "Observer = NEWSPAPER SUBSCRIPTION. Publisher publishes. Subscribers react. Neither knows the other's internals." },
  { day: 5, slot: 3, title: "Command - Encapsulate Actions", type: "behavioral", content: "WHAT: Encapsulates a request as an object. Allows you to parameterize, queue, log, and undo operations.\n\nWHEN: Job queues, undo/redo, transaction logging, macro recording, deferred execution.\n\nHOW: A command interface with execute(). Each concrete command wraps a receiver and its action. Commands can be stored, queued, or reversed.", realWorld: "A restaurant order slip. The waiter (invoker) writes the order (command). The kitchen (receiver) executes it. The slip can be queued, prioritized, or cancelled. The waiter and kitchen are decoupled.", bhnExample: "SQS messages ARE commands. SendEmailCommand contains all info needed to send an email. The SQS consumer picks it up and executes it. If it fails, the command goes to DLQ. Perfectly decoupled.", memoryTrick: "Command = a SEALED ENVELOPE with instructions. Write it now, execute later, undo if needed. The envelope travels independently." },
  { day: 5, slot: 4, title: "Chain of Responsibility - Pass It Along", type: "behavioral", content: "WHAT: Passes a request along a chain of handlers. Each handler decides to process the request or pass it to the next handler.\n\nWHEN: Multiple objects might handle a request, and the handler isn't known in advance. Middleware pipelines, approval workflows, validation chains.\n\nHOW: Each handler has a reference to the next. It processes or delegates.", realWorld: "Customer support: first line support tries to help. If they can't, it escalates to L2, then L3, then engineering. The customer doesn't choose the handler. The CHAIN does.", bhnExample: "Laravel middleware IS Chain of Responsibility. Request -> AuthMiddleware -> RateLimitMiddleware -> LoggingMiddleware -> Controller. Each can handle, modify, or pass the request to the next.", memoryTrick: "Chain of Responsibility = a RELAY RACE. Each runner (handler) either finishes or passes the baton to the next." },
  { day: 5, slot: 5, title: "Iterator - Traverse Without Exposing", type: "behavioral", content: "WHAT: Provides a way to access elements of a collection sequentially without exposing its underlying representation.\n\nWHEN: You need to traverse different data structures (arrays, trees, graphs) with the same interface.\n\nHOW: An iterator interface with next(), hasNext(), current(). The collection provides an iterator without exposing internals.", realWorld: "A TV remote's channel up/down buttons. You don't know how channels are stored internally. You just press 'next.' That's an iterator.", bhnExample: "PHP's Iterator interface. Your email template collection: foreach ($templates as $template) works whether templates come from database, cache, or file system. The iteration logic is hidden.", memoryTrick: "Iterator = a PLAYLIST. You press next/previous. You don't care if songs are stored as MP3s, streams, or vinyl. You just navigate." },

  // DAY 6: BEHAVIORAL II (Advanced Orchestration)
  { day: 6, slot: 1, title: "State - Object Changes Behavior", type: "behavioral", content: "WHAT: Allows an object to change its behavior when its internal state changes. The object appears to change its class.\n\nWHEN: An object behaves differently based on its state, and state transitions are complex. Replaces large if/else or switch statements.\n\nHOW: Each state is a separate class implementing a state interface. The context delegates to the current state object.", realWorld: "A traffic light: Red state (stop behavior), Yellow state (caution behavior), Green state (go behavior). The light doesn't have if/else for each state. Each state IS a different object.", bhnExample: "Email lifecycle: DraftState -> QueuedState -> SendingState -> SentState -> FailedState. Each state knows what actions are valid. You can't 'send' a DraftState email directly. State enforces rules.", memoryTrick: "State = a SHAPESHIFTER. Same object, different behavior depending on what 'form' (state) it's in." },
  { day: 6, slot: 2, title: "Template Method - The Skeleton", type: "behavioral", content: "WHAT: Defines the skeleton of an algorithm in a base class, letting subclasses override specific steps without changing the structure.\n\nWHEN: Multiple classes share the same algorithm structure but differ in specific steps.\n\nHOW: Abstract class with a template method that calls abstract steps. Subclasses implement the steps.", realWorld: "Building a house: foundation -> walls -> roof -> interior. Every house follows this ORDER (template). But materials, design, and finishes (steps) vary per house.", bhnExample: "abstract class EmailProcessor { final function process() { $this->validate(); $this->transform(); $this->send(); $this->log(); } }. MarketingEmailProcessor and TransactionalEmailProcessor override validate() and transform() differently.", memoryTrick: "Template Method = a MADLIBS story. The structure is fixed. The blanks (steps) are filled differently each time." },
  { day: 6, slot: 3, title: "Mediator - The Coordinator", type: "behavioral", content: "WHAT: Defines an object that encapsulates how a set of objects interact. Promotes loose coupling by preventing objects from referring to each other directly.\n\nWHEN: Many objects communicate in complex ways. Instead of everyone knowing everyone, they all know ONE mediator.\n\nHOW: A mediator class that coordinates communication. Objects send messages to the mediator, which routes them.", realWorld: "An air traffic controller (mediator). Planes (objects) don't communicate directly. They all talk to the tower, which coordinates. Without the tower, chaos.", bhnExample: "An EmailOrchestrator mediator: coordinates between TemplateService, VariableResolver, QueueService, and NotificationTracker. None of these services know about each other. The orchestrator coordinates.", memoryTrick: "Mediator = AIR TRAFFIC CONTROL. Everyone talks to the tower. Nobody talks directly to each other. Order from chaos." },
  { day: 6, slot: 4, title: "Memento - Save and Restore", type: "behavioral", content: "WHAT: Captures an object's internal state so it can be restored later. Without violating encapsulation.\n\nWHEN: Undo/redo, checkpoints, versioning, transaction rollback.\n\nHOW: The originator creates a memento (snapshot). A caretaker stores it. To restore, the caretaker gives the memento back to the originator.", realWorld: "Video game save points. You save your state (memento) before a boss fight. If you die, you restore from the save. The game state is captured and restored perfectly.", bhnExample: "Email template editor: save a memento before each edit. User can 'undo' to previous versions. $memento = $template->save(); // edit happens; $template->restore($memento);", memoryTrick: "Memento = a PHOTOGRAPH of your object. Take the photo before changes. If you don't like the result, restore from the photo." },
  { day: 6, slot: 5, title: "Visitor - Add Operations Without Changing Classes", type: "behavioral", content: "WHAT: Lets you add new operations to existing object structures without modifying them. The visitor 'visits' each element and performs an operation.\n\nWHEN: You need to perform many unrelated operations on objects and don't want to pollute their classes.\n\nHOW: Elements accept a visitor. The visitor has a method for each element type. Double dispatch.", realWorld: "A tax auditor (visitor) visits different businesses (elements). The auditor performs audits on restaurants, shops, and offices. Each business 'accepts' the auditor. The auditor knows how to audit each type.", bhnExample: "EmailReportVisitor visits different email types: visitMarketingEmail(), visitTransactionalEmail(), visitSystemEmail(). Generates a report without modifying any email class.", memoryTrick: "Visitor = a DOCTOR making house calls. Each patient (element) accepts the doctor. The doctor knows how to treat each patient type differently." },
  { day: 6, slot: 6, title: "Interpreter - Mini Language Parser", type: "behavioral", content: "WHAT: Defines a grammar for a simple language and an interpreter to parse sentences in that language.\n\nWHEN: You need to evaluate expressions, parse DSLs (domain-specific languages), or interpret simple rules.\n\nHOW: Each grammar rule is a class. Terminal expressions (literals) and non-terminal expressions (operators) compose into a tree.", realWorld: "A calculator: '5 + 3 * 2'. The interpreter breaks this into an expression tree and evaluates it following grammar rules (operator precedence).", bhnExample: "Email template variables: '{{user.name}} just bought {{order.item}}'. The interpreter parses these expressions, resolves variables from context, and produces the final string.", memoryTrick: "Interpreter = a TRANSLATOR for a mini-language. You define the grammar, it speaks the language." },

  // DAY 7: MASTERY
  { day: 7, slot: 1, title: "Pattern Combinations in Real Systems", type: "mastery", content: "Real systems combine multiple patterns:\n\nFactory + Strategy: Factory creates the right strategy based on config.\nObserver + Command: Events trigger commands that are queued.\nDecorator + Proxy: Caching proxy wrapped in a logging decorator.\nComposite + Iterator: Traverse tree structures uniformly.\nBuilder + Prototype: Clone a prototype, then modify with builder methods.\n\nThe power is in COMBINATION, not isolation.", realWorld: "A restaurant uses: Factory (menu creates dishes), Observer (kitchen notified of orders), Command (order slips), Strategy (different cooking methods), Facade (waiter simplifies for customer).", bhnExample: "Your email centralization: Factory creates email objects, Strategy selects the sender, Observer triggers on events, Command represents SQS messages, Facade simplifies the API, Decorator adds logging/retry.", memoryTrick: "Single patterns are NOTES. Combined patterns are MUSIC. The symphony comes from how they play together." },
  { day: 7, slot: 2, title: "Modern Patterns Beyond GoF", type: "mastery", content: "Patterns that emerged after GoF:\n\nRepository Pattern: Abstracts data access (Laravel's Eloquent IS this).\nDependency Injection: Invert control of object creation (Laravel Service Container).\nService Layer: Business logic in dedicated service classes.\nCQRS: Separate read and write models.\nEvent Sourcing: Store events, not state.\nCircuit Breaker: Prevent cascading failures.\nStrangler Fig: Gradually replace legacy systems (YOUR email centralization!).\nSaga Pattern: Manage distributed transactions.", realWorld: "Modern architecture is built on these patterns. Netflix uses Circuit Breaker extensively. Amazon uses CQRS and Event Sourcing. Your BHN work uses Strangler Fig.", bhnExample: "You're already using: Repository (Eloquent models), DI (Laravel container), Service Layer (your service classes), Strangler Fig (email migration), and soon Circuit Breaker (for BNS calls).", memoryTrick: "GoF patterns are CLASSICAL music. Modern patterns are JAZZ. Both are music. Both have structure. Jazz just evolved for modern problems." },
  { day: 7, slot: 3, title: "Anti-Patterns: What NOT to Do", type: "mastery", content: "Common mistakes:\n\nGod Object: One class that does everything. Break it up.\nSpaghetti Code: No structure, everything calls everything. Use Mediator or Facade.\nGolden Hammer: Using your favorite pattern for EVERY problem. Match pattern to problem.\nPremature Abstraction: Creating factories and strategies for code that will never change.\nSingleton Abuse: Making everything a singleton. Testability dies.\nOver-Engineering: 5 patterns where 1 simple class would work.", realWorld: "A golden hammer: 'I just learned Strategy pattern, so EVERYTHING is a strategy now.' That's like using a Swiss Army knife to eat soup. Wrong tool.", bhnExample: "Don't create an AbstractEmailFactoryStrategyBuilderProxy. If a simple class with a send() method works, use that. Add patterns when COMPLEXITY demands them, not before.", memoryTrick: "Anti-patterns are HABITS that feel productive but cause damage. Like eating fast food: satisfying now, painful later." },
  { day: 7, slot: 4, title: "The Pattern Decision Flowchart", type: "mastery", content: "When facing a design problem, ask:\n\n1. Is the problem about CREATING objects? -> Creational patterns.\n   - Need one instance? Singleton. Need to decide type at runtime? Factory. Complex construction? Builder.\n\n2. Is the problem about CONNECTING/STRUCTURING objects? -> Structural.\n   - Incompatible interfaces? Adapter. Too complex? Facade. Need to add behavior? Decorator. Need access control? Proxy.\n\n3. Is the problem about COMMUNICATION between objects? -> Behavioral.\n   - Multiple algorithms? Strategy. Event notification? Observer. Undo needed? Command/Memento. State-dependent behavior? State.", realWorld: "Like a doctor's diagnostic tree: Fever? Check throat. Cough? Check lungs. Each symptom (problem) leads to a diagnosis (pattern).", bhnExample: "Your email centralization decision tree: 'How to create different email types?' -> Factory. 'How to add retry/logging?' -> Decorator. 'How to handle SQS messages?' -> Command. 'How to notify on send?' -> Observer.", memoryTrick: "The decision tree is your PATTERN GPS. Describe your destination (problem), and it routes you to the right pattern." },
  { day: 7, slot: 5, title: "Your Pattern Cheat Sheet", type: "mastery", content: "ALL 23 GoF Patterns in one breath:\n\nCREATIONAL: Singleton (one instance), Factory Method (delegate creation), Abstract Factory (family of objects), Builder (step-by-step), Prototype (clone).\n\nSTRUCTURAL: Adapter (translate interface), Bridge (decouple abstraction/implementation), Composite (tree structure), Decorator (add behavior), Facade (simplify), Flyweight (share memory), Proxy (control access).\n\nBEHAVIORAL: Chain of Responsibility (pass along), Command (encapsulate action), Interpreter (parse language), Iterator (traverse), Mediator (coordinate), Memento (save/restore), Observer (notify), State (change behavior), Strategy (swap algorithm), Template Method (skeleton), Visitor (add operations).\n\nYou now know ALL 23. The journey from here is PRACTICE.", realWorld: "This is your PERIODIC TABLE of patterns. Scientists don't memorize properties. They reference the table. Do the same. Know WHERE to find each pattern and WHEN it applies.", bhnExample: "Print this summary. Put it near your monitor. Every time you face a design decision, glance at it. Within months, you won't need it anymore. The patterns will be instinct.", memoryTrick: "23 patterns. 3 categories. Infinite combinations. You don't need to memorize them all. You need to recognize the PROBLEM and know where to look." },
];

const typeColor = (type, dark) => {
  const colors = {
    concept: dark ? "#38bdf8" : "#0369a1",
    creational: dark ? "#4ade80" : "#15803d",
    structural: dark ? "#fbbf24" : "#b45309",
    behavioral: dark ? "#c084fc" : "#7e22ce",
    comparison: dark ? "#fb923c" : "#c2410c",
    mastery: dark ? "#fde047" : "#ca8a04",
  };
  return colors[type] || colors.concept;
};
const typeLabel = (type) => {
  const labels = { concept: "Concept", creational: "Creational", structural: "Structural", behavioral: "Behavioral", comparison: "Comparison", mastery: "Mastery" };
  return labels[type] || "Lesson";
};

export default function App() {
  const [dark, setDark] = useState(true);
  const [selDay, setSelDay] = useState(null);
  const [selSlot, setSelSlot] = useState(null);
  const [done, setDone] = useState(() => { try { return JSON.parse(localStorage.getItem("masterclass_design-patterns_done")) || {}; } catch { return {}; } });
  const [vw, setVw] = useState("home");
  const ref = useRef(null);
  useEffect(() => { localStorage.setItem("masterclass_design-patterns_done", JSON.stringify(done)); }, [done]);
  const toggleDone = (key) => setDone((p) => ({ ...p, [key]: !p[key] }));
  const totalLessons = ALL_LESSONS.length;
  const ct = Object.values(done).filter(Boolean).length;
  const pct = Math.round((ct / totalLessons) * 100);
  const day = selDay ? DAYS.find((d) => d.id === selDay) : null;

  useEffect(() => { ref.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [selSlot]);

  const m = dark ? "dark" : "light";
  const t = {
    bg: dark ? "#060810" : "#f8f9fc",
    surface: dark ? "rgba(10,14,25,0.9)" : "rgba(255,255,255,0.9)",
    surfHov: dark ? "rgba(14,18,32,0.96)" : "rgba(246,248,252,0.97)",
    bdr: dark ? "rgba(56,189,248,0.07)" : "rgba(0,50,100,0.07)",
    txt: dark ? "#e2e8f0" : "#0f172a",
    sub: dark ? "#7e8a9a" : "#64748b",
    mut: dark ? "#4a5568" : "#94a3b8",
    card: dark ? "rgba(8,12,22,0.75)" : "rgba(255,255,255,0.75)",
    ring: dark ? "#141c2e" : "#e2e8f0",
    tag: dark ? "rgba(0,0,0,0.35)" : "rgba(0,40,80,0.035)",
    togBg: dark ? "rgba(56,189,248,0.06)" : "rgba(0,50,100,0.06)",
    hero: dark
      ? "radial-gradient(ellipse at 20% 0%, rgba(56,189,248,0.1), transparent 45%), radial-gradient(ellipse at 80% 0%, rgba(74,222,128,0.08), transparent 45%), radial-gradient(ellipse at 50% 90%, rgba(192,132,252,0.06), transparent 50%)"
      : "radial-gradient(ellipse at 20% 0%, rgba(3,105,161,0.04), transparent 45%), radial-gradient(ellipse at 80% 0%, rgba(21,128,61,0.03), transparent 45%), radial-gradient(ellipse at 50% 90%, rgba(126,34,206,0.025), transparent 50%)",
  };
  const hGrad = dark
    ? "linear-gradient(135deg, #38bdf8 0%, #4ade80 20%, #fbbf24 40%, #c084fc 60%, #f472b6 80%, #fde047 100%)"
    : "linear-gradient(135deg, #0369a1 0%, #15803d 20%, #b45309 40%, #7e22ce 60%, #db2777 80%, #ca8a04 100%)";

  const Tog = () => (
    <button onClick={() => setDark(!dark)} style={{ position: "fixed", top: 14, right: 14, zIndex: 999, background: t.togBg, backdropFilter: "blur(14px)", border: `1px solid ${t.bdr}`, borderRadius: 40, padding: "7px 14px", cursor: "pointer", display: "flex", alignItems: "center", gap: 7, color: t.sub, fontSize: 12.5, fontFamily: "'JetBrains Mono', monospace", transition: "all 0.35s" }}>
      <span style={{ fontSize: 15 }}>{dark ? "☀️" : "🌙"}</span>{dark ? "Light" : "Dark"}
    </button>
  );

  if (vw === "home") {
    return (
      <div style={{ fontFamily: "'Outfit', sans-serif", background: t.bg, minHeight: "100vh", color: t.txt, transition: "background 0.45s, color 0.45s" }}>
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <style>{`@keyframes fu{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}.pc:hover{transform:translateY(-2px);box-shadow:${dark?"0 6px 28px rgba(0,0,0,0.5)":"0 6px 28px rgba(0,0,0,0.06)"}}.pc{transition:all 0.28s cubic-bezier(0.4,0,0.2,1)}`}</style>
        <Tog />
        <div style={{ position: "relative", padding: "52px 24px 28px", textAlign: "center", overflow: "hidden" }}>
          <div style={{ position: "absolute", inset: 0, background: t.hero, pointerEvents: "none" }} />
          {dark && <div style={{ position: "absolute", inset: 0, background: "repeating-linear-gradient(0deg, transparent, transparent 40px, rgba(56,189,248,0.015) 40px, rgba(56,189,248,0.015) 41px), repeating-linear-gradient(90deg, transparent, transparent 40px, rgba(56,189,248,0.015) 40px, rgba(56,189,248,0.015) 41px)", pointerEvents: "none" }} />}
          <div style={{ position: "relative", zIndex: 1 }}>
            <div style={{ fontSize: 10.5, letterSpacing: 8, textTransform: "uppercase", fontFamily: "'JetBrains Mono', monospace", color: t.mut, marginBottom: 14 }}>7-Day Intensive</div>
            <h1 style={{ fontFamily: "'Outfit', sans-serif", fontSize: "clamp(28px,5.5vw,46px)", fontWeight: 900, lineHeight: 1.05, margin: "0 0 6px", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>Design Patterns</h1>
            <p style={{ fontSize: 12, color: t.sub, fontFamily: "'JetBrains Mono', monospace", margin: "10px 0 8px", fontWeight: 300, letterSpacing: 2 }}>All 23 GoF + Modern Patterns</p>
            <p style={{ fontSize: 11, color: t.mut, margin: "0 0 28px", fontFamily: "'JetBrains Mono', monospace" }}>Beginner to Advanced in 7 days</p>
            <div style={{ display: "inline-flex", alignItems: "center", gap: 18, background: t.surface, border: `1px solid ${t.bdr}`, borderRadius: 18, padding: "16px 26px", backdropFilter: "blur(16px)" }}>
              <div style={{ position: "relative", width: 58, height: 58 }}>
                <svg width="58" height="58" viewBox="0 0 58 58">
                  <circle cx="29" cy="29" r="25" fill="none" stroke={t.ring} strokeWidth="3" />
                  <defs><linearGradient id="pg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#38bdf8"/><stop offset="33%" stopColor="#4ade80"/><stop offset="66%" stopColor="#c084fc"/><stop offset="100%" stopColor="#fde047"/></linearGradient></defs>
                  <circle cx="29" cy="29" r="25" fill="none" stroke="url(#pg)" strokeWidth="3" strokeDasharray={`${(pct/100)*157.1} 157.1`} strokeLinecap="round" transform="rotate(-90 29 29)" style={{ transition: "stroke-dasharray 0.7s cubic-bezier(0.4,0,0.2,1)" }} />
                </svg>
                <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 700, fontFamily: "'JetBrains Mono', monospace", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>{pct}%</div>
              </div>
              <div style={{ textAlign: "left" }}>
                <div style={{ fontSize: 26, fontWeight: 900 }}>{ct}<span style={{ fontSize: 14, color: t.mut, fontWeight: 400 }}> / {totalLessons}</span></div>
                <div style={{ fontSize: 10, color: t.mut, fontFamily: "'JetBrains Mono', monospace", letterSpacing: 1.5 }}>lessons completed</div>
              </div>
            </div>
          </div>
        </div>
        <div style={{ padding: "8px 20px 48px", maxWidth: 720, margin: "0 auto" }}>
          {DAYS.map((d, i) => {
            const dl = ALL_LESSONS.filter(l => l.day === d.id);
            const dc = dl.filter(l => done[`${l.day}-${l.slot}`]).length;
            const ac = d.accent[m];
            return (
              <div key={d.id} className="pc" onClick={() => { setSelDay(d.id); setVw("day"); }} style={{ background: t.card, border: `1px solid ${t.bdr}`, borderRadius: 16, padding: "20px 22px", cursor: "pointer", marginBottom: 12, borderLeft: `3px solid ${ac}`, animation: `fu 0.55s ease ${i*0.08}s both`, position: "relative", overflow: "hidden", backdropFilter: "blur(10px)" }}>
                <div style={{ position: "absolute", top: -20, right: -20, width: 120, height: 120, background: `radial-gradient(circle, ${d.glow}, transparent 65%)`, pointerEvents: "none", opacity: dark ? 0.5 : 0.3 }} />
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", position: "relative" }}>
                  <div style={{ display: "flex", gap: 14, alignItems: "center" }}>
                    <span style={{ fontSize: 26 }}>{d.icon}</span>
                    <div>
                      <div style={{ fontSize: 10, color: ac, letterSpacing: 4, textTransform: "uppercase", fontFamily: "'JetBrains Mono', monospace", marginBottom: 4 }}>Day {d.id}</div>
                      <div style={{ fontSize: 19, fontWeight: 800 }}>{d.title}</div>
                      <div style={{ fontSize: 12, color: t.sub, fontWeight: 400, marginTop: 2 }}>{d.subtitle}</div>
                    </div>
                  </div>
                  <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: t.mut, textAlign: "right", minWidth: 48 }}>
                    <span style={{ color: ac, fontWeight: 600 }}>{dc}</span>/{dl.length}
                  </div>
                </div>
                <div style={{ marginTop: 14, height: 2.5, background: t.ring, borderRadius: 3, overflow: "hidden" }}>
                  <div style={{ height: "100%", width: `${dl.length > 0 ? (dc/dl.length)*100 : 0}%`, background: `linear-gradient(90deg, ${ac}, ${ac}55)`, borderRadius: 3, transition: "width 0.5s ease" }} />
                </div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  if (vw === "day" && day) {
    const dl = ALL_LESSONS.filter(l => l.day === day.id);
    const ac = day.accent[m];
    return (
      <div style={{ fontFamily: "'Outfit', sans-serif", background: t.bg, minHeight: "100vh", color: t.txt, transition: "background 0.45s, color 0.45s" }}>
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <style>{`@keyframes fu{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}@keyframes ex{from{opacity:0;max-height:0}to{opacity:1;max-height:1200px}}`}</style>
        <Tog />
        <div style={{ position: "relative", overflow: "hidden" }}>
          <div style={{ position: "absolute", inset: 0, background: day.gradient[m], opacity: dark ? 0.5 : 0.3 }} />
          {dark && <div style={{ position: "absolute", inset: 0, background: "repeating-linear-gradient(0deg, transparent, transparent 40px, rgba(56,189,248,0.012) 40px, rgba(56,189,248,0.012) 41px), repeating-linear-gradient(90deg, transparent, transparent 40px, rgba(56,189,248,0.012) 40px, rgba(56,189,248,0.012) 41px)", pointerEvents: "none" }} />}
          <div style={{ position: "relative", zIndex: 1, padding: "20px 20px 6px" }}>
            <button onClick={() => { setVw("home"); setSelDay(null); setSelSlot(null); }} style={{ background: t.togBg, border: `1px solid ${t.bdr}`, color: t.sub, padding: "7px 16px", borderRadius: 10, cursor: "pointer", fontSize: 12, fontFamily: "'JetBrains Mono', monospace" }}>{"←"} Back</button>
          </div>
          <div style={{ position: "relative", zIndex: 1, padding: "8px 24px 24px", textAlign: "center" }}>
            <span style={{ fontSize: 38 }}>{day.icon}</span>
            <h2 style={{ fontSize: 30, fontWeight: 900, margin: "8px 0 4px" }}>Day {day.id}: {day.title}</h2>
            <p style={{ color: t.sub, fontWeight: 400, margin: 0, fontSize: 13 }}>{day.subtitle}</p>
          </div>
        </div>
        <div style={{ display: "flex", gap: 6, padding: "8px 20px", overflowX: "auto", WebkitOverflowScrolling: "touch", scrollbarWidth: "none" }}>
          {DAYS.map(d => (
            <button key={d.id} onClick={() => { setSelDay(d.id); setSelSlot(null); }} style={{ background: d.id === day.id ? `${d.accent[m]}18` : "transparent", border: `1px solid ${d.id === day.id ? `${d.accent[m]}44` : t.bdr}`, color: d.id === day.id ? d.accent[m] : t.mut, padding: "4px 10px", borderRadius: 8, cursor: "pointer", fontSize: 10, fontFamily: "'JetBrains Mono', monospace", whiteSpace: "nowrap", transition: "all 0.2s" }}>D{d.id}</button>
          ))}
        </div>
        <div style={{ padding: "8px 20px 48px", maxWidth: 720, margin: "0 auto" }}>
          {dl.map((l, i) => {
            const key = `${l.day}-${l.slot}`;
            const op = selSlot === key;
            const tc = typeColor(l.type, dark);
            return (
              <div key={key} ref={op ? ref : null} style={{ marginBottom: 8, animation: `fu 0.4s ease ${i*0.05}s both` }}>
                <div onClick={() => setSelSlot(op ? null : key)} style={{ background: op ? t.surfHov : t.card, border: `1px solid ${op ? `${ac}35` : t.bdr}`, borderRadius: op ? "13px 13px 0 0" : 13, padding: "14px 16px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", transition: "all 0.25s", backdropFilter: "blur(8px)" }}>
                  <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
                    <div onClick={e => { e.stopPropagation(); toggleDone(key); }} style={{ width: 24, height: 24, borderRadius: "50%", border: done[key] ? `2.5px solid ${ac}` : `2px solid ${t.bdr}`, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", background: done[key] ? `${ac}15` : "transparent", transition: "all 0.25s", flexShrink: 0 }}>
                      {done[key] && <span style={{ color: ac, fontSize: 11, fontWeight: 700 }}>{"✓"}</span>}
                    </div>
                    <div>
                      <div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 3 }}>
                        <span style={{ fontSize: 9, color: tc, letterSpacing: 2, textTransform: "uppercase", fontFamily: "'JetBrains Mono', monospace", padding: "2px 6px", background: `${tc}15`, borderRadius: 4, border: `1px solid ${tc}25` }}>{typeLabel(l.type)}</span>
                      </div>
                      <div style={{ fontSize: 14.5, fontWeight: 600, color: done[key] ? t.mut : t.txt, textDecoration: done[key] ? "line-through" : "none" }}>{l.title}</div>
                    </div>
                  </div>
                  <span style={{ color: t.mut, fontSize: 13, transform: op ? "rotate(180deg)" : "rotate(0)", transition: "transform 0.25s", flexShrink: 0 }}>{"▾"}</span>
                </div>
                {op && (
                  <div style={{ background: t.surfHov, border: `1px solid ${ac}35`, borderTop: "none", borderRadius: "0 0 13px 13px", padding: 22, animation: "ex 0.35s ease", overflow: "hidden", backdropFilter: "blur(8px)" }}>
                    <p style={{ color: t.txt, lineHeight: 1.85, margin: "0 0 18px", fontSize: 14, fontWeight: 300, whiteSpace: "pre-line" }}>{l.content}</p>
                    {[
                      { label: "🌍 Real World Analogy", text: l.realWorld, c: dark ? [`rgba(56,189,248,0.05)`,`rgba(56,189,248,0.12)`,`#38bdf8`] : [`rgba(3,105,161,0.04)`,`rgba(3,105,161,0.09)`,`#0369a1`] },
                      { label: "🏭 BHN / Laravel Example", text: l.bhnExample, c: dark ? [`rgba(74,222,128,0.05)`,`rgba(74,222,128,0.11)`,`#4ade80`] : [`rgba(21,128,61,0.04)`,`rgba(21,128,61,0.09)`,`#15803d`] },
                      { label: "🧠 Memory Trick", text: l.memoryTrick, c: dark ? [`rgba(251,191,36,0.05)`,`rgba(251,191,36,0.12)`,`#fbbf24`] : [`rgba(180,83,9,0.04)`,`rgba(180,83,9,0.1)`,`#b45309`], hl: true },
                    ].map((s, si) => (
                      <div key={si} style={{ background: s.c[0], border: `1px solid ${s.c[1]}`, borderRadius: 11, padding: "13px 16px", marginBottom: si < 2 ? 10 : 0 }}>
                        <div style={{ fontSize: 9.5, color: s.c[2], letterSpacing: 2.5, textTransform: "uppercase", fontFamily: "'JetBrains Mono', monospace", marginBottom: 6 }}>{s.label}</div>
                        <p style={{ color: s.hl ? (dark ? "#fef08a" : "#854d0e") : t.txt, fontSize: s.hl ? 13.5 : 13, lineHeight: 1.65, margin: 0, fontWeight: s.hl ? 500 : 300 }}>{s.text}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    );
  }
  return null;
}
