import { useState, useEffect, useRef } from "react";

const PHASES = [
  { id: 1, title: "PRESENCE", subtitle: "How you show up matters", days: "Day 1-21", icon: "🧔", description: "Master first impressions, body language, grooming, and the quiet confidence that makes people take notice.", mnemonic: "G.R.A.C.E. - Grooming, Respect, Awareness, Composure, Eye contact", gradient: { dark: "linear-gradient(135deg, #1a0f2e 0%, #2a1b4e 50%, #0d1f2d 100%)", light: "linear-gradient(135deg, #f3edff 0%, #ece4ff 50%, #f7f2ff 100%)" }, accent: { dark: "#a78bfa", light: "#6d28d9" }, glow: "rgba(167, 139, 250, 0.3)" },
  { id: 2, title: "CHARACTER", subtitle: "Who you are when no one watches", days: "Day 22-42", icon: "💠", description: "Build the inner qualities that define a true gentleman: integrity, honesty, discipline, and moral courage.", mnemonic: "S.T.E.E.L. - Self-discipline, Truth, Empathy, Ethics, Loyalty", gradient: { dark: "linear-gradient(135deg, #0d2818 0%, #1a4030 50%, #0d1f2d 100%)", light: "linear-gradient(135deg, #edf8f1 0%, #ddf0e5 50%, #ecf9f0 100%)" }, accent: { dark: "#34d399", light: "#059669" }, glow: "rgba(52, 211, 153, 0.3)" },
  { id: 3, title: "CONDUCT", subtitle: "Actions speak your values", days: "Day 43-63", icon: "🤝", description: "Learn the art of social grace, dining etiquette, professional manners, and how to navigate any room.", mnemonic: "C.L.A.S.S. - Courtesy, Listening, Attire, Speech, Service", gradient: { dark: "linear-gradient(135deg, #2d1a0a 0%, #4a2c12 50%, #2d200d 100%)", light: "linear-gradient(135deg, #fef3e2 0%, #fde9cc 50%, #fef5e7 100%)" }, accent: { dark: "#fbbf24", light: "#d97706" }, glow: "rgba(251, 191, 36, 0.3)" },
  { id: 4, title: "WISDOM", subtitle: "Think before you act, speak, or judge", days: "Day 64-77", icon: "🧠", description: "Develop emotional intelligence, conflict resolution, and the ethical frameworks that guide difficult choices.", mnemonic: "M.I.N.D. - Measure words, Inquire first, Never assume, Deliberate", gradient: { dark: "linear-gradient(135deg, #0d1a2e 0%, #12304e 50%, #0a1e30 100%)", light: "linear-gradient(135deg, #e8f0fa 0%, #d8e8f8 50%, #eaf3ff 100%)" }, accent: { dark: "#38bdf8", light: "#0284c7" }, glow: "rgba(56, 189, 248, 0.3)" },
  { id: 5, title: "LEGACY", subtitle: "Leave every room better than you found it", days: "Day 78-90", icon: "🌟", description: "Bring it all together. Mentorship, generosity, leading by example, and building a reputation that outlasts you.", mnemonic: "L.I.F.T. - Lead, Inspire, Follow-through, Teach", gradient: { dark: "linear-gradient(135deg, #2e0d1e 0%, #4e1535 50%, #2d0a20 100%)", light: "linear-gradient(135deg, #fce8f1 0%, #f8d5e5 50%, #fdeaf3 100%)" }, accent: { dark: "#f472b6", light: "#db2777" }, glow: "rgba(244, 114, 182, 0.3)" },
];

const ALL_LESSONS = [
  // PHASE 1: PRESENCE (Day 1-21)
  { day: 1, phase: 1, type: "bite", title: "The 7-Second Rule", content: "People form their first impression of you in roughly 7 seconds. Before you speak a single word, your posture, eye contact, and energy have already told a story. Today's mission: become aware of the story YOUR body tells.", workChallenge: "Before your next meeting, check your posture, your expression, and your energy. Walk in 2 seconds early, not rushing. Stand tall. Make eye contact with the first person you see.", lifeChallenge: "Next time you enter a cafe, shop, or someone's home, notice how you walk in. Do you slouch? Look at your phone? Or do you arrive with presence?", memoryTrick: "7 seconds to impress. 7 years to correct. Get the first 7 right." },
  { day: 2, phase: 1, type: "bite", title: "The Power of a Real Smile", content: "A genuine smile (called a Duchenne smile) involves both your mouth AND your eyes. A fake smile only moves the mouth. People can tell the difference subconsciously. A real smile says 'I'm glad you're here.'", workChallenge: "Today, when greeting colleagues on Teams/Slack or in person, smile before you speak. Notice how the energy of the conversation shifts.", lifeChallenge: "Smile at 3 strangers today. The chai wallah, the security guard, a neighbor. Watch what happens.", memoryTrick: "A smile that reaches the EYES reaches the HEART. Mouth-only smiles reach nowhere." },
  { day: 3, phase: 1, type: "bite", title: "The Handshake Protocol", content: "A handshake is your first physical contract with another person. Too firm = aggressive. Too limp = disinterested. Match the other person's grip. 2-3 seconds. Look them in the eye.", workChallenge: "Next time you meet someone new (client, new team member, stakeholder), be intentional about your handshake. Firm, warm, brief.", lifeChallenge: "Practice with a friend or family member. Ask for honest feedback: too strong? Too weak? Just right?", memoryTrick: "A handshake is a CONVERSATION between palms. Listen to theirs, match it." },
  { day: 4, phase: 1, type: "bite", title: "Dress 10% Better", content: "You don't need expensive clothes. You need INTENTIONAL clothes. A gentleman dresses slightly better than the occasion demands. Not to show off, but to show respect for the people and the moment.", workChallenge: "Tomorrow, wear something 10% more polished than your usual. Iron that shirt. Clean those shoes. Watch how differently people interact with you.", lifeChallenge: "Audit your wardrobe. Do your clothes say 'I care about details' or 'I grabbed whatever was closest'?", memoryTrick: "Dress for the person you want to BECOME, not the person you were YESTERDAY." },
  { day: 5, phase: 1, type: "bite", title: "The Name Game", content: "A person's name is the sweetest sound to them. Remembering and using someone's name is one of the most powerful social skills. It says: you matter enough for me to remember.", workChallenge: "In your next 3 interactions, use the person's name at least twice in conversation. 'Great point, Saurav' instead of just 'Great point.'", lifeChallenge: "Next time you meet someone new, repeat their name immediately: 'Nice to meet you, Priya.' Then use it once more before the conversation ends.", memoryTrick: "R.A.C.E. to remember names: Repeat it, Associate it (visual), Connect it (rhyme/story), End with it." },
  { day: 6, phase: 1, type: "deep", title: "Body Language Mastery", content: "55% of communication is body language. Your arms, posture, hand gestures, and micro-expressions speak louder than your words. A gentleman's body language says: I'm confident, I'm open, and I'm listening to YOU.", workChallenge: "In your next meeting, observe: Are your arms crossed? (defensive) Are you leaning in? (engaged) Are you fidgeting? (anxious) Consciously adopt open, grounded posture.", lifeChallenge: "Watch a conversation between two people without hearing the words. What story does their body language tell? Who has power? Who is comfortable?", memoryTrick: "O.P.E.N. body = Open palms, Posture tall, Eye contact, Nod to show listening." },
  { day: 7, phase: 1, type: "practice", title: "Week 1 Reflection: Your Presence Audit", content: "After 6 days of presence training, it's time to honestly assess where you stand.", workChallenge: "Rate yourself 1-10 on: Posture, Eye contact, Smile, Attire, Name recall. Pick the lowest score. That's your focus for next week.", lifeChallenge: "Ask a trusted friend: 'What's your first impression when I walk into a room?' Listen without defending.", memoryTrick: "You can't improve what you can't MEASURE. Your presence audit is your baseline." },
  { day: 8, phase: 1, type: "bite", title: "Standing When It Matters", content: "A gentleman stands when someone enters the room, when being introduced, when a woman arrives at the table, and when someone leaves. It's not old-fashioned. It's a physical statement of respect.", workChallenge: "Next time someone walks into your meeting room or your desk area, stand to greet them. Notice their reaction.", lifeChallenge: "At your next social gathering, stand when greeting someone new. It immediately sets you apart.", memoryTrick: "Standing UP is how you show someone they're not BENEATH your attention." },
  { day: 9, phase: 1, type: "bite", title: "The Art of Being On Time", content: "Punctuality is the first promise you make to someone, and the easiest one to keep. Being late says: my time matters more than yours. Being on time says: I respect you.", workChallenge: "For the next 7 days, arrive 3 minutes early to every meeting. Not 10 (awkward), not 0 (cutting it close). 3 minutes. The sweet spot.", lifeChallenge: "If you're running late, ALWAYS communicate. A simple 'Running 5 min behind, sorry' before the time arrives shows respect.", memoryTrick: "Early is on time. On time is late. Late is unacceptable." },
  { day: 10, phase: 1, type: "bite", title: "Phone Etiquette: The Modern Test", content: "The #1 way people judge your manners in 2026: how you handle your phone. Checking your phone while someone is talking to you says: this screen is more interesting than you.", workChallenge: "In your next meeting or 1:1, put your phone face-down or in your pocket. Give 100% attention. Notice the difference in conversation depth.", lifeChallenge: "At your next meal with someone, keep your phone completely out of sight. Not face-down on the table. GONE.", memoryTrick: "A phone on the table is a WALL between two people. Remove the wall." },
  { day: 11, phase: 1, type: "bite", title: "Voice: Your Invisible Outfit", content: "Your tone, pace, and volume communicate as much as your words. Speaking too fast = nervous. Too slow = condescending. Too loud = aggressive. Too soft = unsure. Find your natural, grounded voice.", workChallenge: "Record yourself in your next call (with permission). Listen back. Are you speaking too fast? Too many filler words (um, basically, like)?", lifeChallenge: "Practice speaking 15% slower than your natural pace today. Slower speech communicates confidence and thoughtfulness.", memoryTrick: "P.A.C.E. - Pause before answering, Articulate clearly, Control volume, End sentences with conviction." },
  { day: 12, phase: 1, type: "bite", title: "The 2-Minute Introduction", content: "A gentleman can introduce himself clearly, warmly, and memorably in under 2 minutes. Not a resume dump. A human connection. Name, what you do (simply), and something that invites conversation.", workChallenge: "Write a 30-second introduction for professional settings. Practice it until it feels natural, not rehearsed.", lifeChallenge: "Write a casual version for social settings. 'I'm Vishwanath, I build software at BHN and ride motorcycles on weekends. What about you?'", memoryTrick: "An introduction is a BRIDGE, not a billboard. Build connection, don't broadcast achievements." },
  { day: 13, phase: 1, type: "deep", title: "The Art of Entering a Room", content: "How you enter a room sets the tone for everything that follows. A gentleman walks in with calm confidence, acknowledges people, and makes others feel comfortable, not intimidated.", workChallenge: "Before entering your next meeting, take one deep breath. Walk in at a steady pace. Make eye contact with at least 2 people. Sit down without rushing.", lifeChallenge: "At a social event, resist the urge to immediately find your phone or someone you know. Stand still for 5 seconds, take in the room, then move with purpose.", memoryTrick: "Enter like you BELONG. Not like you OWN the place, but like you were INVITED." },
  { day: 14, phase: 1, type: "practice", title: "Week 2 Practice: The Mirror Test", content: "This week, use the mirror technique. Before leaving home each morning, spend 30 seconds in front of a mirror: check posture, check expression, check attire.", workChallenge: "Set a daily alarm for 5 minutes before you start work. Do a 30-second presence check: camera on, posture, expression, background.", lifeChallenge: "Ask yourself in the mirror each morning: 'Would I want to meet me today?' If no, fix what's off.", memoryTrick: "The mirror shows your OUTSIDE. Your actions show your INSIDE. Align both." },
  { day: 15, phase: 1, type: "bite", title: "Grooming: The Details That Speak", content: "A gentleman's grooming speaks before he does. Clean nails, trimmed beard, fresh breath, neat hair. These aren't vanity. They're signals that you care about the details.", workChallenge: "Do a grooming audit: nails, hair, breath, shoes. Fix the one thing you've been ignoring.", lifeChallenge: "Invest in one grooming upgrade this week: a better trimmer, a good deodorant, a proper face wash. Small investment, big impact.", memoryTrick: "N.A.I.L.S. - Nails trimmed, Attire pressed, Intent fresh, Look neat, Shoes clean." },
  { day: 16, phase: 1, type: "bite", title: "Walking With Purpose", content: "Your walk communicates your inner state. Shuffling = defeated. Rushing = anxious. Steady, upright, chin level = confident and calm. A gentleman walks like he knows where he's going.", workChallenge: "Today, pay attention to how you walk between meetings, to lunch, to your desk. Walk 10% slower, with shoulders back.", lifeChallenge: "On your next walk or ride, notice other people's walks. What does each one communicate? Now check your own.", memoryTrick: "Walk like you have 3 books balanced on your head. Not stiff, just ALIGNED." },
  { day: 17, phase: 1, type: "bite", title: "The Goodbye Matters Too", content: "Most people focus on hellos and forget goodbyes. But the last impression is what people carry with them. A proper goodbye includes: eye contact, a warm statement, and using their name.", workChallenge: "End your next meeting with: 'Thanks for your time, [name]. I really appreciate the discussion.' Watch how it lands.", lifeChallenge: "When leaving a gathering, say goodbye to the host and at least 2 other people individually. Don't do the 'Irish goodbye.'", memoryTrick: "Hello opens the door. Goodbye decides if they'll open it AGAIN." },
  { day: 18, phase: 1, type: "bite", title: "Personal Space Awareness", content: "A gentleman respects physical boundaries. Standing too close = intimidating. Too far = disengaged. The sweet spot is about an arm's length. And always let the other person set the comfort distance.", workChallenge: "In your next in-person conversation, notice the distance. Are you too close? Adjust. Let them set the zone.", lifeChallenge: "In crowded places (metro, lift, events), be the person who gives space, not takes it.", memoryTrick: "Space is a GIFT you give others. Crowding is a gift you take from them." },
  { day: 19, phase: 1, type: "bite", title: "The Thank You Habit", content: "A gentleman says thank you genuinely and specifically. Not 'thanks' (generic), but 'Thank you for taking the time to explain that, it really helped' (specific). Specific gratitude is 10x more powerful.", workChallenge: "Send 2 specific thank-you messages today. Not 'thanks for the help' but 'Thank you for explaining the SQS retry logic, it saved me hours.'", lifeChallenge: "Thank someone in your personal life for something specific they did recently that you never acknowledged.", memoryTrick: "Generic thanks = a mass email. Specific thanks = a handwritten letter. Which would YOU rather receive?" },
  { day: 20, phase: 1, type: "deep", title: "Confidence vs Arrogance: The Line", content: "Confidence says: 'I know my value.' Arrogance says: 'I know my value is MORE than yours.' The difference is subtle but everyone can feel it. A gentleman is confident WITHOUT making others feel small.", workChallenge: "Think about your last 3 strong opinions in meetings. Did you share them with curiosity ('Here's what I think, what do you see?') or with finality ('This is how it should be')?", lifeChallenge: "Notice today: when you feel confident, are you lifting others up or subtly putting them down? The test: do people feel BETTER about themselves after talking to you?", memoryTrick: "Confidence FILLS a room. Arrogance EMPTIES it. One attracts, the other repels." },
  { day: 21, phase: 1, type: "practice", title: "Phase 1 Graduation: The Presence Score", content: "21 days of presence training. You've worked on body language, grooming, punctuality, voice, and confidence. Time to measure your growth.", workChallenge: "Re-take the Day 7 audit. Rate yourself again on Posture, Eye contact, Smile, Attire, Name recall. Compare with Week 1. Where did you grow?", lifeChallenge: "Ask the same trusted friend from Day 7: 'Have you noticed anything different about me lately?' Their answer is your real score.", memoryTrick: "Phase 1 done. You now SHOW UP differently. Phase 2 builds who you ARE underneath." },

  // PHASE 2: CHARACTER (Day 22-42)
  { day: 22, phase: 2, type: "bite", title: "Integrity: The Foundation", content: "Integrity means your actions match your words, even when no one is watching. It's the gap between what you SAY you value and what you actually DO. A gentleman closes that gap.", workChallenge: "Think of one thing you said you'd do at work but haven't. Do it today. Or honestly communicate why you can't.", lifeChallenge: "Think of a small promise you broke recently (I'll call you back, I'll start exercising). Honor one today.", memoryTrick: "Integrity = your WORD and your ACTION are the SAME file, not two versions." },
  { day: 23, phase: 2, type: "bite", title: "The Truth Tax", content: "Telling the truth sometimes costs something. A missed opportunity, an awkward moment, a difficult conversation. A gentleman pays the 'truth tax' because the alternative, living with dishonesty, costs more.", workChallenge: "Today, in a situation where a white lie would be easier, choose honesty delivered with kindness. 'I don't think this approach will work, and here's why.'", lifeChallenge: "Is there a truth you've been avoiding telling someone? Practice how you'd say it with respect. You don't have to say it today, just prepare.", memoryTrick: "Lies have INTEREST. You pay a little now to avoid truth, but the debt COMPOUNDS." },
  { day: 24, phase: 2, type: "bite", title: "Keeping Secrets Sacred", content: "When someone trusts you with information, that trust is sacred. A gentleman never shares someone else's secrets, struggles, or private moments. Not for gossip, not for bonding, not for leverage.", workChallenge: "Think about the last time someone shared something personal at work. Did you keep it to yourself? Going forward, treat every private conversation as confidential by default.", lifeChallenge: "If someone shared something vulnerable with you recently, check on them. 'Hey, how are you doing with that thing you mentioned?' without telling anyone else.", memoryTrick: "A SECRET shared with a gentleman goes into a VAULT, not a group chat." },
  { day: 25, phase: 2, type: "bite", title: "Admitting When You're Wrong", content: "It takes more strength to say 'I was wrong' than to defend a losing position. A gentleman's ego serves his character, not the other way around. Admitting mistakes earns MORE respect, not less.", workChallenge: "Think of a recent work decision that didn't go as planned. In your next standup or 1:1, own it: 'I made a wrong call on X, here's what I learned.'", lifeChallenge: "Is there a past argument where you knew you were wrong but never admitted it? Send that message today.", memoryTrick: "'I was wrong' has 3 words and builds 10x the trust that 'I'm never wrong' destroys." },
  { day: 26, phase: 2, type: "bite", title: "Self-Discipline: The Quiet Superpower", content: "A gentleman doesn't need external pressure to do the right thing. He has an internal compass that says: do the work, keep the promise, maintain the standard, even when no one is checking.", workChallenge: "Pick one professional habit you only do when someone is watching (code reviews, documentation, testing). Do it perfectly today when NO ONE will check.", lifeChallenge: "Do one thing today purely for self-discipline: make your bed, workout at the scheduled time, skip the easy shortcut.", memoryTrick: "Discipline is doing what's right even when your MOOD says otherwise. Mood is weather. Discipline is climate." },
  { day: 27, phase: 2, type: "bite", title: "Empathy: Walking in Their Shoes", content: "Empathy isn't agreement. It's understanding. A gentleman can disagree with someone completely while still understanding WHY they feel the way they do. This is the foundation of all good relationships.", workChallenge: "Think of a colleague whose approach frustrates you. Spend 5 minutes genuinely trying to understand their perspective. What pressures are they under? What do they fear?", lifeChallenge: "Next time someone complains about something that seems trivial to you, resist the urge to dismiss it. Ask: 'That sounds frustrating. Tell me more.'", memoryTrick: "Empathy = putting on someone else's GLASSES. You see differently, even if you go back to your own pair." },
  { day: 28, phase: 2, type: "practice", title: "Week 4 Practice: The Character Mirror", content: "Time to look inward. Character isn't built in a day, but it IS revealed in daily choices.", workChallenge: "Write down 3 values you claim to hold. Then write down 3 actions from this week. Do they match? Where's the gap?", lifeChallenge: "Ask yourself: 'If my actions this week were broadcast to everyone I know, would I be proud?' If not, what would you change?", memoryTrick: "Character is a PHOTOGRAPH of your repeated actions. What picture are you developing?" },
  { day: 29, phase: 2, type: "bite", title: "Patience: The Gentleman's Weapon", content: "In a world of instant everything, patience is revolutionary. A gentleman waits for the right moment, listens fully before responding, and doesn't rush others to match his timeline.", workChallenge: "Today, in every conversation, let the other person finish completely before you respond. No interrupting, no pre-loading your answer.", lifeChallenge: "When stuck in traffic, in a queue, or waiting for food, practice being completely calm. No phone. Just patience. Observe the world.", memoryTrick: "Patience isn't WAITING. It's how you BEHAVE while waiting. That's the test." },
  { day: 30, phase: 2, type: "bite", title: "Humility: Strength in Quiet", content: "Humility isn't thinking LESS of yourself. It's thinking of yourself LESS. A gentleman lets his work speak, credits others, and doesn't need to be the loudest person in the room.", workChallenge: "In your next team discussion, credit someone else's contribution before mentioning yours. 'Saurav's approach on X was really smart, I built on that with Y.'", lifeChallenge: "Next time you achieve something, share the credit with someone who helped, even indirectly.", memoryTrick: "Humility is a MAGNET. The less you brag, the more people are drawn to you." },
  { day: 31, phase: 2, type: "bite", title: "Consistency: Character's Proof", content: "Anyone can be kind once. Anyone can be honest in easy moments. A gentleman is kind and honest CONSISTENTLY, especially when it's hard. Consistency is character's receipt.", workChallenge: "Think of how you treat different people at work. Do you treat the intern the same as your manager? A gentleman treats the janitor and the CEO with equal respect.", lifeChallenge: "Are you the same person at home as you are at work? With friends as with strangers? Consistency = no masks.", memoryTrick: "Character isn't what you do ONCE. It's what you do ALWAYS. One kind act is a moment. Consistent kindness is identity." },
  { day: 32, phase: 2, type: "bite", title: "Moral Courage: Doing the Hard Right", content: "There's the easy wrong and the hard right. Moral courage means choosing the hard right, standing up when something is wrong, even when it's uncomfortable or unpopular.", workChallenge: "Think of something at work that you know is wrong but nobody is addressing. How could you raise it constructively? 'I think we should revisit how we handle X because it's not fair to Y.'", lifeChallenge: "Is there a situation in your life where staying quiet is easier but speaking up is right? Plan how you'd say it.", memoryTrick: "Moral courage is a MUSCLE. Every time you use it, it gets stronger. Every time you dodge it, it atrophies." },
  { day: 33, phase: 2, type: "deep", title: "The Ethics Framework: Your Inner Compass", content: "Every gentleman needs a personal ethics framework. A set of non-negotiable principles that guide decisions when the path isn't clear. Not rules from outside, but convictions from within.", workChallenge: "Write your personal 'Code of Ethics' in 5 statements. Example: '1. I will not take credit for others' work. 2. I will speak up when I see unfairness.' Post it where you'll see it daily.", lifeChallenge: "Think of 3 ethical dilemmas you've faced. How did you decide? Would your 5 statements have helped? Refine them.", memoryTrick: "A compass works even in the dark. Your ethics should too." },
  { day: 34, phase: 2, type: "bite", title: "Accountability: Owning Your Impact", content: "A gentleman owns the consequences of his actions, intended or not. 'That wasn't my intention' doesn't erase impact. Accountability means: 'Regardless of intent, here's what happened, and I own it.'", workChallenge: "If a deployment you touched caused issues, own it fully in the retro. 'This was my change, here's what I missed, here's how I'll prevent it.'", lifeChallenge: "Think of a time your actions hurt someone unintentionally. Did you take accountability for the impact, not just the intent?", memoryTrick: "Intent is what you AIMED for. Impact is where the arrow LANDED. Own the landing." },
  { day: 35, phase: 2, type: "practice", title: "Week 5 Practice: The Accountability Log", content: "Start tracking moments where you chose the harder right path and moments where you didn't.", workChallenge: "Create a simple log: 'Situation | What I did | What I should have done | Gap.' No judgment, just honest tracking.", lifeChallenge: "Review 3 recent decisions. Were they driven by convenience or by your values? Rate each as 'value-driven' or 'convenience-driven.'", memoryTrick: "An accountability log is a SCORECARD for your character. No one sees it but you. That's the point." },
  { day: 36, phase: 2, type: "bite", title: "Controlling Your Temper", content: "A gentleman does not lose his temper in public. Not because he doesn't feel anger, but because he chooses not to let anger choose his actions. Controlled emotions = powerful emotions.", workChallenge: "Next time something frustrates you at work (a blocker, a bad review, a broken pipeline), pause for 10 seconds before reacting. Respond, don't react.", lifeChallenge: "When someone cuts you off on the road, when food takes too long, when plans change unexpectedly, practice the 10-second pause.", memoryTrick: "Anyone can EXPLODE. It takes a gentleman to ABSORB, process, and respond with control." },
  { day: 37, phase: 2, type: "bite", title: "Respecting Everyone Equally", content: "The true measure of a gentleman is how he treats people who can do NOTHING for him. The auto driver, the office cleaning staff, the restaurant server. Their dignity is equal to anyone's.", workChallenge: "Learn the name of one person at work you interact with but never really acknowledged: the office help, the security guard, the canteen staff.", lifeChallenge: "Next time you interact with a service worker, look them in the eye, smile, use 'please' and 'thank you', and mean it.", memoryTrick: "A gentleman's respect doesn't have a DIMMER SWITCH based on someone's job title." },
  { day: 38, phase: 2, type: "bite", title: "Generosity Without Expectation", content: "A gentleman gives without keeping score. Help without expecting return. Compliment without wanting one back. The moment you track generosity, it becomes a transaction.", workChallenge: "Help a colleague today with something they're struggling with. Don't mention it to anyone. Don't track it. Just help.", lifeChallenge: "Do one anonymous act of kindness today. Pay for someone's chai. Leave a bigger tip. Help carry something.", memoryTrick: "True generosity has NO RECEIPT. If you need credit, it's a transaction, not kindness." },
  { day: 39, phase: 2, type: "bite", title: "Loyalty: The Long Game", content: "Loyalty means defending someone when they're not in the room. It means not participating in gossip about colleagues, friends, or family. A gentleman is the same behind your back as to your face.", workChallenge: "Next time someone at work is being criticized behind their back, either defend them or redirect the conversation. 'I think there's more to the story. Let's talk to them directly.'", lifeChallenge: "Think about the last time someone wasn't present and you said something about them. Would you say it to their face?", memoryTrick: "Loyalty is a BRIDGE you build in someone's ABSENCE. Gossip is a bridge you BURN." },
  { day: 40, phase: 2, type: "deep", title: "The Stoic Gentleman", content: "The ancient Stoics taught: control what you can, accept what you can't, and know the difference. A gentleman doesn't waste energy on things outside his control. He focuses on his responses, his effort, his character.", workChallenge: "List 3 things at work that frustrate you. For each, write: 'Can I control this? If yes, what action? If no, what can I control in my response?'", lifeChallenge: "Think about what's causing you stress right now. Separate it into 'in my control' and 'outside my control.' Release the second list.", memoryTrick: "The Stoic test: if you CAN change it, why worry? If you CAN'T change it, why worry? Either way, stop worrying." },
  { day: 41, phase: 2, type: "bite", title: "Keeping Promises, Especially Small Ones", content: "Big promises are remembered. Small promises are forgotten, except by the person you made them to. 'I'll send that link' and 'I'll check on that' are promises. A gentleman keeps ALL of them.", workChallenge: "Go through your messages from this week. Did you promise to send anything, follow up on anything, or check on anything? Do ALL of them today.", lifeChallenge: "Make one small promise to someone today and keep it before sunset. 'I'll send you that recipe' or 'I'll call you back in 10 minutes.' Then do it.", memoryTrick: "Small promises are BRICKS. Break enough small ones, and the wall of trust CRUMBLES." },
  { day: 42, phase: 2, type: "practice", title: "Phase 2 Graduation: The Character Audit", content: "21 days of building inner character. Time to honestly assess your growth.", workChallenge: "Revisit your 5-statement Code of Ethics from Day 33. Have you lived by them this month? Rate each 1-10. Your lowest score = your next focus.", lifeChallenge: "Write a letter to yourself 1 year from now about the gentleman you're becoming. Seal it. Open it next year.", memoryTrick: "Phase 2 done. You've built the INSIDE. Phase 3 teaches you to express it in ACTIONS and social grace." },

  // PHASE 3: CONDUCT (Day 43-63)
  { day: 43, phase: 3, type: "bite", title: "Dining Etiquette: The Basics", content: "How you eat reveals how you were raised, and how you've chosen to refine yourself. Chew with mouth closed, napkin on lap, don't start until everyone is served, and pace yourself with the slowest eater.", workChallenge: "At your next team lunch or dinner, practice: napkin on lap, phone away, wait for everyone before starting.", lifeChallenge: "Next time you eat out, observe which fork goes where, how you hold cutlery, and whether you're eating too fast. Slow down.", memoryTrick: "Dining is a PERFORMANCE of your character. Every bite is a scene." },
  { day: 44, phase: 3, type: "bite", title: "The Art of Conversation", content: "A great conversationalist is 70% listener, 30% speaker. Ask questions, show genuine curiosity, remember details, and never hijack someone's story with your own.", workChallenge: "In your next 1:1 or casual chat, ask 3 follow-up questions before sharing your own perspective. 'That's interesting, how did that happen?'", lifeChallenge: "At your next social gathering, make it your goal to learn 2 new things about someone you already know.", memoryTrick: "Conversation is a TENNIS match. If you hold the ball too long, nobody wants to play." },
  { day: 45, phase: 3, type: "bite", title: "Writing Like a Gentleman", content: "Your written communication represents you when you're not in the room. Proper grammar, courteous tone, clear structure, and a warm closing. No ALL CAPS. No passive-aggressive language.", workChallenge: "Before sending your next email or Slack message, re-read it and ask: 'Would I say this to their face in this tone?' If not, rewrite.", lifeChallenge: "Send a thoughtful, well-written message to someone you haven't talked to in a while. Not 'Hey, what's up' but something that shows you thought about them.", memoryTrick: "An email is a LETTER that arrives instantly. Write it like it'll be read a HUNDRED times." },
  { day: 46, phase: 3, type: "bite", title: "Holding Doors and Other Micro-Courtesies", content: "Hold the door. Offer your seat. Let someone go first. Pick up something someone dropped. These tiny acts cost nothing but communicate everything about your character.", workChallenge: "Today, practice 3 micro-courtesies at work: hold a door, offer to help carry something, or let someone go first in line.", lifeChallenge: "Count how many micro-courtesies you naturally do vs miss. Aim to add 3 new ones to your daily autopilot.", memoryTrick: "Micro-courtesies are CHARACTER in small print. Only the attentive can read them." },
  { day: 47, phase: 3, type: "bite", title: "How to Give a Compliment", content: "A gentleman's compliment is specific, sincere, and not about getting something in return. 'Your presentation was excellent' is good. 'The way you structured the data migration timeline was really clear and convincing' is memorable.", workChallenge: "Give 2 specific compliments at work today. Not 'good job' but 'The way you handled that edge case in the PR was really elegant.'", lifeChallenge: "Compliment a stranger today. Not about appearance but about something they did: 'You're really patient with your kids, that's impressive.'", memoryTrick: "A compliment is a SPOTLIGHT. Generic = flashlight on the whole room. Specific = spotlight on what MATTERS." },
  { day: 48, phase: 3, type: "deep", title: "Navigating Difficult Conversations", content: "A gentleman doesn't avoid hard conversations, he handles them with grace. The formula: acknowledge the discomfort, state facts without blame, express your perspective, and invite their view.", workChallenge: "Think of a difficult conversation you need to have at work. Draft it using: 'I noticed [fact], I feel [perspective], I'd like to hear your view on this.'", lifeChallenge: "Is there a personal conversation you've been putting off? Write down what you'd say using the same formula. Kindness + honesty = respect.", memoryTrick: "A.F.I. formula: Acknowledge the elephant, share Facts, Invite their perspective. In that order." },
  { day: 49, phase: 3, type: "practice", title: "Week 7 Practice: Social Grace Challenge", content: "This week, consciously practice social graces in every interaction.", workChallenge: "For 5 days: Mon=punctuality, Tue=active listening, Wed=specific compliments, Thu=proper email tone, Fri=hold doors/let people go first. Track your score each day.", lifeChallenge: "Attend one social event this week and practice everything from Phases 1-3. How many principles can you naturally incorporate?", memoryTrick: "Social grace isn't PERFORMING politeness. It's BEING polite so naturally that others feel at ease." },
  { day: 50, phase: 3, type: "bite", title: "How to Handle Criticism Gracefully", content: "A gentleman receives criticism without defensiveness. Listen fully. Thank them for the feedback. Reflect before responding. Even unfair criticism usually contains a kernel of truth.", workChallenge: "Next time you receive feedback on a PR or a proposal, resist the urge to defend. Say: 'Thank you, let me think about that.' Then actually think about it.", lifeChallenge: "Ask someone you trust: 'What's one thing I could do better?' Listen without explaining or defending.", memoryTrick: "Criticism is a ROUGH DIAMOND. You have to cut away the harshness to find the valuable insight inside." },
  { day: 51, phase: 3, type: "bite", title: "The Art of Apologizing", content: "A real apology has 4 parts: acknowledge what you did, acknowledge its impact, express genuine remorse, and commit to change. 'I'm sorry you feel that way' is NOT an apology.", workChallenge: "Think of the last time you apologized at work. Did it have all 4 parts? If not, consider a redo.", lifeChallenge: "Is there an apology you owe someone? Even an old one? A sincere apology, even late, heals more than you think.", memoryTrick: "A.I.R.C. - Acknowledge, Impact, Remorse, Commit. Real apologies have ALL four." },
  { day: 52, phase: 3, type: "bite", title: "Tipping and Generosity in Public", content: "How you treat waitstaff, tip, and handle money in public reveals your character. A gentleman tips fairly, doesn't haggle disrespectfully, and never makes someone feel small about money.", workChallenge: "Next team lunch, if the bill isn't split exactly, round UP rather than arguing over small amounts. Your reputation is worth more than that difference.", lifeChallenge: "Tip generously today. Not recklessly, but enough to make someone's day better. The auto driver, the delivery person, the waiter.", memoryTrick: "Generosity in PUBLIC is a mirror of generosity in PRIVATE. What you give when others see reveals what you'd give when they don't." },
  { day: 53, phase: 3, type: "bite", title: "Digital Etiquette: The 2026 Gentleman", content: "Reply to messages within reasonable time. Don't leave people on 'seen.' Don't send voice notes to people who didn't ask for them. Don't tag people in memes during work hours. Digital respect is modern respect.", workChallenge: "Audit your response times. Is there anyone waiting on a reply from you right now? Clear your queue.", lifeChallenge: "Review your last 10 WhatsApp/social media interactions. Were they all respectful of the other person's time and attention?", memoryTrick: "Your phone is a WINDOW into your character. Every message, reply, and reaction is a tiny display of who you are." },
  { day: 54, phase: 3, type: "bite", title: "How to Disagree Respectfully", content: "Disagreement is not conflict. A gentleman can disagree with your idea while respecting you as a person. The secret: attack the idea, never the person.", workChallenge: "In your next code review or meeting where you disagree, use: 'I see it differently. Here's my thinking...' instead of 'That's wrong.'", lifeChallenge: "Next disagreement with a friend or family member, try: 'I respect your view, but here's where I see it differently.' Notice the difference.", memoryTrick: "Disagree with the MAP, not the MAP-MAKER. Ideas can be wrong. People deserve respect." },
  { day: 55, phase: 3, type: "deep", title: "The Host Mindset", content: "A gentleman has the 'host mindset' everywhere, not just at home. In meetings, he makes sure everyone is heard. At events, he introduces people. He's always thinking: who here might feel uncomfortable, and how can I help?", workChallenge: "In your next meeting, notice who hasn't spoken. Invite them in: 'Kevin, what's your take on this?' Be the host of conversations, not just a participant.", lifeChallenge: "At your next social event, introduce 2 people who don't know each other. 'Ravi, meet Ankit. You both love motorcycles.'", memoryTrick: "A HOST makes everyone feel like they BELONG. Be the host of every room, even rooms you don't own." },
  { day: 56, phase: 3, type: "practice", title: "Week 8 Practice: The Social Experiment", content: "Pick 3 of the hardest social skills from this phase and practice them deliberately today.", workChallenge: "Today's challenge: Give a specific compliment, handle one disagreement gracefully, and practice the host mindset in one meeting.", lifeChallenge: "Go to a social setting and practice: introduce yourself to someone new, hold doors, and have a conversation where you listen 70% of the time.", memoryTrick: "Social skills are like coding skills. You learn the theory in 5 minutes. You master them through PRACTICE over months." },
  { day: 57, phase: 3, type: "bite", title: "How to Receive a Compliment", content: "Most people deflect compliments: 'Oh, it was nothing.' A gentleman receives them gracefully: 'Thank you, I appreciate that.' Not arrogant, not dismissive. Just gracious.", workChallenge: "Next time someone compliments your work, resist the urge to downplay. Simply say: 'Thank you, that means a lot.' Full stop.", lifeChallenge: "Notice how you respond to compliments today. Do you deflect? Downplay? Practice accepting gracefully.", memoryTrick: "Deflecting a compliment is like RETURNING a gift. Accept it with grace. The giver chose it for you." },
  { day: 58, phase: 3, type: "bite", title: "Respecting Others' Time", content: "Time is the only resource that can never be refunded. A gentleman respects others' time like he respects his own. Short meetings, clear emails, no unnecessary pings.", workChallenge: "Before scheduling your next meeting, ask: 'Could this be an email?' Before sending a long Slack message, ask: 'Could this be 3 sentences?'", lifeChallenge: "Are you the friend who's always 'just 10 more minutes' late? If yes, that's a character issue disguised as a scheduling issue.", memoryTrick: "Wasting someone's time is stealing something they can NEVER get back." },
  { day: 59, phase: 3, type: "bite", title: "Public Speaking as a Gentleman", content: "When a gentleman speaks publicly, he's clear, respectful, and never talks down to the audience. He speaks to include, not to impress. He uses 'we' more than 'I.'", workChallenge: "In your next presentation or standup, replace 'I' with 'we' where appropriate. 'We identified a gap in the retry logic' instead of 'I found a bug.'", lifeChallenge: "If asked to give a toast or speak at an event, speak from the heart, keep it brief, and make it about OTHERS, not yourself.", memoryTrick: "A speech is a GIFT to the audience. Not a stage for your ego." },
  { day: 60, phase: 3, type: "bite", title: "How to Handle Success Gracefully", content: "Success reveals character as much as failure does. A gentleman celebrates without boasting, shares credit, and remembers who helped along the way.", workChallenge: "Think of your recent promotion to Senior Engineer. In any conversation about it, mention at least one person who helped you get there.", lifeChallenge: "Next time something goes well, resist the urge to post about it immediately. Sit with it. Appreciate it privately first. Then share with gratitude, not pride.", memoryTrick: "Success is a TEAM photo. If you crop everyone out, you're not celebrating, you're advertising." },
  { day: 61, phase: 3, type: "bite", title: "How to Handle Failure Gracefully", content: "A gentleman in failure doesn't blame, doesn't sulk, and doesn't disappear. He stands up, acknowledges what happened, learns from it, and moves forward with dignity.", workChallenge: "Think of a recent setback. How did you handle it? Did you blame, deflect, or own it? Practice the 3-step: Own it, learn from it, move forward.", lifeChallenge: "Share a failure story with someone you trust. Not for sympathy, but to practice being vulnerable without being a victim.", memoryTrick: "A gentleman in failure is like a tree in a storm. It BENDS, it doesn't BREAK, and it grows back STRONGER." },
  { day: 62, phase: 3, type: "deep", title: "Cultural Sensitivity: The Global Gentleman", content: "In a connected world, a gentleman respects cultures he doesn't fully understand. Different greetings, different dining customs, different conversation norms. Curiosity, not judgment.", workChallenge: "At BHN, you work with global teams. Research one cultural etiquette difference with a region you frequently interact with. Apply it next time.", lifeChallenge: "Next time you encounter a custom or behavior you don't understand, ask with genuine curiosity instead of judging. 'I'd love to learn more about that tradition.'", memoryTrick: "Culture is not RIGHT or WRONG. It's DIFFERENT. A gentleman finds beauty in differences." },
  { day: 63, phase: 3, type: "practice", title: "Phase 3 Graduation: The Conduct Scorecard", content: "21 days of social grace and ethical conduct. Time to assess.", workChallenge: "Rate yourself 1-10 on: Conversation skills, Written communication, Handling criticism, Handling success/failure, Micro-courtesies. Lowest score = next focus.", lifeChallenge: "Ask someone: 'Am I easy to be around? What could I do better?' Listen without defending.", memoryTrick: "Phase 3 done. You can SHOW UP (Phase 1), BE solid inside (Phase 2), and ACT with grace (Phase 3). Next: THINK wisely." },

  // PHASE 4: WISDOM (Day 64-77)
  { day: 64, phase: 4, type: "bite", title: "Think Before You Speak", content: "T.H.I.N.K. before you speak: Is it True? Is it Helpful? Is it Inspiring? Is it Necessary? Is it Kind? If it doesn't pass at least 3, reconsider.", workChallenge: "Before your next strong opinion in a meeting, run it through the T.H.I.N.K. filter. Does it pass?", lifeChallenge: "Before your next social media comment or WhatsApp reply, run T.H.I.N.K. Would you still send it?", memoryTrick: "T.H.I.N.K. is a 5-door filter. Your words must pass through at least 3 doors to deserve to be spoken." },
  { day: 65, phase: 4, type: "bite", title: "Emotional Intelligence: Read the Room", content: "A wise gentleman reads emotional undercurrents. Is someone stressed but pretending to be fine? Is the room tense but everyone is being polite? Reading the room is a superpower.", workChallenge: "In your next meeting, look beyond words. Is someone unusually quiet? Is someone's tone different? After the meeting, check on them privately.", lifeChallenge: "At your next social gathering, observe the energy. Who needs to be included? Who seems uncomfortable? Act on what you see.", memoryTrick: "Words are the SURFACE. Emotions are the CURRENT underneath. Swim below the surface." },
  { day: 66, phase: 4, type: "bite", title: "The Power of Not Reacting", content: "Not every provocation deserves a response. A wise gentleman knows when silence, a pause, or a redirect is more powerful than the cleverest reply.", workChallenge: "Next time someone says something that triggers you in a meeting or review, practice the art of the pause. Breathe. Then choose whether to respond at all.", lifeChallenge: "Next time you see a social media comment that angers you, close the app. Come back in an hour. Do you still need to respond?", memoryTrick: "REACTING is a reflex. RESPONDING is a choice. The gap between them is where wisdom lives." },
  { day: 67, phase: 4, type: "bite", title: "Knowing When to Stay Silent", content: "Silence is not weakness. Sometimes the wisest thing is to say nothing: when someone is venting, when a fight isn't worth having, when your words would hurt more than help.", workChallenge: "In your next meeting, practice strategic silence. Let a discussion flow without adding your opinion. Observe what happens.", lifeChallenge: "Next time someone vents to you, don't offer solutions. Just listen. Sometimes presence IS the answer.", memoryTrick: "A full cup can't receive. Silence EMPTIES your cup so you can receive what others pour." },
  { day: 68, phase: 4, type: "deep", title: "Ethical Decision-Making Framework", content: "When facing a moral dilemma, use the 4-way test: Is it the TRUTH? Is it FAIR to all concerned? Will it build GOODWILL? Will it be BENEFICIAL to all concerned?", workChallenge: "Think of a gray-area decision at work. Run it through the 4-way test. Does your choice pass all 4? If not, reconsider.", lifeChallenge: "Think of a difficult personal decision. Apply the 4-way test. Notice which criterion is hardest to satisfy. That reveals where the tension is.", memoryTrick: "T.F.G.B. - Truth, Fairness, Goodwill, Benefit. Four pillars of ethical decisions." },
  { day: 69, phase: 4, type: "bite", title: "Forgiving Without Being Asked", content: "Holding a grudge is drinking poison and expecting the other person to get sick. A wise gentleman forgives not because the other person deserves it, but because HE deserves peace.", workChallenge: "Is there a colleague who wronged you that you're still carrying resentment toward? Decide today to release it. Not for them. For your own clarity.", lifeChallenge: "Think of someone who hurt you. Write down what happened, how it made you feel, and then write: 'I release this.' You don't have to send it.", memoryTrick: "Forgiveness is not saying 'it was okay.' It's saying 'I won't carry this WEIGHT anymore.'" },
  { day: 70, phase: 4, type: "practice", title: "Week 10 Practice: The Wisdom Journal", content: "Start a wisdom journal. Each day, write one situation where you chose reaction vs response. Track your growth.", workChallenge: "For 5 days, log: 'Situation | My first impulse | What I actually did | Was it wise?' This builds the muscle between trigger and response.", lifeChallenge: "Ask an older person you respect: 'What's the wisest thing you've learned about relationships?' Write it down.", memoryTrick: "A wisdom journal is a TRAINING LOG for your soul." },
  { day: 71, phase: 4, type: "bite", title: "Choosing Battles Wisely", content: "Not every hill is worth dying on. A wise gentleman picks his battles carefully: fight for values, let go of ego. Win the war of character, not every skirmish of opinion.", workChallenge: "Think of the last 3 arguments you had at work. Were they about VALUES or PREFERENCES? A gentleman fights for the first, compromises on the second.", lifeChallenge: "Next time you feel the urge to argue about something trivial (restaurant choice, movie pick, route to take), let it go. Practice choosing peace.", memoryTrick: "Ask: 'Will this matter in 5 years?' If no, it's not a hill. It's a SPEED BUMP. Drive over it." },
  { day: 72, phase: 4, type: "bite", title: "The Golden Rule Upgrade", content: "The Golden Rule says: treat others as YOU want to be treated. The Platinum Rule says: treat others as THEY want to be treated. A wise gentleman uses the Platinum Rule.", workChallenge: "Think about a colleague whose communication style is different from yours. Do they prefer detailed emails or quick Slack messages? Match THEIR preference, not yours.", lifeChallenge: "Does your parent, partner, or friend feel loved through words, actions, time, or gifts? Give love in THEIR language, not yours.", memoryTrick: "Golden Rule = YOUR perspective. Platinum Rule = THEIR perspective. Upgrade from gold to platinum." },
  { day: 73, phase: 4, type: "bite", title: "The Long View: Reputation Takes Years", content: "A reputation takes 20 years to build and 5 minutes to destroy. A wise gentleman makes decisions with his long-term reputation in mind, not short-term wins.", workChallenge: "Before your next significant work decision, ask: 'How will this affect my reputation in 5 years?' If negatively, reconsider.", lifeChallenge: "Google yourself. What does your digital presence say about you? Is it the gentleman you're building? If not, start curating.", memoryTrick: "Reputation is a SAVINGS ACCOUNT. Every ethical act is a deposit. Every shortcut is a withdrawal." },
  { day: 74, phase: 4, type: "bite", title: "Respecting Boundaries", content: "A wise gentleman recognizes and respects boundaries: physical, emotional, professional. He never pushes someone to share more than they're comfortable with, and he sets his own boundaries clearly.", workChallenge: "Are you respecting your team's boundaries? Off-hours messages, unrealistic expectations, personal questions they didn't invite? Check yourself.", lifeChallenge: "Do you respect your OWN boundaries? Saying yes when you mean no? Allowing people to take your time without permission? Set one boundary today.", memoryTrick: "Boundaries are not WALLS that keep people out. They're DOORS that let the right people in, at the right time." },
  { day: 75, phase: 4, type: "bite", title: "The Courage to Be Vulnerable", content: "True strength includes the courage to be vulnerable. 'I don't know' is brave. 'I need help' is brave. 'I'm struggling' is brave. A gentleman shows strength through honesty, not masks.", workChallenge: "In your next standup or 1:1, if you're stuck on something, say: 'I'm finding this challenging. Can we brainstorm?' Notice how it deepens trust.", lifeChallenge: "Share one genuine struggle with someone close to you. Not for solutions, just for connection. Vulnerability builds bridges.", memoryTrick: "Vulnerability is not WEAKNESS shown. It's STRENGTH shared." },
  { day: 76, phase: 4, type: "deep", title: "Building Your Wisdom Framework", content: "Combine everything from this phase into your personal wisdom toolkit. Your go-to mental models for ethical living and wise decision-making.", workChallenge: "Write your personal 'Wisdom Checklist': 5 questions you'll ask before any significant decision. Post it where you'll see it.", lifeChallenge: "Share your framework with a younger person or a friend. Teaching wisdom deepens it.", memoryTrick: "Wisdom isn't knowing everything. It's knowing which QUESTIONS to ask before acting." },
  { day: 77, phase: 4, type: "practice", title: "Phase 4 Graduation: The Wisdom Portfolio", content: "14 days of building emotional intelligence and ethical thinking. Time to demonstrate.", workChallenge: "Write 3 'wisdom stories' from your recent work: moments where you chose the hard right, practiced patience, or read the room and acted on it. Evidence for your 5-star review.", lifeChallenge: "Reflect: how has your REACTION speed changed? Are you responding more, reacting less? That's the shift.", memoryTrick: "Phase 4 done. You can SHOW UP, BE solid, ACT with grace, and THINK wisely. Final phase: build a LEGACY." },

  // PHASE 5: LEGACY (Day 78-90)
  { day: 78, phase: 5, type: "bite", title: "Mentoring: Lifting Others Up", content: "A gentleman's greatest achievement isn't his own success. It's the success of people he helped along the way. Mentoring isn't a formal program. It's a daily habit of sharing knowledge, encouragement, and time.", workChallenge: "Identify one junior developer or colleague who could benefit from your experience. Share one useful insight with them today without being asked.", lifeChallenge: "Think of someone who mentored you. Send them a thank-you message today. Then pay it forward.", memoryTrick: "A CANDLE loses nothing by lighting another candle. Mentoring multiplies your light." },
  { day: 79, phase: 5, type: "bite", title: "Leading by Example, Not Authority", content: "A gentleman leads through actions, not titles. He doesn't say 'do as I say.' He says nothing and does it first. Others follow naturally.", workChallenge: "Is there a standard you expect from your team that you don't consistently follow yourself? (Documentation, testing, code quality) Fix that gap TODAY.", lifeChallenge: "In your family or friend group, be the first to apologize, the first to help, the first to take responsibility. Leadership starts at home.", memoryTrick: "A LEADER walks in front not to be followed, but to clear the PATH. A gentleman leads by doing the clearing." },
  { day: 80, phase: 5, type: "bite", title: "Leaving Spaces Better", content: "A gentleman leaves every room, every meeting, every conversation, and every relationship in better condition than he found it. Not for recognition. Because that's who he is.", workChallenge: "After your next meeting, clean up: send the summary, clarify the action items, thank the participants. Leave it BETTER.", lifeChallenge: "Next time you use a shared space (kitchen, bathroom, park), leave it cleaner than you found it. Pick up one thing that isn't yours.", memoryTrick: "The GENTLEMAN'S RULE: Leave it better. Every room. Every conversation. Every person." },
  { day: 81, phase: 5, type: "bite", title: "Teaching Without Condescension", content: "A gentleman teaches with patience, not superiority. He remembers what it felt like to not know. He explains without making the learner feel small.", workChallenge: "Next time someone asks you a 'basic' question, answer as if it's the most important question you've heard today. Because for them, it might be.", lifeChallenge: "Teach someone a skill you have (cooking, photography, coding, riding). Focus on their experience, not your expertise.", memoryTrick: "A great teacher doesn't show how much THEY know. They show how much the STUDENT can learn." },
  { day: 82, phase: 5, type: "deep", title: "Your Gentleman's Code", content: "Every knight had a code. Every gentleman needs one. This is your personal code: the principles you live by, the standards you hold yourself to, the legacy you're building.", workChallenge: "Write your 'Gentleman's Code' in 10 statements. Not aspirational fluff, but concrete commitments. 'I will always credit others.' 'I will never gossip.' 'I will respond within 24 hours.'", lifeChallenge: "Share your code with someone who will hold you accountable. A code without accountability is just poetry.", memoryTrick: "A CODE is not a wish list. It's a CONTRACT with yourself. Sign it with your actions." },
  { day: 83, phase: 5, type: "bite", title: "Generational Kindness", content: "Treat elderly people with extra patience and warmth. Treat children with extra attention and encouragement. A gentleman adjusts his energy to make EVERY generation feel valued.", workChallenge: "Think of the most senior person in your organization. Send them a message of appreciation. And the most junior. Encourage them.", lifeChallenge: "Next time you interact with an elderly person (grandparent, neighbor, stranger), give them your full attention and patience. They've earned it.", memoryTrick: "The OLD planted trees they'd never sit under. The YOUNG water trees they didn't plant. A gentleman does BOTH." },
  { day: 84, phase: 5, type: "practice", title: "Week 12 Practice: Impact Inventory", content: "Take stock of the impact you've had on others over the past 12 weeks.", workChallenge: "List 5 people whose day, week, or work was better because of something you did in the last 3 months. If you can't list 5, that's your growth area.", lifeChallenge: "Ask 3 people: 'Has anything I've done recently made a positive difference for you?' Their answers might surprise you.", memoryTrick: "Your IMPACT is your real resume. Not what you built, but who you LIFTED." },
  { day: 85, phase: 5, type: "bite", title: "Grace Under Pressure", content: "The ultimate test of a gentleman: how he behaves under pressure. When deadlines are crushing, when emotions are high, when everything is going wrong. THAT is when your character matters most.", workChallenge: "Think of the last time you were under intense pressure at work. How did you treat people? Were you still kind? Still patient? If not, what would the gentleman version look like?", lifeChallenge: "Next time life throws something unexpected at you, pause and ask: 'How would the gentleman handle this?' Then do that.", memoryTrick: "PRESSURE doesn't create character. It REVEALS it. Under pressure, you meet the REAL you." },
  { day: 86, phase: 5, type: "bite", title: "Building a Reputation Through Small Acts", content: "Reputation isn't built in grand gestures. It's built in thousands of small moments: returning a call, keeping a promise, showing up on time, saying thank you.", workChallenge: "Today, do 3 small things perfectly: reply to that pending message, follow up on that commitment, thank someone specifically.", lifeChallenge: "Think of someone whose reputation you admire. What SMALL, repeated acts built that reputation? Do those acts.", memoryTrick: "Reputation is SAND on a beach. Each grain is a small act. Enough grains build ISLANDS." },
  { day: 87, phase: 5, type: "bite", title: "Content Creation as a Gentleman", content: "Your online presence is your digital handshake. On Vishwa Motovlogs, on LinkedIn, on any platform: be authentic, be respectful, be helpful. Never tear others down to build yourself up.", workChallenge: "Audit your last 10 social media posts/comments. Do they reflect the gentleman you're becoming? Are they adding value or just noise?", lifeChallenge: "Create one piece of content this week that HELPS someone without asking for anything in return. A tip, a lesson, an encouragement.", memoryTrick: "Your content is your CHARACTER on display. Post what you'd be proud of in 10 years." },
  { day: 88, phase: 5, type: "bite", title: "The Daily Gentleman Routine", content: "Build a daily 5-minute routine that keeps your gentleman practices sharp: morning mirror check, one act of kindness, one specific compliment, one moment of patience, one evening reflection.", workChallenge: "Start today: Morning (presence check), Midday (one kindness), Evening (one reflection). 5 minutes total. Do it for 30 days and it becomes automatic.", lifeChallenge: "Write your 5-minute routine on a card. Keep it on your desk or bedside. Consistency makes it identity.", memoryTrick: "5 MINUTES a day = 30 hours a year of character building. Small inputs, massive outputs." },
  { day: 89, phase: 5, type: "deep", title: "Your Legacy Statement", content: "If people described you after you left the room, what would you want them to say? 'He was kind.' 'He made everyone feel respected.' 'He walked the talk.' This is your legacy statement.", workChallenge: "Write your legacy statement in 1 sentence. Not what you want to ACHIEVE, but how you want to be REMEMBERED. Share it with your manager in a 1:1 as your personal north star.", lifeChallenge: "Write letters (or mental notes) to 3 people who shaped you. Tell them their impact. That's legacy in reverse.", memoryTrick: "Your LEGACY isn't written in your resume. It's written in the HEARTS of people you touched." },
  { day: 90, phase: 5, type: "practice", title: "GRADUATION: The Gentleman's Manifesto", content: "90 days. 5 phases. One transformed life. You've built Presence, Character, Conduct, Wisdom, and Legacy. Now seal it.", workChallenge: "Write your 1-page Gentleman's Manifesto: your code, your principles, your legacy statement, and 3 commitments for the next 90 days. This is portfolio material for your 5-star review under 'BeOneTeam' and 'BeAccountable'.", lifeChallenge: "Share your 90-day journey. A LinkedIn post, a Motovlogs video, or a conversation with someone who needs to hear it. Your growth inspires others.", memoryTrick: "Day 1, you walked into rooms. Day 90, you light them up. The masterclass ends. The gentleman never stops becoming." },
];

const typeLabel = (t) => t === "bite" ? "5-min Bite" : t === "deep" ? "Deep Dive" : "Practice Day";
const typeIcon = (t) => t === "bite" ? "⚡" : t === "deep" ? "🌊" : "🏋️";

export default function App() {
  const [dark, setDark] = useState(true);
  const [selPhase, setSelPhase] = useState(null);
  const [selDay, setSelDay] = useState(null);
  const [done, setDone] = useState(() => { try { return JSON.parse(localStorage.getItem("masterclass_gentleman-ethics_done")) || {}; } catch { return {}; } });
  const [vw, setVw] = useState("home");
  const ref = useRef(null);
  useEffect(() => { localStorage.setItem("masterclass_gentleman-ethics_done", JSON.stringify(done)); }, [done]);
  const toggle = (d) => setDone((p) => ({ ...p, [d]: !p[d] }));
  const ct = Object.values(done).filter(Boolean).length;
  const pct = Math.round((ct / 90) * 100);
  const phase = selPhase ? PHASES.find((p) => p.id === selPhase) : null;

  useEffect(() => { ref.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [selDay]);

  const m = dark ? "dark" : "light";
  const t = {
    bg: dark ? "#07080c" : "#faf8f4",
    surface: dark ? "rgba(14,16,24,0.88)" : "rgba(255,255,255,0.88)",
    surfHov: dark ? "rgba(20,23,36,0.95)" : "rgba(248,246,242,0.96)",
    bdr: dark ? "rgba(255,255,255,0.055)" : "rgba(0,0,0,0.07)",
    bdrAct: dark ? "rgba(255,255,255,0.12)" : "rgba(0,0,0,0.14)",
    txt: dark ? "#e8e4f0" : "#1a1625",
    sub: dark ? "#8a8599" : "#6b6680",
    mut: dark ? "#55506a" : "#9a95a8",
    card: dark ? "rgba(12,14,22,0.72)" : "rgba(255,255,255,0.72)",
    ring: dark ? "#1c1930" : "#e8e4ee",
    tag: dark ? "rgba(0,0,0,0.32)" : "rgba(0,0,0,0.035)",
    togBg: dark ? "rgba(255,255,255,0.055)" : "rgba(0,0,0,0.055)",
    hero: dark
      ? "radial-gradient(ellipse at 18% 0%, rgba(167,139,250,0.13), transparent 48%), radial-gradient(ellipse at 82% 0%, rgba(52,211,153,0.11), transparent 48%), radial-gradient(ellipse at 50% 90%, rgba(251,191,36,0.07), transparent 50%)"
      : "radial-gradient(ellipse at 18% 0%, rgba(109,40,217,0.055), transparent 48%), radial-gradient(ellipse at 82% 0%, rgba(5,150,105,0.045), transparent 48%), radial-gradient(ellipse at 50% 90%, rgba(217,119,6,0.035), transparent 50%)",
  };
  const hGrad = dark
    ? "linear-gradient(135deg, #a78bfa 0%, #34d399 35%, #fbbf24 70%, #f472b6 100%)"
    : "linear-gradient(135deg, #6d28d9 0%, #059669 35%, #d97706 70%, #db2777 100%)";

  const Tog = () => (
    <button onClick={() => setDark(!dark)} style={{ position: "fixed", top: 14, right: 14, zIndex: 999, background: dark ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.05)", backdropFilter: "blur(14px)", border: `1px solid ${t.bdr}`, borderRadius: 40, padding: "7px 14px", cursor: "pointer", display: "flex", alignItems: "center", gap: 7, color: t.sub, fontSize: 12.5, fontFamily: "'DM Mono', monospace", transition: "all 0.35s", letterSpacing: 0.5 }}>
      <span style={{ fontSize: 15 }}>{dark ? "☀️" : "🌙"}</span>{dark ? "Light" : "Dark"}
    </button>
  );

  if (vw === "home") {
    return (
      <div style={{ fontFamily: "'DM Sans', sans-serif", background: t.bg, minHeight: "100vh", color: t.txt, transition: "background 0.45s, color 0.45s" }}>
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600;9..40,700&family=DM+Mono:wght@300;400;500&display=swap" rel="stylesheet" />
        <style>{`@keyframes fu{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:translateY(0)}}.pc:hover{transform:translateY(-3px);box-shadow:${dark?"0 8px 32px rgba(0,0,0,0.4)":"0 8px 32px rgba(0,0,0,0.08)"}}.pc{transition:all 0.28s cubic-bezier(0.4,0,0.2,1)}`}</style>
        <Tog />
        <div style={{ position: "relative", padding: "54px 24px 34px", textAlign: "center", overflow: "hidden" }}>
          <div style={{ position: "absolute", inset: 0, background: t.hero, pointerEvents: "none" }} />
          <div style={{ position: "relative", zIndex: 1 }}>
            <div style={{ fontSize: 11.5, letterSpacing: 6, textTransform: "uppercase", fontFamily: "'DM Mono', monospace", color: t.mut, marginBottom: 16 }}>90-Day Masterclass</div>
            <h1 style={{ fontFamily: "'DM Sans', sans-serif", fontSize: "clamp(30px,6vw,48px)", fontWeight: 700, lineHeight: 1.1, margin: "0 0 8px", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>Gentleman & Ethics</h1>
            <p style={{ fontSize: 14.5, color: t.sub, fontFamily: "'DM Mono', monospace", margin: "10px 0 34px", fontWeight: 300, letterSpacing: 1.5 }}>presence / character / conduct / wisdom / legacy</p>
            <div style={{ display: "inline-flex", alignItems: "center", gap: 20, background: t.surface, border: `1px solid ${t.bdr}`, borderRadius: 22, padding: "20px 30px", backdropFilter: "blur(18px)" }}>
              <div style={{ position: "relative", width: 64, height: 64 }}>
                <svg width="64" height="64" viewBox="0 0 64 64">
                  <circle cx="32" cy="32" r="28" fill="none" stroke={t.ring} strokeWidth="3.5" />
                  <defs><linearGradient id="pg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#a78bfa"/><stop offset="33%" stopColor="#34d399"/><stop offset="66%" stopColor="#fbbf24"/><stop offset="100%" stopColor="#f472b6"/></linearGradient></defs>
                  <circle cx="32" cy="32" r="28" fill="none" stroke="url(#pg)" strokeWidth="3.5" strokeDasharray={`${(pct/100)*175.9} 175.9`} strokeLinecap="round" transform="rotate(-90 32 32)" style={{ transition: "stroke-dasharray 0.7s cubic-bezier(0.4,0,0.2,1)" }} />
                </svg>
                <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, fontWeight: 600, fontFamily: "'DM Mono', monospace", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>{pct}%</div>
              </div>
              <div style={{ textAlign: "left" }}>
                <div style={{ fontSize: 28, fontWeight: 700, fontFamily: "'DM Sans', sans-serif" }}>{ct}<span style={{ fontSize: 15, color: t.mut }}> / 90</span></div>
                <div style={{ fontSize: 11, color: t.mut, fontFamily: "'DM Mono', monospace", letterSpacing: 1.5 }}>days completed</div>
              </div>
            </div>
          </div>
        </div>
        <div style={{ padding: "8px 20px 52px", maxWidth: 720, margin: "0 auto" }}>
          {PHASES.map((p, i) => {
            const pl = ALL_LESSONS.filter(l => l.phase === p.id);
            const pc = pl.filter(l => done[l.day]).length;
            const ac = p.accent[m];
            return (
              <div key={p.id} className="pc" onClick={() => { setSelPhase(p.id); setVw("phase"); }} style={{ background: t.card, border: `1px solid ${t.bdr}`, borderRadius: 18, padding: "22px 24px", cursor: "pointer", marginBottom: 14, borderLeft: `3px solid ${ac}`, animation: `fu 0.55s ease ${i*0.09}s both`, position: "relative", overflow: "hidden", backdropFilter: "blur(10px)" }}>
                <div style={{ position: "absolute", top: -20, right: -20, width: 140, height: 140, background: `radial-gradient(circle, ${p.glow}, transparent 65%)`, pointerEvents: "none", opacity: dark ? 0.45 : 0.25 }} />
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", position: "relative" }}>
                  <div style={{ display: "flex", gap: 14, alignItems: "center" }}>
                    <span style={{ fontSize: 32, filter: dark ? "none" : "saturate(0.85)" }}>{p.icon}</span>
                    <div>
                      <div style={{ fontSize: 10.5, color: ac, letterSpacing: 3.5, textTransform: "uppercase", fontFamily: "'DM Mono', monospace", marginBottom: 4 }}>Phase {p.id} | {p.days}</div>
                      <div style={{ fontSize: 20, fontFamily: "'DM Sans', sans-serif", fontWeight: 700 }}>{p.title}</div>
                      <div style={{ fontSize: 12.5, color: t.sub, fontWeight: 400, marginTop: 1 }}>{p.subtitle}</div>
                    </div>
                  </div>
                  <div style={{ fontFamily: "'DM Mono', monospace", fontSize: 12.5, color: t.mut, textAlign: "right", minWidth: 50 }}>
                    <span style={{ color: ac, fontWeight: 600 }}>{pc}</span>/{pl.length}
                  </div>
                </div>
                <div style={{ marginTop: 16, height: 3, background: t.ring, borderRadius: 3, overflow: "hidden" }}>
                  <div style={{ height: "100%", width: `${(pc/pl.length)*100}%`, background: `linear-gradient(90deg, ${ac}, ${ac}77)`, borderRadius: 3, transition: "width 0.5s ease" }} />
                </div>
                <div style={{ marginTop: 11, fontSize: 11, color: t.mut, padding: "7px 12px", background: t.tag, borderRadius: 9, fontFamily: "'DM Mono', monospace", lineHeight: 1.5 }}>🧠 {p.mnemonic}</div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  if (vw === "phase" && phase) {
    const pl = ALL_LESSONS.filter(l => l.phase === phase.id);
    const ac = phase.accent[m];
    return (
      <div style={{ fontFamily: "'DM Sans', sans-serif", background: t.bg, minHeight: "100vh", color: t.txt, transition: "background 0.45s, color 0.45s" }}>
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600;9..40,700&family=DM+Mono:wght@300;400;500&display=swap" rel="stylesheet" />
        <style>{`@keyframes fu{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:translateY(0)}}@keyframes ex{from{opacity:0;max-height:0}to{opacity:1;max-height:900px}}`}</style>
        <Tog />
        <div style={{ position: "relative", overflow: "hidden" }}>
          <div style={{ position: "absolute", inset: 0, background: phase.gradient[m], opacity: dark ? 0.55 : 0.35, transition: "opacity 0.4s" }} />
          <div style={{ position: "relative", zIndex: 1, padding: "20px 20px 6px" }}>
            <button onClick={() => { setVw("home"); setSelPhase(null); setSelDay(null); }} style={{ background: t.togBg, border: `1px solid ${t.bdr}`, color: t.sub, padding: "7px 16px", borderRadius: 10, cursor: "pointer", fontSize: 12.5, fontFamily: "'DM Mono', monospace" }}>{"←"} Back</button>
          </div>
          <div style={{ position: "relative", zIndex: 1, padding: "10px 24px 30px", textAlign: "center" }}>
            <span style={{ fontSize: 44 }}>{phase.icon}</span>
            <h2 style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 34, fontWeight: 700, margin: "10px 0 4px" }}>Phase {phase.id}: {phase.title}</h2>
            <p style={{ color: t.sub, fontWeight: 400, margin: 0, fontSize: 14 }}>{phase.subtitle}</p>
            <p style={{ color: t.sub, fontSize: 13.5, marginTop: 12, maxWidth: 500, marginInline: "auto", lineHeight: 1.65 }}>{phase.description}</p>
            <div style={{ marginTop: 14, display: "inline-block", fontSize: 11.5, color: ac, padding: "7px 16px", background: `${ac}12`, borderRadius: 9, fontFamily: "'DM Mono', monospace", border: `1px solid ${ac}22` }}>{phase.mnemonic}</div>
          </div>
        </div>
        <div style={{ padding: "14px 20px 52px", maxWidth: 720, margin: "0 auto" }}>
          {pl.map((l, i) => {
            const op = selDay === l.day;
            return (
              <div key={l.day} ref={op ? ref : null} style={{ marginBottom: 8, animation: `fu 0.45s ease ${i*0.035}s both` }}>
                <div onClick={() => setSelDay(op ? null : l.day)} style={{ background: op ? t.surfHov : t.card, border: `1px solid ${op ? `${ac}40` : t.bdr}`, borderRadius: op ? "15px 15px 0 0" : 15, padding: "15px 18px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", transition: "all 0.25s", backdropFilter: "blur(8px)" }}>
                  <div style={{ display: "flex", gap: 14, alignItems: "center" }}>
                    <div onClick={e => { e.stopPropagation(); toggle(l.day); }} style={{ width: 27, height: 27, borderRadius: "50%", border: done[l.day] ? `2.5px solid ${ac}` : `2px solid ${t.bdr}`, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", background: done[l.day] ? `${ac}15` : "transparent", transition: "all 0.25s", flexShrink: 0 }}>
                      {done[l.day] && <span style={{ color: ac, fontSize: 13, fontWeight: 700 }}>{"✓"}</span>}
                    </div>
                    <div>
                      <div style={{ fontSize: 10.5, color: t.mut, fontFamily: "'DM Mono', monospace", letterSpacing: 1.2 }}>Day {l.day} | {typeIcon(l.type)} {typeLabel(l.type)}</div>
                      <div style={{ fontSize: 15, fontWeight: 500, color: done[l.day] ? t.mut : t.txt, textDecoration: done[l.day] ? "line-through" : "none", marginTop: 3 }}>{l.title}</div>
                    </div>
                  </div>
                  <span style={{ color: t.mut, fontSize: 15, transform: op ? "rotate(180deg)" : "rotate(0)", transition: "transform 0.25s", flexShrink: 0 }}>{"▾"}</span>
                </div>
                {op && (
                  <div style={{ background: t.surfHov, border: `1px solid ${ac}40`, borderTop: "none", borderRadius: "0 0 15px 15px", padding: 22, animation: "ex 0.35s ease", overflow: "hidden", backdropFilter: "blur(8px)" }}>
                    <p style={{ color: t.txt, lineHeight: 1.8, margin: "0 0 22px", fontSize: 14.5, fontWeight: 300 }}>{l.content}</p>
                    {[
                      { label: "💼 Work Challenge (BHN)", text: l.workChallenge, c: dark ? ["rgba(167,139,250,0.06)","rgba(167,139,250,0.13)","#a78bfa"] : ["rgba(109,40,217,0.04)","rgba(109,40,217,0.1)","#6d28d9"] },
                      { label: "🌱 Life Challenge", text: l.lifeChallenge, c: dark ? ["rgba(52,211,153,0.05)","rgba(52,211,153,0.11)","#34d399"] : ["rgba(5,150,105,0.04)","rgba(5,150,105,0.09)","#059669"] },
                      { label: "🧠 Memory Trick", text: l.memoryTrick, c: dark ? ["rgba(251,191,36,0.06)","rgba(251,191,36,0.14)","#fbbf24"] : ["rgba(217,119,6,0.04)","rgba(217,119,6,0.1)","#d97706"], highlight: true },
                    ].map((s, si) => (
                      <div key={si} style={{ background: s.c[0], border: `1px solid ${s.c[1]}`, borderRadius: 13, padding: "15px 18px", marginBottom: si < 2 ? 12 : 0 }}>
                        <div style={{ fontSize: 10.5, color: s.c[2], letterSpacing: 2.5, textTransform: "uppercase", fontFamily: "'DM Mono', monospace", marginBottom: 7 }}>{s.label}</div>
                        <p style={{ color: s.highlight ? (dark ? "#fde68a" : "#92400e") : t.txt, fontSize: s.highlight ? 14 : 13.5, lineHeight: 1.65, margin: 0, fontWeight: s.highlight ? 500 : 300 }}>{s.text}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    );
  }
  return null;
}
