import { useState, useEffect, useRef } from "react";

const SECTIONS = [
  { id: "laravel", title: "Laravel Mastery", subtitle: "From user to architect", icon: "\uD83D\uDD34" },
  { id: "beyond", title: "Beyond The Framework", subtitle: "The engine underneath", icon: "\u2699\uFE0F" },
];

const CONCEPTS = [
  // === LARAVEL MASTERY ===
  { id: "lifecycle", section: "laravel", title: "Request Lifecycle", subtitle: "How a request becomes a response", icon: "\uD83D\uDD04", accent: "#38bdf8", difficulty: "beginner",
    surface: "Every Laravel request starts at public/index.php, boots the application, runs through middleware, hits a route, executes a controller, and returns a response.",
    deep: "The full journey:\n\n1. Web server (Nginx/Apache) routes request to public/index.php\n2. Composer autoloader loads (vendor/autoload.php)\n3. Application instance created from bootstrap/app.php\n4. HTTP Kernel resolves from container\n5. Kernel bootstrappers run: DetectEnvironment, LoadConfiguration, HandleExceptions, RegisterFacades, RegisterProviders, BootProviders\n6. Request passes through global middleware stack\n7. Router matches URI to route definition\n8. Route middleware executes\n9. Controller method invoked\n10. Response object created\n11. Response passes back through middleware (reverse order)\n12. Kernel sends response to client\n13. Kernel terminates (terminable middleware runs)",
    code: "// public/index.php (simplified)\n$app = require_once __DIR__.'/../bootstrap/app.php';\n\n// Resolve the HTTP Kernel\n$kernel = $app->make(\n    Illuminate\\Contracts\\Http\\Kernel::class\n);\n\n// Handle the request\n$response = $kernel->handle(\n    $request = Request::capture()\n);\n\n// Send response to browser\n$response->send();\n\n// Run terminable middleware\n$kernel->terminate($request, $response);",
    diagram: "REQUEST FLOW:\n\n[Browser] --HTTP--> [Nginx/Apache]\n    |\n    v\n[public/index.php]\n    |\n    v\n[Bootstrap App] --> [Service Providers]\n    |\n    v\n[HTTP Kernel]\n    |\n    v\n[Global Middleware Stack]\n    |  Auth, CSRF, Session, etc.\n    v\n[Router] --> matches URI\n    |\n    v\n[Route Middleware]\n    |\n    v\n[Controller@method]\n    |\n    v\n[Response] --reverse middleware--> [Browser]",
    bhn: "In schemes-api, every API request follows this exact lifecycle. Your SQS consumer uses the Console Kernel instead of HTTP Kernel, but the bootstrapping (providers, config, facades) is identical. Understanding this explains why your queue workers sometimes need restart after config changes.",
    memoryTrick: "The lifecycle is a SANDWICH: bread (middleware) wraps the filling (controller). The bread is the SAME going in and coming out, but in REVERSE order." },

  { id: "container", section: "laravel", title: "Service Container", subtitle: "The beating heart of Laravel", icon: "\uD83D\uDC9A", accent: "#4ade80", difficulty: "intermediate",
    surface: "The Service Container is Laravel's IoC (Inversion of Control) container. It manages class dependencies and performs dependency injection. When you type-hint a class in a constructor, Laravel automatically resolves it.",
    deep: "The container uses PHP's Reflection API to inspect constructor parameters and auto-wire dependencies. Key binding types:\n\nbind(): New instance every time\nsingleton(): One instance, reused\nscoped(): One per request/job lifecycle\ninstance(): Bind an existing object\n\nContextual binding: different implementations for different consumers\nTagging: group related bindings\nExtending: modify resolved instances\n\nResolution order:\n1. Check if already resolved (singleton cache)\n2. Check explicit bindings\n3. Check contextual bindings\n4. Use Reflection to auto-wire\n5. Recursively resolve constructor dependencies",
    code: "// Basic binding\n$this->app->bind(EmailSender::class, SqsEmailSender::class);\n\n// Singleton (one instance forever)\n$this->app->singleton(EmailConfig::class, function ($app) {\n    return new EmailConfig(config('email'));\n});\n\n// Scoped (one per request, reset for queue jobs)\n$this->app->scoped(TemplateResolver::class);\n\n// Contextual binding\n$this->app->when(MarketingController::class)\n    ->needs(EmailSender::class)\n    ->give(SesEmailSender::class);\n\n$this->app->when(TransactionalController::class)\n    ->needs(EmailSender::class)\n    ->give(SqsEmailSender::class);\n\n// Auto-wiring (no binding needed!)\nclass EmailService {\n    public function __construct(\n        private EmailSender $sender, // auto-resolved\n        private TemplateResolver $resolver // auto-resolved\n    ) {}\n}",
    diagram: "SERVICE CONTAINER RESOLUTION:\n\n[Type-hint in constructor]\n    |\n    v\n[Container receives request]\n    |\n    +-- Is it a singleton already resolved?\n    |     YES --> return cached instance\n    |     NO  --> continue\n    |\n    +-- Is there an explicit binding?\n    |     YES --> use bound closure/class\n    |     NO  --> continue\n    |\n    +-- Is there a contextual binding?\n    |     YES --> use context-specific impl\n    |     NO  --> continue\n    |\n    +-- Use Reflection API\n    |     Read constructor params\n    |     Recursively resolve each\n    |     Create new instance\n    |\n    v\n[Return resolved instance]",
    bhn: "Your schemes-api uses the container everywhere. When you type-hint interfaces in controllers or services, the container resolves them. Your EmailCentralization service should be bound as a singleton (one config, reused) while individual email jobs should use scoped binding (fresh per job).",
    memoryTrick: "The container is a SMART VENDING MACHINE. You press the button (type-hint), it knows exactly which product (class) to dispense, and it builds it with all ingredients (dependencies) automatically." },

  { id: "providers", section: "laravel", title: "Service Providers", subtitle: "The bootstrapping backbone", icon: "\uD83D\uDD0C", accent: "#a78bfa", difficulty: "intermediate",
    surface: "Service Providers are the central place for all Laravel application bootstrapping. They register bindings, event listeners, middleware, routes, and any other setup. Every Laravel feature is bootstrapped by a service provider.",
    deep: "Two lifecycle methods:\n\nregister(): ONLY bind things into the container. No access to other services yet. No event listeners, no route registration.\n\nboot(): Called AFTER all providers are registered. Now you can use any service. Register event listeners, routes, view composers, etc.\n\nDeferred providers: Don't load until needed. Implement DeferrableProvider interface and provides() method listing what you offer. Can save 50ms+ per request in large apps.\n\nbootstrap/providers.php lists all active providers. Framework providers load first, then package providers, then your app providers.",
    code: "class EmailServiceProvider extends ServiceProvider\n{\n    // register() - ONLY container bindings\n    public function register(): void\n    {\n        $this->app->singleton(\n            EmailSender::class,\n            fn($app) => new SqsEmailSender(\n                $app->make(SqsClient::class),\n                config('email.queue_url')\n            )\n        );\n    }\n\n    // boot() - everything else\n    public function boot(): void\n    {\n        // Register event listeners\n        Event::listen(\n            EmailSent::class,\n            LogEmailDelivery::class\n        );\n\n        // Publish config\n        $this->publishes([\n            __DIR__.'/../config/email.php'\n                => config_path('email.php'),\n        ]);\n    }\n}\n\n// Deferred provider (loads only when needed)\nclass ReportServiceProvider extends ServiceProvider\n    implements DeferrableProvider\n{\n    public function provides(): array\n    {\n        return [ReportGenerator::class];\n    }\n}",
    diagram: "PROVIDER LIFECYCLE:\n\n[App Boot]\n    |\n    v\n[Load bootstrap/providers.php]\n    |\n    v\n[For each provider: call register()]\n    |  Container bindings ONLY\n    |  No cross-service access\n    v\n[ALL providers registered]\n    |\n    v\n[For each provider: call boot()]\n    |  Full access to everything\n    |  Events, routes, views, etc.\n    v\n[Application ready]\n\nDEFERRED PROVIDERS:\n[Not loaded at boot]\n    |\n    v\n[Container asked for EmailSender]\n    |\n    v\n[Checks provides() of deferred providers]\n    |\n    v\n[Loads provider on-demand]\n    |\n    v\n[Resolves the binding]",
    bhn: "In schemes-api, you likely have AppServiceProvider doing too much. Split into domain-specific providers: EmailServiceProvider, SchemeServiceProvider, NotificationServiceProvider. Each registers only its own bindings. Deferred providers reduce boot time for your API.",
    memoryTrick: "register() = PUT items on the shelf. boot() = OPEN the store. You can't sell items (boot) until everything is on the shelf (register)." },

  { id: "facades", section: "laravel", title: "Facades & Real-Time Facades", subtitle: "How the 'magic' actually works", icon: "\uD83C\uDFAD", accent: "#f472b6", difficulty: "intermediate",
    surface: "Facades provide a 'static' interface to classes available in the service container. When you call Cache::get('key'), you're NOT calling a static method. You're resolving a class from the container and calling an instance method.",
    deep: "How facades work internally:\n\n1. You call Cache::get('key')\n2. PHP's __callStatic() magic method intercepts\n3. Facade calls getFacadeAccessor() which returns a string (e.g., 'cache')\n4. That string is used to resolve from the container: app('cache')\n5. The real method get('key') is called on the resolved instance\n\nReal-time facades: prefix any class with Facades\\ namespace and it becomes a facade automatically. use Facades\\App\\Services\\EmailSender;\n\nFacades vs Dependency Injection:\n- Facades: convenient, harder to test, hide dependencies\n- DI: explicit, testable, clear dependencies\n- Best practice: Use DI in services/controllers, facades in routes/config/views",
    code: "// What you WRITE:\nCache::get('email_template_123');\n\n// What ACTUALLY HAPPENS:\nclass Cache extends Facade {\n    protected static function getFacadeAccessor() {\n        return 'cache'; // container key\n    }\n}\n\n// __callStatic intercepts:\npublic static function __callStatic($method, $args) {\n    $instance = static::getFacadeRoot();\n    // $instance = app('cache')\n    return $instance->$method(...$args);\n    // = app('cache')->get('email_template_123')\n}\n\n// Real-time facade (no registration needed):\nuse Facades\\App\\Services\\EmailSender;\n\nEmailSender::dispatch($email);\n// Resolves App\\Services\\EmailSender from\n// container and calls dispatch()",
    diagram: "FACADE RESOLUTION:\n\n[Your code: Cache::get('key')]\n    |\n    v\n[__callStatic('get', ['key'])]\n    |\n    v\n[getFacadeAccessor() returns 'cache']\n    |\n    v\n[app('cache')] --> Service Container\n    |\n    v\n[Illuminate\\Cache\\CacheManager instance]\n    |\n    v\n[->get('key')] on the REAL object\n    |\n    v\n[Result returned]\n\nIT'S NOT STATIC. It LOOKS static.\nThe container does the real work.",
    bhn: "In schemes-api, when you use Mail::send() or Queue::push(), these are facades. For testability in your email centralization, prefer injecting the Mailer interface via constructor DI over using the Mail facade. This makes mocking trivial in tests.",
    memoryTrick: "A Facade is a PUPPET SHOW. The puppet (static call) is what you see. The puppeteer (container instance) does the real work behind the curtain." },

  { id: "middleware", section: "laravel", title: "Middleware Pipeline", subtitle: "The Chain of Responsibility in action", icon: "\uD83D\uDEE1\uFE0F", accent: "#fbbf24", difficulty: "intermediate",
    surface: "Middleware filter HTTP requests entering your application. They form a pipeline where each middleware can inspect, modify, or reject the request before passing it to the next middleware or the controller.",
    deep: "Laravel uses the Pipeline class (Illuminate\\Pipeline\\Pipeline) which implements the Chain of Responsibility pattern using array_reduce. Each middleware receives the request and a $next closure.\n\nBefore middleware: runs code BEFORE the request hits the controller\nAfter middleware: runs code AFTER the response is generated\nTerminable middleware: runs AFTER the response is sent to the browser\n\nMiddleware groups: 'web' (session, CSRF, cookies), 'api' (throttle, auth:sanctum)\nMiddleware priority: certain middleware must run before others (session before auth)\n\nThe pipeline works in a Russian doll (decorator) pattern:\nMiddleware1(Middleware2(Middleware3(Controller)))\nRequest flows IN through 1->2->3->Controller\nResponse flows OUT through Controller->3->2->1",
    code: "// Before middleware\nclass CheckEmailQuota {\n    public function handle(Request $request, Closure $next) {\n        if ($this->quotaExceeded($request->user())) {\n            return response('Quota exceeded', 429);\n        }\n        return $next($request); // pass to next\n    }\n}\n\n// After middleware\nclass AddResponseHeaders {\n    public function handle(Request $request, Closure $next) {\n        $response = $next($request); // run first\n        $response->header('X-Email-Service', 'v2');\n        return $response; // modify response\n    }\n}\n\n// Terminable middleware (after response sent)\nclass LogEmailMetrics {\n    public function handle($request, Closure $next) {\n        return $next($request);\n    }\n    \n    public function terminate($request, $response) {\n        // Runs AFTER browser receives response\n        Metrics::record('email.api', [\n            'status' => $response->status(),\n            'duration' => microtime(true) - LARAVEL_START\n        ]);\n    }\n}",
    diagram: "MIDDLEWARE PIPELINE (Onion Model):\n\n         Request IN -->\n    +---------------------------+\n    | Middleware 1 (Auth)        |\n    |  +---------------------+  |\n    |  | Middleware 2 (CSRF)  |  |\n    |  |  +---------------+  |  |\n    |  |  | Middleware 3   |  |  |\n    |  |  |  +---------+   |  |  |\n    |  |  |  |Controller|  |  |  |\n    |  |  |  +---------+   |  |  |\n    |  |  +---------------+  |  |\n    |  +---------------------+  |\n    +---------------------------+\n         <-- Response OUT\n\n  Request:  M1 -> M2 -> M3 -> Controller\n  Response: Controller -> M3 -> M2 -> M1",
    bhn: "Your schemes-api API routes use the 'api' middleware group. For email centralization, you could add a custom CheckEmailServiceHealth middleware that checks if BNS is reachable before allowing email dispatch requests. This is the Circuit Breaker pattern implemented as middleware.",
    memoryTrick: "Middleware is an ONION. Each layer wraps the core (controller). Peel inward for requests, build outward for responses. Crying optional." },

  { id: "eloquent", section: "laravel", title: "Eloquent ORM Internals", subtitle: "How models come alive", icon: "\uD83D\uDCCA", accent: "#f97316", difficulty: "advanced",
    surface: "Eloquent is Laravel's ORM that maps database rows to PHP objects. Each model represents a table, and each instance represents a row. It uses the Active Record pattern.",
    deep: "Hydration: When Eloquent fetches rows, it 'hydrates' them into model instances. The raw PDO result (associative array) is mapped to model attributes via the $attributes array. The model tracks 'original' values separately to detect changes (dirty checking).\n\nDirty tracking: $model->isDirty('name') compares $attributes['name'] with $original['name']. Only dirty attributes are included in UPDATE queries.\n\nRelationship loading:\n- Eager loading (with()): uses separate queries with WHERE IN\n- Lazy loading: queries on first access (N+1 problem)\n- Lazy eager loading (load()): load after initial query\n\nQuery scopes: local scopes (scopeActive) and global scopes (SoftDeletes) modify the underlying query builder.\n\nModel events: creating, created, updating, updated, saving, saved, deleting, deleted. Observers and closures.\n\nCasting: $casts array transforms raw DB values to PHP types (json -> array, datetime -> Carbon, encrypted).",
    code: "// How hydration works internally:\n$results = DB::select('SELECT * FROM email_templates');\n// Returns array of stdClass objects\n\n// Eloquent hydrates each into a Model:\nforeach ($results as $row) {\n    $model = new EmailTemplate();\n    $model->setRawAttributes((array) $row, true);\n    // true = sync original (for dirty tracking)\n    $models[] = $model;\n}\n\n// Dirty tracking:\n$template = EmailTemplate::find(1);\n$template->subject = 'New Subject';\n$template->isDirty('subject');  // true\n$template->isDirty('body');     // false\n$template->getDirty();          // ['subject' => 'New Subject']\n// UPDATE only includes dirty fields!\n\n// N+1 problem:\n$templates = EmailTemplate::all(); // 1 query\nforeach ($templates as $t) {\n    echo $t->category->name; // N queries!\n}\n\n// Fix with eager loading:\n$templates = EmailTemplate::with('category')->get();\n// Query 1: SELECT * FROM email_templates\n// Query 2: SELECT * FROM categories\n//          WHERE id IN (1, 2, 3, ...)\n// Total: 2 queries regardless of N\n\n// Custom cast:\nclass EmailTemplate extends Model {\n    protected $casts = [\n        'variables_schema' => 'json',   // auto JSON decode\n        'sent_at' => 'datetime',         // auto Carbon\n        'is_active' => 'boolean',\n        'metadata' => AsEncryptedCollection::class,\n    ];\n}",
    diagram: "ELOQUENT HYDRATION FLOW:\n\n[DB Query executed]\n    |\n    v\n[PDO returns array of stdClass]\n    |\n    v\n[Model::hydrate()]\n    |  For each row:\n    |  1. new Model()\n    |  2. setRawAttributes(row)\n    |  3. syncOriginal() // for dirty tracking\n    |  4. Apply $casts transformations\n    |  5. Fire 'retrieved' event\n    v\n[Collection of Model instances]\n\nDIRTY TRACKING:\n\n$original = ['subject' => 'Old']\n$attributes = ['subject' => 'New']\n\nisDirty() compares $attributes vs $original\nOnly DIRTY fields go in UPDATE query\nSaves bandwidth and prevents race conditions",
    bhn: "Your email_templates table with variables_schema JSON column benefits from the 'json' cast. Eloquent auto-decodes it to array on read and encodes on write. For your 153+ templates across repos, eager loading relationships (with('category', 'variables')) prevents N+1 queries in admin panels.",
    memoryTrick: "Eloquent models are LIVING PHOTOGRAPHS of database rows. They remember their ORIGINAL state and know what CHANGED since they were loaded." },

  { id: "querybuilder", section: "laravel", title: "Query Builder vs Raw SQL", subtitle: "The SQL generation engine", icon: "\uD83D\uDD0D", accent: "#06b6d4", difficulty: "intermediate",
    surface: "The Query Builder provides a fluent interface for creating SQL queries. It uses PDO parameter binding for security and builds queries for multiple database drivers (MySQL, PostgreSQL, SQLite).",
    deep: "The Query Builder (Illuminate\\Database\\Query\\Builder) constructs SQL through a fluent API. Each method (where, join, orderBy) adds to internal arrays ($wheres, $joins, $orders). When you call get(), the Grammar class compiles these arrays into the final SQL string.\n\nEloquent's Builder wraps the Query Builder, adding model-specific features (scopes, eager loading, events). You can always drop to raw Query Builder via DB::table() or raw SQL via DB::select().\n\nPerformance considerations:\n- Query Builder adds ~0.1ms overhead vs raw SQL\n- Eloquent adds ~0.3ms overhead vs Query Builder (hydration)\n- For bulk operations (10,000+ rows), use Query Builder or raw SQL\n- For CRUD with events/observers, use Eloquent\n\nThe Leftmost Prefix Rule for composite indexes applies regardless of which method you use.",
    code: "// Eloquent (model-aware, events, hydration)\n$templates = EmailTemplate::where('active', true)\n    ->where('type', 'transactional')\n    ->orderBy('priority')\n    ->get();\n// Returns Collection of EmailTemplate models\n// Fires events, applies casts, tracks dirty\n\n// Query Builder (lighter, no model overhead)\n$templates = DB::table('email_templates')\n    ->where('active', true)\n    ->where('type', 'transactional')\n    ->orderBy('priority')\n    ->get();\n// Returns Collection of stdClass objects\n// No events, no casts, no dirty tracking\n\n// Raw SQL (full control)\n$templates = DB::select(\n    'SELECT t.*, c.name as category_name\n     FROM email_templates t\n     JOIN categories c ON t.category_id = c.id\n     WHERE t.active = ? AND t.type = ?\n     ORDER BY t.priority',\n    [true, 'transactional']\n);\n// Returns array of stdClass\n// YOU control the exact SQL\n\n// Bulk insert (skip Eloquent for performance)\nDB::table('email_logs')->insert(\n    collect($emails)->map(fn($e) => [\n        'template_id' => $e->template_id,\n        'sent_at' => now(),\n        'status' => 'queued',\n    ])->toArray()\n);\n// 1 query for 10,000 rows vs 10,000 Eloquent saves",
    diagram: "QUERY BUILDING PIPELINE:\n\n[Your fluent calls]\n    where('active', true)\n    orderBy('priority')\n    |\n    v\n[Builder stores in arrays]\n    $wheres = [['column'=>'active', 'value'=>true]]\n    $orders = [['column'=>'priority', 'direction'=>'asc']]\n    |\n    v\n[->get() triggers compilation]\n    |\n    v\n[Grammar::compileSelect()]\n    Reads $wheres, $joins, $orders arrays\n    Builds SQL string with ? placeholders\n    |\n    v\n[PDO::prepare() + execute()]\n    SQL: SELECT * FROM email_templates\n         WHERE active = ? ORDER BY priority\n    Bindings: [true]\n    |\n    v\n[Results returned]\n\nCHOOSE WISELY:\n  Eloquent  = CRUD + events + casting (< 100 rows)\n  Builder   = bulk reads + reports (100-10K rows)\n  Raw SQL   = complex joins + perf (10K+ rows)",
    bhn: "For your email_logs table which could grow to millions of rows, use Query Builder for reads and bulk inserts. For email_templates (smaller, needs events/casting), use Eloquent. Your Leftmost Prefix Rule knowledge from the MySQL deep dive applies here.",
    memoryTrick: "Eloquent = LUXURY car (comfortable, heavy, all features). Query Builder = SPORTS car (fast, lighter, fewer features). Raw SQL = FORMULA 1 (fastest, you build it yourself, no comfort)." },

  { id: "events", section: "laravel", title: "Events & Listeners", subtitle: "The Observer pattern at framework scale", icon: "\uD83D\uDCE1", accent: "#8b5cf6", difficulty: "intermediate",
    surface: "Laravel's event system is the Observer pattern: something happens (event), and one or more handlers react (listeners). Events decouple the 'what happened' from the 'what to do about it.'",
    deep: "Events are dispatched via the Dispatcher class. Listeners can be synchronous (run immediately) or queued (run in background via SQS/Redis).\n\nEvent discovery: Laravel can auto-discover listeners based on naming conventions (EventServiceProvider) or you register them explicitly.\n\nModel events: Eloquent models fire events on CRUD operations. Observers group model event handlers. The 'saving' event fires before BOTH create and update.\n\nEvent subscribers: a single class that handles multiple events (useful for audit logging).\n\nEvent broadcasting: push events to frontend via WebSockets (Pusher, Laravel Echo). Real-time notifications.",
    code: "// Define an event\nclass EmailDispatched {\n    public function __construct(\n        public readonly EmailTemplate $template,\n        public readonly string $recipient,\n        public readonly string $messageId\n    ) {}\n}\n\n// Listener (synchronous)\nclass LogEmailDispatch {\n    public function handle(EmailDispatched $event): void {\n        EmailLog::create([\n            'template_id' => $event->template->id,\n            'recipient' => $event->recipient,\n            'message_id' => $event->messageId,\n            'dispatched_at' => now(),\n        ]);\n    }\n}\n\n// Queued listener (runs in background)\nclass UpdateEmailMetrics implements ShouldQueue {\n    public $queue = 'metrics';\n    \n    public function handle(EmailDispatched $event): void {\n        // Heavy metric calculation\n        // Runs async via SQS\n    }\n}\n\n// Dispatching\nEmailDispatched::dispatch($template, $email, $msgId);\n// OR\nevent(new EmailDispatched($template, $email, $msgId));",
    diagram: "EVENT FLOW:\n\n[Something happens]\n    |\n    v\n[Event::dispatch(EmailDispatched)]\n    |\n    v\n[Dispatcher checks registered listeners]\n    |\n    +-- Sync listeners: execute immediately\n    |     LogEmailDispatch->handle()\n    |\n    +-- Queued listeners: push to queue\n    |     UpdateEmailMetrics -> SQS\n    |\n    +-- Subscribers: route to methods\n    |     EmailSubscriber->onDispatched()\n    |\n    v\n[All sync listeners complete]\n[Queued listeners run in background]",
    bhn: "Your email centralization SHOULD use events heavily. When an email is dispatched: event triggers logging, metrics, and any future reactions. Adding a new behavior (like tracking opens) = adding a new listener. ZERO changes to existing code. This is the Open/Closed Principle in action.",
    memoryTrick: "Events are RADIO BROADCASTS. You broadcast once. Anyone tuned to that frequency (listener) hears it. Adding a new radio (listener) doesn't change the broadcast." },

  { id: "queues", section: "laravel", title: "Queues, Jobs & Workers", subtitle: "Async processing engine", icon: "\u23F3", accent: "#ec4899", difficulty: "advanced",
    surface: "Queues let you defer time-consuming tasks (sending emails, processing uploads) to be handled in the background. Laravel supports SQS, Redis, Beanstalkd, and database queues.",
    deep: "Job lifecycle:\n1. dispatch(new SendEmail($data)) serializes the job and pushes to queue driver\n2. Queue worker (php artisan queue:work) polls the queue\n3. Worker deserializes the job\n4. Calls the job's handle() method\n5. On success: delete from queue\n6. On failure: retry (based on $tries) or move to failed_jobs table\n\nSQS specifics:\n- Visibility timeout: how long SQS hides a message while being processed\n- DLQ (Dead Letter Queue): messages that fail maxReceiveCount times\n- Long polling: reduces empty responses and API costs\n\nJob middleware: rate limiting, preventing overlaps, throttling\nJob batching: dispatch many jobs, track completion, handle failures\nJob chaining: sequential execution (Job A -> Job B -> Job C)\n\nqueue:work vs queue:listen:\n- work: boots app ONCE, processes many jobs (faster, needs restart for code changes)\n- listen: boots app PER job (slower, always uses latest code)",
    code: "class DispatchEmail implements ShouldQueue {\n    use Dispatchable, InteractsWithQueue,\n        Queueable, SerializesModels;\n\n    public $tries = 3;\n    public $backoff = [10, 60, 300]; // exponential\n    public $timeout = 30;\n    public $maxExceptions = 2;\n\n    public function __construct(\n        private EmailTemplate $template,\n        private string $recipient\n    ) {}\n\n    public function handle(EmailSender $sender): void {\n        $sender->send(\n            $this->template,\n            $this->recipient\n        );\n    }\n\n    public function failed(Throwable $e): void {\n        // Notify team, log to email_failures\n        EmailFailure::record($this->template, $e);\n    }\n\n    // Job middleware\n    public function middleware(): array {\n        return [\n            new RateLimited('emails'),\n            new WithoutOverlapping($this->recipient),\n        ];\n    }\n}\n\n// Dispatching with options\nDispatchEmail::dispatch($template, $email)\n    ->onQueue('emails')\n    ->delay(now()->addSeconds(30));",
    diagram: "QUEUE JOB LIFECYCLE:\n\n[dispatch()] --> [Serialize job]\n    |\n    v\n[Push to SQS/Redis]\n    |\n    v\n[Worker polls queue]\n    |\n    v\n[Deserialize job]\n    |\n    v\n[Run job middleware]\n    |  RateLimited, WithoutOverlapping\n    v\n[Execute handle()]\n    |\n    +-- SUCCESS --> delete from queue\n    |\n    +-- FAILURE --> retry?\n         |  YES ($tries remaining)\n         |    --> release back with backoff\n         |  NO (exhausted)\n         |    --> failed() callback\n         |    --> move to failed_jobs table\n         |    --> (SQS: move to DLQ)",
    bhn: "This is YOUR email centralization core. Your SQS-based pipeline dispatches DispatchEmail jobs. The backoff strategy [10, 60, 300] handles BNS temporary failures gracefully. Job middleware with RateLimited prevents overwhelming BNS. The DLQ catches poison messages that would otherwise block the queue.",
    memoryTrick: "A queue is a POST OFFICE. Jobs are LETTERS. Workers are POSTAL WORKERS. Failed letters go to the DEAD LETTER OFFICE. The sender doesn't wait for delivery." },

  { id: "caching", section: "laravel", title: "Caching Layer", subtitle: "Speed through smart storage", icon: "\u26A1", accent: "#eab308", difficulty: "intermediate",
    surface: "Laravel provides a unified API for various caching backends (Redis, Memcached, file, database, array). The Cache facade and cache() helper abstract the driver.",
    deep: "Cache operations: get, put, remember (get or compute), forever, forget, flush, tags.\n\nCache::remember() is the most powerful: check cache, if miss then compute and store.\n\nCache tags: group related items for bulk invalidation. Only Redis/Memcached support tags.\n\nCache locks: distributed locks for preventing race conditions. Cache::lock('process-email-123')->get()\n\nAtomic operations: increment/decrement for counters without race conditions.\n\nYour Redis/ElastiCache migration means you can use:\n- Cache tags for template groups\n- Distributed locks for queue processing\n- Atomic counters for rate limiting\n\nCache invalidation strategies:\n- TTL (time-based expiry)\n- Event-based (invalidate on model update)\n- Version-based (cache key includes version number)",
    code: "// remember: get from cache OR compute and store\n$template = Cache::remember(\n    'email_template_' . $id,\n    now()->addHours(24),\n    fn() => EmailTemplate::with('variables')->find($id)\n);\n\n// Cache tags (Redis only)\nCache::tags(['email', 'templates'])->put(\n    'template_123', $template, 3600\n);\nCache::tags(['email'])->flush(); // clear all email cache\n\n// Distributed lock (prevent double processing)\n$lock = Cache::lock('sending_email_' . $emailId, 30);\nif ($lock->get()) {\n    try {\n        $this->sendEmail($emailId);\n    } finally {\n        $lock->release();\n    }\n}\n\n// Atomic counter for rate limiting\n$count = Cache::increment('emails_sent_' . $userId);\nif ($count === 1) {\n    Cache::put('emails_sent_' . $userId, 1, 3600);\n}\nif ($count > 100) {\n    throw new RateLimitExceededException();\n}\n\n// Event-based invalidation\nclass EmailTemplate extends Model {\n    protected static function booted() {\n        static::updated(function ($template) {\n            Cache::forget('email_template_' . $template->id);\n            Cache::tags(['templates'])->flush();\n        });\n    }\n}",
    diagram: "CACHE::REMEMBER() FLOW:\n\n[Cache::remember('key', ttl, closure)]\n    |\n    v\n[Check cache for 'key']\n    |\n    +-- HIT: return cached value (fast!)\n    |\n    +-- MISS:\n         |  Execute closure\n         |  Store result in cache with TTL\n         |  Return result\n\nINVALIDATION STRATEGIES:\n\n  TTL-based:     Set expiry, let it expire naturally\n  Event-based:   Model updated -> flush related cache\n  Version-based: 'template_v3_123' -> change version on update\n  Tag-based:     Group items, flush entire group\n\nBEST PRACTICE:\n  Cache::remember() + Event-based invalidation\n  = Fresh data + Fast reads",
    bhn: "Your ElastiCache/Redis migration enables all of this. For email templates, use Cache::remember() with event-based invalidation. When a template is updated in the CMS, fire a TemplateUpdated event that flushes the cache. Your 153+ templates will load from Redis instead of MySQL for every single email.",
    memoryTrick: "Cache is a SHORTCUT through a forest. The first person (cache miss) blazes the trail. Everyone after (cache hit) walks the shortcut. Event invalidation = clearing the shortcut when the forest changes." },

  { id: "testing", section: "laravel", title: "Testing: Unit, Feature & Mocking", subtitle: "Confidence through verification", icon: "\u2705", accent: "#22c55e", difficulty: "intermediate",
    surface: "Laravel uses PHPUnit with added testing helpers. Feature tests hit the full application stack (HTTP tests). Unit tests isolate single classes. Mocking fakes external dependencies.",
    deep: "Test types:\n- Unit: test a single class/method in isolation. Mock dependencies.\n- Feature: test through HTTP. Hit routes, check responses, verify database.\n- Integration: test multiple classes working together.\n\nLaravel fakes: built-in test doubles for Queue, Event, Mail, Notification, Storage, HTTP.\n\nQueue::fake() prevents actual jobs from dispatching. Then assert:\nQueue::assertPushed(SendEmail::class)\nQueue::assertPushedOn('emails', SendEmail::class)\n\nDatabase testing: RefreshDatabase (migrate + rollback per test), DatabaseTransactions (wrap in transaction, rollback).\n\nFactories: generate realistic test data. EmailTemplate::factory()->create();\n\nHTTP tests: get(), post(), put(), delete() with assertions on status, JSON, redirects.",
    code: "// Feature test: API endpoint\nclass EmailDispatchTest extends TestCase {\n    use RefreshDatabase;\n\n    public function test_dispatches_email_to_queue(): void {\n        Queue::fake();\n\n        $template = EmailTemplate::factory()->create();\n\n        $response = $this->postJson('/api/emails/dispatch', [\n            'template_id' => $template->id,\n            'recipient' => 'user@example.com',\n        ]);\n\n        $response->assertStatus(202);\n\n        Queue::assertPushed(DispatchEmail::class,\n            fn($job) => $job->recipient === 'user@example.com'\n        );\n    }\n}\n\n// Unit test: service in isolation\nclass EmailServiceTest extends TestCase {\n    public function test_resolves_template_variables(): void {\n        $resolver = new VariableResolver();\n\n        $result = $resolver->resolve(\n            'Hello {{name}}, your order {{orderId}}',\n            ['name' => 'Vishwanath', 'orderId' => '12345']\n        );\n\n        $this->assertEquals(\n            'Hello Vishwanath, your order 12345',\n            $result\n        );\n    }\n}\n\n// Mocking external services\npublic function test_handles_bns_failure(): void {\n    $this->mock(BnsClient::class)\n        ->shouldReceive('sendRaw')\n        ->andThrow(new ConnectionException());\n\n    $this->expectException(EmailDeliveryException::class);\n\n    app(EmailSender::class)->send($template, $email);\n}",
    diagram: "TESTING PYRAMID:\n\n         /\\      E2E Tests\n        /  \\     (Few: browser, Dusk)\n       /    \\\n      /------\\   Feature Tests\n     / HTTP    \\  (Some: API, routes)\n    /  testing  \\\n   /------------\\  Unit Tests\n  / Class-level   \\(Many: services, models)\n /  isolation       \\\n/____________________\\\n\nFAKES vs MOCKS:\n  Queue::fake()  --> captures dispatched jobs\n  Mail::fake()   --> captures sent emails\n  Event::fake()  --> captures fired events\n  Http::fake()   --> returns preset responses\n  Storage::fake()--> in-memory filesystem",
    bhn: "For your email centralization, use Queue::fake() to verify jobs dispatch correctly without touching SQS. Mock BnsClient to test failure handling without calling the real BNS service. Your SonarQube quality gate failures for missing PHPUnit coverage? Feature tests with fakes are the fastest path to coverage.",
    memoryTrick: "Fakes are STUNT DOUBLES. They look and behave like the real thing, but nobody gets hurt. Test with stunt doubles, deploy with the real actors." },

  { id: "errorhandling", section: "laravel", title: "Error Handling & Exceptions", subtitle: "Graceful failure management", icon: "\uD83D\uDEA8", accent: "#ef4444", difficulty: "intermediate",
    surface: "Laravel's exception handler (app/Exceptions/Handler.php in older versions, or bootstrap/app.php withExceptions in Laravel 11+) catches all exceptions and converts them to appropriate HTTP responses.",
    deep: "Exception flow:\n1. Exception thrown anywhere in your code\n2. Caught by the exception handler\n3. report() method called (logging, external services)\n4. render() method converts to HTTP response\n\nIn Laravel 11+/12, exception handling is configured in bootstrap/app.php:\n- withExceptions() closure for customization\n- Reportable exceptions: log or send to external services\n- Renderable exceptions: custom HTTP responses\n- Don't report: exceptions that shouldn't be logged\n\nCustom exceptions for your domain:\n- EmailDeliveryException (503 response)\n- TemplateNotFoundException (404 response)\n- QuotaExceededException (429 response)\n\nEach exception can define its own report() and render() methods.",
    code: "// Custom domain exception\nclass EmailDeliveryException extends Exception {\n    public function __construct(\n        public readonly string $templateId,\n        public readonly string $provider,\n        string $message,\n        Throwable $previous = null\n    ) {\n        parent::__construct($message, 503, $previous);\n    }\n\n    // Custom reporting\n    public function report(): void {\n        Log::channel('email_errors')->error(\n            'Email delivery failed', [\n                'template' => $this->templateId,\n                'provider' => $this->provider,\n                'error' => $this->getMessage(),\n            ]\n        );\n    }\n\n    // Custom rendering\n    public function render(Request $request): JsonResponse {\n        return response()->json([\n            'error' => 'Email delivery failed',\n            'template_id' => $this->templateId,\n            'retry_after' => 30,\n        ], 503);\n    }\n}\n\n// In bootstrap/app.php (Laravel 12)\n->withExceptions(function (Exceptions $exceptions) {\n    $exceptions->dontReport([\n        TemplateNotFoundException::class,\n    ]);\n\n    $exceptions->reportable(function (EmailDeliveryException $e) {\n        // Send to New Relic\n        newrelic_notice_error($e);\n    });\n})",
    diagram: "EXCEPTION FLOW:\n\n[Exception thrown]\n    |\n    v\n[Exception Handler catches it]\n    |\n    v\n[Should report?]\n    +-- NO (in dontReport list) --> skip\n    +-- YES\n         |  Call exception's report() method\n         |  OR handler's reportable() callback\n         |  Log, send to New Relic, Slack, etc.\n    |\n    v\n[Render response]\n    +-- Has custom render()? --> use it\n    +-- No? --> default response\n         |  API request? --> JSON error\n         |  Web request? --> error view\n    |\n    v\n[HTTP Response to client]",
    bhn: "Your email centralization should have domain-specific exceptions. When BNS returns a 503, throw EmailDeliveryException with context. Your New Relic integration can catch these via the reportable callback. Structured exceptions make debugging 10x faster than generic catch blocks.",
    memoryTrick: "Exception handling is a FIRE DEPARTMENT. The exception is the fire. report() = calling 911. render() = evacuating people safely. Custom exceptions = fire department knowing exactly which building is burning." },

  { id: "artisan", section: "laravel", title: "Artisan Console & Custom Commands", subtitle: "The CLI backbone", icon: "\uD83D\uDCBB", accent: "#64748b", difficulty: "beginner",
    surface: "Artisan is Laravel's CLI tool. Beyond built-in commands (migrate, queue:work, cache:clear), you can create custom commands for any task: data migrations, reports, maintenance, cron jobs.",
    deep: "Custom commands extend Illuminate\\Console\\Command. Key features:\n- $signature: define arguments and options with a readable syntax\n- handle(): the command logic\n- Scheduling: commands can run on a schedule via app/Console/Kernel.php or routes/console.php\n- Output helpers: info(), error(), table(), progressBar(), choice()\n- Calling other commands: $this->call('email:verify')\n\nFor your email centralization, custom commands are essential:\n- email:health (check BNS connectivity)\n- email:migrate-templates (strangler fig migration)\n- email:stats (daily email metrics)\n- email:retry-failed (reprocess DLQ messages)",
    code: "class EmailHealthCheck extends Command {\n    protected $signature = 'email:health\n        {--provider=all : Which provider to check}\n        {--verbose : Show detailed output}';\n\n    protected $description = 'Check email service health';\n\n    public function handle(BnsClient $bns): int {\n        $this->info('Checking email service health...');\n\n        $bar = $this->output->createProgressBar(3);\n\n        // Check SQS\n        $bar->advance();\n        $sqsOk = $this->checkSqs();\n\n        // Check BNS\n        $bar->advance();\n        $bnsOk = $this->checkBns($bns);\n\n        // Check templates\n        $bar->advance();\n        $templatesOk = $this->checkTemplates();\n\n        $bar->finish();\n        $this->newLine();\n\n        $this->table(\n            ['Service', 'Status'],\n            [\n                ['SQS', $sqsOk ? 'OK' : 'FAIL'],\n                ['BNS', $bnsOk ? 'OK' : 'FAIL'],\n                ['Templates', $templatesOk ? 'OK' : 'FAIL'],\n            ]\n        );\n\n        return $sqsOk && $bnsOk && $templatesOk\n            ? Command::SUCCESS\n            : Command::FAILURE;\n    }\n}\n\n// Schedule it (routes/console.php)\nSchedule::command('email:health')\n    ->everyFiveMinutes()\n    ->onFailure(fn() => Notification::send(\n        $admins, new HealthCheckFailed()\n    ));",
    diagram: "ARTISAN COMMAND LIFECYCLE:\n\n[php artisan email:health --verbose]\n    |\n    v\n[Console Kernel resolves command]\n    |\n    v\n[Parse $signature for args/options]\n    |\n    v\n[Resolve dependencies via Container]\n    |  BnsClient injected into handle()\n    v\n[Execute handle() method]\n    |\n    v\n[Return exit code]\n    SUCCESS = 0, FAILURE = 1\n\nSCHEDULING:\n[Laravel Scheduler runs every minute via cron]\n    * * * * * php artisan schedule:run\n    |\n    v\n[Checks which commands are due]\n    |\n    v\n[Runs due commands]",
    bhn: "Build an email:health command for your centralization. Run it every 5 minutes via the scheduler. When BNS is down, it notifies your team before users notice. This is proactive observability, exactly what your New Relic dashboards complement.",
    memoryTrick: "Artisan commands are ROBOTS you build for repetitive tasks. Once built, they work tirelessly, on schedule, without your intervention." },

  // === BEYOND THE FRAMEWORK ===
  { id: "php-execution", section: "beyond", title: "PHP Execution Model", subtitle: "From source code to CPU instructions", icon: "\u2699\uFE0F", accent: "#f97316", difficulty: "advanced",
    surface: "PHP is an interpreted language. Your .php file goes through: Lexing (tokenizing) -> Parsing (AST) -> Compilation (opcodes) -> Execution (Zend VM). OPcache stores compiled opcodes. JIT compiles hot opcodes to machine code.",
    deep: "The full pipeline:\n\n1. LEXING (Tokenizer): Source code -> tokens. <?php echo 'hello'; becomes T_OPEN_TAG, T_ECHO, T_CONSTANT_ENCAPSED_STRING, ';'\n\n2. PARSING: Tokens -> Abstract Syntax Tree (AST). The hierarchical structure of your code. Added in PHP 7.0, previously parser generated opcodes directly.\n\n3. COMPILATION: AST -> Opcodes. Low-level instructions for the Zend Virtual Machine. Like assembly language for PHP.\n\n4. EXECUTION: Zend VM reads opcodes and executes them. This is where your code actually 'runs.'\n\nOPcache caches step 3 output (opcodes) in shared memory. Skips steps 1-3 on subsequent requests. This alone can 2x your performance.\n\nJIT (PHP 8.0+): Takes frequently executed opcodes and compiles them to native machine code (x86/x64). Bypasses the Zend VM entirely for hot paths. Uses DynASM from LuaJIT.\n\nPreloading (PHP 7.4+): Load framework files into OPcache at server start. Never re-read from disk.",
    code: "// See what PHP does with your code:\n\n// 1. Tokenizer output:\n$tokens = token_get_all('<?php echo \"hello\";');\n// T_OPEN_TAG, T_ECHO, T_WHITESPACE,\n// T_CONSTANT_ENCAPSED_STRING, ';'\n\n// 2. AST (use php-ast extension):\n// echo 'hello' becomes:\n// AST_STMT_LIST\n//   AST_ECHO\n//     AST_ZVAL 'hello'\n\n// 3. Opcodes (use phpdbg or vld extension):\n// php -d vld.active=1 script.php\n// ECHO      'hello'\n// RETURN    1\n\n// 4. OPcache status:\n$status = opcache_get_status();\n$scripts = $status['scripts']; // cached files\n$memory = $status['memory_usage'];\n$hitRate = $status['opcache_statistics']['opcache_hit_rate'];\n// Target: > 99% hit rate in production\n\n// 5. JIT status:\n$jit = $status['jit'];\n// enabled, buffer_size, buffer_free\n// opt_level, opt_flags\n\n// OPcache config for production:\n// opcache.enable=1\n// opcache.memory_consumption=256\n// opcache.max_accelerated_files=20000\n// opcache.validate_timestamps=0  (don't check files!)\n// opcache.jit=tracing\n// opcache.jit_buffer_size=128M",
    diagram: "PHP EXECUTION PIPELINE:\n\n[your_file.php] (source code)\n    |\n    v\n[LEXER/TOKENIZER]\n    Breaks source into tokens\n    <?php echo 'hi'; -> T_ECHO, 'hi', ';'\n    |\n    v\n[PARSER]\n    Tokens -> Abstract Syntax Tree (AST)\n    Tree structure of your code\n    |\n    v\n[COMPILER]\n    AST -> Opcodes (bytecode)\n    Low-level Zend VM instructions\n    |\n    +-- [OPcache stores opcodes here]\n    |    Next request skips Lexer/Parser/Compiler\n    |    Straight to execution (2x faster)\n    |\n    v\n[ZEND VIRTUAL MACHINE]\n    Reads and executes opcodes\n    |\n    +-- [JIT compiles hot opcodes to machine code]\n    |    Frequently executed paths\n    |    Bypasses VM entirely\n    |    Native CPU execution (up to 3x faster)\n    |\n    v\n[OUTPUT] -> Response\n\nWITHOUT OPcache: Lex -> Parse -> Compile -> Execute (every request)\nWITH OPcache:    Execute (from cached opcodes)\nWITH JIT:        CPU runs native code directly",
    bhn: "Your schemes-api on ECS should have OPcache enabled with validate_timestamps=0 (since you deploy new containers for code changes). JIT with tracing mode benefits your SQS consumers (long-running processes). A preloaded Laravel app reduces cold-start latency from ~45ms to ~18ms.",
    memoryTrick: "PHP execution is a TRANSLATION AGENCY. Source code (English) -> Tokens (words) -> AST (sentence structure) -> Opcodes (simplified instructions) -> Execution (action). OPcache memorizes the translation. JIT speaks the CPU's NATIVE language." },

  { id: "phpfpm", section: "beyond", title: "PHP-FPM & Process Management", subtitle: "How PHP serves millions of requests", icon: "\uD83D\uDD04", accent: "#06b6d4", difficulty: "advanced",
    surface: "PHP-FPM (FastCGI Process Manager) is the process manager that runs PHP for web servers. It pre-forks worker processes that handle requests. Each worker handles ONE request at a time (shared-nothing architecture).",
    deep: "Process model:\n- Master process: manages worker pool, handles signals, monitors health\n- Worker processes: handle individual requests\n\nPool configuration:\npm = dynamic (recommended for most cases)\npm.max_children = maximum number of workers\npm.start_servers = workers at startup\npm.min_spare_servers = minimum idle workers\npm.max_spare_servers = maximum idle workers\npm.max_requests = requests before worker restart (prevents memory leaks)\n\nSizing formula:\npm.max_children = Available_RAM / Average_PHP_Memory_Per_Process\nExample: 2GB available / 40MB per process = 50 workers\n\nShared-nothing architecture: each request starts clean. No shared state between requests (unless you use external storage like Redis/sessions). This is WHY PHP scales so well for web: no thread safety issues, no shared memory corruption.\n\nThe tradeoff: every request bootstraps the application. This is why OPcache and preloading matter so much.",
    code: "// PHP-FPM pool configuration (/etc/php/8.3/fpm/pool.d/www.conf)\n\n[www]\nuser = www-data\ngroup = www-data\n\n; Process management\npm = dynamic\npm.max_children = 50        ; max concurrent requests\npm.start_servers = 10       ; workers at startup\npm.min_spare_servers = 5    ; min idle workers waiting\npm.max_spare_servers = 20   ; max idle workers\npm.max_requests = 1000      ; restart after 1000 requests\n                            ; prevents memory leaks\n\n; Performance tuning\npm.process_idle_timeout = 10s\nrequest_terminate_timeout = 60s  ; kill slow requests\nrequest_slowlog_timeout = 5s     ; log slow requests\n\n; Status page (for monitoring)\npm.status_path = /fpm-status\nping.path = /fpm-ping\n\n// Check FPM status programmatically:\n// curl http://localhost/fpm-status?json&full\n// Returns: active processes, idle, queue length,\n//          max children reached, slow requests\n\n// In your Dockerfile (ECS):\nRUN echo 'pm.max_children = 30' >> /usr/local/etc/php-fpm.d/zz-docker.conf\nRUN echo 'pm.max_requests = 500' >> /usr/local/etc/php-fpm.d/zz-docker.conf",
    diagram: "PHP-FPM PROCESS MODEL:\n\n[Nginx] --FastCGI--> [PHP-FPM Master]\n                         |\n              +----------+----------+\n              |          |          |\n           [Worker]  [Worker]  [Worker]  ...\n           (idle)    (busy)    (idle)\n\nDYNAMIC POOL MANAGEMENT:\n\n  Low traffic:  5 workers idle, waiting\n  Normal:       10-20 workers active\n  Spike:        Spawns up to max_children (50)\n  After spike:  Kills extra workers back to min_spare\n\nSHARED-NOTHING ARCHITECTURE:\n\n  Request 1 --> [Worker A] --> Response 1\n                  (dies/resets)\n  Request 2 --> [Worker B] --> Response 2\n                  (dies/resets)\n\n  No shared state between requests!\n  Each request = clean slate\n  This is WHY PHP scales for web\n\nMEMORY MATH:\n  Available RAM:  2 GB\n  Per worker:     40 MB average\n  max_children:   2048 / 40 = ~50 workers\n  Concurrent:     50 requests at same time",
    bhn: "Your ECS containers run PHP-FPM. If your container has 512MB memory, and each Laravel request uses ~30MB, you can handle ~15 concurrent requests per container. If you're getting 503s, check if pm.max_children is too low. Your ECS Deployment Circuit Breaker failures could be FPM workers dying from OOM (Out of Memory). Set pm.max_requests=500 to prevent memory leaks from accumulating.",
    memoryTrick: "PHP-FPM is a TAXI FLEET. The master is the DISPATCHER. Workers are TAXIS. Each taxi takes ONE passenger (request) at a time. When the passenger arrives, the taxi is free for the next. max_children = how many taxis you own." },

  { id: "http-protocol", section: "beyond", title: "How HTTP Actually Works", subtitle: "The protocol beneath every request", icon: "\uD83C\uDF10", accent: "#8b5cf6", difficulty: "intermediate",
    surface: "HTTP (HyperText Transfer Protocol) is the language browsers and servers speak. Every Laravel request is an HTTP message: method (GET/POST), headers (metadata), body (payload), and status code (200, 404, 500).",
    deep: "The full network journey:\n\n1. DNS Resolution: browser looks up IP for domain name\n2. TCP 3-Way Handshake: SYN -> SYN-ACK -> ACK (establish connection)\n3. TLS Handshake (HTTPS): negotiate encryption (adds 1-2 round trips)\n4. HTTP Request sent: method, URI, headers, body\n5. Server processes request (Laravel lifecycle)\n6. HTTP Response sent: status, headers, body\n7. Connection: keep-alive (reuse) or close\n\nHTTP/1.1: one request per connection (or pipelining)\nHTTP/2: multiplexing (multiple requests on one connection)\nHTTP/3: QUIC protocol (UDP-based, faster handshakes)\n\nHeaders that matter:\nContent-Type: how to interpret the body\nAuthorization: who you are\nCache-Control: caching instructions\nX-Request-ID: trace requests across services\nConnection: keep-alive vs close\n\nStatus codes:\n2xx: success (200 OK, 201 Created, 204 No Content)\n3xx: redirect (301 Permanent, 302 Temporary, 304 Not Modified)\n4xx: client error (400 Bad Request, 401 Unauthorized, 404 Not Found, 429 Too Many Requests)\n5xx: server error (500 Internal, 502 Bad Gateway, 503 Unavailable)",
    code: "// What an HTTP request ACTUALLY looks like on the wire:\n\n// REQUEST:\n// POST /api/v2/emails/dispatch HTTP/1.1\n// Host: schemes-api.bhn.com\n// Authorization: Bearer eyJhbGci...\n// Content-Type: application/json\n// X-Request-ID: req-abc-123\n// Accept: application/json\n//\n// {\"template_id\": 42, \"recipient\": \"user@example.com\"}\n\n// RESPONSE:\n// HTTP/1.1 202 Accepted\n// Content-Type: application/json\n// X-Request-ID: req-abc-123\n// X-RateLimit-Remaining: 99\n// Cache-Control: no-store\n//\n// {\"message_id\": \"msg-xyz-789\", \"status\": \"queued\"}\n\n// In Laravel, you work with abstracted Request/Response:\n$request->method();      // 'POST'\n$request->header('Authorization'); // 'Bearer eyJ...'\n$request->json('template_id');     // 42\n\nreturn response()->json(\n    ['message_id' => $msgId, 'status' => 'queued'],\n    202  // HTTP status code\n)->header('X-Request-ID', $request->header('X-Request-ID'));",
    diagram: "HTTP REQUEST JOURNEY:\n\n[Browser/Client]\n    |\n    v\n[DNS Resolution] example.com -> 93.184.216.34\n    |\n    v\n[TCP 3-Way Handshake]\n    Client: SYN -------->\n    Server: <-------- SYN-ACK\n    Client: ACK -------->\n    (Connection established)\n    |\n    v\n[TLS Handshake] (if HTTPS)\n    Negotiate cipher suite\n    Exchange certificates\n    Generate session keys\n    (1-2 extra round trips)\n    |\n    v\n[HTTP Request]\n    POST /api/emails HTTP/1.1\n    Headers + Body\n    |\n    v\n[Server Processes] (Laravel lifecycle)\n    |\n    v\n[HTTP Response]\n    202 Accepted\n    Headers + Body\n    |\n    v\n[Connection]\n    Keep-alive? Reuse for next request\n    Close? TCP FIN handshake",
    bhn: "Understanding HTTP helps you debug issues your abstractions hide. When BNS returns a 503, that's HTTP telling you the service is overloaded. When your ECS health checks fail, it's because the load balancer's HTTP GET to /health didn't get a 200 back. Your SQS messages aren't HTTP, they're AWS SDK calls, which use HTTP underneath.",
    memoryTrick: "HTTP is a CONVERSATION. Request = question. Response = answer. Status code = the TONE of the answer (200='sure!', 404='what?', 500='I broke')." },

  { id: "memory", section: "beyond", title: "PHP Memory Management", subtitle: "How PHP handles your data in RAM", icon: "\uD83E\uDDE0", accent: "#ef4444", difficulty: "advanced",
    surface: "PHP manages memory automatically with reference counting and a garbage collector for circular references. Each variable takes memory, and PHP cleans up when a variable is no longer referenced.",
    deep: "Reference counting: every value has a refcount. When a variable points to a value, refcount++. When it goes out of scope or is unset, refcount--. When refcount hits 0, memory is freed.\n\nCopy-on-write (COW): when you assign $b = $a, PHP doesn't copy the data. Both point to the same value. Only when one is MODIFIED does PHP create a copy. This is why passing large arrays to functions is cheap (until you modify them).\n\nGarbage collector: handles circular references (A -> B -> A). Runs periodically when the root buffer fills (10,000 potential roots by default).\n\nMemory limit: memory_limit in php.ini (default 128M). Laravel apps typically use 30-60MB per request. Queue workers accumulate memory over time (why pm.max_requests matters).\n\nGenerators: for processing large datasets without loading everything into memory. yield returns one item at a time.",
    code: "// Reference counting & COW:\n$a = str_repeat('x', 1000000); // 1MB allocated\n$b = $a; // NO copy! Both point to same memory (COW)\n// Memory: still ~1MB\n\n$b .= 'y'; // NOW PHP copies (write happened)\n// Memory: ~2MB\n\nunset($a); // refcount for original drops to 0, freed\n// Memory: ~1MB again\n\n// Memory tracking:\n$before = memory_get_usage();\n$data = EmailTemplate::all(); // loads ALL templates\n$after = memory_get_usage();\n$used = ($after - $before) / 1024 / 1024; // in MB\n\n// Generator for memory-efficient processing:\nfunction getEmailBatches(int $batchSize = 100): Generator {\n    $offset = 0;\n    while (true) {\n        $batch = DB::table('email_logs')\n            ->offset($offset)\n            ->limit($batchSize)\n            ->get();\n        \n        if ($batch->isEmpty()) break;\n        \n        yield $batch; // return batch, free previous\n        $offset += $batchSize;\n    }\n}\n\n// Process millions of rows with constant memory:\nforeach (getEmailBatches(500) as $batch) {\n    foreach ($batch as $log) {\n        // Process each log\n    }\n    // Previous batch is garbage collected!\n}\n// Peak memory: ~500 rows worth, not millions\n\n// Laravel's lazy() and cursor() do this for you:\nEmailLog::cursor()->each(function ($log) {\n    // Processes one row at a time\n    // Constant memory regardless of table size\n});",
    diagram: "REFERENCE COUNTING:\n\n$a = 'hello';    refcount = 1\n$b = $a;         refcount = 2 (COW, same memory)\n$b .= '!';       copy made, $a refcount = 1, $b refcount = 1\nunset($a);       $a refcount = 0, memory FREED\n\nGENERATOR vs ARRAY:\n\n  Array: [Load ALL 1M rows into memory]\n         Memory: 500MB+\n         Speed: fast after loading\n\n  Generator: [Load 100 rows] -> process -> [free]\n             [Load next 100] -> process -> [free]\n             Memory: ~5MB constant\n             Speed: slightly slower per item\n\nMEMORY LIFECYCLE per FPM request:\n\n  [Request starts] -> memory_limit = 128M\n  [Bootstrap Laravel] -> ~15MB\n  [Execute controller] -> ~30-50MB\n  [Response sent] -> ALL memory freed\n  [Next request] -> starts fresh at 0\n\n  Queue workers DON'T reset!\n  Memory accumulates unless managed.",
    bhn: "Your SQS queue workers run for hours without resetting. Use pm.max_requests=500 to restart workers and free accumulated memory. For bulk email operations (processing 10,000+ templates), use cursor() or chunk() instead of all() to avoid memory exhaustion. Your ECS containers with limited memory benefit most from this understanding.",
    memoryTrick: "PHP memory is like a WHITEBOARD in a meeting room. Each meeting (request) uses the whiteboard. At the end, it's ERASED completely (shared-nothing). But queue workers are meetings that NEVER END, so the whiteboard fills up. Set a limit and erase periodically." },

  { id: "autoloading", section: "beyond", title: "Autoloading & Composer Internals", subtitle: "How PHP finds your classes", icon: "\uD83D\uDCE6", accent: "#a855f7", difficulty: "intermediate",
    surface: "When you use 'use App\\Services\\EmailSender', PHP doesn't automatically know where that file is. Autoloading (via Composer's PSR-4) maps namespaces to directories and loads files on demand.",
    deep: "Without autoloading, you'd need require/include for EVERY class file. Autoloading registers a function that PHP calls when it encounters an unknown class.\n\nComposer generates vendor/autoload.php which registers a PSR-4 autoloader:\nNamespace prefix -> directory mapping\nApp\\ -> app/\nApp\\Services\\EmailSender -> app/Services/EmailSender.php\n\nComposer autoloader types:\n1. PSR-4: namespace maps to directory (most common)\n2. PSR-0: older standard, similar but different directory structure\n3. Classmap: scans directories, builds class -> file map (fastest)\n4. Files: always-include files (helpers, polyfills)\n\ncomposer dump-autoload --optimize: generates a classmap for ALL classes. Turns every lookup into a hash table check instead of filesystem scan. Essential for production.\n\nLaravel's bootstrap loads vendor/autoload.php FIRST, before anything else. This is why autoloading is the foundation of everything.",
    code: "// composer.json PSR-4 mapping:\n{\n    \"autoload\": {\n        \"psr-4\": {\n            \"App\\\\\": \"app/\",\n            \"Database\\\\\": \"database/\"\n        },\n        \"files\": [\n            \"app/helpers.php\"\n        ]\n    }\n}\n\n// What happens when you write:\nuse App\\Services\\Email\\SqsEmailSender;\n\n// 1. PHP encounters SqsEmailSender class\n// 2. Doesn't know where it is\n// 3. Calls registered autoload function\n// 4. Composer autoloader checks:\n//    'App\\' maps to 'app/'\n//    So App\\Services\\Email\\SqsEmailSender\n//    -> app/Services/Email/SqsEmailSender.php\n// 5. require_once that file\n// 6. Class is now available\n\n// Optimize for production:\n// composer dump-autoload --optimize --classmap-authoritative\n// This:\n// 1. Scans ALL directories\n// 2. Builds complete class -> file map\n// 3. Stores in vendor/composer/autoload_classmap.php\n// 4. Hash table lookup instead of filesystem scan\n// 5. ~20-25% faster autoloading\n\n// See what Composer mapped:\n$classmap = require 'vendor/composer/autoload_classmap.php';\n// ['App\\Services\\EmailSender' => '/var/www/app/Services/EmailSender.php', ...]",
    diagram: "AUTOLOADING FLOW:\n\n[Your code: new SqsEmailSender()]\n    |\n    v\n[PHP: class not found!]\n    |\n    v\n[Call registered autoload functions]\n    |\n    v\n[Composer autoloader]\n    |\n    +-- Check classmap (optimized)\n    |     Hash table: class -> file path\n    |     O(1) lookup, fastest\n    |\n    +-- Check PSR-4 map\n    |     App\\ -> app/\n    |     Convert \\ to /\n    |     Check file exists\n    |\n    v\n[require_once 'app/Services/Email/SqsEmailSender.php']\n    |\n    v\n[Class available!]\n\nDEV vs PRODUCTION:\n  Dev:  PSR-4 lookup (flexible, checks filesystem)\n  Prod: Classmap (fast, no filesystem checks)\n        composer dump-autoload --optimize",
    bhn: "In your Dockerfile for schemes-api, run 'composer install --no-dev --optimize-autoloader' for production. The --optimize-autoloader flag generates the classmap. Combined with OPcache, your app finds and loads classes from memory instantly. Your 5 repositories (schemes-api, myschemes-extranet, etc.) each have their own composer.json with their own PSR-4 mappings.",
    memoryTrick: "Autoloading is a LIBRARY CATALOG. Without it, you'd wander through shelves (directories) looking for every book (class). With the classmap, you look up the catalog (hash table) and go directly to the shelf." },

  { id: "generators-fibers", section: "beyond", title: "Generators & Fibers", subtitle: "Concurrency primitives in PHP", icon: "\uD83E\uDDF5", accent: "#14b8a6", difficulty: "advanced",
    surface: "Generators (yield) let functions produce values one at a time without loading everything into memory. Fibers (PHP 8.1+) enable lightweight concurrency, pausing and resuming function execution.",
    deep: "Generators:\n- A function with yield is a Generator\n- It returns a Generator object (implements Iterator)\n- Execution pauses at each yield, resumes on next()\n- Memory efficient: only one value in memory at a time\n- Use for: large dataset processing, infinite sequences, lazy evaluation\n\nFibers (PHP 8.1+):\n- Lightweight cooperative multitasking\n- A fiber can suspend itself and be resumed later\n- Unlike threads: no parallelism, no race conditions\n- Used internally by Laravel for concurrent HTTP requests\n- Laravel Octane uses fibers for concurrent task execution\n\nFiber::suspend() pauses execution\nFiber::resume() continues from where it paused\n\nLaravel uses fibers in:\n- Concurrency::run() for parallel HTTP calls\n- Octane for handling multiple requests\n- Promise-like patterns for async operations",
    code: "// GENERATOR: memory-efficient iteration\nfunction emailBatchGenerator(): Generator {\n    $page = 1;\n    while (true) {\n        $batch = DB::table('emails')\n            ->forPage($page, 1000)\n            ->get();\n        \n        if ($batch->isEmpty()) return; // ends generator\n        \n        yield $batch; // pause here, return batch\n        $page++;      // resume here on next call\n    }\n}\n\nforeach (emailBatchGenerator() as $batch) {\n    // Only 1 batch in memory at a time!\n    processBatch($batch);\n}\n\n// yield can also RECEIVE values:\nfunction emailFilter(): Generator {\n    while (true) {\n        $email = yield; // receive from send()\n        if (str_contains($email, '@bhn.com')) {\n            echo \"Internal: $email\\n\";\n        }\n    }\n}\n$filter = emailFilter();\n$filter->current(); // initialize\n$filter->send('user@bhn.com');    // \"Internal: user@bhn.com\"\n$filter->send('user@gmail.com');  // (nothing)\n\n// FIBER: cooperative multitasking (PHP 8.1+)\n$fiber = new Fiber(function (): void {\n    $value = Fiber::suspend('paused');\n    echo \"Resumed with: $value\";\n});\n\n$result = $fiber->start();     // 'paused'\n$fiber->resume('hello');        // 'Resumed with: hello'\n\n// Laravel Concurrency (uses Fibers):\nuse Illuminate\\Support\\Facades\\Concurrency;\n\n[$users, $templates, $config] = Concurrency::run([\n    fn() => User::all(),\n    fn() => EmailTemplate::active()->get(),\n    fn() => Config::get('email'),\n]);\n// All three run concurrently, not sequentially!",
    diagram: "GENERATOR FLOW:\n\n[emailBatchGenerator()]\n    |\n    v\n[yield $batch1] -- pauses --> caller gets $batch1\n    |                          caller processes it\n    v                          caller calls next()\n[yield $batch2] -- pauses --> caller gets $batch2\n    |                          ...\n    v\n[return] -- generator ends\n\nOnly 1 batch in memory at any time!\n\nFIBER FLOW:\n\n[Main code]              [Fiber]\n    |                       |\n    start() ---------> executes...\n    |                  Fiber::suspend('data')\n    gets 'data' <------    |\n    |                      | (paused)\n    resume('input') -->    |\n    |                  gets 'input'\n    |                  continues...\n    |                  returns\n    continues <--------    |\n\nLike PING PONG between main code and fiber.",
    bhn: "Use generators for processing your email_logs table (could be millions of rows). EmailLog::cursor() uses generators internally. For your email centralization, Concurrency::run() can parallelize: check BNS health + load template + resolve variables simultaneously instead of sequentially. This can reduce your email dispatch latency by 40%+.",
    memoryTrick: "Generators are LAZY WORKERS. They only work when you ask, and they only hold ONE item at a time. Fibers are MULTITASKERS who can PAUSE one task, do another, and RESUME where they left off." },

  { id: "sessions-cookies", section: "beyond", title: "Sessions, Cookies & State Management", subtitle: "How stateless HTTP becomes stateful", icon: "\uD83C\uDF6A", accent: "#f59e0b", difficulty: "intermediate",
    surface: "HTTP is stateless. Every request is independent. Sessions and cookies add state: cookies store small data on the client, sessions store data on the server (identified by a session cookie).",
    deep: "Cookie flow:\n1. Server sends Set-Cookie header in response\n2. Browser stores the cookie\n3. Browser sends cookie back with every subsequent request\n4. Server reads the cookie to identify the user\n\nSession flow:\n1. Server creates a session with a unique ID\n2. Session data stored server-side (file, database, Redis)\n3. Session ID sent to client as a cookie\n4. Client sends session ID cookie with every request\n5. Server loads session data from storage using the ID\n\nLaravel session drivers:\n- file: stored in storage/framework/sessions (default)\n- database: sessions table\n- redis: ElastiCache/Redis (recommended for production)\n- cookie: encrypted data in the cookie itself\n- array: in-memory (testing only)\n\nYour Redis/ElastiCache migration with TLS: sessions in Redis = shared across multiple ECS containers. File-based sessions = stuck to one container (not scalable).",
    code: "// How sessions work in Laravel:\n\n// Setting session data:\nsession(['user_preferences' => ['theme' => 'dark']]);\n// OR\n$request->session()->put('email_draft', $draftData);\n\n// Getting session data:\n$prefs = session('user_preferences');\n$draft = $request->session()->get('email_draft');\n\n// Flash data (available for ONE request only):\nsession()->flash('success', 'Email sent!');\n// Available in next request, then gone\n\n// Under the hood, Laravel:\n// 1. Reads session ID from 'laravel_session' cookie\n// 2. Loads session data from driver (Redis/file/DB)\n// 3. Makes data available via session() helper\n// 4. At end of request, saves modified data back\n// 5. Sends updated Set-Cookie header if needed\n\n// Redis session config (config/session.php):\n'driver' => 'redis',\n'connection' => 'session',\n'lifetime' => 120,     // minutes\n'expire_on_close' => false,\n'encrypt' => true,     // encrypt session data\n'cookie' => 'bhn_session',\n'secure' => true,      // HTTPS only\n'http_only' => true,   // No JavaScript access\n'same_site' => 'lax',  // CSRF protection\n\n// Redis key structure:\n// laravel_session:abc123def456 -> serialized session data\n// TTL: 7200 seconds (120 minutes)",
    diagram: "SESSION FLOW:\n\n[Browser]                      [Server]\n    |                              |\n    | POST /login                  |\n    |---------------------------->>|\n    |                              | Authenticate user\n    |                              | Create session:\n    |                              |   ID: abc123\n    |                              |   Data: {user_id: 42}\n    |                              |   Store in Redis\n    |                              |\n    |    Set-Cookie: bhn_session=abc123\n    |<<----------------------------|\n    |                              |\n    | GET /dashboard               |\n    | Cookie: bhn_session=abc123   |\n    |---------------------------->>|\n    |                              | Read cookie: abc123\n    |                              | Load from Redis\n    |                              | {user_id: 42}\n    |                              | User is authenticated!\n    |    <HTML dashboard>           |\n    |<<----------------------------|\n\nFILE vs REDIS SESSIONS:\n  File:  Stored on ONE server's disk\n         Can't share across ECS containers\n  Redis: Stored in ElastiCache\n         Shared across ALL containers\n         Required for horizontal scaling",
    bhn: "Your Redis/ElastiCache migration with TLS directly enables shared sessions across ECS containers. Without Redis sessions, a user could be authenticated on Container A but get routed to Container B (where no session exists) and be logged out. This is why your session migration was critical for scaling myschemes-extranet.",
    memoryTrick: "Sessions are COAT CHECK tickets. You give your coat (data) to the server, get a ticket (cookie). Next visit, show the ticket, get your coat back. Redis coat check = any attendant (server) can find your coat." },

  { id: "security-deep", section: "beyond", title: "Security: Beyond the Basics", subtitle: "How attacks work and how PHP defends", icon: "\uD83D\uDD12", accent: "#dc2626", difficulty: "advanced",
    surface: "SQL injection, XSS, CSRF, and authentication vulnerabilities are the common threats. Laravel protects against most automatically, but understanding HOW the protection works makes you a better engineer.",
    deep: "SQL Injection:\n- Attacker sends: ' OR 1=1 --\n- Laravel's query builder uses PDO prepared statements\n- Values are BOUND, never concatenated into SQL\n- Raw queries (DB::raw) bypass this protection!\n\nXSS (Cross-Site Scripting):\n- Attacker injects JavaScript into your page\n- Blade's {{ }} auto-escapes output (htmlspecialchars)\n- {!! !!} does NOT escape (only use for trusted HTML)\n\nCSRF (Cross-Site Request Forgery):\n- Attacker tricks user's browser into making requests\n- Laravel generates a token per session\n- Every form includes @csrf, verified by middleware\n- API routes don't use CSRF (use auth tokens instead)\n\nMass Assignment:\n- Attacker sends extra fields: {is_admin: true}\n- $fillable whitelist or $guarded blacklist prevents this\n\nEncryption:\n- Laravel uses AES-256-CBC via APP_KEY\n- encrypt()/decrypt() for sensitive data\n- Cookies are encrypted AND signed (tamper-proof)\n\nPassword hashing:\n- bcrypt by default (configurable to argon2)\n- Hash::make() is one-way (can't reverse)\n- Hash::check() compares without timing attacks",
    code: "// SQL INJECTION PROTECTION:\n\n// SAFE (parameterized):\n$user = DB::table('users')\n    ->where('email', $request->email) // bound parameter\n    ->first();\n// SQL: SELECT * FROM users WHERE email = ?\n// Binding: ['evil@hack.com']\n// The ? is NEVER replaced in the SQL string\n\n// DANGEROUS (raw, unparameterized):\n$user = DB::select(\n    \"SELECT * FROM users WHERE email = '$input'\"\n);\n// If $input = \"' OR 1=1 --\"\n// SQL becomes: SELECT * FROM users WHERE email = '' OR 1=1 --'\n// Returns ALL users!\n\n// XSS PROTECTION:\n// Blade auto-escapes:\n{{ $user->name }}\n// If name = '<script>alert(1)</script>'\n// Output: &lt;script&gt;alert(1)&lt;/script&gt;\n// Script does NOT execute\n\n// MASS ASSIGNMENT:\nclass EmailTemplate extends Model {\n    protected $fillable = ['subject', 'body', 'type'];\n    // Only these fields can be mass-assigned\n    // $template->fill($request->all()) ignores 'is_active'\n}\n\n// ENCRYPTION:\n$encrypted = encrypt($apiKey);     // AES-256-CBC\n$decrypted = decrypt($encrypted);  // back to original\n// Stored encrypted in DB, decrypted on read\n\n// Your AWS Secrets Manager pattern is even better:\n// Secrets never touch the database at all",
    diagram: "SQL INJECTION EXPLAINED:\n\n  VULNERABLE CODE:\n  \"WHERE email = '$input'\"\n  \n  Normal input: user@example.com\n  SQL: WHERE email = 'user@example.com'  (OK)\n  \n  Attack input: ' OR 1=1 --\n  SQL: WHERE email = '' OR 1=1 --'  (ALL ROWS!)\n\n  PROTECTED CODE (PDO Prepared Statements):\n  \"WHERE email = ?\"\n  Binding: [user input]\n  \n  The ? is a PLACEHOLDER\n  Input is NEVER inserted into the SQL string\n  Even malicious input is treated as DATA, not CODE\n\nLARAVEL'S SECURITY LAYERS:\n\n  Layer 1: CSRF tokens (form protection)\n  Layer 2: Prepared statements (SQL injection)\n  Layer 3: Blade escaping (XSS)\n  Layer 4: Mass assignment protection\n  Layer 5: Encrypted cookies (tampering)\n  Layer 6: Password hashing (credential theft)\n  Layer 7: Rate limiting (brute force)",
    bhn: "Your schemes-api handles sensitive scheme data. Ensure: all user input goes through validation (FormRequest), all Eloquent queries use parameterized bindings (never DB::raw with user input), and API authentication uses proper token validation. Your AWS Secrets Manager pattern for storing API keys is superior to .env files because secrets never touch the codebase.",
    memoryTrick: "Security is like a CASTLE with 7 WALLS. Each wall stops a different attack. Remove one wall, and that specific attack gets through. Laravel builds 6 walls automatically. The 7th (your code quality) is on you." },

  { id: "serialization", section: "beyond", title: "Serialization & Unserialization", subtitle: "How PHP stores and recreates objects", icon: "\uD83D\uDCBE", accent: "#6366f1", difficulty: "advanced",
    surface: "Serialization converts PHP objects/arrays to a string for storage (database, cache, queue). Unserialization recreates the object from the string. Laravel uses this heavily for queue jobs and cache.",
    deep: "serialize() / unserialize(): PHP's native serialization.\njson_encode() / json_decode(): JSON format (more portable).\n\nQueue jobs are serialized when dispatched and unserialized when processed. This is why:\n- Job properties must be serializable\n- Closures can't be serialized (use SerializableClosure)\n- Eloquent models use SerializesModels trait (stores ID, re-fetches on unserialize)\n\nSecurity risk: unserialize() with untrusted data can execute arbitrary code via __wakeup() and __destruct() magic methods. NEVER unserialize user input.\n\nLaravel's solution: signed serialization for cookies and encrypted serialization for sensitive data.\n\nCache serialization: when you Cache::put() an Eloquent model, it's serialized. On Cache::get(), it's unserialized. Large models with loaded relationships = large cache entries.",
    code: "// Basic serialization:\n$template = EmailTemplate::with('variables')->find(1);\n$serialized = serialize($template);\n// string: O:8:\"App\\Models\\EmailTemplate\":20:{s:10:\"...}\n\n$restored = unserialize($serialized);\n// Full model object recreated!\n\n// Queue job serialization:\nclass SendEmail implements ShouldQueue {\n    use SerializesModels; // KEY trait!\n    \n    public function __construct(\n        public EmailTemplate $template // Eloquent model\n    ) {}\n}\n\n// When dispatched:\n// SerializesModels stores: template_id = 42\n// NOT the entire model object\n\n// When worker picks it up:\n// SerializesModels re-queries: EmailTemplate::find(42)\n// Fresh data from database!\n\n// WHY this matters:\n// If template was updated between dispatch and process,\n// the worker gets the UPDATED version.\n\n// DANGER: never unserialize user input!\n$data = unserialize($_GET['data']); // CRITICAL VULNERABILITY\n// Attacker can craft malicious serialized strings\n// that execute code via __wakeup() or __destruct()\n\n// SAFE: use json_decode for user data\n$data = json_decode($request->input('data'), true);",
    diagram: "QUEUE JOB SERIALIZATION:\n\n[Dispatch time]\n    SendEmail job created\n    template = EmailTemplate (loaded from DB)\n    |\n    v\n[SerializesModels kicks in]\n    Instead of serializing the ENTIRE model,\n    stores only: {class: 'EmailTemplate', id: 42}\n    |\n    v\n[Push serialized job to SQS]\n    Compact payload (just the ID)\n    |\n    v\n[Worker picks up job]\n    |\n    v\n[Unserialize]\n    SerializesModels re-queries:\n    EmailTemplate::findOrFail(42)\n    |\n    v\n[handle() runs with FRESH model data]\n\nWHY NOT serialize the whole model?\n  1. Model could be large (relationships, casts)\n  2. Data could be stale by processing time\n  3. Queue payload should be small\n  4. Fresh query = current data",
    bhn: "Your SQS email pipeline serializes jobs when dispatching. SerializesModels ensures your email templates are fresh when processed (critical if someone updates a template between dispatch and processing). Keep queue payloads small: store IDs, not full objects. This also reduces SQS message size costs.",
    memoryTrick: "Serialization is FREEZE-DRYING food. You remove the water (memory structure) for storage/transport. Unserialization adds water back (recreates the object). SerializesModels is smart freeze-drying: it stores the RECIPE (ID), not the MEAL (full model)." },

  { id: "unix-processes", section: "beyond", title: "Unix Process Model & Signals", subtitle: "How your PHP processes live and die", icon: "\uD83D\uDDA5\uFE0F", accent: "#78716c", difficulty: "advanced",
    surface: "Every PHP-FPM worker and queue worker is a Unix process. Understanding process management, signals, and how Linux handles your PHP code helps you debug container issues, worker crashes, and deployment problems.",
    deep: "Process hierarchy:\n- init (PID 1) -> PHP-FPM master -> worker processes\n- In Docker: your ENTRYPOINT becomes PID 1\n- SIGTERM: graceful shutdown (finish current request, then exit)\n- SIGKILL: immediate kill (no cleanup)\n- SIGHUP: reload configuration\n- SIGUSR2: graceful restart (FPM reloads workers)\n\nQueue workers and signals:\n- php artisan queue:work listens for SIGTERM\n- On SIGTERM: finishes current job, then exits\n- On SIGKILL: job is interrupted (may be lost or retried)\n- ECS sends SIGTERM first, then SIGKILL after stopTimeout\n\nThis is why your ECS Deployment Circuit Breaker fails:\n1. ECS sends SIGTERM to old container\n2. Queue worker is mid-job\n3. If job takes longer than stopTimeout, ECS sends SIGKILL\n4. Job is interrupted, health check fails, circuit breaks\n\nSolution: set stopTimeout > max job duration, handle SIGTERM gracefully in long-running jobs.",
    code: "// PHP signal handling (for custom daemons):\npcntl_async_signals(true);\n\npcntl_signal(SIGTERM, function () {\n    echo \"Received SIGTERM, shutting down gracefully...\\n\";\n    // Finish current work\n    // Close connections\n    // Flush logs\n    exit(0);\n});\n\npcntl_signal(SIGUSR1, function () {\n    echo \"Received SIGUSR1, reloading config...\\n\";\n    // Re-read config without restart\n});\n\n// Laravel queue worker handles signals automatically:\n// queue:work --timeout=60 --tries=3\n// On SIGTERM: finish current job, then exit\n// On timeout: kill the job, mark as failed\n\n// Docker / ECS considerations:\n// Dockerfile:\nCMD [\"php-fpm\"] // PID 1, receives signals directly\n\n// docker-compose.yml:\nstop_grace_period: 30s // SIGTERM, wait 30s, then SIGKILL\n\n// ECS task definition:\n\"stopTimeout\": 30  // seconds before SIGKILL\n\n// Check processes:\n// ps aux | grep php\n// Shows: master process + worker processes\n// Each worker = one concurrent request capacity\n\n// Check what signal killed a process:\n// dmesg | grep -i oom\n// If you see 'Out of memory: Kill process'\n// -> your container needs more memory or fewer workers",
    diagram: "UNIX PROCESS MODEL:\n\n[Linux Kernel]\n    |\n    v\n[PID 1: init / Docker entrypoint]\n    |\n    v\n[PHP-FPM Master Process]\n    |  Manages worker pool\n    |  Handles signals\n    |  Monitors worker health\n    |\n    +-- [Worker 1] (handling request)\n    +-- [Worker 2] (idle, waiting)\n    +-- [Worker 3] (handling request)\n    +-- [Worker N] ...\n\nSIGNAL FLOW (ECS Deployment):\n\n[ECS: deploy new task]\n    |\n    v\n[Send SIGTERM to old container]\n    |\n    v\n[PHP-FPM master receives SIGTERM]\n    |  Tells workers: finish current request\n    |  Stop accepting new requests\n    |\n    v\n[Workers finish + exit]\n    |\n    v\n[Container exits cleanly]\n\nIF workers don't exit in time:\n[ECS sends SIGKILL after stopTimeout]\n    |\n    v\n[Processes killed immediately]\n    |  No cleanup, no graceful shutdown\n    |  Queue jobs may be lost/retried\n    v\n[Health check fails -> Circuit Breaker!]",
    bhn: "THIS explains your recurring ECS Deployment Circuit Breaker failures across myschemes-extranet, cs-public, and cyclescheme stacks. If your queue workers or FPM workers take longer than ECS stopTimeout to finish, ECS kills them, health checks fail, and the circuit breaker triggers. Solution: set stopTimeout to at least 2x your longest expected request/job duration. For queue workers processing email batches, 120 seconds might be needed.",
    memoryTrick: "Unix signals are PHONE CALLS to your process. SIGTERM = 'Please finish up and leave.' SIGKILL = 'Security is dragging you out NOW.' Always answer the phone (handle SIGTERM gracefully) before security arrives." },
];

const diffColor = (d, dark) => {
  if (d === "beginner") return dark ? "#4ade80" : "#16a34a";
  if (d === "intermediate") return dark ? "#fbbf24" : "#b45309";
  return dark ? "#f87171" : "#dc2626";
};

export default function App() {
  const [dark, setDark] = useState(true);
  const [selSection, setSelSection] = useState(null);
  const [selConcept, setSelConcept] = useState(null);
  const [done, setDone] = useState(() => { try { return JSON.parse(localStorage.getItem("masterclass_laravel-beyond_done")) || {}; } catch { return {}; } });
  const [search, setSearch] = useState("");
  const ref = useRef(null);
  useEffect(() => { localStorage.setItem("masterclass_laravel-beyond_done", JSON.stringify(done)); }, [done]);
  const toggle = (id) => setDone(p => ({ ...p, [id]: !p[id] }));
  const ct = Object.values(done).filter(Boolean).length;
  const pct = Math.round((ct / CONCEPTS.length) * 100);

  useEffect(() => { ref.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [selConcept]);

  const m = dark ? "dark" : "light";
  const t = {
    bg: dark ? "#0a0c10" : "#f7f8fa",
    surface: dark ? "rgba(14,17,24,0.92)" : "rgba(255,255,255,0.92)",
    surfHov: dark ? "rgba(18,22,32,0.97)" : "rgba(246,248,252,0.97)",
    bdr: dark ? "rgba(34,197,94,0.08)" : "rgba(0,80,40,0.07)",
    txt: dark ? "#d4d8e0" : "#1a1f2e",
    sub: dark ? "#7a8494" : "#5a6474",
    mut: dark ? "#454d5c" : "#9aa4b4",
    card: dark ? "rgba(12,15,22,0.8)" : "rgba(255,255,255,0.8)",
    ring: dark ? "#1a1f2a" : "#e4e8ee",
    tag: dark ? "rgba(0,0,0,0.4)" : "rgba(0,40,20,0.03)",
    codeBg: dark ? "rgba(0,0,0,0.4)" : "rgba(0,0,0,0.03)",
    togBg: dark ? "rgba(34,197,94,0.06)" : "rgba(0,80,40,0.05)",
    hero: dark
      ? "radial-gradient(ellipse at 20% 0%, rgba(34,197,94,0.08), transparent 45%), radial-gradient(ellipse at 80% 0%, rgba(239,68,68,0.06), transparent 45%)"
      : "radial-gradient(ellipse at 20% 0%, rgba(22,163,74,0.03), transparent 45%), radial-gradient(ellipse at 80% 0%, rgba(220,38,38,0.02), transparent 45%)",
  };
  const hGrad = dark
    ? "linear-gradient(135deg, #22c55e 0%, #ef4444 50%, #f59e0b 100%)"
    : "linear-gradient(135deg, #16a34a 0%, #dc2626 50%, #d97706 100%)";

  const filtered = CONCEPTS.filter(c => {
    const s = search.toLowerCase();
    if (selSection && c.section !== selSection) return false;
    if (!s) return true;
    return c.title.toLowerCase().includes(s) || c.subtitle.toLowerCase().includes(s);
  });

  const Tog = () => (
    <button onClick={() => setDark(!dark)} style={{ position: "fixed", top: 14, right: 14, zIndex: 999, background: t.togBg, backdropFilter: "blur(14px)", border: `1px solid ${t.bdr}`, borderRadius: 40, padding: "7px 14px", cursor: "pointer", display: "flex", alignItems: "center", gap: 7, color: t.sub, fontSize: 12, fontFamily: "'IBM Plex Mono', monospace", transition: "all 0.35s" }}>
      <span style={{ fontSize: 14 }}>{dark ? "\u2600\uFE0F" : "\uD83C\uDF19"}</span>{dark ? "Light" : "Dark"}
    </button>
  );

  const concept = selConcept ? CONCEPTS.find(c => c.id === selConcept) : null;

  return (
    <div style={{ fontFamily: "'IBM Plex Sans', sans-serif", background: t.bg, minHeight: "100vh", color: t.txt, transition: "background 0.45s, color 0.45s" }}>
      <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600;700&family=IBM+Plex+Mono:wght@300;400;500;600&display=swap" rel="stylesheet" />
      <style>{`@keyframes fu{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}.cc:hover{transform:translateY(-1px);border-color:${dark?"rgba(255,255,255,0.1)":"rgba(0,0,0,0.12)"}}.cc{transition:all 0.25s}pre{margin:0;white-space:pre-wrap;word-break:break-word;font-size:12.5px;line-height:1.7;font-family:'IBM Plex Mono',monospace}*::-webkit-scrollbar{width:4px}*::-webkit-scrollbar-thumb{background:${dark?"#333":"#ccc"};border-radius:4px}`}</style>
      <Tog />

      {/* Header */}
      <div style={{ position: "relative", padding: "48px 24px 20px", textAlign: "center", overflow: "hidden" }}>
        <div style={{ position: "absolute", inset: 0, background: t.hero, pointerEvents: "none" }} />
        <div style={{ position: "relative", zIndex: 1 }}>
          <div style={{ fontSize: 10, letterSpacing: 8, textTransform: "uppercase", fontFamily: "'IBM Plex Mono', monospace", color: t.mut, marginBottom: 12 }}>Deep Dive Masterclass</div>
          <h1 style={{ fontSize: "clamp(26px,5vw,42px)", fontWeight: 700, lineHeight: 1.1, margin: "0 0 4px", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>Laravel & Beyond</h1>
          <p style={{ fontSize: 12, color: t.sub, fontFamily: "'IBM Plex Mono', monospace", margin: "8px 0 6px", letterSpacing: 2 }}>framework mastery + the engine underneath</p>
          <p style={{ fontSize: 11, color: t.mut, fontFamily: "'IBM Plex Mono', monospace", margin: "0 0 22px" }}>{CONCEPTS.length} concepts | PHP code | diagrams | BHN examples</p>
          <div style={{ display: "inline-flex", alignItems: "center", gap: 14, background: t.surface, border: `1px solid ${t.bdr}`, borderRadius: 14, padding: "12px 22px", backdropFilter: "blur(14px)" }}>
            <div style={{ position: "relative", width: 48, height: 48 }}>
              <svg width="48" height="48" viewBox="0 0 48 48">
                <circle cx="24" cy="24" r="21" fill="none" stroke={t.ring} strokeWidth="2.5" />
                <defs><linearGradient id="pg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#22c55e"/><stop offset="50%" stopColor="#ef4444"/><stop offset="100%" stopColor="#f59e0b"/></linearGradient></defs>
                <circle cx="24" cy="24" r="21" fill="none" stroke="url(#pg)" strokeWidth="2.5" strokeDasharray={`${(pct/100)*131.9} 131.9`} strokeLinecap="round" transform="rotate(-90 24 24)" style={{ transition: "stroke-dasharray 0.7s ease" }} />
              </svg>
              <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 600, fontFamily: "'IBM Plex Mono', monospace", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>{pct}%</div>
            </div>
            <div style={{ textAlign: "left" }}>
              <div style={{ fontSize: 22, fontWeight: 700 }}>{ct}<span style={{ fontSize: 13, color: t.mut, fontWeight: 400 }}> / {CONCEPTS.length}</span></div>
              <div style={{ fontSize: 9.5, color: t.mut, fontFamily: "'IBM Plex Mono', monospace", letterSpacing: 1 }}>concepts mastered</div>
            </div>
          </div>
        </div>
      </div>

      {/* Section tabs + Search */}
      <div style={{ padding: "12px 20px 6px", maxWidth: 760, margin: "0 auto" }}>
        <div style={{ display: "flex", gap: 8, marginBottom: 10, flexWrap: "wrap" }}>
          <button onClick={() => setSelSection(null)} style={{ background: !selSection ? `${dark?"#22c55e":"#16a34a"}18` : "transparent", border: `1px solid ${!selSection ? (dark?"#22c55e55":"#16a34a44") : t.bdr}`, color: !selSection ? (dark?"#22c55e":"#16a34a") : t.mut, padding: "5px 14px", borderRadius: 8, cursor: "pointer", fontSize: 11.5, fontFamily: "'IBM Plex Mono', monospace", transition: "all 0.2s" }}>All ({CONCEPTS.length})</button>
          {SECTIONS.map(s => {
            const count = CONCEPTS.filter(c => c.section === s.id).length;
            return <button key={s.id} onClick={() => setSelSection(s.id)} style={{ background: selSection === s.id ? `${dark?"#22c55e":"#16a34a"}18` : "transparent", border: `1px solid ${selSection === s.id ? (dark?"#22c55e55":"#16a34a44") : t.bdr}`, color: selSection === s.id ? (dark?"#22c55e":"#16a34a") : t.mut, padding: "5px 14px", borderRadius: 8, cursor: "pointer", fontSize: 11.5, fontFamily: "'IBM Plex Mono', monospace", transition: "all 0.2s" }}>{s.icon} {s.title} ({count})</button>;
          })}
        </div>
        <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search concepts..." style={{ width: "100%", padding: "9px 14px", background: t.card, border: `1px solid ${t.bdr}`, borderRadius: 10, color: t.txt, fontSize: 13, fontFamily: "'IBM Plex Mono', monospace", outline: "none", boxSizing: "border-box" }} />
      </div>

      {/* Concept List */}
      <div style={{ padding: "8px 20px 48px", maxWidth: 760, margin: "0 auto" }}>
        {filtered.map((c, i) => {
          const open = selConcept === c.id;
          const dc = diffColor(c.difficulty, dark);
          return (
            <div key={c.id} ref={open ? ref : null} style={{ marginBottom: 8, animation: `fu 0.35s ease ${i*0.025}s both` }}>
              <div className="cc" onClick={() => setSelConcept(open ? null : c.id)} style={{ background: open ? t.surfHov : t.card, border: `1px solid ${open ? `${c.accent}35` : t.bdr}`, borderRadius: open ? "12px 12px 0 0" : 12, padding: "13px 16px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", backdropFilter: "blur(8px)" }}>
                <div style={{ display: "flex", gap: 12, alignItems: "center", flex: 1, minWidth: 0 }}>
                  <div onClick={e => { e.stopPropagation(); toggle(c.id); }} style={{ width: 22, height: 22, borderRadius: "50%", border: done[c.id] ? `2px solid ${c.accent}` : `2px solid ${t.bdr}`, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", background: done[c.id] ? `${c.accent}15` : "transparent", transition: "all 0.2s", flexShrink: 0 }}>
                    {done[c.id] && <span style={{ color: c.accent, fontSize: 10, fontWeight: 700 }}>{"\u2713"}</span>}
                  </div>
                  <div style={{ minWidth: 0 }}>
                    <div style={{ display: "flex", gap: 6, alignItems: "center", flexWrap: "wrap", marginBottom: 2 }}>
                      <span style={{ fontSize: 9, color: dc, padding: "1px 6px", background: `${dc}15`, borderRadius: 4, fontFamily: "'IBM Plex Mono', monospace", letterSpacing: 1, textTransform: "uppercase", border: `1px solid ${dc}25` }}>{c.difficulty}</span>
                      <span style={{ fontSize: 9, color: c.accent, padding: "1px 6px", background: `${c.accent}12`, borderRadius: 4, fontFamily: "'IBM Plex Mono', monospace", letterSpacing: 1 }}>{c.section === "laravel" ? "Laravel" : "Beyond"}</span>
                    </div>
                    <div style={{ fontSize: 14, fontWeight: 600, color: done[c.id] ? t.mut : t.txt, textDecoration: done[c.id] ? "line-through" : "none" }}>{c.icon} {c.title}</div>
                    <div style={{ fontSize: 11.5, color: t.sub, marginTop: 1 }}>{c.subtitle}</div>
                  </div>
                </div>
                <span style={{ color: t.mut, fontSize: 12, transform: open ? "rotate(180deg)" : "rotate(0)", transition: "transform 0.25s", flexShrink: 0, marginLeft: 8 }}>{"\u25BE"}</span>
              </div>

              {open && (
                <div style={{ background: t.surfHov, border: `1px solid ${c.accent}35`, borderTop: "none", borderRadius: "0 0 12px 12px", padding: "18px 18px 20px", overflow: "hidden", backdropFilter: "blur(8px)" }}>
                  {/* Surface */}
                  <div style={{ marginBottom: 16 }}>
                    <div style={{ fontSize: 10, color: c.accent, letterSpacing: 2, textTransform: "uppercase", fontFamily: "'IBM Plex Mono', monospace", marginBottom: 6 }}>SURFACE LEVEL</div>
                    <p style={{ color: t.txt, fontSize: 13.5, lineHeight: 1.75, margin: 0, fontWeight: 300 }}>{c.surface}</p>
                  </div>

                  {/* Deep */}
                  <div style={{ marginBottom: 16 }}>
                    <div style={{ fontSize: 10, color: dark ? "#f87171" : "#dc2626", letterSpacing: 2, textTransform: "uppercase", fontFamily: "'IBM Plex Mono', monospace", marginBottom: 6 }}>DEEP DIVE</div>
                    <pre style={{ color: t.txt, background: t.codeBg, padding: 14, borderRadius: 10, border: `1px solid ${t.bdr}`, fontWeight: 300, lineHeight: 1.8, fontSize: 12.5 }}>{c.deep}</pre>
                  </div>

                  {/* Code */}
                  <div style={{ marginBottom: 16 }}>
                    <div style={{ fontSize: 10, color: dark ? "#22c55e" : "#16a34a", letterSpacing: 2, textTransform: "uppercase", fontFamily: "'IBM Plex Mono', monospace", marginBottom: 6 }}>PHP CODE</div>
                    <pre style={{ color: dark ? "#a5f3ab" : "#14532d", background: dark ? "rgba(0,20,0,0.5)" : "rgba(0,60,0,0.03)", padding: 14, borderRadius: 10, border: `1px solid ${dark ? "rgba(34,197,94,0.15)" : "rgba(22,163,74,0.1)"}`, fontSize: 12, lineHeight: 1.7 }}>{c.code}</pre>
                  </div>

                  {/* Diagram */}
                  <div style={{ marginBottom: 16 }}>
                    <div style={{ fontSize: 10, color: dark ? "#38bdf8" : "#0369a1", letterSpacing: 2, textTransform: "uppercase", fontFamily: "'IBM Plex Mono', monospace", marginBottom: 6 }}>CONCEPTUAL DIAGRAM</div>
                    <pre style={{ color: dark ? "#7dd3fc" : "#0c4a6e", background: dark ? "rgba(0,10,30,0.5)" : "rgba(0,40,100,0.03)", padding: 14, borderRadius: 10, border: `1px solid ${dark ? "rgba(56,189,248,0.15)" : "rgba(3,105,161,0.1)"}`, fontSize: 11.5, lineHeight: 1.65 }}>{c.diagram}</pre>
                  </div>

                  {/* BHN */}
                  <div style={{ background: dark ? "rgba(251,146,60,0.05)" : "rgba(234,88,12,0.03)", border: `1px solid ${dark ? "rgba(251,146,60,0.12)" : "rgba(234,88,12,0.08)"}`, borderRadius: 10, padding: "12px 16px", marginBottom: 12 }}>
                    <div style={{ fontSize: 10, color: dark ? "#fb923c" : "#c2410c", letterSpacing: 2, textTransform: "uppercase", fontFamily: "'IBM Plex Mono', monospace", marginBottom: 6 }}>AT BHN (YOUR REAL WORLD)</div>
                    <p style={{ color: t.txt, fontSize: 12.5, lineHeight: 1.65, margin: 0, fontWeight: 300 }}>{c.bhn}</p>
                  </div>

                  {/* Memory Trick */}
                  <div style={{ background: dark ? "rgba(253,224,71,0.04)" : "rgba(202,138,4,0.03)", border: `1px solid ${dark ? "rgba(253,224,71,0.12)" : "rgba(202,138,4,0.08)"}`, borderRadius: 10, padding: "12px 16px" }}>
                    <div style={{ fontSize: 10, color: dark ? "#fde047" : "#a16207", letterSpacing: 2, textTransform: "uppercase", fontFamily: "'IBM Plex Mono', monospace", marginBottom: 6 }}>MEMORY TRICK</div>
                    <p style={{ color: dark ? "#fef08a" : "#854d0e", fontSize: 13, lineHeight: 1.6, margin: 0, fontWeight: 500 }}>{c.memoryTrick}</p>
                  </div>
                </div>
              )}
            </div>
          );
        })}
        {filtered.length === 0 && <p style={{ textAlign: "center", color: t.mut, padding: 40, fontFamily: "'IBM Plex Mono', monospace" }}>No concepts match your search.</p>}
      </div>
    </div>
  );
}
