import { useState, useEffect, useRef } from "react";

const PHASES = [
  { id: 1, title: "CRAFT", subtitle: "Code that speaks for itself", days: "Day 1-21", icon: "⚒️", description: "Master the fundamentals so deeply that excellence becomes automatic. Clean code, solid testing, efficient debugging, and technical depth that earns respect.", mnemonic: "S.O.L.I.D. - Standards, Ownership, Legibility, Intent-driven, Defensive coding", gradient: { dark: "linear-gradient(160deg, #081418 0%, #0e2830 50%, #061215 100%)", light: "linear-gradient(160deg, #edf8fa 0%, #ddf2f5 50%, #f0fafb 100%)" }, accent: { dark: "#2dd4bf", light: "#0d9488" }, glow: "rgba(45, 212, 191, 0.2)" },
  { id: 2, title: "OWN", subtitle: "From ticket-taker to outcome-driver", days: "Day 22-42", icon: "🎯", description: "Stop completing tasks. Start driving outcomes. Own the WHY behind your work, the quality of your delivery, and the impact of your decisions.", mnemonic: "D.R.I.V.E. - Deliver reliably, Raise quality, Investigate root causes, Verify impact, Extend beyond the ticket", gradient: { dark: "linear-gradient(160deg, #180a10 0%, #301520 50%, #1c0c14 100%)", light: "linear-gradient(160deg, #fdf0f4 0%, #f8e0ea 50%, #fef2f6 100%)" }, accent: { dark: "#fb7185", light: "#e11d48" }, glow: "rgba(251, 113, 133, 0.2)" },
  { id: 3, title: "DESIGN", subtitle: "Think in systems, not just syntax", days: "Day 43-63", icon: "📐", description: "Architect solutions, not just implement them. Understand trade-offs, scalability patterns, database design, and how your code fits the bigger picture.", mnemonic: "B.U.I.L.D. - Business context, Understand scale, Interface design, Long-term thinking, Data modeling", gradient: { dark: "linear-gradient(160deg, #0d0e1c 0%, #161840 50%, #0a0c1a 100%)", light: "linear-gradient(160deg, #eff0fd 0%, #e2e4fa 50%, #f2f2ff 100%)" }, accent: { dark: "#818cf8", light: "#4f46e5" }, glow: "rgba(129, 140, 248, 0.2)" },
  { id: 4, title: "SHIP", subtitle: "Reliable delivery is your reputation", days: "Day 64-77", icon: "🚀", description: "CI/CD mastery, deployment strategies, monitoring, incident response, and the operational excellence that makes you the engineer everyone trusts in production.", mnemonic: "L.A.U.N.C.H. - Logs, Alerts, Uptime, No surprises, Canary deploys, Health checks", gradient: { dark: "linear-gradient(160deg, #0d1808 0%, #1a3010 50%, #0c1a08 100%)", light: "linear-gradient(160deg, #f0f8ed 0%, #e2f0dd 50%, #f2fbf0 100%)" }, accent: { dark: "#a3e635", light: "#65a30d" }, glow: "rgba(163, 230, 53, 0.2)" },
  { id: 5, title: "LEAD", subtitle: "Earn the right to lead before the title", days: "Day 78-90", icon: "🔥", description: "Mentoring, code review excellence, team communication, and the soft skills that make you the senior engineer everyone wants to work with. The bridge to Staff.", mnemonic: "G.U.I.D.E. - Grow others, Unblock teams, Improve processes, Document decisions, Enable juniors", gradient: { dark: "linear-gradient(160deg, #181008 0%, #302210 50%, #1c1408 100%)", light: "linear-gradient(160deg, #fdf6ed 0%, #f8eddd 50%, #fef8f0 100%)" }, accent: { dark: "#fbbf24", light: "#d97706" }, glow: "rgba(251, 191, 36, 0.2)" },
];

const ALL_LESSONS = [
  // PHASE 1: CRAFT (Day 1-21)
  { day: 1, phase: 1, type: "bite", title: "The Craftsman's Oath", content: "Gady Pitaru (CTO, Badger Maps): 'A highly skilled engineer without discipline is like a veteran sailor without a map.' Today you commit: you will not sacrifice quality for speed without acknowledging the debt. You will write code that the NEXT person can understand. You will test what matters.", workChallenge: "Write down 3 coding standards you believe in but don't always follow. Pick one. Follow it religiously for 21 days. Example: 'I will never merge without tests for critical paths.'", lifeChallenge: "Pick one personal discipline you've been inconsistent with. Commit to 21 consecutive days. The discipline muscle is the same at work and in life.", memoryTrick: "A craftsman's oath is a PROMISE to your future self and everyone who reads your code. Sign it with consistency." },
  { day: 2, phase: 1, type: "bite", title: "Read Code Like Literature", content: "The best senior engineers spend as much time READING code as writing it. Read your team's codebase. Read open-source projects in your stack (Laravel, AWS SDK). Reading code builds pattern recognition faster than tutorials.", workChallenge: "Spend 30 minutes today reading a part of schemes-api you didn't write. No editing. Just reading. Note: what patterns do you see? What confuses you? What would you do differently?", lifeChallenge: "Read something outside your comfort zone today: a blog in a different programming language, an architecture doc from a different domain.", memoryTrick: "Writers who don't READ produce shallow work. Engineers who don't READ code produce shallow solutions." },
  { day: 3, phase: 1, type: "bite", title: "The Art of Naming", content: "If you can't name it clearly, you don't understand it clearly. Variable names, function names, class names, and PR titles are all COMMUNICATION. `processData()` tells nothing. `retryFailedEmailDispatch()` tells everything.", workChallenge: "Audit 5 function/variable names in your current codebase. Can a new engineer understand them without context? Rename the unclear ones.", lifeChallenge: "Apply naming clarity to life: your goals should be specific enough to name. Not 'get better' but 'complete AWS SAA-C03 by June 2026.'", memoryTrick: "Naming is COMPRESSED documentation. One good name saves a paragraph of comments." },
  { day: 4, phase: 1, type: "bite", title: "Testing: The Senior's Safety Net", content: "Senior engineers don't just write tests. They write the RIGHT tests. Unit tests for logic. Integration tests for flows. E2E tests for critical paths. The ratio matters: many unit, some integration, few E2E.", workChallenge: "Review your test coverage for email centralization. Is it testing the right things? Are critical paths covered? Is there a test for your most likely failure mode?", lifeChallenge: "Apply 'testing' to life decisions: before committing to a big choice, run a small experiment first. That's a 'life unit test.'", memoryTrick: "The testing pyramid: many UNIT (fast, cheap), some INTEGRATION (medium), few E2E (slow, expensive). Invert it and you'll be debugging forever." },
  { day: 5, phase: 1, type: "bite", title: "Debugging Like a Detective", content: "Senior engineers don't randomly change code hoping the bug disappears. They form hypotheses, gather evidence, isolate variables, and verify fixes. Debugging is SCIENCE, not gambling.", workChallenge: "Next bug you encounter: write down your hypothesis BEFORE changing any code. Then verify it. Track your hypothesis accuracy over 10 bugs. This builds diagnostic intuition.", lifeChallenge: "When something goes wrong in life, don't react randomly. Form a hypothesis about the cause. Gather evidence. Then act.", memoryTrick: "H.I.V.F. - Hypothesize, Investigate, Verify, Fix. In that order. ALWAYS." },
  { day: 6, phase: 1, type: "deep", title: "Technical Depth: Your Moat", content: "A senior engineer should have DEEP knowledge of their stack. Not just 'I use Laravel.' But 'I understand how Laravel's service container resolves dependencies, how Eloquent hydrates models, and how middleware pipelines work.'", workChallenge: "Pick one component of your stack (SQS, Redis, ECS, or Laravel internals). Spend 1 hour going one level deeper than you currently understand. Write a 1-page summary of what you learned.", lifeChallenge: "Go deep on one personal interest instead of skimming many. Depth creates mastery. Breadth creates awareness. You need both, but depth is rarer.", memoryTrick: "Breadth gets you in the door. DEPTH gets you the seat at the table. Go deep where it matters." },
  { day: 7, phase: 1, type: "practice", title: "Week 1: Code Quality Audit", content: "Audit your own recent code with fresh eyes.", workChallenge: "Review your last 5 PRs as if you're reviewing a stranger's code. Score each on: naming clarity (1-10), test coverage (1-10), error handling (1-10), readability (1-10). Average = your craft baseline.", lifeChallenge: "Audit your daily habits the same way. Score: consistency (1-10), quality (1-10), intentionality (1-10).", memoryTrick: "Self-review is harder than peer-review because your ego is in the way. Remove the ego. See the code." },
  { day: 8, phase: 1, type: "bite", title: "Error Handling: The Senior Signature", content: "Junior engineers handle the happy path. Senior engineers handle EVERYTHING: timeouts, null responses, network failures, race conditions, invalid input. Your error handling IS your professional signature.", workChallenge: "Review your email centralization code. For every external call (SQS, BNS, database), ask: what if this fails? What if it's slow? What if it returns garbage? Handle all three.", lifeChallenge: "In life plans, always have: Plan A (ideal), Plan B (if A fails), and a circuit breaker (when to stop trying entirely).", memoryTrick: "Happy path code is the SKELETON. Error handling is the IMMUNE SYSTEM. Without it, your code is one infection away from death." },
  { day: 9, phase: 1, type: "bite", title: "Performance Awareness", content: "Senior engineers don't write slow code by accident. They understand: N+1 queries, unnecessary database calls, memory leaks, inefficient loops, and when 'premature optimization' becomes necessary optimization.", workChallenge: "Profile one critical path in your application. Is there an N+1 query? An unnecessary join? A loop that could be a single query? Fix the worst offender.", lifeChallenge: "Profile your day the same way. Where are your 'N+1 queries'? (Checking email 50 times instead of batching into 3 sessions.)", memoryTrick: "Performance bugs are INVISIBLE until they're CATASTROPHIC. Profile before you're forced to." },
  { day: 10, phase: 1, type: "bite", title: "Refactoring: Small and Continuous", content: "Katherine Wu (New Relic): 'Don't go down rabbit holes or get wrapped up in edge cases.' Great refactoring is small, focused, and continuous. Not a 'big bang rewrite.' Boy Scout Rule: leave the code better than you found it.", workChallenge: "In every PR this week, include one small refactoring: rename a confusing variable, extract a method, remove dead code. Small, safe, continuous improvement.", lifeChallenge: "Apply the Boy Scout Rule to your physical space: every time you leave a room, fix one small thing. Continuous improvement compounds.", memoryTrick: "Big refactors are SCARY. Small refactors are INVISIBLE. But 100 invisible improvements = a transformed codebase." },
  { day: 11, phase: 1, type: "bite", title: "Git Mastery", content: "A senior engineer's git history tells a story. Clean commits, meaningful messages, logical branches, proper rebasing. Your commit messages are documentation that lives forever.", workChallenge: "Review your last 10 commit messages. Would a new team member understand WHAT changed and WHY? Rewrite any that say 'fix bug' or 'update code' into specific descriptions.", lifeChallenge: "Apply commit-message thinking to journaling: what did I do today and WHY? Specific logs beat vague entries.", memoryTrick: "A git commit is a TIME CAPSULE. Future-you opens it in 6 months. Will they thank you or curse you?" },
  { day: 12, phase: 1, type: "bite", title: "Security-First Thinking", content: "Every input is hostile. Every API is a door. Every database query is an injection risk. Senior engineers think about security by DEFAULT, not as an afterthought.", workChallenge: "Review your email centralization for OWASP Top 10 vulnerabilities: SQL injection, XSS, broken auth, sensitive data exposure. Fix any gaps.", lifeChallenge: "Apply security thinking to personal life: strong unique passwords, 2FA everywhere, aware of phishing. Digital hygiene = personal security.", memoryTrick: "Security is like LOCKS on your house. Nobody thinks about them until someone breaks in. Install them BEFORE." },
  { day: 13, phase: 1, type: "deep", title: "Design Patterns in Practice", content: "Don't just KNOW patterns. Know WHEN to use them. Strategy for interchangeable algorithms. Observer for event-driven flows. Factory for object creation. Your email centralization likely uses several.", workChallenge: "Identify 3 design patterns in your current codebase. Are they used correctly? Is there a place where a pattern would simplify the code? Document your findings.", lifeChallenge: "Life has patterns too: your reactions to stress, your decision-making process, your communication style. Identify YOUR patterns. Are they serving you?", memoryTrick: "Patterns are RECIPES, not RULES. A great chef knows when to follow the recipe and when to improvise." },
  { day: 14, phase: 1, type: "practice", title: "Week 2: The Code Challenge Sprint", content: "Sharpen your core coding skills with deliberate practice.", workChallenge: "Spend 30 minutes on a medium-difficulty coding problem (LeetCode, HackerRank). Focus not on solving it but on code QUALITY: naming, structure, edge cases, tests. Quality over speed.", lifeChallenge: "Apply deliberate practice to any skill: 30 focused minutes on Telugu, on writing, on photography. Deliberate > casual.", memoryTrick: "Deliberate practice is UNCOMFORTABLE by design. If it feels easy, you're not growing." },
  { day: 15, phase: 1, type: "bite", title: "Code Review Excellence", content: "Your code reviews reveal your seniority. Don't just check for bugs. Check for: naming, test coverage, error handling, performance implications, security, and whether it matches the team's patterns.", workChallenge: "In your next 3 code reviews, provide at least one comment in each of these categories: correctness, readability, performance, and one positive ('I like how you handled X').", lifeChallenge: "Apply review thinking to your own work before submitting: self-review with the same rigor you'd give a peer's code.", memoryTrick: "A great code review has 3 types of comments: Must-fix (blocking), Should-fix (improving), and Nice-job (encouraging). Use all three." },
  { day: 16, phase: 1, type: "bite", title: "Database Mastery", content: "Senior engineers understand their database deeply: indexing strategies, query optimization, transaction isolation levels, connection pooling, and when to use caching vs direct queries.", workChallenge: "Run EXPLAIN on your 5 most common queries. Are they using indexes? Any full table scans? Optimize the worst performer.", lifeChallenge: "Think of your brain as a database. Are you indexing the right information (organized notes) or doing full scans (searching randomly)?", memoryTrick: "A query without an index is a SEARCH without Google. You'll find what you need, but it'll take forever." },
  { day: 17, phase: 1, type: "bite", title: "API Design for Humans", content: "Your APIs are your team's interface to your work. Consistent naming, proper HTTP methods, clear error responses, and versioning strategy. An API should be intuitive without reading docs.", workChallenge: "Review one API you built. Does it follow RESTful conventions? Are error messages helpful? Could a developer from another team use it without asking you questions?", lifeChallenge: "Your personal 'API' is how people interact with you. Are you consistent? Are your 'responses' clear? Do people know what to expect?", memoryTrick: "A good API is like a good MENU. You know what you're ordering, what you'll get, and what happens if it's unavailable." },
  { day: 18, phase: 1, type: "bite", title: "Logging That Tells Stories", content: "Logs are your system's diary. Great logs tell you: what happened, when, to whom, and what the system was thinking. Bad logs are either silent or screaming everything.", workChallenge: "Review your logging in the email dispatch path. Can you trace a single email from entry to delivery using ONLY logs? If not, add the missing breadcrumbs.", lifeChallenge: "Your personal journal is your life's logging system. Write entries that your future self can trace: what happened, why, and what you learned.", memoryTrick: "Logs are BREADCRUMBS in the forest. Good breadcrumbs lead you home. No breadcrumbs? You're lost in production at 2 AM." },
  { day: 19, phase: 1, type: "bite", title: "The DRY vs WET Debate", content: "DRY (Don't Repeat Yourself) is good. But premature DRY creates bad abstractions. Sometimes WET (Write Everything Twice) is better until you see the real pattern. Senior engineers know when to abstract and when to wait.", workChallenge: "Find one place in your code where DRY created a confusing abstraction. Consider: would two simple, separate implementations be clearer?", lifeChallenge: "In life, not everything needs a 'system.' Sometimes doing something manually twice teaches you more than automating it immediately.", memoryTrick: "DRY saves LINES. Premature DRY costs CLARITY. Wait until the pattern reveals itself before abstracting." },
  { day: 20, phase: 1, type: "deep", title: "Building Your Technical Toolkit", content: "After 19 days, compile YOUR craft standards: the principles, tools, and practices that define how you write code.", workChallenge: "Write your personal 'Engineering Standards' document: naming conventions, testing philosophy, error handling approach, code review checklist, and performance baselines. Keep it and refine it.", lifeChallenge: "Write your personal 'Quality Standards' for life: what does 'good enough' look like for your health, relationships, content, and growth?", memoryTrick: "A toolkit without standards is a JUNK DRAWER. With standards, it's a PRECISION INSTRUMENT." },
  { day: 21, phase: 1, type: "practice", title: "Phase 1 Graduation: The Craft Score", content: "21 days of craft mastery. Assess your growth.", workChallenge: "Re-take the Day 7 audit on your latest code. Compare scores. Write: 'My craft improved in ___. I still need to work on ___. My next focus is ___.' Share with Arun as your growth evidence.", lifeChallenge: "Ask a trusted colleague: 'How would you rate my code quality compared to 3 months ago?' Their answer is your real score.", memoryTrick: "Phase 1 done. Your CODE speaks for you now. Phase 2: your OWNERSHIP speaks louder." },

  // PHASE 2: OWN (Day 22-42)
  { day: 22, phase: 2, type: "bite", title: "Beyond the Ticket", content: "Jose Miguel Perez (CTO, MarketGoo): 'Great developers seek understanding of the objective, goals, and impact that goes beyond the part they play.' A ticket says WHAT. A senior engineer understands WHY.", workChallenge: "For every Jira ticket you pick up this week, write one sentence: 'This matters because ___.' If you can't, ask your product owner. Understanding WHY changes how you build.", lifeChallenge: "For every task on your to-do list, ask WHY. If you can't answer, either find out or drop it.", memoryTrick: "A ticket without WHY is a destination without a MAP. You might arrive, but you won't know if you're in the right place." },
  { day: 23, phase: 2, type: "bite", title: "Own the Outcome, Not Just the Output", content: "Output = code delivered. Outcome = problem solved. A senior engineer who delivers code that doesn't solve the problem has FAILED, even if the code is beautiful.", workChallenge: "For your current sprint, list the OUTCOMES expected, not just the tasks. After the sprint, check: did you solve the problem, or just complete the tickets?", lifeChallenge: "Apply to Motovlogs: the output is a video. The outcome is inspiring a viewer. Are you optimizing for output or outcome?", memoryTrick: "Output fills your TIMESHEET. Outcome fills your IMPACT REPORT. Reviews measure outcomes." },
  { day: 24, phase: 2, type: "bite", title: "Proactive Communication", content: "Senior engineers never surprise their manager with bad news. If something is blocked, slipping, or risky, communicate EARLY. 'Hey, I noticed a potential delay' is 10x better than 'Sorry, it's late.'", workChallenge: "Set a daily habit: before end of day, ask yourself 'Is there anything Arun should know that he doesn't?' If yes, send a quick message. No surprises.", lifeChallenge: "In personal relationships, proactive communication prevents 90% of conflicts. 'I'll be late' before the time beats 'Sorry I'm late' after.", memoryTrick: "Proactive communication is a WEATHER FORECAST. Reactive communication is a FLOOD WARNING. One helps you prepare. The other helps you panic." },
  { day: 25, phase: 2, type: "bite", title: "Estimation That Builds Trust", content: "Senior engineers estimate accurately, not optimistically. Add buffer for unknowns. Communicate confidence levels. 'I'm 80% confident this takes 5 days. The 20% risk is if the BNS API has undocumented edge cases.'", workChallenge: "For your next 3 estimations, state: best case, likely case, worst case, and your confidence level. Track accuracy. Adjust your calibration over time.", lifeChallenge: "Estimate personal projects the same way. 'This video edit will take 2 hours (best), 3 hours (likely), 5 hours (if I redo the audio).' Honest estimation reduces stress.", memoryTrick: "Under-promise and over-deliver builds TRUST. Over-promise and under-deliver builds RESENTMENT. Choose trust." },
  { day: 26, phase: 2, type: "bite", title: "Documentation as Ownership", content: "If you built it but didn't document it, you didn't finish it. Documentation is the final 10% that makes your work COMPLETE. ADRs, README updates, runbooks, onboarding notes.", workChallenge: "For every PR you merge this week, update the relevant documentation. If no docs exist, create the initial version. This habit alone sets you apart.", lifeChallenge: "Document your personal processes: your morning routine, your content workflow, your financial system. Written processes are repeatable processes.", memoryTrick: "Code without docs is a GIFT without instructions. The recipient appreciates the thought but can't USE it." },
  { day: 27, phase: 2, type: "bite", title: "Root Cause, Not Band-Aid", content: "When a bug appears, the temptation is to fix the symptom and move on. Senior engineers find the ROOT CAUSE. Why did this happen? What allowed it? How do we prevent it from happening again?", workChallenge: "For the next bug you fix, add a section to your PR description: 'Root cause: ___. Prevention: ___.' This turns a bug fix into a learning moment for the whole team.", lifeChallenge: "When something goes wrong in life, find the root cause, not just the fix. 'I'm tired' -> WHY? -> 'I slept 5 hours' -> WHY? -> 'I was on my phone until 1 AM' -> THERE'S your root cause.", memoryTrick: "A band-aid stops bleeding. Root cause analysis stops the INJURY from happening again. Fix the cause, not the symptom." },
  { day: 28, phase: 2, type: "practice", title: "Week 4: The Ownership Audit", content: "Assess how much you truly OWN vs just COMPLETE.", workChallenge: "Review your last sprint. For each item: did you just complete the ticket (output) or did you ensure the outcome was achieved? Rate each: 'Completed' vs 'Owned.' Aim for 80%+ 'Owned.'", lifeChallenge: "Review your personal goals this month. Which did you OWN (actively drove) vs which did you LET HAPPEN (passive)?", memoryTrick: "Completion is CLOCKING OUT. Ownership is CARING about what happens after." },
  { day: 29, phase: 2, type: "bite", title: "Stakeholder Awareness", content: "Todd Stephan (VP Engineering, Ask): 'Great developers understand how the company works at a business level and speak the business language.' Know who uses your system, why they care, and what success looks like to THEM.", workChallenge: "Identify 3 stakeholders of your email centralization (beyond your team). What do THEY care about? Reliability? Cost? Speed? Tailor your communication to their concerns.", lifeChallenge: "Think about your 'stakeholders': family, friends, audience. What do they need from you? Are you delivering it?", memoryTrick: "Your code has USERS. Your career has STAKEHOLDERS. Know both. Serve both." },
  { day: 30, phase: 2, type: "bite", title: "Learning From Production", content: "Production is the ultimate teacher. Every incident, every slow query, every support ticket contains a lesson. Senior engineers treat production feedback as the most valuable data source.", workChallenge: "Review the last 3 production issues (yours or your team's). For each: what was the lesson? Was the lesson applied? If not, apply it now.", lifeChallenge: "Your 'production' is your daily life. What patterns of failure keep repeating? What lessons have you learned but not applied?", memoryTrick: "Production is a TEACHER who gives the TEST first and the LESSON after. The senior engineer passes by learning from every test." },
  { day: 31, phase: 2, type: "bite", title: "Managing Technical Debt Responsibly", content: "You can't fix all tech debt. Senior engineers categorize it: Critical (fix now, it's hurting us), Important (fix soon, it's slowing us), Nice-to-have (fix when convenient). And they COMMUNICATE the trade-offs.", workChallenge: "Map your team's tech debt into Critical/Important/Nice-to-have. For each Critical item, write the business impact. Present to Arun with a proposed priority.", lifeChallenge: "You have 'life debt' too: health checkups postponed, skills not updated, relationships not maintained. Categorize and prioritize.", memoryTrick: "Tech debt without categorization is a PILE. Tech debt with categorization is a QUEUE. Queues get processed. Piles get ignored." },
  { day: 32, phase: 2, type: "bite", title: "The 'Done' Definition", content: "For a senior engineer, 'done' means: code works, tests pass, edge cases handled, documentation updated, PR reviewed, deployed, and MONITORED. Not just 'it compiles.'", workChallenge: "Write your personal 'Definition of Done' checklist. Print it. Stick it near your monitor. Check it before every 'done' declaration.", lifeChallenge: "Apply to personal tasks: 'done' isn't 'started.' It's FINISHED, reviewed, and the next person can pick it up without asking you.", memoryTrick: "Half-done work is INVENTORY, not PROGRESS. Inventory costs you. Only truly DONE work creates value." },
  { day: 33, phase: 2, type: "deep", title: "Impact Tracking System", content: "You can't get a 5-star review on vibes. You need DATA. Track your impact: bugs prevented, performance improved, engineers unblocked, documentation written, incidents handled.", workChallenge: "Start an Impact Log: weekly, record what you shipped, who you helped, what you improved, and the measurable result. This feeds directly into your review. Start NOW, not in November.", lifeChallenge: "Track personal impact too: content published, skills learned, health improvements, relationships maintained.", memoryTrick: "An Impact Log is your career's FLIGHT RECORDER. When review time comes, you play the recording. No log = no evidence = no promotion." },
  { day: 34, phase: 2, type: "bite", title: "Saying No to the Wrong Work", content: "Senior engineers protect their focus. Not every request deserves a yes. If work doesn't align with team goals, doesn't have clear value, or could be done by someone else more appropriately, push back respectfully.", workChallenge: "This week, when asked to do something, ask: 'How does this connect to our sprint goals?' If it doesn't, negotiate: 'I can do this, but it means X gets delayed. Which is the priority?'", lifeChallenge: "Say no to one thing today that doesn't align with your goals. Protect your time like you protect your codebase.", memoryTrick: "Every YES to the wrong work is a NO to the right work. Guard your yeses." },
  { day: 35, phase: 2, type: "practice", title: "Week 5: The Sprint Retrospective", content: "Run a personal retrospective on your last 2 weeks of work.", workChallenge: "Answer honestly: What went well? What didn't? What will I change? Be specific. 'I'll add integration tests before merging' is better than 'I'll write more tests.'", lifeChallenge: "Personal retro: What went well in life? What didn't? One specific change for next week.", memoryTrick: "Retros without ACTION ITEMS are therapy sessions. Helpful, but they don't change the system." },
  { day: 36, phase: 2, type: "bite", title: "Cross-Functional Partnership", content: "Senior engineers don't just work with other engineers. They partner with product, QA, ops, design, and support. Understanding their world makes YOUR work better.", workChallenge: "Schedule a 15-minute chat with someone from a non-engineering function (product, support, or ops). Ask: 'What's your biggest pain point related to our systems?' You'll learn things code reviews never teach.", lifeChallenge: "Talk to someone outside your professional bubble today. A different industry, a different skill set. Cross-pollination creates insight.", memoryTrick: "Engineers who only talk to engineers build technically perfect solutions to the WRONG problems." },
  { day: 37, phase: 2, type: "bite", title: "Handling Ambiguity", content: "Junior engineers need clear specs. Senior engineers THRIVE in ambiguity. When requirements are unclear, they ask clarifying questions, make reasonable assumptions, document decisions, and iterate.", workChallenge: "Next ambiguous requirement, don't wait for clarity. Write down your assumptions, propose a solution, and share it: 'Based on my understanding, here's what I'd build. Does this match your intent?'", lifeChallenge: "Life is ambiguous by nature. Practice making decisions with incomplete information. Done is better than perfect.", memoryTrick: "Ambiguity is not a BLOCKER. It's an INVITATION to demonstrate judgment. Judgment is the senior skill." },
  { day: 38, phase: 2, type: "bite", title: "Time Management for Engineers", content: "Context switching kills deep work. Senior engineers protect 2-3 hour blocks for coding, batch meetings, and timebox research. Your calendar is your productivity architecture.", workChallenge: "Design your ideal workday: when do you code? When do you review? When do you communicate? Block your calendar accordingly for one week. Measure the difference.", lifeChallenge: "Batch similar tasks: all errands in one trip, all messages in one session, all content editing in one block. Batching beats task-switching.", memoryTrick: "Context switching costs 23 MINUTES to recover focus. 5 switches = 2 HOURS lost. Protect your deep work like you protect production." },
  { day: 39, phase: 2, type: "bite", title: "Incident Response Ownership", content: "When production breaks, senior engineers step up. They don't wait to be assigned. They triage, communicate, fix, and retrospect. Incident response is where reputations are made.", workChallenge: "Review your team's incident response process. Is it documented? Do you know the escalation path? If not, create or improve the runbook. Be ready BEFORE the next incident.", lifeChallenge: "In life emergencies, be the calm center: assess the situation, communicate clearly, take action, then reflect. Same process, different domain.", memoryTrick: "In incidents, everyone remembers who STEPPED UP and who STEPPED BACK. Be the person who steps up." },
  { day: 40, phase: 2, type: "deep", title: "Building Your Ownership Framework", content: "Compile your ownership principles: how you approach tasks, communicate status, handle ambiguity, and ensure quality.", workChallenge: "Write your 'Ownership Manifesto': 5 statements about how you approach work. 'I don't mark tickets done until docs are updated.' 'I communicate blockers within 2 hours of discovery.' Post it.", lifeChallenge: "Write a personal ownership manifesto: how you handle commitments, deadlines, and promises.", memoryTrick: "An ownership manifesto is your professional CONSTITUTION. It governs your behavior when no one is watching." },
  { day: 41, phase: 2, type: "bite", title: "Continuous Improvement", content: "The best senior engineers are never 'done' growing. They read, practice, reflect, and adapt. 30 minutes a day of deliberate learning compounds into mastery over years.", workChallenge: "Set a daily learning habit: 30 minutes before work or during lunch. Alternate between: reading code, reading articles, practicing system design, and reviewing new tools.", lifeChallenge: "Your 1% philosophy already covers this. But are you learning in the RIGHT areas? Focus on what's most valuable for your next 12 months.", memoryTrick: "30 minutes/day = 182 hours/year = a full MONTH of learning. Compounded over 5 years, that's the difference between average and exceptional." },
  { day: 42, phase: 2, type: "practice", title: "Phase 2 Graduation: The Ownership Scorecard", content: "21 days of ownership training. Assess your transformation.", workChallenge: "Score yourself: proactive communication (1-10), estimation accuracy (1-10), documentation completeness (1-10), outcome focus (1-10), stakeholder awareness (1-10). Lowest = your Phase 3 growth area.", lifeChallenge: "Ask Arun: 'What's one area where I could take more ownership?' Their answer = your roadmap.", memoryTrick: "Phase 2 done. You OWN your work completely. Phase 3: think beyond code. Think in SYSTEMS and DESIGN." },

  // PHASE 3: DESIGN (Day 43-63)
  { day: 43, phase: 3, type: "bite", title: "Think Before You Code", content: "Senior engineers spend MORE time thinking and LESS time coding than juniors. 30 minutes of design thinking saves 3 hours of coding the wrong thing.", workChallenge: "Before your next feature, spend 30 minutes with pen and paper (or a whiteboard). Draw the data flow. Identify the components. List the edge cases. THEN open your IDE.", lifeChallenge: "Before any big personal project (video, trip, purchase), spend 15 minutes planning. The planning-to-doing ratio should be at least 1:5.", memoryTrick: "A carpenter who cuts without measuring wastes wood. An engineer who codes without designing wastes time." },
  { day: 44, phase: 3, type: "bite", title: "Understanding Your System End-to-End", content: "A senior engineer should be able to explain what happens when a user triggers an action: from the UI click through the network, load balancer, application, queue, database, and back. The full journey.", workChallenge: "Trace one email dispatch end-to-end through your system. From the trigger event through SQS to BNS to delivery. Can you explain every hop? Where are the gaps in your understanding?", lifeChallenge: "Trace your content creation end-to-end: from idea to published video. Where are the bottlenecks? Where does quality drop?", memoryTrick: "If you can't explain the full journey, you can only fix problems you can SEE. Senior engineers see the WHOLE road." },
  { day: 45, phase: 3, type: "bite", title: "Scalability Thinking", content: "What works for 100 users breaks at 10,000. What works for 10,000 breaks at 1M. Senior engineers think: 'What happens when this grows 10x?' and design accordingly.", workChallenge: "For your email centralization: what happens when email volume grows 10x? Where's the first bottleneck? SQS limits? Database writes? BNS rate limits? Plan for it.", lifeChallenge: "If your YouTube channel grows 10x, would your current workflow handle it? Plan your content system for scale.", memoryTrick: "Design for TODAY's traffic and TOMORROW's growth. If you only design for today, tomorrow will BREAK you." },
  { day: 46, phase: 3, type: "bite", title: "Data Modeling Mastery", content: "Your data model determines 80% of your system's fate. Get it right, and everything flows. Get it wrong, and you'll fight migrations forever. Senior engineers design data models for the NEXT 2 years, not just the current sprint.", workChallenge: "Review your email_templates table design. Is the variables_schema JSON column flexible enough for future needs? Would a new template type require schema changes? Design for extensibility.", lifeChallenge: "Your personal data model = how you organize information: notes, files, goals, contacts. Is it structured for growth?", memoryTrick: "A data model is the SKELETON of your system. Change the skeleton later, and everything attached to it SCREAMS." },
  { day: 47, phase: 3, type: "bite", title: "Caching Strategies", content: "Know WHEN to cache, WHAT to cache, HOW to invalidate, and WHEN NOT to cache. Caching wrong data is worse than not caching at all. Your Redis/ElastiCache knowledge should be deep.", workChallenge: "Map the caching in your system: what's cached, TTLs, invalidation strategy. Is there stale data risk? Is there a cache stampede scenario? Address gaps.", lifeChallenge: "Your brain 'caches' beliefs and assumptions. When did you last 'invalidate' an outdated belief? Fresh data leads to better decisions.", memoryTrick: "Cache is a SHORTCUT. Shortcuts that aren't maintained become DEAD ENDS. Invalidation is as important as caching." },
  { day: 48, phase: 3, type: "deep", title: "System Design Fundamentals", content: "Load balancing, message queues, database sharding, CDNs, rate limiting, circuit breakers. These aren't just interview topics. They're tools you use in REAL systems at BHN.", workChallenge: "Pick one system design concept you're weakest on (sharding, consistent hashing, event sourcing). Spend 1 hour learning it deeply. Write a 1-page summary with how it applies to BHN.", lifeChallenge: "System design thinking applies to life: redundancy (backup plans), load balancing (distributing energy), queues (managing priorities).", memoryTrick: "System design isn't just for interviews. It's the VOCABULARY of senior engineering. Speak it fluently." },
  { day: 49, phase: 3, type: "practice", title: "Week 7: Design Review Practice", content: "Practice designing and reviewing architectures.", workChallenge: "Design a system on a whiteboard (notification system, URL shortener, or rate limiter). Time: 45 minutes. Then review your own design: what are the weak points? How would it handle 10x traffic?", lifeChallenge: "Design a 'life system' on paper: how your week flows, where energy goes, what outputs you produce. Review it for bottlenecks.", memoryTrick: "Designing on paper is 10x faster than designing in code. And 10x cheaper to throw away." },
  { day: 50, phase: 3, type: "bite", title: "Trade-off Documentation", content: "Every design decision is a trade-off. 'We chose SQS over Kafka because ___. The downside is ___. We'll revisit when ___.' Documenting trade-offs shows mature engineering thinking.", workChallenge: "For your 3 most recent design decisions, write a trade-off summary: what you chose, what you rejected, why, and what would make you reconsider. This is ADR material.", lifeChallenge: "Document personal trade-offs too: 'I chose to focus on AWS cert over DSA because ___. I'll revisit in Q3.'", memoryTrick: "A decision without documented trade-offs is a GUESS. A decision WITH documented trade-offs is ENGINEERING." },
  { day: 51, phase: 3, type: "bite", title: "Queue Design Patterns", content: "Your email centralization depends on SQS. Understand: FIFO vs Standard, dead-letter queues, visibility timeouts, retry strategies, poison message handling. Deep queue knowledge = reliable systems.", workChallenge: "Map your SQS configuration: queue type, visibility timeout, DLQ setup, retry count. Is it optimal? What happens when a message fails 5 times? Do you know?", lifeChallenge: "Your personal 'queue' is your task list. Do you have a 'dead letter queue' for tasks that keep failing? Move them out or fix the root cause.", memoryTrick: "A queue without a DLQ is a pipe without a drain. When things back up, the whole system floods." },
  { day: 52, phase: 3, type: "bite", title: "Feature Flags as Architecture", content: "Feature flags aren't just for deployments. They're an architectural pattern: progressive rollout, A/B testing, kill switches, and gradual migration. Your Strangler Fig Pattern uses them.", workChallenge: "Review your feature flag strategy for email centralization. Can you roll back instantly? Can you target specific email types? Is the flag lifecycle documented?", lifeChallenge: "Apply feature flags to life changes: try a new habit for 1 week (canary). If it works, roll it out fully. If not, revert.", memoryTrick: "Feature flags are SAFETY NETS for change. Deploy bravely because you can roll back instantly." },
  { day: 53, phase: 3, type: "bite", title: "Monitoring-Driven Development", content: "Design your monitoring ALONGSIDE your code, not after. What metrics will tell you it's healthy? What alerts will fire when it's sick? Build the dashboard before the feature.", workChallenge: "For your next feature, write the monitoring plan FIRST: key metrics, alert thresholds, dashboard widgets. THEN write the code. Your New Relic expertise makes this natural.", lifeChallenge: "Define personal health metrics: sleep quality, energy level, mood, productivity. Monitor them weekly. Can't improve what you don't track.", memoryTrick: "Monitoring-first is like building a CAR with a dashboard included. Monitoring-after is adding a speedometer to a moving vehicle." },
  { day: 54, phase: 3, type: "bite", title: "Async vs Sync Decision Making", content: "Not everything needs to be synchronous. Email dispatch? Async. User authentication? Sync. Senior engineers choose the right communication pattern for each operation.", workChallenge: "Audit your system's sync vs async decisions. Is anything synchronous that should be async (slow operations blocking requests)? Is anything async that should be sync (user-facing responses)?", lifeChallenge: "In communication: what needs immediate response (sync) vs what can wait (async)? Not every Slack message needs a real-time reply.", memoryTrick: "Sync = phone call (immediate, blocking). Async = email (flexible, non-blocking). Use the right one for the right situation." },
  { day: 55, phase: 3, type: "deep", title: "Your Architecture Patterns Catalog", content: "Build your personal catalog of patterns you've used and when they apply. Strangler Fig, Circuit Breaker, Saga, CQRS, Event Sourcing. Know 5-7 deeply.", workChallenge: "Create a 'My Architecture Patterns' doc: for each pattern you know, write: what it is, when to use it, when NOT to, and where you've used it at BHN.", lifeChallenge: "Catalog your life patterns too: decision frameworks, stress responses, energy management techniques. Know your toolkit.", memoryTrick: "A pattern catalog is a RECIPE BOOK for systems. When a problem arrives, you flip to the right recipe." },
  { day: 56, phase: 3, type: "practice", title: "Week 8: The Design Sprint", content: "Full design exercise combining everything from Phase 3.", workChallenge: "Take a real BHN challenge (or a hypothetical). Design the full solution: data model, API contracts, queue strategy, caching layer, monitoring plan, trade-offs. Document it as an RFC. Get feedback.", lifeChallenge: "Design your next 90 days as a 'system': inputs (learning, health, relationships), processing (daily routines), outputs (career growth, content, wellbeing).", memoryTrick: "A design sprint compresses WEEKS of thinking into HOURS of focused work. The constraint creates clarity." },
  { day: 57, phase: 3, type: "bite", title: "Infrastructure as Code Awareness", content: "Senior engineers understand how their code gets deployed: Docker, ECS, CloudFormation, CI/CD pipelines. You don't need to be a DevOps expert, but you should understand the deployment path.", workChallenge: "Trace how your code goes from PR merge to production. Every step: CI tests, Docker build, ECR push, ECS deployment. Understand each stage. Where could it break?", lifeChallenge: "Understand the 'deployment pipeline' for your goals: what steps take an idea from conception to reality? Where's the bottleneck?", memoryTrick: "An engineer who doesn't understand deployment is a chef who doesn't understand the OVEN. You need to know what happens after you prepare the dish." },
  { day: 58, phase: 3, type: "bite", title: "Cost-Aware Engineering", content: "Cloud costs matter. Senior engineers design with cost awareness: right-sizing instances, efficient queries, appropriate storage tiers, reserved capacity vs on-demand.", workChallenge: "Check your team's AWS bill breakdown. What's the biggest cost? Can any resource be right-sized? Is there idle capacity? Present one cost optimization to your team.", lifeChallenge: "Apply cost awareness to personal finance: what are your biggest expenses? Can any be optimized without sacrificing quality?", memoryTrick: "Cloud bills are INVISIBLE until they're ENORMOUS. A cost-aware engineer saves the company money silently. That's senior value." },
  { day: 59, phase: 3, type: "bite", title: "Security in Architecture", content: "Security isn't a feature. It's a property of the architecture. Authentication, authorization, encryption at rest and in transit, secrets management, least privilege access.", workChallenge: "Audit your email centralization for security: how are API keys stored? Is data encrypted? Who has access to what? Is the principle of least privilege applied?", lifeChallenge: "Audit your personal security: password manager, 2FA, backup codes, encrypted storage. Your digital life deserves the same rigor as production.", memoryTrick: "Security in architecture is like FOUNDATIONS in a building. You don't see it, but without it, everything collapses." },
  { day: 60, phase: 3, type: "bite", title: "Backward Compatibility Thinking", content: "Senior engineers never break existing consumers. When changing APIs, data formats, or interfaces: maintain backward compatibility, provide migration paths, and communicate changes clearly.", workChallenge: "For your next API change: can existing consumers still work without modification? If not, what's the migration plan? How will you communicate the breaking change?", lifeChallenge: "In relationships, 'backward compatibility' means not suddenly changing expectations without communication. Transition gradually, communicate clearly.", memoryTrick: "Breaking backward compatibility is like changing the LOCKS without telling your roommates. Don't do it." },
  { day: 61, phase: 3, type: "bite", title: "Observability Triad: Logs, Metrics, Traces", content: "Logs tell you WHAT happened. Metrics tell you HOW MUCH. Traces tell you WHERE (across services). All three together give you complete system visibility.", workChallenge: "For your email dispatch path: do you have all three? Logs (structured, with correlation IDs), Metrics (latency, error rate, throughput), Traces (request journey across services)? Fill the gaps.", lifeChallenge: "Personal observability: journal = logs, habit tracker = metrics, weekly reflection = traces. All three together = self-awareness.", memoryTrick: "Logs without metrics is a DIARY. Metrics without traces is a SCORECARD. All three together is a COCKPIT." },
  { day: 62, phase: 3, type: "deep", title: "Building Your Design Playbook", content: "Compile your design toolkit: patterns, decision frameworks, trade-off matrices, and review checklists.", workChallenge: "Write your 'Design Playbook': your go-to patterns, your data modeling principles, your monitoring approach, your trade-off documentation template. This is your reusable brain.", lifeChallenge: "Create a personal 'Life Design Playbook': your decision framework, your planning template, your review process.", memoryTrick: "A playbook turns EXPERIENCE into PROCESS. Process is repeatable. Repeatable is scalable. Scalable is senior." },
  { day: 63, phase: 3, type: "practice", title: "Phase 3 Graduation: Design Portfolio", content: "21 days of design thinking. Demonstrate it.", workChallenge: "Compile: 1 system design you created, 1 RFC you wrote, 1 trade-off analysis, and 1 architecture review. This portfolio is evidence for your 5-star review under BeInnovative.", lifeChallenge: "Present one personal 'design decision' to a friend: how you structured a goal, a routine, or a project.", memoryTrick: "Phase 3 done. You can CRAFT code, OWN outcomes, and DESIGN systems. Phase 4: SHIP reliably." },

  // PHASE 4: SHIP (Day 64-77)
  { day: 64, phase: 4, type: "bite", title: "The Release Checklist", content: "Senior engineers never 'just deploy.' They have a checklist: tests passed, docs updated, monitoring configured, rollback plan ready, stakeholders notified. Every. Single. Time.", workChallenge: "Create a deployment checklist for your team. Include: pre-deploy checks, deployment steps, post-deploy verification, and rollback procedure. Share it.", lifeChallenge: "Create checklists for your important personal processes: video publishing, monthly review, travel planning. Checklists prevent mistakes.", memoryTrick: "Surgeons use checklists. Pilots use checklists. If they can't afford to skip steps, neither can you." },
  { day: 65, phase: 4, type: "bite", title: "Canary Deployments", content: "Don't deploy to 100% at once. Deploy to 5%, verify, then 25%, then 100%. Canary deployments catch problems before they impact all users.", workChallenge: "Is your team using canary or rolling deployments? If not, propose it. If yes, review the strategy: is the canary window long enough? Are you monitoring the right metrics?", lifeChallenge: "Canary your life changes: try a new routine for 1 week before committing. Try new content format for 3 videos before pivoting.", memoryTrick: "Canary deployments: send the CANARY into the mine first. If it survives, the miners follow. If not, you saved everyone." },
  { day: 66, phase: 4, type: "bite", title: "Zero-Downtime Deployments", content: "Senior engineers deploy without users noticing. Blue-green deployments, rolling updates, database migrations that don't lock tables. Invisible deployment = mature engineering.", workChallenge: "Review your deployment pipeline. Can you deploy during peak hours without user impact? If not, what needs to change?", lifeChallenge: "Make your personal transitions smooth too: changing routines, moving locations, switching projects. Gradual transitions beat sudden switches.", memoryTrick: "Zero-downtime deployment is like changing a tire on a MOVING car. Difficult, but when you master it, nobody even notices the change." },
  { day: 67, phase: 4, type: "bite", title: "Alert Fatigue Prevention", content: "Too many alerts = no alerts. If your team ignores notifications because there are too many false positives, you have alert fatigue. Every alert should require ACTION.", workChallenge: "Audit your New Relic alerts. How many fired this month? How many required action? Remove or tune any that are noise. Every alert should make someone DO something.", lifeChallenge: "Audit your phone notifications. How many actually need your immediate attention? Reduce noise. Protect your attention.", memoryTrick: "Alerts are like a fire alarm. If it goes off every hour for no reason, nobody evacuates when there's a REAL fire." },
  { day: 68, phase: 4, type: "deep", title: "Incident Management Mastery", content: "When things go wrong (and they will), senior engineers: 1) Assess severity, 2) Communicate immediately, 3) Mitigate (not necessarily fix), 4) Root cause after stability, 5) Document and prevent.", workChallenge: "Write or improve your team's incident response playbook: severity levels, communication templates, escalation paths, and post-incident review process.", lifeChallenge: "Create a personal crisis playbook: what to do when things go wrong (financial emergency, health scare, relationship conflict). Having a plan reduces panic.", memoryTrick: "In incidents: M.I.C. - Mitigate first, Investigate second, Communicate throughout." },
  { day: 69, phase: 4, type: "bite", title: "Post-Incident Reviews That Matter", content: "Blameless retrospectives after incidents are where the REAL learning happens. Not 'who broke it' but 'how did our system allow this to happen?'", workChallenge: "Run or improve your next post-incident review using: Timeline, Impact, Root cause, Contributing factors, Action items with owners and deadlines.", lifeChallenge: "After any personal setback, run a blameless retro with yourself: what happened, what allowed it, what will I change?", memoryTrick: "A blameless retro focuses on SYSTEMS, not PEOPLE. People make mistakes. Systems allow or prevent them." },
  { day: 70, phase: 4, type: "practice", title: "Week 10: Operational Readiness Review", content: "Assess: is your system READY for production success?", workChallenge: "Run an Operational Readiness Review on your email centralization: monitoring coverage, alert quality, runbook completeness, deployment safety, rollback capability. Score each 1-10.", lifeChallenge: "Run an 'operational readiness review' on your personal systems: is your routine sustainable? Is your health monitored? Is your career plan documented?", memoryTrick: "A system that works is GOOD. A system that works AND is observable, recoverable, and documented is EXCELLENT." },
  { day: 71, phase: 4, type: "bite", title: "SLOs and Error Budgets", content: "SLOs (Service Level Objectives) define 'good enough.' Error budgets define 'how much failure is acceptable.' 99.9% uptime means 8.7 hours of allowed downtime per year. Know your numbers.", workChallenge: "Define SLOs for your email dispatch: acceptable latency, acceptable error rate, acceptable throughput. Present them to your team.", lifeChallenge: "Define personal SLOs: 'I will exercise 4/7 days' (85.7% 'uptime'). Perfection isn't the goal. Consistency is.", memoryTrick: "SLOs turn vague 'be reliable' into concrete 'achieve 99.5%.' Concrete targets get measured. Measured targets get improved." },
  { day: 72, phase: 4, type: "bite", title: "Performance Testing", content: "Load testing, stress testing, and performance benchmarking should happen BEFORE production, not after users complain. Senior engineers know their system's limits.", workChallenge: "Run a load test on one critical path of your system. What's the breaking point? What degrades first? Document the results and set a performance baseline.", lifeChallenge: "'Stress test' your personal routines: what happens when life gets intense? Does your system (routine, health, relationships) degrade gracefully or crash?", memoryTrick: "A system that hasn't been load tested is a bridge that hasn't been weight tested. It MIGHT hold. Do you want to find out in production?" },
  { day: 73, phase: 4, type: "bite", title: "Dependency Management", content: "Your system's reliability is only as strong as its weakest dependency. Understand your external dependencies, their SLAs, their failure modes, and your fallback strategy.", workChallenge: "Map your external dependencies (SQS, BNS, RDS, ElastiCache). For each: what's their SLA? What happens when they fail? What's your fallback? Document it.", lifeChallenge: "Map your personal dependencies: single employer, single income, single skill set. Diversify where the risk is concentrated.", memoryTrick: "Dependencies are LINKS in a chain. One weak link breaks the whole chain. Know your links." },
  { day: 74, phase: 4, type: "bite", title: "Database Migration Safety", content: "Database migrations are the scariest deployments. Senior engineers: test migrations on staging first, have rollback scripts, avoid locking tables, and time migrations during low traffic.", workChallenge: "Review your MySQL migration strategy. Do you have a rollback plan for every migration? Are you testing on staging? Can you run migrations without downtime?", lifeChallenge: "Big life changes (career moves, relocations) are 'migrations.' Have a rollback plan. Test on a small scale first.", memoryTrick: "A database migration without a rollback plan is BUNGEE JUMPING without checking the cord. Thrilling, but potentially fatal." },
  { day: 75, phase: 4, type: "bite", title: "Documentation-Driven Operations", content: "If your operational procedures exist only in someone's head, you have a single point of failure: that person. Runbooks, playbooks, and operational docs are reliability insurance.", workChallenge: "Identify your team's top 3 operational procedures. Are they documented? Can someone who's NEVER done them follow the docs? If not, improve them this week.", lifeChallenge: "Document your important life procedures: where your passwords are, how to access your accounts, emergency contacts. Don't be a single point of failure.", memoryTrick: "Operational docs are INSURANCE POLICIES. You hope you never need them. But when you do, they save everything." },
  { day: 76, phase: 4, type: "deep", title: "Building Your Shipping Playbook", content: "Compile your operational toolkit: deployment checklists, monitoring standards, incident response procedures, and performance baselines.", workChallenge: "Create your 'Shipping Playbook': deployment checklist, monitoring setup template, incident response flow, SLO definitions, and performance testing plan.", lifeChallenge: "Create a 'Life Shipping Playbook': how you publish content, how you handle health routines, how you manage finances.", memoryTrick: "A shipping playbook ensures CONSISTENCY. Consistent delivery builds TRUST. Trust builds REPUTATION." },
  { day: 77, phase: 4, type: "practice", title: "Phase 4 Graduation: Operational Excellence Report", content: "14 days of shipping mastery. Demonstrate it.", workChallenge: "Write an Operational Excellence Report: your deployment safety record, monitoring coverage, incident response improvements, and SLO performance. This is BeAccountable evidence for your 5-star review.", lifeChallenge: "Review your personal 'shipping record': content published on schedule? Health routines maintained? Commitments honored?", memoryTrick: "Phase 4 done. You CRAFT, OWN, DESIGN, and SHIP with excellence. Final phase: LEAD others." },

  // PHASE 5: LEAD (Day 78-90)
  { day: 78, phase: 5, type: "bite", title: "Mentoring Without the Title", content: "You don't need 'mentor' in your title to mentor. Every code review, every pair programming session, every Slack answer is a mentoring opportunity. Help juniors think, not just code.", workChallenge: "Identify one junior or mid-level engineer. This week, instead of GIVING them the answer, ask them 3 guiding questions that lead to the answer. Teach them to fish.", lifeChallenge: "In any teaching moment (explaining your motorcycle, sharing a recipe, helping a friend), guide don't tell. Let them discover.", memoryTrick: "The best mentors don't give FISH. They don't even teach FISHING. They make the student CURIOUS about fish." },
  { day: 79, phase: 5, type: "bite", title: "Code Reviews as Teaching", content: "Your code reviews are your most frequent teaching opportunity. Don't just say 'change this.' Say 'consider this approach because ___.' Explain the WHY behind your suggestions.", workChallenge: "In your next 5 code reviews, add at least one educational comment: 'Here's why this pattern is preferred: ___' or 'This could cause issues at scale because ___.'", lifeChallenge: "In any feedback you give (Motovlogs comments, friend advice), explain the reasoning, not just the recommendation.", memoryTrick: "A code review with only 'fix this' is a RED PEN. A code review with 'consider this because' is a CLASSROOM." },
  { day: 80, phase: 5, type: "bite", title: "Team Communication Excellence", content: "Senior engineers are the communication backbone of their team. Clear standup updates, concise Slack messages, well-structured emails. You set the communication standard.", workChallenge: "In your next standup: 'Yesterday I [completed/progressed]. Today I'm [focusing on]. Blockers: [none/specific]. This impacts [outcome].' Clear, structured, useful.", lifeChallenge: "Apply the same structure to personal updates: 'What I did, what I'm doing, what I need.' Clear communication respects everyone's time.", memoryTrick: "A standup that runs over 15 minutes is a MEETING pretending to be efficient. Keep it tight. Keep it structured." },
  { day: 81, phase: 5, type: "bite", title: "Giving Constructive Feedback", content: "Senior engineers give feedback that HELPS, not hurts. Specific, kind, and actionable. Not 'this code is bad' but 'this function would be more testable if we extracted the database logic.'", workChallenge: "Give one piece of constructive feedback to a colleague this week using SBI: Situation, Behavior, Impact. Keep it specific. Keep it kind.", lifeChallenge: "Practice giving feedback in personal relationships with the same care: specific, kind, and about behavior (not character).", memoryTrick: "Constructive feedback is a GIFT in careful wrapping. Destructive feedback is the same gift thrown at someone's head." },
  { day: 82, phase: 5, type: "deep", title: "Knowledge Sharing as Leadership", content: "Present at team meetings. Write internal blog posts. Create learning resources. The senior engineer who shares knowledge raises the ENTIRE team's level.", workChallenge: "Schedule and deliver one knowledge-sharing session for your team: a tech talk on SQS patterns, a walkthrough of your email centralization architecture, or a debugging technique demo.", lifeChallenge: "Share knowledge publicly: a LinkedIn post, a Motovlogs educational segment, a Twitter thread. Teaching solidifies YOUR understanding and helps others.", memoryTrick: "Teaching is LEARNING twice. First when you prepare, again when you present. Double the growth." },
  { day: 83, phase: 5, type: "bite", title: "Onboarding Excellence", content: "How quickly a new team member becomes productive reflects on the TEAM, not just the new hire. Senior engineers create onboarding that works without their personal presence.", workChallenge: "Review your team's onboarding: can a new engineer set up the project, understand the architecture, and make their first PR within 1 week? If not, create or improve the onboarding guide.", lifeChallenge: "Create 'onboarding' for your personal systems: could someone else manage your content workflow, your finances, or your household if you were unavailable?", memoryTrick: "Great onboarding is the ultimate TEST of your documentation. If a new person can get productive fast, your docs are excellent." },
  { day: 84, phase: 5, type: "practice", title: "Week 12: The Leadership Sprint", content: "Practice all leadership skills simultaneously this week.", workChallenge: "This week: mentor 1 person, give 1 educational code review, share 1 piece of knowledge, and improve 1 process. Track each. This is staff-level behavior within senior scope.", lifeChallenge: "This week: teach someone something, improve one relationship, publish one piece of content, and reflect once. Full-spectrum leadership.", memoryTrick: "Leadership at senior level is SUBTLE. It's not about authority. It's about EXAMPLE." },
  { day: 85, phase: 5, type: "bite", title: "Process Improvement", content: "Senior engineers don't just follow processes. They improve them. Slow PR reviews? Propose a solution. Flaky tests? Fix the pipeline. Unclear requirements? Create a template.", workChallenge: "Identify one process pain point on your team. Propose a specific improvement. Implement it. Measure the result. This is BeTheSolution in action.", lifeChallenge: "Identify one personal process that's inefficient. Improve it. One small system upgrade per week compounds into transformation.", memoryTrick: "Improving a process benefits EVERYONE, forever. That's the highest leverage a senior engineer can have without the staff title." },
  { day: 86, phase: 5, type: "bite", title: "Cross-Team Collaboration", content: "The bridge to staff: working effectively across team boundaries. Senior engineers who collaborate well across teams demonstrate they can operate at a larger scope.", workChallenge: "Initiate one cross-team collaboration this month: help another team with a code review, share a useful tool, or solve a shared problem. Document the interaction.", lifeChallenge: "Collaborate outside your usual circles: a content collab, a community project, a learning group with people from different backgrounds.", memoryTrick: "Cross-team collaboration is the BRIDGE between senior and staff. Walk it as often as you can." },
  { day: 87, phase: 5, type: "bite", title: "Influence Through Excellence", content: "At senior level, you don't need to 'influence' politically. You influence through the QUALITY of your work. When your code is excellent, your docs are clear, and your communication is crisp, people naturally follow your lead.", workChallenge: "This week, make everything you produce 10% better than usual: cleaner code, more thorough reviews, more structured communication. Excellence creates its own gravity.", lifeChallenge: "In everything you create (content, work, relationships), aim for 10% better than your baseline. That's where the 1% philosophy lives.", memoryTrick: "Excellence doesn't need a MEGAPHONE. It creates its own ECHO. Do great work and watch people start following." },
  { day: 88, phase: 5, type: "bite", title: "Building Your 5-Star Evidence", content: "Your year-end review is built DAILY, not in December. Every achievement, every impact, every growth moment should be logged. By review time, you're presenting evidence, not remembering.", workChallenge: "Update your Impact Log with this week's contributions. Map each to BHN pillars: BeOneTeam, BeInnovative, BeTheSolution, BeAccountable. Gaps? Fill them in the remaining months.", lifeChallenge: "Update your personal growth log: skills gained, milestones hit, relationships deepened. Your life deserves the same tracking as your career.", memoryTrick: "A 5-star review is HARVESTED in December but PLANTED every single day. Don't start farming in November." },
  { day: 89, phase: 5, type: "deep", title: "The Bridge to Staff", content: "After 89 days, you ARE the best senior engineer on the team. Your craft is sharp. Your ownership is complete. Your designs are sound. Your shipping is reliable. Your leadership is evident. The Staff Mindset masterclass is now your natural next step.", workChallenge: "Write a self-assessment: where were you 89 days ago vs now? Score yourself on each phase. Present it to Arun as your growth trajectory for the review.", lifeChallenge: "Write a letter to Day-1-you: what you've learned, how you've changed, what you're proud of.", memoryTrick: "The gap between senior and staff isn't a CLIFF. It's a SLOPE. You've been climbing it for 89 days. The Staff masterclass takes you to the summit." },
  { day: 90, phase: 5, type: "practice", title: "GRADUATION: The Senior Excellence Manifesto", content: "90 days. 5 phases. One transformed senior engineer. You've mastered Craft, Ownership, Design, Shipping, and Leadership. You are READY.", workChallenge: "Write your 1-page Senior Excellence Manifesto: your craft standards, ownership principles, design philosophy, shipping checklist, and leadership style. This is your career constitution AND your 5-star review foundation.", lifeChallenge: "Share your 90-day journey publicly: LinkedIn, Motovlogs, or a conversation with a junior who needs to hear it. Your growth inspires theirs.", memoryTrick: "Day 1: you wrote code. Day 90: you craft solutions, own outcomes, design systems, ship reliably, and lead others. THAT is a senior engineer. Now go be a staff engineer." },
];

const typeLabel = (t) => t === "bite" ? "5-min Bite" : t === "deep" ? "Deep Dive" : "Practice Day";
const typeIcon = (t) => t === "bite" ? "⚡" : t === "deep" ? "🌊" : "🏋️";

export default function App() {
  const [dark, setDark] = useState(true);
  const [selPhase, setSelPhase] = useState(null);
  const [selDay, setSelDay] = useState(null);
  const [done, setDone] = useState(() => { try { return JSON.parse(localStorage.getItem("masterclass_senior-engineer_done")) || {}; } catch { return {}; } });
  const [vw, setVw] = useState("home");
  const ref = useRef(null);
  useEffect(() => { localStorage.setItem("masterclass_senior-engineer_done", JSON.stringify(done)); }, [done]);
  const toggle = (d) => setDone((p) => ({ ...p, [d]: !p[d] }));
  const ct = Object.values(done).filter(Boolean).length;
  const pct = Math.round((ct / 90) * 100);
  const phase = selPhase ? PHASES.find((p) => p.id === selPhase) : null;

  useEffect(() => { ref.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [selDay]);

  const m = dark ? "dark" : "light";
  const t = {
    bg: dark ? "#080a0c" : "#f9fafb",
    surface: dark ? "rgba(12,14,18,0.9)" : "rgba(255,255,255,0.9)",
    surfHov: dark ? "rgba(16,19,26,0.96)" : "rgba(247,249,251,0.97)",
    bdr: dark ? "rgba(45,212,191,0.07)" : "rgba(0,80,70,0.07)",
    txt: dark ? "#e5e7eb" : "#111827",
    sub: dark ? "#7c8594" : "#6b7280",
    mut: dark ? "#4b5260" : "#9ca3af",
    card: dark ? "rgba(10,12,16,0.75)" : "rgba(255,255,255,0.75)",
    ring: dark ? "#161a22" : "#e5e7eb",
    tag: dark ? "rgba(0,0,0,0.35)" : "rgba(0,60,50,0.035)",
    togBg: dark ? "rgba(45,212,191,0.06)" : "rgba(0,80,70,0.05)",
    hero: dark
      ? "radial-gradient(ellipse at 15% 0%, rgba(45,212,191,0.1), transparent 45%), radial-gradient(ellipse at 85% 0%, rgba(251,113,133,0.08), transparent 45%), radial-gradient(ellipse at 50% 90%, rgba(163,230,53,0.06), transparent 50%)"
      : "radial-gradient(ellipse at 15% 0%, rgba(13,148,136,0.04), transparent 45%), radial-gradient(ellipse at 85% 0%, rgba(225,29,72,0.03), transparent 45%), radial-gradient(ellipse at 50% 90%, rgba(101,163,13,0.025), transparent 50%)",
  };
  const hGrad = dark
    ? "linear-gradient(135deg, #2dd4bf 0%, #fb7185 25%, #818cf8 50%, #a3e635 75%, #fbbf24 100%)"
    : "linear-gradient(135deg, #0d9488 0%, #e11d48 25%, #4f46e5 50%, #65a30d 75%, #d97706 100%)";

  const Tog = () => (
    <button onClick={() => setDark(!dark)} style={{ position: "fixed", top: 14, right: 14, zIndex: 999, background: t.togBg, backdropFilter: "blur(14px)", border: `1px solid ${t.bdr}`, borderRadius: 40, padding: "7px 14px", cursor: "pointer", display: "flex", alignItems: "center", gap: 7, color: t.sub, fontSize: 12.5, fontFamily: "'JetBrains Mono', monospace", transition: "all 0.35s", letterSpacing: 0.5 }}>
      <span style={{ fontSize: 15 }}>{dark ? "☀️" : "🌙"}</span>{dark ? "Light" : "Dark"}
    </button>
  );

  if (vw === "home") {
    return (
      <div style={{ fontFamily: "'Outfit', sans-serif", background: t.bg, minHeight: "100vh", color: t.txt, transition: "background 0.45s, color 0.45s" }}>
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <style>{`@keyframes fu{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}.pc:hover{transform:translateY(-2px);box-shadow:${dark?"0 6px 28px rgba(0,0,0,0.5)":"0 6px 28px rgba(0,0,0,0.06)"}}.pc{transition:all 0.28s cubic-bezier(0.4,0,0.2,1)}`}</style>
        <Tog />
        <div style={{ position: "relative", padding: "52px 24px 28px", textAlign: "center", overflow: "hidden" }}>
          <div style={{ position: "absolute", inset: 0, background: t.hero, pointerEvents: "none" }} />
          <div style={{ position: "relative", zIndex: 1 }}>
            <div style={{ fontSize: 10.5, letterSpacing: 8, textTransform: "uppercase", fontFamily: "'JetBrains Mono', monospace", color: t.mut, marginBottom: 14 }}>90-Day Masterclass</div>
            <h1 style={{ fontFamily: "'Outfit', sans-serif", fontSize: "clamp(28px,5.5vw,46px)", fontWeight: 900, lineHeight: 1.05, margin: "0 0 6px", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>Senior Engineer Excellence</h1>
            <p style={{ fontSize: 12, color: t.sub, fontFamily: "'JetBrains Mono', monospace", margin: "10px 0 8px", fontWeight: 300, letterSpacing: 2.5 }}>craft / own / design / ship / lead</p>
            <p style={{ fontSize: 11, color: t.mut, margin: "0 0 28px", fontFamily: "'JetBrains Mono', monospace" }}>Master your level. Then transcend it.</p>
            <div style={{ display: "inline-flex", alignItems: "center", gap: 18, background: t.surface, border: `1px solid ${t.bdr}`, borderRadius: 18, padding: "16px 26px", backdropFilter: "blur(16px)" }}>
              <div style={{ position: "relative", width: 58, height: 58 }}>
                <svg width="58" height="58" viewBox="0 0 58 58">
                  <circle cx="29" cy="29" r="25" fill="none" stroke={t.ring} strokeWidth="3" />
                  <defs><linearGradient id="pg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#2dd4bf"/><stop offset="25%" stopColor="#fb7185"/><stop offset="50%" stopColor="#818cf8"/><stop offset="75%" stopColor="#a3e635"/><stop offset="100%" stopColor="#fbbf24"/></linearGradient></defs>
                  <circle cx="29" cy="29" r="25" fill="none" stroke="url(#pg)" strokeWidth="3" strokeDasharray={`${(pct/100)*157.1} 157.1`} strokeLinecap="round" transform="rotate(-90 29 29)" style={{ transition: "stroke-dasharray 0.7s cubic-bezier(0.4,0,0.2,1)" }} />
                </svg>
                <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 700, fontFamily: "'JetBrains Mono', monospace", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>{pct}%</div>
              </div>
              <div style={{ textAlign: "left" }}>
                <div style={{ fontSize: 26, fontWeight: 900 }}>{ct}<span style={{ fontSize: 14, color: t.mut, fontWeight: 400 }}> / 90</span></div>
                <div style={{ fontSize: 10, color: t.mut, fontFamily: "'JetBrains Mono', monospace", letterSpacing: 1.5 }}>days completed</div>
              </div>
            </div>
          </div>
        </div>
        <div style={{ padding: "8px 20px 48px", maxWidth: 720, margin: "0 auto" }}>
          {PHASES.map((p, i) => {
            const pl = ALL_LESSONS.filter(l => l.phase === p.id);
            const pc = pl.filter(l => done[l.day]).length;
            const ac = p.accent[m];
            return (
              <div key={p.id} className="pc" onClick={() => { setSelPhase(p.id); setVw("phase"); }} style={{ background: t.card, border: `1px solid ${t.bdr}`, borderRadius: 16, padding: "20px 22px", cursor: "pointer", marginBottom: 12, borderLeft: `3px solid ${ac}`, animation: `fu 0.55s ease ${i*0.1}s both`, position: "relative", overflow: "hidden", backdropFilter: "blur(10px)" }}>
                <div style={{ position: "absolute", top: -20, right: -20, width: 120, height: 120, background: `radial-gradient(circle, ${p.glow}, transparent 65%)`, pointerEvents: "none", opacity: dark ? 0.5 : 0.3 }} />
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", position: "relative" }}>
                  <div style={{ display: "flex", gap: 14, alignItems: "center" }}>
                    <span style={{ fontSize: 28 }}>{p.icon}</span>
                    <div>
                      <div style={{ fontSize: 10, color: ac, letterSpacing: 4, textTransform: "uppercase", fontFamily: "'JetBrains Mono', monospace", marginBottom: 4 }}>Phase {p.id} | {p.days}</div>
                      <div style={{ fontSize: 19, fontWeight: 800 }}>{p.title}</div>
                      <div style={{ fontSize: 12, color: t.sub, fontWeight: 400, marginTop: 2 }}>{p.subtitle}</div>
                    </div>
                  </div>
                  <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: t.mut, textAlign: "right", minWidth: 48 }}>
                    <span style={{ color: ac, fontWeight: 600 }}>{pc}</span>/{pl.length}
                  </div>
                </div>
                <div style={{ marginTop: 14, height: 2.5, background: t.ring, borderRadius: 3, overflow: "hidden" }}>
                  <div style={{ height: "100%", width: `${(pc/pl.length)*100}%`, background: `linear-gradient(90deg, ${ac}, ${ac}55)`, borderRadius: 3, transition: "width 0.5s ease" }} />
                </div>
                <div style={{ marginTop: 10, fontSize: 10, color: t.mut, padding: "6px 11px", background: t.tag, borderRadius: 8, fontFamily: "'JetBrains Mono', monospace", lineHeight: 1.5 }}>🧠 {p.mnemonic}</div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  if (vw === "phase" && phase) {
    const pl = ALL_LESSONS.filter(l => l.phase === phase.id);
    const ac = phase.accent[m];
    return (
      <div style={{ fontFamily: "'Outfit', sans-serif", background: t.bg, minHeight: "100vh", color: t.txt, transition: "background 0.45s, color 0.45s" }}>
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <style>{`@keyframes fu{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}@keyframes ex{from{opacity:0;max-height:0}to{opacity:1;max-height:900px}}`}</style>
        <Tog />
        <div style={{ position: "relative", overflow: "hidden" }}>
          <div style={{ position: "absolute", inset: 0, background: phase.gradient[m], opacity: dark ? 0.5 : 0.3, transition: "opacity 0.4s" }} />
          <div style={{ position: "relative", zIndex: 1, padding: "20px 20px 6px" }}>
            <button onClick={() => { setVw("home"); setSelPhase(null); setSelDay(null); }} style={{ background: t.togBg, border: `1px solid ${t.bdr}`, color: t.sub, padding: "7px 16px", borderRadius: 10, cursor: "pointer", fontSize: 12, fontFamily: "'JetBrains Mono', monospace" }}>{"←"} Back</button>
          </div>
          <div style={{ position: "relative", zIndex: 1, padding: "8px 24px 24px", textAlign: "center" }}>
            <span style={{ fontSize: 38 }}>{phase.icon}</span>
            <h2 style={{ fontSize: 30, fontWeight: 900, margin: "8px 0 4px" }}>Phase {phase.id}: {phase.title}</h2>
            <p style={{ color: t.sub, fontWeight: 400, margin: 0, fontSize: 13 }}>{phase.subtitle}</p>
            <p style={{ color: t.sub, fontSize: 12.5, marginTop: 10, maxWidth: 520, marginInline: "auto", lineHeight: 1.6 }}>{phase.description}</p>
            <div style={{ marginTop: 12, display: "inline-block", fontSize: 10.5, color: ac, padding: "6px 14px", background: `${ac}10`, borderRadius: 8, fontFamily: "'JetBrains Mono', monospace", border: `1px solid ${ac}20` }}>{phase.mnemonic}</div>
          </div>
        </div>
        <div style={{ padding: "12px 20px 48px", maxWidth: 720, margin: "0 auto" }}>
          {pl.map((l, i) => {
            const op = selDay === l.day;
            return (
              <div key={l.day} ref={op ? ref : null} style={{ marginBottom: 7, animation: `fu 0.4s ease ${i*0.03}s both` }}>
                <div onClick={() => setSelDay(op ? null : l.day)} style={{ background: op ? t.surfHov : t.card, border: `1px solid ${op ? `${ac}35` : t.bdr}`, borderRadius: op ? "13px 13px 0 0" : 13, padding: "13px 16px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", transition: "all 0.25s", backdropFilter: "blur(8px)" }}>
                  <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
                    <div onClick={e => { e.stopPropagation(); toggle(l.day); }} style={{ width: 24, height: 24, borderRadius: "50%", border: done[l.day] ? `2.5px solid ${ac}` : `2px solid ${t.bdr}`, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", background: done[l.day] ? `${ac}15` : "transparent", transition: "all 0.25s", flexShrink: 0 }}>
                      {done[l.day] && <span style={{ color: ac, fontSize: 11, fontWeight: 700 }}>{"✓"}</span>}
                    </div>
                    <div>
                      <div style={{ fontSize: 9.5, color: t.mut, fontFamily: "'JetBrains Mono', monospace", letterSpacing: 1.2 }}>Day {l.day} | {typeIcon(l.type)} {typeLabel(l.type)}</div>
                      <div style={{ fontSize: 14, fontWeight: 600, color: done[l.day] ? t.mut : t.txt, textDecoration: done[l.day] ? "line-through" : "none", marginTop: 2 }}>{l.title}</div>
                    </div>
                  </div>
                  <span style={{ color: t.mut, fontSize: 13, transform: op ? "rotate(180deg)" : "rotate(0)", transition: "transform 0.25s", flexShrink: 0 }}>{"▾"}</span>
                </div>
                {op && (
                  <div style={{ background: t.surfHov, border: `1px solid ${ac}35`, borderTop: "none", borderRadius: "0 0 13px 13px", padding: 20, animation: "ex 0.35s ease", overflow: "hidden", backdropFilter: "blur(8px)" }}>
                    <p style={{ color: t.txt, lineHeight: 1.8, margin: "0 0 18px", fontSize: 14, fontWeight: 300 }}>{l.content}</p>
                    {[
                      { label: "💼 Work Challenge (BHN)", text: l.workChallenge, c: dark ? ["rgba(45,212,191,0.05)","rgba(45,212,191,0.12)","#2dd4bf"] : ["rgba(13,148,136,0.04)","rgba(13,148,136,0.09)","#0d9488"] },
                      { label: "🌱 Life Challenge", text: l.lifeChallenge, c: dark ? ["rgba(129,140,248,0.05)","rgba(129,140,248,0.11)","#818cf8"] : ["rgba(79,70,229,0.04)","rgba(79,70,229,0.09)","#4f46e5"] },
                      { label: "🧠 Memory Trick", text: l.memoryTrick, c: dark ? ["rgba(251,191,36,0.05)","rgba(251,191,36,0.12)","#fbbf24"] : ["rgba(217,119,6,0.04)","rgba(217,119,6,0.1)","#d97706"], highlight: true },
                    ].map((s, si) => (
                      <div key={si} style={{ background: s.c[0], border: `1px solid ${s.c[1]}`, borderRadius: 11, padding: "13px 16px", marginBottom: si < 2 ? 10 : 0 }}>
                        <div style={{ fontSize: 9.5, color: s.c[2], letterSpacing: 2.5, textTransform: "uppercase", fontFamily: "'JetBrains Mono', monospace", marginBottom: 6 }}>{s.label}</div>
                        <p style={{ color: s.highlight ? (dark ? "#fef08a" : "#854d0e") : t.txt, fontSize: s.highlight ? 13.5 : 13, lineHeight: 1.6, margin: 0, fontWeight: s.highlight ? 500 : 300 }}>{s.text}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    );
  }
  return null;
}
