import { useState, useEffect, useRef } from "react";

const PHASES = [
  { id: 1, title: "MULTIPLY", subtitle: "From doer to force multiplier", days: "Day 1-21", icon: "\u00D7", description: "The #1 mindset shift: stop measuring YOUR output. Start measuring the output you ENABLE in others. Will Larson (Stripe/Uber): 'Staff is not senior but more. It's a different job.'", mnemonic: "L.E.V.E.R. - Lead through others, Enable teams, Vision over tasks, Elevate peers, Results at scale", gradient: { dark: "linear-gradient(160deg, #0a1628 0%, #0f2440 50%, #081420 100%)", light: "linear-gradient(160deg, #eef4fb 0%, #e2eef8 50%, #f0f6fc 100%)" }, accent: { dark: "#38bdf8", light: "#0369a1" }, glow: "rgba(56, 189, 248, 0.2)" },
  { id: 2, title: "ARCHITECT", subtitle: "Systems thinking at org scale", days: "Day 22-42", icon: "\u25E3", description: "Think beyond code. Design systems, processes, and architectures that outlive you. Evan King (Meta Staff in 3 yrs): 'Find simple solutions to complex problems.'", mnemonic: "S.C.A.L.E. - Systems over code, Cross-team impact, Abstractions, Long-term bets, Evolutionary design", gradient: { dark: "linear-gradient(160deg, #0d1a12 0%, #142e1e 50%, #0a1810 100%)", light: "linear-gradient(160deg, #eefbf2 0%, #dff5e8 50%, #f0fcf4 100%)" }, accent: { dark: "#4ade80", light: "#15803d" }, glow: "rgba(74, 222, 128, 0.2)" },
  { id: 3, title: "INFLUENCE", subtitle: "Lead without authority", days: "Day 43-63", icon: "\u2B50", description: "Staff engineers lead through influence, not title. Irina Stanescu (Google/Uber): 'It's not about you anymore. It's about the team.'", mnemonic: "T.R.U.S.T. - Technical credibility, Relationships, Understanding context, Sponsoring others, Transparent communication", gradient: { dark: "linear-gradient(160deg, #1a1008 0%, #2e1c0e 50%, #1a1408 100%)", light: "linear-gradient(160deg, #fdf6ed 0%, #faeedd 50%, #fef8f0 100%)" }, accent: { dark: "#fbbf24", light: "#b45309" }, glow: "rgba(251, 191, 36, 0.2)" },
  { id: 4, title: "STRATEGIZE", subtitle: "Connect tech to business", days: "Day 64-77", icon: "\u2693", description: "The gap between senior and staff: connecting technical decisions to business outcomes. Frame everything in impact, not effort.", mnemonic: "I.M.P.A.C.T. - Identify business value, Map technical decisions, Propose trade-offs, Align stakeholders, Communicate outcomes, Track results", gradient: { dark: "linear-gradient(160deg, #180a1c 0%, #2a1236 50%, #1a0c20 100%)", light: "linear-gradient(160deg, #f9eefe 0%, #f2e0fa 50%, #fbf2ff 100%)" }, accent: { dark: "#c084fc", light: "#7e22ce" }, glow: "rgba(192, 132, 252, 0.2)" },
  { id: 5, title: "LEGACY", subtitle: "Ship engineers, not just products", days: "Day 78-90", icon: "\u269B", description: "Google's staff saying: 'Senior engineers ship products. Staff engineers ship engineers.' Build the culture, grow the people, define the standards.", mnemonic: "G.R.O.W. - Give sponsorship, Raise the bar, Own the culture, Write the playbook", gradient: { dark: "linear-gradient(160deg, #1a0808 0%, #2e1010 50%, #1c0a0a 100%)", light: "linear-gradient(160deg, #fdf0f0 0%, #fae0e0 50%, #fef2f2 100%)" }, accent: { dark: "#f87171", light: "#dc2626" }, glow: "rgba(248, 113, 113, 0.2)" },
];

const ALL_LESSONS = [
  // PHASE 1: MULTIPLY (Day 1-21) - From doer to force multiplier
  { day: 1, phase: 1, type: "bite", title: "The Multiplier Mindset Shift", content: "Will Larson (Stripe/Uber): 'Becoming a Staff engineer is both a promotion and a job change.' You're no longer measured by YOUR code. You're measured by the code, decisions, and growth you ENABLE in others. Today's shift: think 'How can I make 5 people 20% faster?' instead of 'How can I be 100% faster myself?'", workChallenge: "Identify one bottleneck your team faces that ISN'T your code. A slow process, unclear docs, a confusing architecture decision. Fix THAT instead of writing another feature.", lifeChallenge: "In any group today (friends, family), be the person who helps OTHERS shine. Ask questions that let them talk. Help them look good.", memoryTrick: "Senior = 1x output. Staff = 5x through others. One cannonball vs five arrows." },
  { day: 2, phase: 1, type: "bite", title: "Stop Snacking, Start Feasting", content: "Will Larson's concept of 'snacking': doing easy, low-impact tasks that FEEL productive but don't move the needle. Staff engineers avoid snacks. They feast on the hard, ambiguous, high-impact problems nobody else wants to touch.", workChallenge: "Audit your last sprint. How many tasks were 'snacks' (quick fixes, minor refactors, small PRs) vs 'meals' (architectural decisions, unblocking others, cross-team problems)? Shift the ratio.", lifeChallenge: "In life too: are you snacking on easy wins (cleaning inbox, reorganizing notes) while avoiding the real meal (that hard conversation, that big goal)?", memoryTrick: "Snacks feel good NOW. Meals build muscle for LATER. Staff engineers eat meals." },
  { day: 3, phase: 1, type: "bite", title: "The Speed Multiplier", content: "Evan King (New Grad to Meta Staff in 3 years): 'Speed is the ultimate multiplier. That extra 30% of time when you're good at your core job unlocks everything else.' Master your basics so fast that you CREATE spare time for staff-level work.", workChallenge: "Time yourself on your routine tasks today: PR reviews, standup prep, email replies. Can you do each 20% faster without sacrificing quality? That recovered time = your multiplier time.", lifeChallenge: "What daily tasks can you systemize or speed up (morning routine, meal prep, commute decisions) to free time for growth?", memoryTrick: "Speed at the basics = OXYGEN for the advanced. You can't think strategically if you're gasping through the basics." },
  { day: 4, phase: 1, type: "bite", title: "Operate One Level Up", content: "Evan King (Meta): 'I wasn't just focused on my tasks. I was studying how my senior teammates approached problems, evaluated trade-offs, and thought about systems.' Don't wait for the title. Start operating at the next level NOW.", workChallenge: "Ask yourself before every task: 'How would Surendra (Principal) approach this?' Not just the code, but the FRAMING, the stakeholder communication, the trade-off analysis.", lifeChallenge: "In any situation, ask: 'What would the BEST version of me do here?' The gap between that answer and your action is your growth opportunity.", memoryTrick: "Don't dress for the job you HAVE. Think like the role you WANT. The title follows the mindset." },
  { day: 5, phase: 1, type: "bite", title: "Extreme Ownership", content: "Arpit (Staff Eng): 'The most important trait for Staff transition is extreme ownership. It means going beyond solving tasks to driving outcomes.' You own the OUTCOME, not just the ticket.", workChallenge: "Pick one project. Instead of completing your assigned tasks, own the entire outcome: timeline, risks, dependencies, communication, and delivery. Act as if you're the project lead.", lifeChallenge: "Apply extreme ownership to one personal goal. Don't just 'try'. Own every input: schedule, blockers, resources, accountability.", memoryTrick: "Ownership isn't blame. Ownership is saying: 'This succeeded or failed, and I take responsibility for what happened under my watch.'" },
  { day: 6, phase: 1, type: "deep", title: "The Four Staff Archetypes", content: "Will Larson defines 4 Staff archetypes: 1) Tech Lead: guides a team's approach. 2) Architect: designs cross-team systems. 3) Solver: dives into gnarly problems. 4) Right Hand: extends a leader's reach. Know which archetype fits YOU. At BHN, with your email centralization work spanning 5+ repos, you're likely a mix of Architect and Tech Lead.", workChallenge: "Map yourself: which archetype matches your current work? Which matches your ideal? Talk to Surendra about which archetype BHN needs most. Align your growth with that need.", lifeChallenge: "Think about your life roles too. Are you a solver (fix everything yourself) or a multiplier (help others solve)? Shift toward multiplier.", memoryTrick: "T.A.S.R. - Tech Lead, Architect, Solver, Right Hand. Know your archetype, play to your strengths." },
  { day: 7, phase: 1, type: "practice", title: "Week 1: Your Multiplier Audit", content: "Time to honestly assess: how much of your current work is staff-level vs senior-level?", workChallenge: "Categorize your last 2 weeks of work: Individual (wrote code alone), Collaborative (pair work, reviews), Multiplicative (unblocked others, improved processes, mentored). What's the ratio? Staff = 30%+ Multiplicative.", lifeChallenge: "Ask a colleague: 'What's the most helpful thing I've done for you recently?' If they can't answer, that's your signal.", memoryTrick: "If nobody notices your ABSENCE, you're not multiplying. A multiplier's absence creates a vacuum." },
  { day: 8, phase: 1, type: "bite", title: "Work On What Matters", content: "Will Larson's framework: avoid snacking (easy tasks), preening (high-visibility low-impact), and chasing ghosts (fixing non-problems). Instead, focus on existential issues (what could kill the project) and grow-the-pie work (expanding capacity for everyone).", workChallenge: "List your top 5 current tasks. Label each: Snack, Preen, Ghost, Existential, or Grow-the-pie. If most are snacks, reprioritize.", lifeChallenge: "Apply to your personal goals: are you snacking (easy YouTube edits) or feasting (learning video storytelling)?", memoryTrick: "S.P.G.E.G. - Snack, Preen, Ghost = avoid. Existential, Grow-pie = pursue." },
  { day: 9, phase: 1, type: "bite", title: "Unblocking > Building", content: "Norberto Lopes (incident.io): 'Senior+ engineers become bar keepers and bar raisers.' Your highest-leverage activity isn't building features. It's unblocking the 5 people who are stuck because of unclear requirements, missing context, or architectural ambiguity.", workChallenge: "Today, before writing any code, ask: 'Is anyone on my team blocked right now?' If yes, unblock them first. Track how much total output you enabled vs what you produced.", lifeChallenge: "In your personal life, who is 'blocked'? A friend needing advice? A family member needing help? Unblock one person today.", memoryTrick: "A blocked engineer costs 8 hours/day. Unblocking them in 30 minutes = 7.5 hours CREATED. That's 15x leverage." },
  { day: 10, phase: 1, type: "bite", title: "The Favor Economy", content: "Evan King (Meta): 'Build a favor economy.' Help others generously without keeping score. When you've helped 20 people, you'll have 20 allies who want to see you succeed. This is how sponsorship begins.", workChallenge: "Help 2 people today with zero expectation of return. Review their PR thoroughly, share a useful resource, explain a concept they're struggling with.", lifeChallenge: "Do a favor for someone who can do NOTHING for you. That's the test of genuine generosity vs transactional networking.", memoryTrick: "Favors are SEEDS. You plant 100, and maybe 30 grow into trees. But those 30 trees provide shade for your entire career." },
  { day: 11, phase: 1, type: "bite", title: "Making Others Successful", content: "From staffeng.com interviews: 'Staff engineers sponsor others.' Push others to present at meetings, give them credit for ideas, invite them to important discussions. Create space for others to shine.", workChallenge: "In your next team meeting, credit someone else's idea before sharing yours: 'Saurav had a great insight on X, and building on that...' Notice how it elevates both of you.", lifeChallenge: "On your YouTube channel, feature or shoutout another creator. On LinkedIn, share someone else's achievement. Lifting others lifts you.", memoryTrick: "A SPOTLIGHT has two effects: it illuminates the person AND the one holding it. Shine it on others." },
  { day: 12, phase: 1, type: "bite", title: "The 30% Rule", content: "Evan King (Meta): When you're fast at your core job, you free up ~30% of your time. That 30% is where ALL staff-level growth happens: reading code across repos, attending cross-team meetings, mentoring, writing proposals.", workChallenge: "Calculate: how much of your day is spent on 'expected' senior work? How much is spent on 'above and beyond' staff work? Target: 70/30 split.", lifeChallenge: "Apply the 30% rule to life: 70% routine, 30% growth. Are you spending your 30% on growth or on more routine?", memoryTrick: "The 30% is your RUNWAY. Without it, you never take off. With it, you fly above your current altitude." },
  { day: 13, phase: 1, type: "deep", title: "Energized Over Impactful", content: "Michelle Bu (Stripe): 'I've taken to using the word energized over impactful. Impactful feels company-centric. Energized is more inwards looking.' Do work that energizes you AND creates impact. That intersection is where sustainable staff-level contribution lives.", workChallenge: "List 5 things that ENERGIZE you at BHN and 5 that DRAIN you. How can you shift toward more energizing work while still driving impact? Discuss with Arun.", lifeChallenge: "Apply to Motovlogs: what content energizes you vs what you do because 'the algorithm wants it'? Sustainable growth comes from energized creation.", memoryTrick: "Energized work is RENEWABLE energy. Draining work is fossil fuel. One lasts forever. The other burns out." },
  { day: 14, phase: 1, type: "practice", title: "Week 2: The Leverage Log", content: "Start tracking your daily work through a leverage lens.", workChallenge: "For 5 days, log every work activity with its leverage type: Direct (you did it), Enabling (you helped someone do it), Multiplicative (you created something many people benefit from). Aim for 30%+ non-Direct.", lifeChallenge: "Track your personal time the same way. Direct (solo tasks), Enabling (helping others), Multiplicative (creating systems/habits that serve you repeatedly).", memoryTrick: "Your leverage log is your PORTFOLIO of staff-readiness. Show it. Don't tell it." },
  { day: 15, phase: 1, type: "bite", title: "Document Everything", content: "ADRs (Architecture Decision Records), RFCs, runbooks, onboarding guides. Documentation is the ultimate multiplier: you write once, it helps hundreds. Yet most engineers skip it because it 'feels like overhead.'", workChallenge: "Write ONE document today that will save your team time: a decision record for a recent architecture choice, a runbook for a common process, or an onboarding FAQ.", lifeChallenge: "Apply to personal life: document your routines, your financial plan, your content strategy. Written systems are repeatable systems.", memoryTrick: "Documentation is TIME TRAVEL. You spend 1 hour now to save 100 hours across 20 people in the future." },
  { day: 16, phase: 1, type: "bite", title: "The Glue Work Trap", content: "Tanya Reilly (author, staffeng.com foreword) warns about 'glue work': the invisible coordination, facilitation, and process work that keeps teams running but doesn't get recognized. Staff engineers do glue work deliberately AND ensure it's visible.", workChallenge: "Identify 3 pieces of 'glue work' you do that nobody sees. Make them visible: document them, mention them in standups, or propose they become part of the team process.", lifeChallenge: "Is there 'glue work' in your personal life that goes unrecognized? Acknowledge it in yourself and others.", memoryTrick: "Glue holds everything together. But invisible glue gets no credit. Make your glue VISIBLE or it won't count." },
  { day: 17, phase: 1, type: "bite", title: "No One Has All the Answers", content: "Evan King (Meta): 'No one has all the answers. Not the senior engineers, not the directors, not even the VPs.' Once you internalize this, you're free to share ideas broadly. Post proposals, challenge assumptions, question conventions.", workChallenge: "Share one idea or proposal publicly this week (Slack, Teams, or a short doc) that you've been holding back because 'someone more senior probably knows better.' Test it.", lifeChallenge: "Stop waiting for permission to have opinions. Share your perspective on something you care about, even if you're 'not the expert.'", memoryTrick: "If everyone waited to be an expert before speaking, NO ONE would ever speak first. Be the first voice." },
  { day: 18, phase: 1, type: "bite", title: "Positivity as a Multiplier", content: "Evan King (Meta): 'Happiness and positivity are wild accelerants in life, not just work.' Norberto Lopes (incident.io): 'Positivity and grit.' The staff engineers who get promoted are the ones who bring energy to problems, not complaints.", workChallenge: "For the next 3 days, reframe every problem statement. 'This is broken' becomes 'Here's an opportunity to improve X, and here's my proposal.' Watch how differently people engage.", lifeChallenge: "Positivity isn't denial. It's choosing to see the path forward instead of just the obstacle. Practice today.", memoryTrick: "Negativity is CONTAGIOUS. But so is positivity. A positive staff engineer is a SUPERCONDUCTOR for team energy." },
  { day: 19, phase: 1, type: "bite", title: "Navigating Without a Map", content: "Norberto Lopes (incident.io): 'Ability to navigate without a map.' Staff engineers face ambiguity daily. There's no ticket, no clear requirement, no roadmap. They CREATE the map.", workChallenge: "Identify one ambiguous problem at BHN that nobody owns. Don't wait for it to be assigned. Write a 1-page proposal: what the problem is, why it matters, and your suggested approach.", lifeChallenge: "In life, what's an ambiguous situation you've been waiting for clarity on? Create your own clarity. Write a plan.", memoryTrick: "Senior engineers follow the GPS. Staff engineers DRAW the map. When there's no road, build one." },
  { day: 20, phase: 1, type: "deep", title: "Company > Function > Team > Individual", content: "Norberto Lopes (incident.io): The priority stack. Staff engineers optimize for the COMPANY first, then their function, then their team, then themselves. This is the hardest mindset shift: sometimes your team's 'best' choice isn't the company's best.", workChallenge: "Think about your email centralization project. Is it optimized for YOUR team's convenience or the COMPANY's long-term health? Where might those diverge? Address the gap.", lifeChallenge: "Apply this hierarchy to life: Community > Family > Friends > Self. When you serve the wider circle first, everything else falls into place.", memoryTrick: "Company > Function > Team > Self. Like oxygen masks in reverse: secure the BIGGEST plane first." },
  { day: 21, phase: 1, type: "practice", title: "Phase 1 Graduation: The Multiplier Portfolio", content: "21 days of multiplier training. Time to demonstrate your shift.", workChallenge: "Write a 1-page 'Multiplier Impact Report': 5 instances where you created value THROUGH others this month. This is direct evidence for your 5-star review under BeAccountable and BeInnovative.", lifeChallenge: "Ask 3 colleagues: 'How have I helped you be more effective recently?' Their answers are your real portfolio.", memoryTrick: "Phase 1 done. You think in LEVERAGE now. Phase 2: think in SYSTEMS." },

  // PHASE 2: ARCHITECT (Day 22-42)
  { day: 22, phase: 2, type: "bite", title: "Think in Systems, Not Features", content: "Staff engineers don't think about the next feature. They think about the SYSTEM that enables the next 100 features. Your email centralization isn't a feature. It's a platform that enables every future communication need.", workChallenge: "Reframe your current project: what SYSTEM are you building, and what does it enable for the next 2 years? Write it as a 3-line vision statement.", lifeChallenge: "Think about your daily routines as SYSTEMS. A morning routine isn't a task. It's a system that enables a productive day. Design your systems.", memoryTrick: "Features are FLOWERS. Systems are GARDENS. Staff engineers build gardens." },
  { day: 23, phase: 2, type: "bite", title: "Cross-Team Thinking", content: "The #1 difference between senior and staff at Uber: 'Senior engineers own complex team-level projects. Staff engineers own complex, organization-wide projects.' Your impact boundary expands from your team to the organization.", workChallenge: "Identify how your email centralization affects teams OUTSIDE yours. Map at least 3 teams that will benefit or be impacted. Have you talked to them?", lifeChallenge: "In your social circles, think beyond your immediate group. How can you connect people from different circles who would benefit from knowing each other?", memoryTrick: "Senior = team telescope. Staff = organization satellite. Same sky, vastly different view." },
  { day: 24, phase: 2, type: "bite", title: "The RFC Culture", content: "At Google, Meta, and Stripe, major decisions go through RFCs (Request for Comments). This isn't bureaucracy. It's how staff engineers get buy-in, surface risks, and build alignment BEFORE writing code.", workChallenge: "Write an RFC for your next significant technical decision. Structure: Context, Problem, Proposed Solution, Alternatives Considered, Trade-offs, Migration Plan. Share it for review.", lifeChallenge: "Before any big personal decision, write a personal RFC. The act of writing forces clarity that thinking alone doesn't provide.", memoryTrick: "An RFC is a CONVERSATION on paper. It invites input before commitment. That's how alignment happens." },
  { day: 25, phase: 2, type: "bite", title: "Evolutionary Architecture", content: "Staff engineers design systems that EVOLVE rather than systems that are 'perfect.' Your Strangler Fig Pattern for email centralization is exactly this: evolutionary, incremental, reversible.", workChallenge: "For your current design, ask: 'Can we reverse this decision in 6 months if we're wrong?' If not, find a way to make it reversible. Build escape hatches.", lifeChallenge: "Design your goals with evolution in mind. Don't commit to rigid 5-year plans. Build 90-day experiments with review points.", memoryTrick: "Perfect architectures are BRITTLE. Evolutionary architectures are ANTIFRAGILE. Build to adapt, not to last." },
  { day: 26, phase: 2, type: "bite", title: "Technical Debt as Strategy", content: "Staff engineers don't eliminate all tech debt. They manage it strategically. Some debt is worth carrying (fast delivery). Some is toxic (blocks everything). Knowing the difference is an art.", workChallenge: "Map your team's tech debt into 3 buckets: Strategic (worth keeping), Tactical (fix when convenient), Toxic (fix NOW or it compounds). Present this to your team.", lifeChallenge: "You have 'life debt' too: postponed decisions, avoided conversations, skipped maintenance. Which are toxic? Address those first.", memoryTrick: "Tech debt is like financial debt. Mortgage = strategic. Credit card at 24% = toxic. Know your interest rates." },
  { day: 27, phase: 2, type: "bite", title: "Thinking in Trade-offs", content: "Addy Osmani (Google): Staff engineers think in trade-offs, not absolutes. 'Microservices vs monolith' is the wrong question. 'Given our team size, growth rate, and operational maturity, which approach has better trade-offs?' is the right one.", workChallenge: "For every technical opinion you have this week, add the phrase 'given our constraints.' 'We should use SQS GIVEN our existing AWS infrastructure and team familiarity.' Context changes everything.", lifeChallenge: "Apply trade-off thinking to personal decisions. 'Should I learn X?' becomes 'Given my goals, time, and energy, does X have the best trade-off ratio?'", memoryTrick: "Absolutes are for beginners. Trade-offs are for experts. The word 'GIVEN' is the staff engineer's secret weapon." },
  { day: 28, phase: 2, type: "practice", title: "Week 4: Architecture Review", content: "Practice the staff-level skill of reviewing architecture, not just code.", workChallenge: "Pick any system at BHN (not yours). Read its architecture. Write a 1-page review: strengths, risks, and one improvement suggestion. Share it with the team. This is how you build cross-team credibility.", lifeChallenge: "Review your personal 'architecture': how your time, energy, and attention flow through your week. Where are the bottlenecks?", memoryTrick: "Code reviews check SYNTAX. Architecture reviews check SANITY. Staff engineers do both." },
  { day: 29, phase: 2, type: "bite", title: "The Migration Mindset", content: "Most staff-level projects are MIGRATIONS: moving from old to new, safely, incrementally, without breaking production. Your email centralization is exactly this. Mastering migrations = mastering staff work.", workChallenge: "Create a migration checklist for your email centralization: rollback plan, feature flags, monitoring, canary deployment, communication plan. Make it reusable for future migrations.", lifeChallenge: "Life transitions are migrations too. New habits, new roles, new relationships. Apply the same safety nets: go gradually, have rollback plans, monitor progress.", memoryTrick: "A migration is a TIGHTROPE walk. The net below is your rollback plan. Never walk without a net." },
  { day: 30, phase: 2, type: "bite", title: "Observability-First Design", content: "Staff engineers build systems that TELL you when they're broken, not systems you have to constantly CHECK. Your New Relic dashboards are a start. But observability should be built into the architecture, not bolted on.", workChallenge: "For your email centralization, define the 5 key metrics that tell you 'this system is healthy' without anyone looking. Automated alerts, not manual checks.", lifeChallenge: "Build 'observability' into your personal goals: monthly check-ins, progress metrics, health indicators. If your system is silent, you don't know it's working.", memoryTrick: "A system without observability is a car without a dashboard. You're driving blind at 120 km/h." },
  { day: 31, phase: 2, type: "bite", title: "Design for the Next Team", content: "The code you write will be maintained by someone who doesn't know you, in a context you can't predict. Staff engineers design for THAT person. Clear interfaces, good documentation, obvious naming, defensive error handling.", workChallenge: "Review your email centralization code. Would a new engineer joining next month understand it without asking you? If not, improve the self-documenting aspects.", lifeChallenge: "In your Motovlogs content, think about future viewers. Will your videos make sense to someone discovering your channel 2 years from now?", memoryTrick: "Write code for STRANGERS. They'll thank the stranger who wrote it for them. That stranger is future-you or future-nobody." },
  { day: 32, phase: 2, type: "bite", title: "The Technical Vision Doc", content: "Staff engineers write technical vision documents: 'Here's where our system is today. Here's where it should be in 2 years. Here's the path between.' This is the highest-leverage document you can write.", workChallenge: "Write a 2-page technical vision for email communication at BHN. Current state, ideal state, milestones. Share with Surendra for feedback. This is your staff-level artifact.", lifeChallenge: "Write a personal vision doc: where you are now, where you want to be in 2 years, and the milestones between. Clarity drives action.", memoryTrick: "A vision doc is a NORTH STAR for your team. Without it, everyone navigates by their own compass. With it, everyone walks together." },
  { day: 33, phase: 2, type: "deep", title: "Wardley Mapping Your Domain", content: "Will Larson's current focus: Wardley Mapping. A technique to visualize your technology landscape, identify what's commodity vs custom, and make strategic bets. Map your email system: what should you BUILD vs BUY vs USE?", workChallenge: "Create a simple Wardley Map of your email stack: which components are custom-built, which are commodity (AWS SES, SQS), and which are in between? This reveals where to invest.", lifeChallenge: "Map your skills the same way: which are commodity (everyone has them), which are rare, which are your unique differentiator?", memoryTrick: "A Wardley Map is a TREASURE MAP for where to invest your engineering effort. Don't dig where there's no gold." },
  { day: 34, phase: 2, type: "bite", title: "API Design as Communication", content: "Your APIs are your system's language. A well-designed API communicates intent, prevents misuse, and enables users without documentation. This is architectural empathy.", workChallenge: "Review the APIs you've designed recently. Would a developer from another team understand them without reading docs? If not, rename, restructure, or add better error messages.", lifeChallenge: "Your personal 'API' is how people interact with you. Are you clear about what you need, what you offer, and how to engage with you?", memoryTrick: "An API is a HANDSHAKE between systems. A good handshake is firm, clear, and communicates intent instantly." },
  { day: 35, phase: 2, type: "practice", title: "Week 5: The Architecture Kata", content: "Practice designing systems at scale, not just components.", workChallenge: "Pick a system design problem (rate limiter, notification system, URL shortener). Design it in 45 minutes covering: requirements, scale estimation, component design, data flow, trade-offs. Do this weekly.", lifeChallenge: "Design a 'life system' on paper: your weekly schedule as an architecture diagram. Inputs, outputs, bottlenecks, feedback loops.", memoryTrick: "Architecture is a MUSCLE. System design katas are the GYM. Weekly practice beats annual cramming." },
  { day: 36, phase: 2, type: "bite", title: "Failure Mode Thinking", content: "Staff engineers ask: 'How will this BREAK?' before asking 'How will this WORK?' Every system will fail. The question is: will it fail gracefully or catastrophically?", workChallenge: "For your SQS email pipeline, list 5 failure scenarios: SQS down, consumer crash, BNS timeout, duplicate messages, poison messages. Write the recovery plan for each.", lifeChallenge: "For your important goals, plan for failure: what's your backup if the primary plan doesn't work? Having Plan B reduces anxiety and increases confidence.", memoryTrick: "Optimists HOPE it works. Pessimists FEAR it fails. Staff engineers PLAN for both." },
  { day: 37, phase: 2, type: "bite", title: "Simplicity as Sophistication", content: "Evan King (Meta): 'Focus on simple solutions to complex problems.' The best architecture isn't the most complex. It's the simplest one that solves the problem. Complexity is easy. Simplicity is hard.", workChallenge: "Look at your current architecture. Can you remove a component? Merge two services? Simplify a flow? Often the best optimization is DELETION.", lifeChallenge: "What can you REMOVE from your life to make it simpler? A commitment, an app, a habit that adds complexity without value?", memoryTrick: "A junior adds code to solve problems. A senior adds abstractions. A staff engineer REMOVES complexity. That's the highest skill." },
  { day: 38, phase: 2, type: "bite", title: "Technical Decision Quality", content: "Staff engineers are judged by the QUALITY of their technical decisions, not the quantity of their code. One good architectural decision is worth more than 50 PRs.", workChallenge: "Start a Decision Journal for technical decisions: What I decided, Why, What alternatives I rejected, What trade-offs I accepted. Review monthly to calibrate your judgment.", lifeChallenge: "Apply decision journaling to life. Track 3 decisions this week. Review next month. Are you getting better at deciding?", memoryTrick: "Code is EXPENDABLE. Decisions are DURABLE. Your decisions outlive your code by years." },
  { day: 39, phase: 2, type: "bite", title: "The Platform Mindset", content: "Staff engineers think in PLATFORMS, not projects. A project solves one problem. A platform solves a CLASS of problems. Your email centralization should be a platform that makes ANY future communication need trivial.", workChallenge: "Ask: 'If 3 new communication channels were added next year (push notifications, SMS, in-app), could my system handle them with minimal changes?' Design for that extensibility.", lifeChallenge: "Build personal PLATFORMS: a content creation system (not one-off videos), a learning system (not random courses), a health system (not crash diets).", memoryTrick: "Projects are TENTS. Platforms are BUILDINGS. Tents are fast to set up but temporary. Buildings take longer but house many." },
  { day: 40, phase: 2, type: "deep", title: "Building Your Architecture Playbook", content: "After 19 days of architectural thinking, compile YOUR playbook: the patterns, principles, and frameworks you use for system design.", workChallenge: "Write your personal 'Architecture Principles' document: 5-7 principles that guide every system you design. Example: 'Design for failure', 'Prefer boring technology', 'Measure before optimizing'.", lifeChallenge: "Write life design principles: 'Simplicity over complexity', 'Systems over goals', 'Energy over discipline'.", memoryTrick: "A playbook is your CHESS OPENING LIBRARY. You don't reinvent your approach every game. You refine it." },
  { day: 41, phase: 2, type: "bite", title: "The Cost of Wrong Abstractions", content: "Staff engineers know that the wrong abstraction is MORE expensive than no abstraction. Don't abstract prematurely. Wait until you see the pattern 3 times, then abstract.", workChallenge: "Review one abstraction in your codebase. Is it helping or hurting? Does it match how the system actually works, or does it force awkward workarounds?", lifeChallenge: "In life, are you over-abstracting? Creating complex systems for simple problems? Sometimes the direct approach is best.", memoryTrick: "Rule of Three: see the pattern ONCE (note it), TWICE (interesting), THREE times (now abstract). Never before." },
  { day: 42, phase: 2, type: "practice", title: "Phase 2 Graduation: The Technical Vision", content: "Demonstrate your architectural thinking.", workChallenge: "Present your technical vision doc (from Day 32) to Surendra or your team. Get feedback. Iterate. A polished technical vision is the #1 artifact for staff promotion packets.", lifeChallenge: "Share your personal vision with someone who will hold you accountable.", memoryTrick: "Phase 2 done. You think in SYSTEMS and PLATFORMS. Phase 3: learn to INFLUENCE without authority." },

  // PHASE 3: INFLUENCE (Day 43-63)
  { day: 43, phase: 3, type: "bite", title: "Influence is Not Authority", content: "Irina Stanescu (Google/Uber): 'Leadership is not about your role. It's about the ability to inspire and empower people.' Staff engineers have zero direct reports. They lead through credibility, relationships, and trust.", workChallenge: "Identify one change you want to make that requires buy-in from people who don't report to you. How will you persuade them? Not 'tell' them. Persuade.", lifeChallenge: "Think of a situation where you want someone to change behavior. Can you influence without demanding? That's the skill.", memoryTrick: "Authority says 'DO this.' Influence says 'Here's WHY this matters to YOU.' One compels. The other inspires." },
  { day: 44, phase: 3, type: "bite", title: "Build Technical Credibility First", content: "You can't influence without credibility. And credibility comes from consistently demonstrating deep technical knowledge, sound judgment, and reliable delivery. No shortcuts.", workChallenge: "Ask yourself: do people trust my technical judgment? When I say 'this approach is risky', do they believe me? If not, what specific credibility gap do I need to fill?", lifeChallenge: "Credibility applies everywhere. On your YouTube channel, do viewers trust your recommendations? Your credibility IS your brand.", memoryTrick: "Credibility is a BANK. Deposits = correct calls, delivered promises. Withdrawals = wrong calls, broken promises. Keep a positive balance." },
  { day: 45, phase: 3, type: "bite", title: "The Sponsorship Ladder", content: "Will Larson: 'Sponsorship is a person who brings your name up in the room.' You need a sponsor AND you need to BE a sponsor. At BHN, Surendra is your natural sponsor. But are you sponsoring anyone?", workChallenge: "Identify one junior or mid-level engineer. Sponsor them: recommend them for a stretch project, mention their good work in a meeting, or invite them to a discussion above their usual scope.", lifeChallenge: "In your personal network, who are you actively helping grow? Being a sponsor is a character trait, not just a work tactic.", memoryTrick: "Sponsorship is ELEVATOR access. A sponsor says 'this person should be in THIS room.' Be the elevator operator for others." },
  { day: 46, phase: 3, type: "bite", title: "Managing Your Manager", content: "Your relationship with Arun is your most important professional relationship. Keep him informed, aligned, and never surprised. A staff engineer's authority comes from alignment with their manager.", workChallenge: "Prepare a weekly 'no surprises' update for Arun: wins, risks, decisions needed, and your growth areas. 5 lines max. Proactive communication builds trust.", lifeChallenge: "Apply 'managing up' to any authority relationship. Proactive communication prevents misunderstandings.", memoryTrick: "A surprised manager is an UNSUPPORTIVE manager. No surprises = full support." },
  { day: 47, phase: 3, type: "bite", title: "Storytelling for Engineers", content: "David Grizzanti (InfoQ): 'Frame technical decisions in business terms.' Don't say 'We need to refactor the email queue.' Say 'We're losing 3% of customer communications due to silent failures. This fix recovers $X in engagement.'", workChallenge: "Rewrite your email centralization proposal in BUSINESS language. What's the cost of the current state? What's the value of the new state? Numbers, not just architecture.", lifeChallenge: "On LinkedIn and Motovlogs, frame your stories in terms of VALUE to the viewer, not just what happened to you.", memoryTrick: "Engineers speak in SYSTEMS. Business speaks in OUTCOMES. The translator between them is the staff engineer." },
  { day: 48, phase: 3, type: "deep", title: "Navigating Organizational Politics", content: "Politics isn't dirty. It's how organizations make decisions. Staff engineers understand the political landscape: who decides, who influences, who blocks, and what motivates each.", workChallenge: "Map BHN's decision-making landscape for your initiative: who needs to approve, who can block, who influences the approver, and what each person cares about. Design your communication for EACH audience.", lifeChallenge: "Every social group has politics. Understanding them isn't manipulation. It's wisdom.", memoryTrick: "Ignoring politics doesn't make you noble. It makes you INVISIBLE. Understand the game, play it with integrity." },
  { day: 49, phase: 3, type: "practice", title: "Week 7: The Influence Experiment", content: "Practice influence skills this week.", workChallenge: "Choose one improvement you want to champion. Create a 1-page proposal. Share it with 3 stakeholders for feedback BEFORE presenting it formally. Build buy-in through consultation, not presentation.", lifeChallenge: "Try influencing one person's decision this week through questions, not statements. Guide them to the conclusion rather than pushing it.", memoryTrick: "Consultation BEFORE presentation = influence. Presentation WITHOUT consultation = resistance." },
  { day: 50, phase: 3, type: "bite", title: "Writing Persuasive Proposals", content: "The P.S.I.E. framework Surendra taught you is gold: Problem, Solution, Impact, Effort. Every proposal should answer: What's broken? What's the fix? What happens if we fix it? What does it cost?", workChallenge: "Take your next proposal and score it on P.S.I.E. clarity: Is the problem compelling? Is the solution concrete? Is the impact quantified? Is the effort realistic? Strengthen the weakest section.", lifeChallenge: "Use P.S.I.E. for any personal pitch: a travel plan, a career move, a content strategy. Structure persuades.", memoryTrick: "P.S.I.E. is your persuasion ENGINE. Fuel it with data, and it runs on its own." },
  { day: 51, phase: 3, type: "bite", title: "Building Alliances Across Teams", content: "Staff engineers build bridges between silos. The person you help in the platform team today becomes your ally when you need their support tomorrow. Relationships are infrastructure.", workChallenge: "Schedule a 15-minute coffee chat (virtual or in-person) with someone from a different team at BHN. Learn about their challenges. Find one area of shared interest.", lifeChallenge: "Build relationships outside your usual circle. Connect with someone in a different industry, interest group, or community.", memoryTrick: "Alliances are BRIDGES between islands. Build enough bridges, and you have a CONTINENT of influence." },
  { day: 52, phase: 3, type: "bite", title: "Presenting to Leadership", content: "When presenting to directors or VPs, remember: they have 10 minutes of attention. Lead with the recommendation. Support with data. End with the ask. No preamble, no journey, no backstory.", workChallenge: "Practice your email centralization pitch in the 'executive elevator' format: 30 seconds for the recommendation, 60 seconds for the evidence, 30 seconds for the ask. 2 minutes total.", lifeChallenge: "Practice 'executive communication' in daily life. When someone asks what you're working on, answer in one powerful sentence, not a 5-minute monologue.", memoryTrick: "Leaders are SPEED READERS. Give them the headline. They'll ask for the article if interested." },
  { day: 53, phase: 3, type: "bite", title: "Disagreeing Productively", content: "Staff engineers disagree often. But they disagree with DATA, propose ALTERNATIVES, and commit to decisions even when overruled. 'Disagree and commit' (Amazon) is a staff-level superpower.", workChallenge: "Next time you disagree with a technical decision, write a 3-line message: 'My concern is [X]. The data suggests [Y]. My alternative proposal is [Z].' No emotion. Pure signal.", lifeChallenge: "Practice disagreeing productively in personal conversations. State your position, show your reasoning, and respect the final decision.", memoryTrick: "Productive disagreement is a GIFT to the team. Unproductive disagreement is a TAX. Know the difference by the presence of alternatives." },
  { day: 54, phase: 3, type: "bite", title: "Building Consensus", content: "Staff engineers don't force decisions. They build consensus through individual conversations, shared data, and inclusive decision-making. By the time a decision is 'made', everyone already agrees.", workChallenge: "Before your next team decision, have individual conversations with 3 key stakeholders. Understand their concerns. Incorporate their input. Present a solution that everyone partially owns.", lifeChallenge: "In group decisions (travel plans, dinner choices, project directions), practice building consensus instead of dominating or withdrawing.", memoryTrick: "Consensus isn't EVERYONE agrees. It's everyone UNDERSTANDS and can COMMIT. Build understanding, and commitment follows." },
  { day: 55, phase: 3, type: "deep", title: "Visibility Without Self-Promotion", content: "Staff engineers need to be visible, but not in a 'look at me' way. Write RFCs, present at tech talks, write internal blog posts, mentor publicly. Let your WORK be visible, not your ego.", workChallenge: "Plan one visibility action this month: present at a BHN tech talk, write an internal blog about your learnings, or lead a knowledge-sharing session. Focus on TEACHING, not showcasing.", lifeChallenge: "On LinkedIn and YouTube, share INSIGHTS and LESSONS, not achievements. Teaching is the most authentic form of visibility.", memoryTrick: "Self-promotion says 'Look what I did.' Visibility through teaching says 'Look what I learned.' The second one attracts. The first one repels." },
  { day: 56, phase: 3, type: "practice", title: "Week 8: The Stakeholder Map", content: "Build your influence infrastructure.", workChallenge: "Create a stakeholder map for your current initiative: Who decides? Who influences? Who's affected? Who might resist? For each, write: their concern, their motivation, and how you'll address them.", lifeChallenge: "Map your personal stakeholders: who are the 10 most important relationships in your life? Are you investing in each appropriately?", memoryTrick: "A stakeholder map is a RELATIONSHIP GPS. Without it, you're navigating influence blindly." },
  { day: 57, phase: 3, type: "bite", title: "Giving Hard Feedback Upward", content: "One of the hardest staff skills: giving honest feedback to people above you. 'I think our current approach to X has risks we're not discussing.' Done with data and respect, this is incredibly valuable.", workChallenge: "Is there a risk or concern you've been hesitant to raise with Arun or leadership? Prepare a fact-based message and share it. Use: 'I've noticed [observation]. I'm concerned about [risk]. My suggestion is [alternative].'", lifeChallenge: "Practice giving upward feedback in any relationship. It builds trust and respect when done with care.", memoryTrick: "Silence in the face of risk isn't LOYALTY. It's LIABILITY. Speak up with data, and you become invaluable." },
  { day: 58, phase: 3, type: "bite", title: "The Art of Saying 'Let's Revisit'", content: "When a decision is going wrong but momentum is strong, staff engineers say: 'Can we revisit this with updated data?' It's non-threatening, data-driven, and gives everyone an exit ramp from a bad path.", workChallenge: "Practice this phrase in your next meeting where you sense a wrong direction: 'I want to suggest we revisit X in 2 weeks with fresh data. Here's what I'd like us to measure.'", lifeChallenge: "In personal conflicts, 'Can we revisit this when we've both had time to think?' is a powerful de-escalation tool.", memoryTrick: "'Let's revisit' is a SPEED BRAKE on a moving train. It doesn't stop progress. It prevents derailment." },
  { day: 59, phase: 3, type: "bite", title: "Setting Cultural Norms", content: "David Grizzanti (InfoQ): 'Culture is a multiplier. How you review code, treat feedback, build consensus, and respond to conflict sets the tone for everyone.' Staff engineers SET culture through behavior, not proclamations.", workChallenge: "Pick one cultural norm you want to establish: thorough PR reviews, blameless retros, documentation-first, or async-first communication. Model it consistently for 30 days. It'll catch on.", lifeChallenge: "What cultural norms do you want in your home, friend group, or online community? Model them. Culture is caught, not taught.", memoryTrick: "Culture is the SHADOW of behavior. Whatever you DO consistently, others will COPY eventually." },
  { day: 60, phase: 3, type: "bite", title: "The Room Where It Happens", content: "Staff engineers need to be 'in the room where it happens.' Not every room. The RIGHT rooms. Architecture reviews, roadmap planning, incident debriefs. If you're not there, decisions happen without your input.", workChallenge: "Identify 2 recurring meetings at BHN where important technical decisions are made. Are you in them? If not, ask Arun or Surendra to include you. Prepare to add value, not just observe.", lifeChallenge: "In life, which 'rooms' are you missing? Industry events, community gatherings, online forums? Be present where decisions happen.", memoryTrick: "If you're not in the room, you're on the MENU, not at the TABLE. Get in the room." },
  { day: 61, phase: 3, type: "bite", title: "Writing for Influence", content: "At staff level, your writing is one of your most powerful tools. Well-written RFCs, proposals, and incident reports travel further than any meeting. Write to influence, not just to inform.", workChallenge: "Write a 1-page internal 'memo' about a topic you're passionate about (observability, email architecture, CI/CD improvement). Share it widely. Good writing creates influence at scale.", lifeChallenge: "Your LinkedIn posts, YouTube descriptions, and public writing shape how the world sees you. Write with influence in mind.", memoryTrick: "A well-written document is a MISSIONARY. It goes places you can't, speaks when you're not there, and persuades on your behalf." },
  { day: 62, phase: 3, type: "deep", title: "Building Your Influence Playbook", content: "Compile your influence toolkit: how you persuade, build consensus, present to leadership, and navigate politics.", workChallenge: "Write your personal 'Influence Playbook': your P.S.I.E. template, stakeholder map approach, executive pitch format, and consensus-building process. Keep it and refine it.", lifeChallenge: "Review your influence across all domains: work, content creation, personal relationships. Where are you strongest? Where do you need growth?", memoryTrick: "Influence is a CRAFT, not a talent. Like any craft, it improves with deliberate practice and a good playbook." },
  { day: 63, phase: 3, type: "practice", title: "Phase 3 Graduation: The Influence Portfolio", content: "21 days of influence training. Demonstrate your growth.", workChallenge: "Document 3 instances where you influenced a decision without authority. Include: the situation, your approach, and the outcome. This is powerful evidence for your 5-star review under BeOneTeam.", lifeChallenge: "Ask a colleague: 'Do you trust my technical judgment? Would you follow my recommendation on a hard problem?' Their honest answer is your influence score.", memoryTrick: "Phase 3 done. You can MULTIPLY, ARCHITECT, and INFLUENCE. Phase 4: connect TECH to BUSINESS." },

  // PHASE 4: STRATEGIZE (Day 64-77)
  { day: 64, phase: 4, type: "bite", title: "Think Business, Speak Business", content: "The biggest gap between senior and staff: staff engineers frame technical decisions in business terms. Not 'This API has 500ms p99 latency' but 'This latency causes 12% of users to abandon the flow, costing $X/month.'", workChallenge: "Take your top 3 current technical improvements. For each, write the business impact in one sentence. If you can't, you don't understand the business value well enough.", lifeChallenge: "Even for Motovlogs: don't just track views. Track what VALUE you're creating: community, inspiration, travel knowledge. Frame everything in value.", memoryTrick: "Engineers speak in METRICS. Business speaks in MONEY and USERS. Learn to translate between them fluently." },
  { day: 65, phase: 4, type: "bite", title: "The Product Mindset", content: "Gregor Ojstersek (CTO): 'The expectation will be to be good technically AND good in product/business.' Staff engineers understand what users need, not just what tickets say. They question requirements, not just implement them.", workChallenge: "For your next feature request, ask: 'What user problem does this solve? How will we know it worked? Is this the simplest solution?' These questions elevate you from executor to partner.", lifeChallenge: "For your content: don't just make what YOU want. Ask: 'What does my AUDIENCE need? How will I know it resonated?'", memoryTrick: "A coder builds what's asked. An engineer builds what's needed. A staff engineer challenges what's assumed." },
  { day: 66, phase: 4, type: "bite", title: "Connecting Technical Debt to Revenue", content: "Business leaders don't care about 'tech debt.' They care about velocity, reliability, and cost. Translate: 'Tech debt slows us by 30%, which means feature delivery takes 6 weeks instead of 4, delaying revenue by X.'", workChallenge: "Pick your top tech debt item. Write its business impact in dollars, time, or risk. Present it to Arun as a business case, not a technical complaint.", lifeChallenge: "Translate your personal pain points into impact terms too. 'I'm tired' becomes 'My energy level affects my decision quality, relationships, and career growth.'", memoryTrick: "Tech debt in BUSINESS language gets FUNDED. Tech debt in ENGINEER language gets ignored." },
  { day: 67, phase: 4, type: "bite", title: "Risk Assessment as a Service", content: "Staff engineers are the team's risk radar. They see technical risks that others miss: scalability cliffs, security gaps, single points of failure, vendor lock-in. Surfacing risks before they materialize is high-value work.", workChallenge: "Run a 15-minute risk assessment of your current sprint or project: what could go wrong? What's the probability? What's the impact? Share it with the team.", lifeChallenge: "Assess personal risks: career dependency on one company, health risks from lifestyle, financial risks from single income source. Mitigate the top one.", memoryTrick: "A staff engineer who surfaces risks BEFORE they hit is INSURANCE for the team. Insurance is boring until you need it." },
  { day: 68, phase: 4, type: "deep", title: "Building a Strategy Document", content: "Engineering strategy isn't just for VPs. Staff engineers write technology strategies for their domain. Will Larson's new work is entirely about refining engineering strategy with Wardley Mapping.", workChallenge: "Write a 2-page strategy for your domain at BHN: current capabilities, market/technical trends, recommended investments, and what to stop doing. This is staff+ artifact gold.", lifeChallenge: "Write a personal strategy: where are you now, where are macro trends going, and what investments should you make in the next 12 months?", memoryTrick: "A strategy is a COMPASS + CALENDAR. It says WHERE to go and WHEN to move. Without it, you're just busy." },
  { day: 69, phase: 4, type: "bite", title: "DORA Metrics and Engineering Excellence", content: "Addy Osmani (Google): 'DORA metrics are invaluable.' Four metrics that matter: Deployment Frequency, Lead Time for Changes, Change Failure Rate, Time to Restore Service. Know yours.", workChallenge: "Find out your team's DORA metrics. If they're not tracked, propose tracking them. Present the baseline to your team. Set a 90-day improvement target.", lifeChallenge: "Create personal DORA-like metrics: How often do you ship content? How fast from idea to publish? How often does a plan fail? How fast do you recover?", memoryTrick: "DORA metrics are the VITAL SIGNS of your engineering team. If you don't measure them, you're operating blind." },
  { day: 70, phase: 4, type: "practice", title: "Week 10: The Business Case Exercise", content: "Practice building business cases for technical investments.", workChallenge: "Pick a technical improvement you believe in. Build a full business case: problem (with data), proposed solution, expected ROI, timeline, risks. Present it as if pitching to a Director.", lifeChallenge: "Build a 'business case' for a personal investment: a course, a tool, a trip. If you can't justify it in ROI terms, reconsider.", memoryTrick: "A business case is a BRIDGE between what engineers want and what leaders fund. Learn to build bridges." },
  { day: 71, phase: 4, type: "bite", title: "Time Horizons: Quarter vs Year vs Multi-Year", content: "Senior engineers think in sprints. Staff engineers think in quarters and years. Your email centralization is a multi-quarter strategy, not a sprint task. Plan accordingly.", workChallenge: "Map your current projects on a time horizon: this sprint, this quarter, this half, this year. Is your mix balanced? Or are you only thinking short-term?", lifeChallenge: "Map your life goals on time horizons: this week, this month, this year, 3 years. Are you investing in the right timescales?", memoryTrick: "Sprints are STEPS. Quarters are STRIDES. Years are JOURNEYS. Staff engineers plan the journey, not just the next step." },
  { day: 72, phase: 4, type: "bite", title: "The Cost of Delay", content: "The most powerful business argument: 'Every week we delay this costs us $X.' Quantify the cost of inaction. It's often more compelling than the benefit of action.", workChallenge: "For your email centralization: what is the weekly cost of NOT doing it? Failed emails, developer time on workarounds, customer impact. Put a number on it.", lifeChallenge: "What's the cost of delay in your personal life? Postponing health improvements, career moves, relationship investments?", memoryTrick: "Action has a cost. But inaction has a HIDDEN cost that's often higher. Make the hidden cost VISIBLE." },
  { day: 73, phase: 4, type: "bite", title: "Build vs Buy vs Partner", content: "Staff engineers evaluate: should we build this, buy it, or partner with someone who has it? The answer changes based on strategic importance, team capacity, and total cost of ownership.", workChallenge: "For each component in your architecture, ask: 'Is this our core differentiator?' If YES, build it. If NO, buy or use a managed service. Save engineering effort for what matters.", lifeChallenge: "Apply to life: what should you DIY (core skills) vs outsource (tax filing, cleaning) vs partner on (content collaborations)?", memoryTrick: "Build your MOAT. Buy your FURNITURE. The moat protects you. The furniture is replaceable." },
  { day: 74, phase: 4, type: "bite", title: "Connecting BHN's 4 Pillars", content: "BHN's pillars: BeOneTeam, BeInnovative, BeTheSolution, BeAccountable. Staff-level work should MAP to these pillars. Your email centralization: BeInnovative (new architecture), BeTheSolution (solving a real problem), BeAccountable (owning it end-to-end).", workChallenge: "For each of your major achievements this year, tag them with BHN pillars. Gaps? Fill them. This is EXACTLY how your 5-star review will be evaluated.", lifeChallenge: "Create your own personal pillars (like BHN's 4). What are your 4 non-negotiable values? Do your actions align?", memoryTrick: "Pillars aren't decorations. They're LOAD-BEARING structures. If your work doesn't connect to pillars, it doesn't support the building." },
  { day: 75, phase: 4, type: "bite", title: "Metrics That Matter", content: "Staff engineers define the metrics that matter for their domain. Not all metrics are equal. Vanity metrics (lines of code, PRs merged) vs actionable metrics (error rate, deployment frequency, time to resolve).", workChallenge: "Define 3-5 'North Star' metrics for your domain. Metrics that, if improved, would signal real progress. Present them to your team.", lifeChallenge: "Define North Star metrics for your life: energy level, meaningful connections per week, hours on growth activities, content published.", memoryTrick: "If you're measuring the WRONG things, you're optimizing for the WRONG outcomes. Choose metrics that drive the RIGHT behavior." },
  { day: 76, phase: 4, type: "deep", title: "Building Your Strategy Toolkit", content: "Compile your strategic thinking frameworks: P.S.I.E., DORA, Wardley Mapping, business case templates, risk assessments.", workChallenge: "Create your 'Strategy Toolkit' document: templates for business cases, risk assessments, strategy docs, and metric definitions. Reuse and refine.", lifeChallenge: "Build a personal strategy toolkit: goal-setting frameworks, decision matrices, time-horizon planning templates.", memoryTrick: "A strategist without tools is a philosopher. A strategist WITH tools is a CHANGEMAKER." },
  { day: 77, phase: 4, type: "practice", title: "Phase 4 Graduation: The Strategy Brief", content: "14 days of strategic thinking. Demonstrate it.", workChallenge: "Deliver a 10-minute strategy presentation to your team or Arun: domain vision, current metrics, investment recommendations, and expected outcomes. This is your staff-level demo.", lifeChallenge: "Present your personal 2026-2027 strategy to yourself: career, health, content, relationships. Written. Measurable. Accountable.", memoryTrick: "Phase 4 done. You can MULTIPLY, ARCHITECT, INFLUENCE, and STRATEGIZE. Final phase: build a LEGACY." },

  // PHASE 5: LEGACY (Day 78-90)
  { day: 78, phase: 5, type: "bite", title: "Ship Engineers, Not Just Products", content: "Google's popular staff saying: 'Senior engineers ship products. Staff engineers ship engineers.' Your legacy isn't the system you built. It's the people you grew who can build the NEXT system.", workChallenge: "Identify 2 engineers on your team who could grow significantly with the right support. What specific skill does each need? How can you help? Start this week.", lifeChallenge: "Who in your personal network is trying to grow? How can you help them? Your legacy is the people you lift.", memoryTrick: "Products have EXPIRY dates. People have INFINITE potential. Invest in what lasts." },
  { day: 79, phase: 5, type: "bite", title: "Writing the Playbook Others Follow", content: "Staff engineers create processes, standards, and playbooks that outlive their presence. Your onboarding docs, architecture guidelines, and incident response procedures ARE your legacy.", workChallenge: "Write ONE playbook this week: a deployment checklist, an onboarding guide, or an architecture decision template. Something the team will use after you move to the next project.", lifeChallenge: "Create a personal playbook: your daily routine, your content creation process, your decision-making framework. Documented systems persist.", memoryTrick: "Code gets deprecated. Playbooks get adopted. Write the PLAYBOOK, not just the CODE." },
  { day: 80, phase: 5, type: "bite", title: "Raising the Bar", content: "Staff engineers set standards that become the new normal. Better code reviews, better documentation, better incident response. Not by mandating. By modeling.", workChallenge: "Pick one area where your team's standards could be higher. Don't announce a new standard. Just START doing it at the higher level. Consistency will shift the norm.", lifeChallenge: "In your content, in your relationships, in your health: raise your own bar by 10%. Others will follow your example.", memoryTrick: "A raised bar looks UNCOMFORTABLE at first. Then it becomes the new NORMAL. Then it becomes the new MINIMUM. That's how standards evolve." },
  { day: 81, phase: 5, type: "bite", title: "Creating Psychological Safety", content: "Addy Osmani (Google): 'Great leaders actively work to create an environment where team members feel safe to take risks, voice opinions, and even fail.' This is the SOIL in which great engineering grows.", workChallenge: "In your next retro or team discussion, share one of YOUR recent mistakes first. When the leader is vulnerable, everyone feels safe to be honest.", lifeChallenge: "Create psychological safety at home and in friend groups. Be the first to admit a mistake. Welcome disagreement. Celebrate honesty.", memoryTrick: "Psychological safety is FERTILIZER for innovation. Without it, even the best seeds won't grow." },
  { day: 82, phase: 5, type: "deep", title: "Your Staff Engineer Promotion Packet", content: "Will Larson: 'Document achievements in a promotion packet.' This isn't bragging. It's building the evidence base that demonstrates you're already operating at staff level.", workChallenge: "Start your promotion packet: list every multiplicative achievement, every cross-team project, every person you mentored, every system you designed, every document you wrote. Map each to BHN's pillars and review criteria.", lifeChallenge: "Build a personal 'life promotion packet': evidence that you've grown this year. Skills gained, relationships deepened, goals achieved.", memoryTrick: "A promotion packet isn't a WISH LIST. It's a RECEIPT of work already done. Build the receipt throughout the year, not at review time." },
  { day: 83, phase: 5, type: "bite", title: "The Knowledge Multiplier", content: "Every insight you gain but don't share dies with your memory. Every insight you DOCUMENT or TEACH lives forever. Tech talks, blog posts, mentoring sessions. Knowledge shared is knowledge squared.", workChallenge: "Take one technical insight you gained this quarter. Turn it into a 5-minute presentation, an internal doc, or a Slack post. Share it with BHN.", lifeChallenge: "Share a life insight on LinkedIn or Motovlogs. What you've learned about discipline, growth, or communication. Your lessons save others years.", memoryTrick: "Knowledge KEPT = one person benefits. Knowledge SHARED = N people benefit. Multiplication, not hoarding." },
  { day: 84, phase: 5, type: "practice", title: "Week 12: The Impact Inventory", content: "Take stock of the impact you've created over these 90 days.", workChallenge: "List: People you unblocked, Systems you designed, Decisions you influenced, Standards you raised, Documents you wrote, Engineers you mentored. This IS your staff-level evidence.", lifeChallenge: "List: Relationships you strengthened, Skills you gained, Content you published, Habits you built. This is your personal growth receipt.", memoryTrick: "An impact inventory is your ANNUAL REPORT. Not for the company. For yourself." },
  { day: 85, phase: 5, type: "bite", title: "Succession Planning", content: "Staff engineers think about succession: if you left tomorrow, would the system survive? Would someone know how it works? Would the team keep improving? If not, you've created a dependency, not a legacy.", workChallenge: "For every system you own, is there at least one other person who can maintain it? If not, start the knowledge transfer NOW. You should be REPLACEABLE. That's the ultimate sign of good engineering.", lifeChallenge: "In personal life, are you creating dependencies or building independence? Teach others what you know so they don't need you to function.", memoryTrick: "Being IRREPLACEABLE feels good. Being replaceable means you built something BIGGER than yourself. That's legacy." },
  { day: 86, phase: 5, type: "bite", title: "Continuous Learning at Scale", content: "Staff engineers never stop learning. But they learn differently: from production incidents (not just textbooks), from cross-team exposure (not just their domain), from business context (not just technical depth).", workChallenge: "Set up 3 learning channels: 1) Follow 3 engineering blogs, 2) Attend 1 cross-team meeting monthly, 3) Read 1 business report about your company's industry quarterly.", lifeChallenge: "Your 1% philosophy already nails this. But are you learning BROADLY enough? Add one domain outside tech to your learning: philosophy, business, psychology, history.", memoryTrick: "A T-shaped engineer: deep in ONE area, broad across MANY. Staff engineers are T-shaped. Build your horizontal bar." },
  { day: 87, phase: 5, type: "bite", title: "Grace Under Pressure", content: "Norberto Lopes (incident.io): 'Grace under pressure.' When production is down, when deadlines are impossible, when politics are messy. THAT is when staff engineers shine. Calm, clear, decisive.", workChallenge: "Think about the last high-pressure situation at work. How did you perform? What would 'grace under pressure' have looked like? Practice that version next time.", lifeChallenge: "When life pressure hits (financial, health, relationship), be the calm center. Your ability to stay composed under pressure is your ultimate leadership test.", memoryTrick: "PRESSURE reveals character. GRACE under pressure reveals MASTERY. Cultivate both." },
  { day: 88, phase: 5, type: "bite", title: "Your Staff Identity", content: "After 88 days, you have a clear picture of the staff engineer you're becoming. Technical depth + business acumen + influence skills + multiplier mindset + legacy thinking. That combination is rare.", workChallenge: "Write your 'Staff Engineer Identity Statement' in 3 sentences: who you are, what you uniquely bring, and how you create impact. This is your professional north star.", lifeChallenge: "Write your 'Life Identity Statement.' Not what you do, but who you ARE becoming. Let everything else flow from that.", memoryTrick: "Identity drives BEHAVIOR. Behavior drives OUTCOMES. Start with identity, and everything else follows." },
  { day: 89, phase: 5, type: "deep", title: "The 5-Star Review Blueprint", content: "Your 5-star rating goal connects to everything in this masterclass. Map your work to BHN's pillars: BeOneTeam (multiplying others), BeInnovative (architectural thinking), BeTheSolution (strategic problem-solving), BeAccountable (ownership and delivery).", workChallenge: "Create a 1-page '5-Star Evidence Sheet' with 3-4 achievements under each BHN pillar, each tied to specific STAFF-level behaviors from this masterclass.", lifeChallenge: "Create your personal '5-star year' evidence sheet: how have you grown across all four masterclasses? Mind (Critical Thinking), Soul (Gentleman), Voice (Communication), Career (Staff Mindset).", memoryTrick: "A 5-star review isn't LUCK. It's ARCHITECTURE. Build the evidence all year, and the review builds itself." },
  { day: 90, phase: 5, type: "practice", title: "GRADUATION: The Staff Mindset Manifesto", content: "90 days. Insights from Will Larson, Evan King, Addy Osmani, Irina Stanescu, Gregor Ojstersek, and dozens of FAANG/Big Tech staff engineers. One transformed engineer.", workChallenge: "Write your 1-page Staff Mindset Manifesto: your multiplier principles, architecture philosophy, influence playbook, strategic frameworks, and legacy commitments. Present it to Surendra. This is your north star.", lifeChallenge: "Share your journey. A LinkedIn post, a Motovlogs video, a conversation with a junior engineer. Your 90-day transformation inspires the next person's Day 1.", memoryTrick: "Day 1: you shipped code. Day 90: you ship ENGINEERS, SYSTEMS, and CULTURE. The code was never the point. The IMPACT was." },
];

const typeLabel = (t) => t === "bite" ? "5-min Bite" : t === "deep" ? "Deep Dive" : "Practice Day";
const typeIcon = (t) => t === "bite" ? "\u26A1" : t === "deep" ? "\uD83C\uDF0A" : "\uD83C\uDFCB\uFE0F";

export default function App() {
  const [dark, setDark] = useState(true);
  const [selPhase, setSelPhase] = useState(null);
  const [selDay, setSelDay] = useState(null);
  const [done, setDone] = useState(() => { try { return JSON.parse(localStorage.getItem("masterclass_staff-mindset_done")) || {}; } catch { return {}; } });
  const [vw, setVw] = useState("home");
  const ref = useRef(null);
  useEffect(() => { localStorage.setItem("masterclass_staff-mindset_done", JSON.stringify(done)); }, [done]);
  const toggle = (d) => setDone((p) => ({ ...p, [d]: !p[d] }));
  const ct = Object.values(done).filter(Boolean).length;
  const pct = Math.round((ct / 90) * 100);
  const phase = selPhase ? PHASES.find((p) => p.id === selPhase) : null;

  useEffect(() => { ref.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }, [selDay]);

  const m = dark ? "dark" : "light";
  const t = {
    bg: dark ? "#060810" : "#f8f9fc",
    surface: dark ? "rgba(10,14,25,0.9)" : "rgba(255,255,255,0.9)",
    surfHov: dark ? "rgba(14,18,32,0.96)" : "rgba(246,248,252,0.97)",
    bdr: dark ? "rgba(56,189,248,0.08)" : "rgba(0,50,100,0.08)",
    txt: dark ? "#e2e8f0" : "#0f172a",
    sub: dark ? "#7e8a9a" : "#64748b",
    mut: dark ? "#4a5568" : "#94a3b8",
    card: dark ? "rgba(8,12,22,0.75)" : "rgba(255,255,255,0.75)",
    ring: dark ? "#141c2e" : "#e2e8f0",
    tag: dark ? "rgba(0,0,0,0.35)" : "rgba(0,40,80,0.035)",
    togBg: dark ? "rgba(56,189,248,0.06)" : "rgba(0,50,100,0.06)",
    hero: dark
      ? "radial-gradient(ellipse at 15% 0%, rgba(56,189,248,0.1), transparent 45%), radial-gradient(ellipse at 85% 0%, rgba(74,222,128,0.08), transparent 45%), radial-gradient(ellipse at 50% 90%, rgba(251,191,36,0.06), transparent 50%)"
      : "radial-gradient(ellipse at 15% 0%, rgba(3,105,161,0.04), transparent 45%), radial-gradient(ellipse at 85% 0%, rgba(21,128,61,0.03), transparent 45%), radial-gradient(ellipse at 50% 90%, rgba(180,83,9,0.025), transparent 50%)",
  };
  const hGrad = dark
    ? "linear-gradient(135deg, #38bdf8 0%, #4ade80 25%, #fbbf24 50%, #c084fc 75%, #f87171 100%)"
    : "linear-gradient(135deg, #0369a1 0%, #15803d 25%, #b45309 50%, #7e22ce 75%, #dc2626 100%)";

  const Tog = () => (
    <button onClick={() => setDark(!dark)} style={{ position: "fixed", top: 14, right: 14, zIndex: 999, background: t.togBg, backdropFilter: "blur(14px)", border: `1px solid ${t.bdr}`, borderRadius: 40, padding: "7px 14px", cursor: "pointer", display: "flex", alignItems: "center", gap: 7, color: t.sub, fontSize: 12.5, fontFamily: "'JetBrains Mono', monospace", transition: "all 0.35s", letterSpacing: 0.5 }}>
      <span style={{ fontSize: 15 }}>{dark ? "\u2600\uFE0F" : "\uD83C\uDF19"}</span>{dark ? "Light" : "Dark"}
    </button>
  );

  if (vw === "home") {
    return (
      <div style={{ fontFamily: "'Outfit', sans-serif", background: t.bg, minHeight: "100vh", color: t.txt, transition: "background 0.45s, color 0.45s" }}>
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <style>{`@keyframes fu{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}.pc:hover{transform:translateY(-2px);box-shadow:${dark?"0 6px 28px rgba(0,0,0,0.5)":"0 6px 28px rgba(0,0,0,0.06)"}}.pc{transition:all 0.28s cubic-bezier(0.4,0,0.2,1)}`}</style>
        <Tog />
        <div style={{ position: "relative", padding: "52px 24px 28px", textAlign: "center", overflow: "hidden" }}>
          <div style={{ position: "absolute", inset: 0, background: t.hero, pointerEvents: "none" }} />
          {dark && <div style={{ position: "absolute", inset: 0, background: "repeating-linear-gradient(0deg, transparent, transparent 40px, rgba(56,189,248,0.02) 40px, rgba(56,189,248,0.02) 41px), repeating-linear-gradient(90deg, transparent, transparent 40px, rgba(56,189,248,0.02) 40px, rgba(56,189,248,0.02) 41px)", pointerEvents: "none" }} />}
          <div style={{ position: "relative", zIndex: 1 }}>
            <div style={{ fontSize: 10.5, letterSpacing: 8, textTransform: "uppercase", fontFamily: "'JetBrains Mono', monospace", color: t.mut, marginBottom: 14 }}>90-Day Masterclass</div>
            <h1 style={{ fontFamily: "'Outfit', sans-serif", fontSize: "clamp(30px,6vw,50px)", fontWeight: 900, lineHeight: 1.05, margin: "0 0 6px", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>Staff Mindset</h1>
            <p style={{ fontSize: 12, color: t.sub, fontFamily: "'JetBrains Mono', monospace", margin: "10px 0 8px", fontWeight: 300, letterSpacing: 2.5 }}>multiply / architect / influence / strategize / legacy</p>
            <p style={{ fontSize: 11, color: t.mut, margin: "0 0 28px", fontFamily: "'JetBrains Mono', monospace" }}>Powered by insights from Stripe, Meta, Google, Uber CTOs</p>
            <div style={{ display: "inline-flex", alignItems: "center", gap: 18, background: t.surface, border: `1px solid ${t.bdr}`, borderRadius: 18, padding: "16px 26px", backdropFilter: "blur(16px)" }}>
              <div style={{ position: "relative", width: 58, height: 58 }}>
                <svg width="58" height="58" viewBox="0 0 58 58">
                  <circle cx="29" cy="29" r="25" fill="none" stroke={t.ring} strokeWidth="3" />
                  <defs><linearGradient id="pg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#38bdf8"/><stop offset="25%" stopColor="#4ade80"/><stop offset="50%" stopColor="#fbbf24"/><stop offset="75%" stopColor="#c084fc"/><stop offset="100%" stopColor="#f87171"/></linearGradient></defs>
                  <circle cx="29" cy="29" r="25" fill="none" stroke="url(#pg)" strokeWidth="3" strokeDasharray={`${(pct/100)*157.1} 157.1`} strokeLinecap="round" transform="rotate(-90 29 29)" style={{ transition: "stroke-dasharray 0.7s cubic-bezier(0.4,0,0.2,1)" }} />
                </svg>
                <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 700, fontFamily: "'JetBrains Mono', monospace", background: hGrad, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>{pct}%</div>
              </div>
              <div style={{ textAlign: "left" }}>
                <div style={{ fontSize: 26, fontWeight: 900 }}>{ct}<span style={{ fontSize: 14, color: t.mut, fontWeight: 400 }}> / 90</span></div>
                <div style={{ fontSize: 10, color: t.mut, fontFamily: "'JetBrains Mono', monospace", letterSpacing: 1.5 }}>days completed</div>
              </div>
            </div>
          </div>
        </div>
        <div style={{ padding: "8px 20px 48px", maxWidth: 720, margin: "0 auto" }}>
          {PHASES.map((p, i) => {
            const pl = ALL_LESSONS.filter(l => l.phase === p.id);
            const pc = pl.filter(l => done[l.day]).length;
            const ac = p.accent[m];
            return (
              <div key={p.id} className="pc" onClick={() => { setSelPhase(p.id); setVw("phase"); }} style={{ background: t.card, border: `1px solid ${t.bdr}`, borderRadius: 16, padding: "20px 22px", cursor: "pointer", marginBottom: 12, borderLeft: `3px solid ${ac}`, animation: `fu 0.55s ease ${i*0.1}s both`, position: "relative", overflow: "hidden", backdropFilter: "blur(10px)" }}>
                <div style={{ position: "absolute", top: -20, right: -20, width: 120, height: 120, background: `radial-gradient(circle, ${p.glow}, transparent 65%)`, pointerEvents: "none", opacity: dark ? 0.5 : 0.3 }} />
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", position: "relative" }}>
                  <div style={{ display: "flex", gap: 14, alignItems: "center" }}>
                    <span style={{ fontSize: 26, fontWeight: 900, color: ac, fontFamily: "'Outfit', sans-serif" }}>{p.icon}</span>
                    <div>
                      <div style={{ fontSize: 10, color: ac, letterSpacing: 4, textTransform: "uppercase", fontFamily: "'JetBrains Mono', monospace", marginBottom: 4 }}>Phase {p.id} | {p.days}</div>
                      <div style={{ fontSize: 19, fontWeight: 800 }}>{p.title}</div>
                      <div style={{ fontSize: 12, color: t.sub, fontWeight: 400, marginTop: 2 }}>{p.subtitle}</div>
                    </div>
                  </div>
                  <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: t.mut, textAlign: "right", minWidth: 48 }}>
                    <span style={{ color: ac, fontWeight: 600 }}>{pc}</span>/{pl.length}
                  </div>
                </div>
                <div style={{ marginTop: 14, height: 2.5, background: t.ring, borderRadius: 3, overflow: "hidden" }}>
                  <div style={{ height: "100%", width: `${(pc/pl.length)*100}%`, background: `linear-gradient(90deg, ${ac}, ${ac}55)`, borderRadius: 3, transition: "width 0.5s ease" }} />
                </div>
                <div style={{ marginTop: 10, fontSize: 10, color: t.mut, padding: "6px 11px", background: t.tag, borderRadius: 8, fontFamily: "'JetBrains Mono', monospace", lineHeight: 1.5 }}>\uD83E\uDDE0 {p.mnemonic}</div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  if (vw === "phase" && phase) {
    const pl = ALL_LESSONS.filter(l => l.phase === phase.id);
    const ac = phase.accent[m];
    return (
      <div style={{ fontFamily: "'Outfit', sans-serif", background: t.bg, minHeight: "100vh", color: t.txt, transition: "background 0.45s, color 0.45s" }}>
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <style>{`@keyframes fu{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}@keyframes ex{from{opacity:0;max-height:0}to{opacity:1;max-height:900px}}`}</style>
        <Tog />
        <div style={{ position: "relative", overflow: "hidden" }}>
          <div style={{ position: "absolute", inset: 0, background: phase.gradient[m], opacity: dark ? 0.5 : 0.3, transition: "opacity 0.4s" }} />
          {dark && <div style={{ position: "absolute", inset: 0, background: "repeating-linear-gradient(0deg, transparent, transparent 40px, rgba(56,189,248,0.015) 40px, rgba(56,189,248,0.015) 41px), repeating-linear-gradient(90deg, transparent, transparent 40px, rgba(56,189,248,0.015) 40px, rgba(56,189,248,0.015) 41px)", pointerEvents: "none" }} />}
          <div style={{ position: "relative", zIndex: 1, padding: "20px 20px 6px" }}>
            <button onClick={() => { setVw("home"); setSelPhase(null); setSelDay(null); }} style={{ background: t.togBg, border: `1px solid ${t.bdr}`, color: t.sub, padding: "7px 16px", borderRadius: 10, cursor: "pointer", fontSize: 12, fontFamily: "'JetBrains Mono', monospace" }}>{"\u2190"} Back</button>
          </div>
          <div style={{ position: "relative", zIndex: 1, padding: "8px 24px 24px", textAlign: "center" }}>
            <span style={{ fontSize: 38, fontWeight: 900, color: ac }}>{phase.icon}</span>
            <h2 style={{ fontSize: 30, fontWeight: 900, margin: "8px 0 4px" }}>Phase {phase.id}: {phase.title}</h2>
            <p style={{ color: t.sub, fontWeight: 400, margin: 0, fontSize: 13 }}>{phase.subtitle}</p>
            <p style={{ color: t.sub, fontSize: 12.5, marginTop: 10, maxWidth: 520, marginInline: "auto", lineHeight: 1.6 }}>{phase.description}</p>
            <div style={{ marginTop: 12, display: "inline-block", fontSize: 10.5, color: ac, padding: "6px 14px", background: `${ac}10`, borderRadius: 8, fontFamily: "'JetBrains Mono', monospace", border: `1px solid ${ac}20` }}>{phase.mnemonic}</div>
          </div>
        </div>
        <div style={{ padding: "12px 20px 48px", maxWidth: 720, margin: "0 auto" }}>
          {pl.map((l, i) => {
            const op = selDay === l.day;
            return (
              <div key={l.day} ref={op ? ref : null} style={{ marginBottom: 7, animation: `fu 0.4s ease ${i*0.03}s both` }}>
                <div onClick={() => setSelDay(op ? null : l.day)} style={{ background: op ? t.surfHov : t.card, border: `1px solid ${op ? `${ac}35` : t.bdr}`, borderRadius: op ? "13px 13px 0 0" : 13, padding: "13px 16px", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", transition: "all 0.25s", backdropFilter: "blur(8px)" }}>
                  <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
                    <div onClick={e => { e.stopPropagation(); toggle(l.day); }} style={{ width: 24, height: 24, borderRadius: "50%", border: done[l.day] ? `2.5px solid ${ac}` : `2px solid ${t.bdr}`, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", background: done[l.day] ? `${ac}15` : "transparent", transition: "all 0.25s", flexShrink: 0 }}>
                      {done[l.day] && <span style={{ color: ac, fontSize: 11, fontWeight: 700 }}>{"\u2713"}</span>}
                    </div>
                    <div>
                      <div style={{ fontSize: 9.5, color: t.mut, fontFamily: "'JetBrains Mono', monospace", letterSpacing: 1.2 }}>Day {l.day} | {typeIcon(l.type)} {typeLabel(l.type)}</div>
                      <div style={{ fontSize: 14, fontWeight: 600, color: done[l.day] ? t.mut : t.txt, textDecoration: done[l.day] ? "line-through" : "none", marginTop: 2 }}>{l.title}</div>
                    </div>
                  </div>
                  <span style={{ color: t.mut, fontSize: 13, transform: op ? "rotate(180deg)" : "rotate(0)", transition: "transform 0.25s", flexShrink: 0 }}>{"\u25BE"}</span>
                </div>
                {op && (
                  <div style={{ background: t.surfHov, border: `1px solid ${ac}35`, borderTop: "none", borderRadius: "0 0 13px 13px", padding: 20, animation: "ex 0.35s ease", overflow: "hidden", backdropFilter: "blur(8px)" }}>
                    <p style={{ color: t.txt, lineHeight: 1.8, margin: "0 0 18px", fontSize: 14, fontWeight: 300 }}>{l.content}</p>
                    {[
                      { label: "\uD83D\uDCBC Work Challenge (BHN)", text: l.workChallenge, c: dark ? ["rgba(56,189,248,0.05)","rgba(56,189,248,0.12)","#38bdf8"] : ["rgba(3,105,161,0.04)","rgba(3,105,161,0.09)","#0369a1"] },
                      { label: "\uD83C\uDF31 Life Challenge", text: l.lifeChallenge, c: dark ? ["rgba(74,222,128,0.05)","rgba(74,222,128,0.11)","#4ade80"] : ["rgba(21,128,61,0.04)","rgba(21,128,61,0.09)","#15803d"] },
                      { label: "\uD83E\uDDE0 Memory Trick", text: l.memoryTrick, c: dark ? ["rgba(251,191,36,0.05)","rgba(251,191,36,0.12)","#fbbf24"] : ["rgba(180,83,9,0.04)","rgba(180,83,9,0.1)","#b45309"], highlight: true },
                    ].map((s, si) => (
                      <div key={si} style={{ background: s.c[0], border: `1px solid ${s.c[1]}`, borderRadius: 11, padding: "13px 16px", marginBottom: si < 2 ? 10 : 0 }}>
                        <div style={{ fontSize: 9.5, color: s.c[2], letterSpacing: 2.5, textTransform: "uppercase", fontFamily: "'JetBrains Mono', monospace", marginBottom: 6 }}>{s.label}</div>
                        <p style={{ color: s.highlight ? (dark ? "#fef08a" : "#854d0e") : t.txt, fontSize: s.highlight ? 13.5 : 13, lineHeight: 1.6, margin: 0, fontWeight: s.highlight ? 500 : 300 }}>{s.text}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    );
  }
  return null;
}
